### ISSUE TITLE
Adicionar nova coluna

### ISSUE THREAD

**Issue by devthiagolino** [owen-it/laravel-auditing#1]
Existe a possibilidade de incluir uma nova coluna no pacote?
Porque tipo preciso relacionar o log a um cliente então eu preciso de uma coluna na tabela tipo, cliente_id para fazer o relacionamento do log, e tipo não sei como fazer isso, porque se fizer no pacote de vocês vou perder minhas alterações quando atualizar o pacote.
Alguma sugestão?

**Comment by anteriovieira** [comment]
@devthiagolino , se o seu cliente for um usuário logado no sistema o laravel-auditing já faz isso por você. Ele grava na colunar user_id o responsável pela alteração. Este processo é feito através da função getUserId presente na class ``` OwenIt\Auditing\Auditing ```

```php
	protected function getUserId()
	{
		try {
			if (\Auth::check()) {
				return \Auth::user()->getAuthIdentifier();
			}
		} catch (\Exception $e) {
			return null;
		}
		return null;
	}
```
Caso precise alterar a forma como ele busca os usuário logado ou gostaria de associar um usuário de outra forma, basta sobrescrever esta função no seu model.

Para recuperar o usuário associado:
```php
    ...
    $log->user
    ...
```

**Comment by devthiagolino** [comment]
Tendi.
na verdade olhando bem, não tem problema não salvar o cliente, pois pelo usuário eu sei quem é o cliente, eu acho que tá resolvido qualquer novidade falo por aqui, abraços e vlw pela atenção.

**Comment by devthiagolino** [comment]
Tem como alterar o nome da tabela tipo de logs para outra qualquer coisa?

**Comment by raphaelfranca** [comment]
@devthiagolino através de parâmetros no pacote não, mas caso seja realmente necessário, sugiro que crie uma fork do projeto e altere os métodos do package para sua necessidade.

**Comment by devthiagolino** [comment]
Entendo. Tranquilo.

**Comment by anteriovieira** [comment]
Ok @devthiagolino , qualquer coisa estamos aqui, em breve estaremos disponibilizando uma aplicação com exemplos práticos do uso do laravel-auditing.

**Comment by ecmattos** [comment]
@devthiagolino Parabéns pelo pacote ! Muito bom !

**Comment by ecmattos** [comment]
@devthiagolino 

Os meus logs aparecem assim:

user.name atualizou os dados de SANTA CATARINA1
De: old.uf -> Para: new.uf updated in 2015-10-02 02:33:45
De: SANTA CATARINA -> Para: SANTA CATARINA1 updated in 2015-10-02 02:33:45
user.name atualizou os dados de SANTA CATARINA
De: old.uf -> Para: new.uf updated in 2015-10-02 11:01:41
De: SANTA CATARINA1 -> Para: SANTA CATARINA updated in 2015-10-02 11:01:41

3 duvidas por mais obvias pois estou comecando a utilizar o laravel:
1) Por que ao inves do nome do usuario aparece user.name ? Tenho que fazer um relacionamento das tabelas logs e users ?
2) Como suprimir os logs onde old.campo e new.campo são nulos ?
3) Gostaria traduzir os textos updated in por alterado em. Como faço ?

**Comment by ecmattos** [comment]
Percebendo agora, inclui as minhas dúvidas no local errado.

Estou refazendo-as corretamente.

Desculpas.
