### ISSUE TITLE
Log - messages > Parte II

### ISSUE THREAD

**Issue by ecmattos** [owen-it/laravel-auditing#10]
@anteriovieira 
Para ir pensando numa atualizacao (seria bem legal pois nao encontrei nada ainda):

Nas mensagens de logs, para os campos com relacoes em outras tabelas, deveria mostrar a informacao do relacionada ao campo correspondente.

Exemplo:
Alterei a categoria de um produto (de TV para Celular).
Na tebela logs, efetuará o registro do log da category_id de 1 para 2 mas na mensagem do log deveria mostrar de "TV" para "Celular" (textos) e nao os valores do campo.

Nao sei se de repente associar tambem:
protected $doKeepLogOf = ['description', 'category_id']; // Informe os campos que deseja registrar no log.
protected $do???????? = ['description ???', 'categories.id']; // Informe os campos que deseja relacionar no log.

Nao sei se me entendeste ?

**Comment by ecmattos** [comment]
@anteriovieira 
Zerei a tabela de logs e continua aparecendo {user.name} !!!

**Comment by anteriovieira** [comment]
Ok, estou meio enrolado aqui mas jaja vou testar uma aplicação do zero.

**Comment by ecmattos** [comment]
@anteriovieira 
OK

**Comment by anteriovieira** [comment]
Ola @ecmattos , dê uma olhada neste exemplo https://github.com/anteriovieira/teams, pode lher ajudar no que esta precisando. Lembre-se de atualizar o auditing para a versão estável. Estou pensando como vou fazer em relação aos relacionamento de tabela. Quando tiver algo te aviso, mas se quiser pode ir brincando ai, qualquer coisa manda um pull request.

**Comment by ecmattos** [comment]
ok
muito legal !
Ajudou muito mesmo !

**Comment by anteriovieira** [comment]
Bom dia @ecmattos , da uma olhadinha na documentação do pacote em [featuring-log](https://github.com/owen-it/laravel-auditing#featuring-log) , pode ser que te ajude caso precise buscar o valor do campo ao invez do id, ainda estou pensando em uma solução mais apropriada, mas o uso de callbacks pode vim a calhar no momento.

**Comment by ecmattos** [comment]
Oi, Antério! 

Andei pesquisando outros pacotes e achei o venturecraft/revisionable. 
Nele eu encontrei e consegui utilizar a função identifiableName() que pega o valor do campo escolhido correspondente ao ID modificado. 
Também muito bom por sinal! 

Dá uma olhada e,  talvez lhe ajude a aperfeiçoar o teu pacote. 

Abraços.
