### ISSUE TITLE
[Proposal] Ability to log that a field value has changed, but not store the actual value (e.g. password)

### ISSUE THREAD

**Issue by kitbs** [owen-it/laravel-auditing#106]
I would like to record an audit log when the User model has been updated if the password has been changed. However, I do not want to store the password/hash in my audit trail table.

If I were to use `$dontKeepAuditOf = ['password']` on my User model, then a change of password field would not be included in the audit log. And if the password was the only value changed, then no audit log would be created at all.

It would be nice if the auditing function looked at the `$hidden = ['password']` on my model, then stored `{"password": null}` in the old and new columns instead of the actual value. Or some other way of customising "hidden" attributes in the audit log.

What do you think?

**Comment by anteriovieira** [comment]
@kitbs , I think a great idea. You like to send a pull request?

**Comment by kitbs** [comment]
Sorry, my automatic indenting is slightly different to yours and was causing lots of unnecessary diffs. The final commit and PR just shows the changed lines.

I decided to make the behaviour respect `$hidden` by default (i.e. change the current behaviour) but it can be switched off by setting `protected $auditRespectsHidden = false;` on the model.

If you prefer that the current behaviour stays as the default, I could reverse the logic so that the new behaviour only works if `$auditRespectsHidden` is `true`. Up to you.

Thanks for the great package and the chance to contribute.

**Comment by anteriovieira** [comment]
I think we should audit all values. If you wish to omit the hidden values, this should be explicit in the model.
