### ISSUE TITLE
How to loop through revision info

### ISSUE THREAD

**Issue by gn0rt0n** [owen-it/laravel-auditing#108]
Here is the output of a single revision:
{
"id":"e3eb0eec-cfe8-4ff4-897f51ea8f39a08",
"type":"updated",
"auditable_id":1,
"auditable_type":"App\\Domain\\Users\\User",
"old":{"name":"Administrator","email":"admin@test.com"},
"new":{"name":"Admin","email":"admin@admin.com"},
"user_id":"1","route":"http:\/\/admin.dev\/users\/1",
"ip_address":"127.0.0.1",
"created_at":"2016-10-04 19:43:25",
"custom_message":"Not defined custom message!",
"custom_fields":[],
"elapsed_time":"1 second ago"
}

I would like to be able to access the information from the revision to get this type of output:
[name => [
     'old' => 'Administrator',
     'new' => 'Admin',
],
email => [
     'old' => 'admin@test.com',
     'new' => 'admin@admin.com',
]]

I don't have to get it out in an array, but basically I want to get the fields that changed (name, email) and their old and new values so that I can loop through them. I am passing these values to a Diff method that presents items in a table based layout.

I also want to have access to the individual properties so that I can restore an old value.

Thanks in  advance,
Gary

**Comment by anteriovieira** [comment]
If I had understood well:

```php
$audits = $post->audits

foreach($audits as $audit){
    
    foreach($audit->new as $key => $value){

        echo $key . ': '. $value;

    }    

}
```
