### ISSUE TITLE
Callback in custom messages does not work

### ISSUE THREAD

**Issue by AndreasSundstrom** [owen-it/laravel-auditing#121]
Callback in custom messages does not work (tested in Laravel 5.3).

It seems like that the `auditable()` method in `\OwenIt\Auditing\Auditing` doesn't do what it's supposed to. `$this->morphTo()` returns an instance of `\Illuminate\Database\Eloquent\Relations\MorphTo`, not the auditable entity. Changing `$this->morphTo()` to `$this->morphTo()->getResults()` seems to solve the problem.

**Comment by anteriovieira** [comment]
Hello @AndreasSundstrom , thank you for reporting. I'll look at it later. Any pull request is welcome.

**Comment by anteriovieira** [comment]
Fix https://github.com/owen-it/laravel-auditing/pull/122
