### ISSUE TITLE
Activating Queue leads to lose the user id, route url and ip

### ISSUE THREAD

**Issue by Belphemur** [owen-it/laravel-auditing#129]
Hello,

I find the queue feature great, only I think you should gather the loggedInUserId, the routeUrl and ip before sending the queue job.

Because in the actual implementation, you lose all those valuable information since it's auditing method are launch from the queue.

Do you think you could change the job to take those invaluable data as parameter and feeds them back into the audit before going through the auditor ?

**Comment by anteriovieira** [comment]
Hello @Belphemur , thank you for reporting this issue.  I'll fix it as soon as possible.

The expected behavior should save this information. 

If you want to send a pull request, feel free. Otherwise, I'll fix as soon as leaving work.

**Comment by anteriovieira** [comment]
Fixed https://github.com/owen-it/laravel-auditing/pull/131
