### ISSUE TITLE
callback won't be called in 'deleted' and 'created' type

### ISSUE THREAD

**Issue by wayson** [owen-it/laravel-auditing#132]
Hi,

I have install 3.1 with Laravel 5.2. I've tried to use this plugin.

But I have some problem with the callback method in custom messages and queries. 

```php
$audit = Auditing::where('type', 'updated')->first();

dd($audit->auditable);exit;
```

It will show 
![image](https://cloud.githubusercontent.com/assets/3485960/19503428/366cf38c-95ff-11e6-848a-0f9615560de7.png)

But it will show empty if the record is 'created' or 'deleted':

```php

$audit = Auditing::where('type', 'deleted')->first();

dd($audit->auditable);exit;
```
It will return 'null'.

Does it mean it only works in update type only?

**Comment by anteriovieira** [comment]
Hello @wayson ,

This is because the model does not exists. 

If you are using [softDelete](https://laravel.com/docs/5.3/eloquent#soft-deleting) you can use **withTrashed** to retrieve your model.

````php
$audit = Auditing::where('type', 'deleted')->first();

dd($audit->auditable->withTrashed());exit;

````
