### ISSUE TITLE
Show specific log

### ISSUE THREAD

**Issue by xDestinatioNx** [owen-it/laravel-auditing#135]
Hello guys,
at the moment I show a table with each audit entry in it.
On another page I want to show a specific entry with some more informations about the user and the changes he did (because this is too much for the table).
But I'm struggling to implement this because of the auditables varchar id an no other unique table column.

Is there any way to implement this and I'm blind or it's not possible at the moment?

**Comment by anteriovieira** [comment]
Hello @xDestinatioNx , you can show me your current code?

**Comment by xDestinatioNx** [comment]
Yeah for sure.
At the moment I try to display the log id like this
```{{ $log->id }}```
If the ID is *4315f4d6-caf7-4dea-85af-8bad6f52cb6c* it displays only the first integer digits like *4315*

In my other tables each ID is an auto increment and I can easily search like *User:find($id);* and passing them to an url to show an specific user.

But the auditable only gives me *4315* instead of *4315f4d6-caf7-4dea-85af-8bad6f52cb6c* so I can't find the specific entry.

**Comment by anteriovieira** [comment]
Hi @xDestinatioNx , excuse the delay in responding. I'll try to see your case today.

**Comment by xDestinatioNx** [comment]
Hi, I only hope that's possible to implement 🙈

**Comment by quetzyg** [comment]
Hi @xDestinatioNx,

I fail to reproduce the issue, since each time I display the `id` of an audit in a view, I get the full value.
```php
{{ $log->id }}
```
will give me something like `8504a0ba-8fe0-4c4d-adc3-ac3ffc3a39c3`

Can you provide more information on what you're doing (i.e. more code)?

**Comment by anteriovieira** [comment]
I am considering this as solved.
