### ISSUE TITLE
How can I audit delete options

### ISSUE THREAD

**Issue by cesarcruzc** [owen-it/laravel-auditing#136]
When I delete a record dont log  in the table audits

**Comment by xDestinatioNx** [comment]
At this point it's already cleared. Take a look here [Behavior Settings - Laravel Auditing](http://www.laravel-auditing.com/docs/3.1/behavior-settings)

**Comment by anteriovieira** [comment]
Hi @cesarcruzc , I would like to better understand your case. Can you provide an example of what you are doing.

**Comment by cesarcruzc** [comment]
Hi @anteriovieira.

I'm using Laravel 5.2 and working with repository pattern.

This is an example of my Models:

`
namespace App\Entities;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable;
use Spatie\Activitylog\Traits\LogsActivity;
`
`
class AccidentCase extends Model
{

    Use Auditable, LogsActivity;

    protected $table = 'bdc_caso_accidente';

    protected $fillable = ['nombres', 'telefono', 'celular', 'ciudad_id', 'bdc_datos_trabajador_id', 'entry_by'];

    protected $guarded = ['id'];

    // LogsActivity
    protected static $logAttributes = ['nombres', 'telefono', 'celular', 'ciudad_id', 'bdc_datos_trabajador_id', 'entry_by'];


    public function getLogNameToUse(string $eventName = ''): string
    {
        return $this->table;
    }
    //

    // Auditable
    protected $auditableTypes = ['created', 'saved', 'deleted'];
    //


    // Mutators

    public function getNombresAttribute($value)
    {
        return title_case(strtolower($value));
    }

    //--

    // Relations

    public function workerData()
    {
        return $this->belongsTo(WorkerData::class, 'bdc_datos_trabajador_id');
    }

    // --
}
`

**Comment by cesarcruzc** [comment]
I am testing this package [https://github.com/spatie/laravel-activitylog](url) and I have the same issue. 

am I doing something wrong?

**Comment by anteriovieira** [comment]
As you are deleting the model?

Because have some queries that laravel does not run events.

**Comment by anteriovieira** [comment]
This should work.

```php
$AccidentCase = AccidentCase::find(1);

$AccidentCase ->delete();
```

**Comment by cesarcruzc** [comment]
My Repository:

`
class AccidentCaseRepository extends BaseRepository
`
`
{
`

`
    public function getModel()
    {
        return new References();
    }
`

`
public function deleteDataByWorker($workerId)
    {
        $model = $this->getModel();
        return $model->where('bdc_datos_trabajador_id', $workerId)->delete();
    }
`

**Comment by anteriovieira** [comment]
This is the same case reported in [issues 139](https://github.com/owen-it/laravel-auditing/issues/139).

**Comment by anteriovieira** [comment]
The solution is the following:

```php
class AccidentCaseRepository extends BaseRepository 
{ 
    protected $accidentCase;

    public function __construct(AccidentCase $accidentCase)
    {
        $this->accidentCase = $accidentCase;
    }

    public function deleteDataByWorker($workerId) 
    { 
        $accidentCase = $this->accidentCase->find($workerId);

        return $accidentCase->delete();
    } 
}
```

**Comment by anteriovieira** [comment]
ops!

**Comment by anteriovieira** [comment]
```php
class AccidentCaseRepository extends BaseRepository 
{ 
    protected $accidentCase;

    public function __construct(AccidentCase $accidentCase)
    {
        $this->accidentCase = $accidentCase;
    }

    public function deleteDataByWorker($workerId) 
    { 
        $accidentCase = $this->accidentCase
                             ->where('bdc_datos_trabajador_id', $workerId)
                             ->firstOrFail();

        return accidentCase->delete();
    } 
}
```

**Comment by cesarcruzc** [comment]
@anteriovieira Thank you so much! 
This solution worked for me!!
