### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by rdehnhardt** [owen-it/laravel-auditing#138]
It would be an excellent choice if the package had an option to save the data in a mongodb or similar

**Comment by anteriovieira** [comment]
Hi @rdehnhardt ,

The [connection configuration](http://laravel-auditing.com/docs/3.1/general-settings) did not help?

[Specify a different database connection for audit.](https://github.com/owen-it/laravel-auditing/blob/3.1/config/auditing.php#L35)

**Comment by rdehnhardt** [comment]
I will try and return the result here

**Comment by kingvish** [comment]
I have specified separate connection but create audit tables.

**Connection:**
 'audit' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_AUDIT', '127.0.0.1'),
            'port' => env('DB_PORT_AUDIT', '3306'),
            'database' => env('DB_DATABASE_AUDIT', 'forge'),
            'username' => env('DB_USERNAME_AUDIT', 'forge'),
            'password' => env('DB_PASSWORD_AUDIT', ''),
            'unix_socket' => env('DB_SOCKET_AUDIT', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ]

**Config:**
    'drivers' => [
        'database' => [
            'table'      => 'audits',
            'connection' => 'audit',
        ],
    ],

**Comment by quetzyg** [comment]
Read the [Audit Implementation](http://www.laravel-auditing.com/docs/5.0/audit-implementation) section on how to use MongoDB.
