### ISSUE TITLE
Update audit not being created

### ISSUE THREAD

**Issue by casenjo** [owen-it/laravel-auditing#139]
I'm having an issue where updates to a model aren't being saved to the audits table.
At first I thought it was because of my repository models, but I stopped using those to test and they're still not created.

I'm using this to create:
`\App\OrderStaffNote::create(['order_id' => $orderForNotes->id, 'notes' => $request->staffNotesText]);`

And this to update:
`\App\OrderStaffNote::where('order_id', $orderForNotes->id)->update(['notes' => $request->staffNotesText]);`

For creating, the audit log is added to the table, but for updates they don't show up. I also added `protected $auditableTypes = ['created', 'updated', 'saved', 'deleted'];` to the model just in case but that didn't work either. Any ideas on how to track down the cause of this problem?

**Comment by anteriovieira** [comment]
Hi @casenjo ,

This `OrderStaffNote::creaate([...])` works for you?

**Comment by casenjo** [comment]
Yeah, it works great. The model is created and the audit entry is also
created. Its only when an update happens that the audit entry doesn't work
:(

**Comment by anteriovieira** [comment]
Hi @casenjo ,

The laravel not fire events for this procedure.

**Comment by casenjo** [comment]
Hi @anteriovieira, I see, so it's only for the create event?

**Comment by anteriovieira** [comment]
Hi @casenjo ,

I believe that the query is executed directly in the database. Thus there is not a concrete object to be updated, but a query to be executed.

[Reference](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Builder.php#L524)

**Comment by anteriovieira** [comment]
When the object to be updated is instantiated -> [update](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L1406-L1413) -> [save](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L1463-L1466) -> [performUpdate](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L1526-L1528)

**Comment by bart** [comment]
You can use the "updated" event instead of "saved". That should do the trick (y)
