### ISSUE TITLE
Display Related Properties

### ISSUE THREAD

**Issue by whereisjefe** [owen-it/laravel-auditing#140]
Sorry if I'm missing something, I'm pretty new to laravel, but i can't seem to figure this out and wasn't sure if I'm doing it wrong or is not part of this package. 

Anyways, this is what i currently have

```
public static $auditCustomMessage = '{user.name|Anonymous} {type} the instructor ({new.employee_id}) {elapsed_time}';
```

which prints out 

> bob smith created the instructor (58) 3 hours ago

which is to be expected, but what i would like to be able to get the related employee_id properties and wasn't sure if that was possible. I tried doing something like 

```
public static $auditCustomMessage = '{user.name|Anonymous} {type} the instructor ({new.employee_id.f_name}) {elapsed_time}';
```

but that didn't work. So if it is possible with this package, could you point me in the right direction so i can get something like this working with the current package. 

> bob smith created the instructor (John) 3 hours ago

Thanks in advance.

**Comment by anteriovieira** [comment]
Hi @whereisjefe , try the following

```php
// ...
class Instructor extends Model
{
    use Auditable;

    public static $auditCustomMessage = '{user.name|Anonymous} {type} the instructor ({||getEmployeeName}) {elapsed_time}';

    public function instructor()
    {
        return // relationship
    }

    public function getEmployeeName($data)
    {
        $employeeId = $data->new['employee_id'];

        if (!empty($employeeId)) {
            return $this->instructor()->find($employeeId)->name;
        }

        return 'something';
    }
}
```

I'm at work and have not tested it, so I wonder if it was useful for you

**Comment by anteriovieira** [comment]
You can also transform the audit data array before it is passed into the database.

```php
use Illuminate\Support\Arr;
use OwenIt\Auditing\Auditable;
use Illuminate\Database\Eloquent\Model;

class Instructor extends Model;
{
  use Auditable;

  public static $auditCustomMessage = '{user.name|Anonymous} {type} the instructor ({employee_name}) {elapsed_time}';

  public function employee()
  {
    return // relationship
  }

  public function transformAudit(array $data)
  {
      if(Arr::has('new.employee_id')){
          Arr::set($data, 'new.employee_name',  $this->employee->name)
      }

      return $data;
  }
}
```

**Comment by whereisjefe** [comment]
@anteriovieira  That was all i needed to get me pointed in the right direction, thanks! 

Follow up question... 

From playing around, it looks like `{property_name|Lorem ipsum}` will just return the string `Lorem ipsum` if `property_name` is empty. Where `{property_name||getPropertyFunction}` will look for a function `getPropertyFunction` and display the returned value.

is the `|` and `||` syntax specific to this package or is it called something? I would like to read up on it to get a better understanding.

Anyways, Thanks again for the help and for making this helpful package. It's a huge time-saver!

**Comment by anteriovieira** [comment]
Hi @whereisjefe , there is nothing specific to this syntax. It was just a way I found to provide a means to fetch the data.

```
{field}
{field|or_default_value}
{field||or_method}
```

**Comment by whereisjefe** [comment]
@anteriovieira Thanks, makes sense, just wanted to make sure i wasn't missing something
