### ISSUE TITLE
Custom audit message translations

### ISSUE THREAD

**Issue by quetzyg** [owen-it/laravel-auditing#143]
Hi there,

First of all, great package!

Now to business. Currently, this package doesn't have support for translated messages.
Also, the way the custom message and custom field are set seems messy, since we're setting them inside the model.

A better approach would be to move that into the `resources/lang/{your_language}/` path and have it set in the model like:
```php
// Booking.php model
public static $auditCustomMessage = 'booking.audit.message';

public static $auditCustomFields = 'booking.audit.fields';
```

Then, we would have a `resources/lang/en/booking.php` with:
```php
<?php

return [
    'audit' => [
        'message' => '{user.name} {type} this Booking {elapsed_time}',
        'fields'  => [
            'date'       => 'The date was defined as "{new.date}"',
            'seats'      => 'The seats were defined as "{new.seats}"',
            'ip_address' => 'Registered from the address {ip_address}',
        ],
    ],
];
```
In the `CustomAuditMessage` trait, the `getCustomMessage()` method would return the translated string:
```php
    public function getCustomMessage($class)
    {
        if (!isset($class::$auditCustomMessage)) {
            return trans('audit.custom.message');
        }

        return trans($class::$auditCustomMessage);
    }
```
and the `getCustomFields()` method would behave the same way:
```php
    public function getCustomFields($class)
    {
        if (!isset($class::$auditCustomFields)) {
            return [];
        }

        return trans($class::$auditCustomFields);
    }
```

Thoughts?

**Comment by anteriovieira** [comment]
Hi @quetzyg , great idea. Feel free to send us a pull request.

**Comment by quetzyg** [comment]
@anteriovieira, to which branch should I PR to? `master` or `3.1`?

**Comment by anteriovieira** [comment]
@quetzyg send to master.
