### ISSUE TITLE
Add a new audits entry only if fields changes

### ISSUE THREAD

**Issue by ilvalerione** [owen-it/laravel-auditing#151]
Hello there, thanks for this package.

Is it possibe to force laravel-auditing to store a new log entry in "audits" table only if observed fields are changing?

Observed fields are registered inside the model by `$keepAuditOf` variable.

Can i use a custom Auditor to accomplish this task?

Thanks

**Comment by anteriovieira** [comment]
Hi @ilvalerione , yes, you can.

**Comment by anteriovieira** [comment]
If you have any questions about how to do it, I'll be happy to help you.

**Comment by mattb2401** [comment]
Hi @anteriovieira, i have set up the dependence but it doesn't seem to audit anything.

**Comment by anteriovieira** [comment]
Can I see what you've done?

**Comment by mattb2401** [comment]
`<?php

namespace App;

use OwenIt\Auditing\Auditable;
use Illuminate\Database\Eloquent\Model;

class QCash extends Model
{
	use Auditable;
}
`

**Comment by mattb2401** [comment]
`<?php

here is one of the models. I dont know whether i have to put something in the controllers

namespace App;

use OwenIt\Auditing\Auditable;
use Illuminate\Database\Eloquent\Model;

class QCash extends Model
{
	use Auditable;
}

**Comment by anteriovieira** [comment]
How are you manipulating data when saving or updating?

You may be going through this https://github.com/owen-it/laravel-auditing/issues/139

**Comment by mattb2401** [comment]
Ooh okay let me try that way
