### ISSUE TITLE
Show custom message only when field has changed

### ISSUE THREAD

**Issue by kay899** [owen-it/laravel-auditing#152]
Hi,

first of all, a wonderful and helpful package. :-)

Would it be possible that the CustomMessages are only shown for "changed" fields.

Actually I get:

**Sabille updated an Address 27 minutes ago**
- The street was changed from " " to " "
- The zip was changed from "23145" to "89765"
- The city was changed from " " to " "
- The country was changed from " " to " "
- IP Address: 127.0.0.1

The only field changed was ist "street", so I would expect only this two to see in the audio log. In the database you are only boring values for it, right?

Thanks

kay899

**Comment by anteriovieira** [comment]
Hello @kay899 , yes, you are right. Can you show me your code?

**Comment by kay899** [comment]
In Address Model:

    public static $auditCustomMessage = '{user.name|Anonymous} {type} an Address {elapsed_time}'; 

    public static $auditCustomFields = [
        'street'  => 'The street was changed from "{old.street}" to "{new.street}"', 
        'zip'  => 'The zip was changed from "{old.zip}" to "{new.zip}"', 
        'city'  => 'The city was changed from "{old.city}" to "{new.city}"', 
        'country'  => 'The country was changed from "{old.country}" to "{new.country}"', 
        'ip_address' => 'IP Address: {ip_address}',
    ];

In View I use exactly your code example.

thanks

kay889

**Comment by anteriovieira** [comment]
Ok, can you show me your view code?

**Comment by kay899** [comment]
sure

                            <ol>
                            @forelse ($address->audits()->latest()->get() as $audit)
                                <li>
                                    {{ $audit->customMessage }}
                                    <ul>
                                        @forelse ($audit->customFields as $custom)
                                            <li>{{ $custom }}</li>
                                        @empty
                                            <li>No details</li>
                                        @endforelse
                                    </ul>
                                </li>
                            @empty
                                <p>No audits</p>
                            @endforelse
                        </ol>

**Comment by anteriovieira** [comment]
@kay899 , try

```blade
                    <ol>
                        @forelse ($address->audits()->latest()->get() as $audit)
                            <li>
                                {{ $audit->customMessage }}
                                <ul>
                                    @forelse ($audit->customFields as $field => $custom)
                                        @if(!empty($audit->new[$fiedl]) or !empty($audit->old[$field]))
                                            <li>{{ $custom }}</li>
                                        @endif
                                    @empty
                                        <li>No details</li>
                                    @endforelse
                                </ul>
                            </li>
                        @empty
                            <p>No audits</p>
                        @endforelse
                    </ol>
```

**Comment by kay899** [comment]
I have done it now like this:

    <ol>
    @forelse ($address->audits()->latest()->get() as $audit)
        <li>
            {{ $audit->customMessage }}
            <ul>
                @forelse ($audit->customFields as $field => $custom)
                    @if(!empty($audit->new[$field]) or !empty($audit->old[$field]))
                        <li>{{ $custom }}</li>
                    @endif
                @empty
                    <li>No details</li>
                @endforelse
                <li>{{ $audit->customFields['ip_address'] }}</li>
            </ul>
        </li>
    @empty
        <p>No audits</p>
    @endforelse
</ol>

As you can see I added one "static" field with date, time and IP.
Here is my output now:

**Sabille updated an Address 6 hours ago**

- The street was changed from "Musterstrasse 100" to "Musterstrasse 99"
- The zip was changed from "43527" to "12345"
- Done at 2016-11-19 11:17:25 by IP 127.0.0.1

**Sabille updated an Address 6 hours ago**

- The street was changed from "Musterstrasse 100 D" to "Musterstrasse 100"
- The zip was changed from "89765" to "43527"
- Done at 2016-11-19 11:07:51 by IP 127.0.0.1

**Sabille updated an Address 7 hours ago**

- The zip was changed from "23145" to "89765"
- Done at 2016-11-19 10:49:49 by IP 127.0.0.1

**Sabille updated an Address 7 hours ago**

- The street was changed from "Musterstrasse 100 C" to "Musterstrasse 100 D"
- Done at 2016-11-19 10:49:18 by IP 127.0.0.1

Thanks very much for your help

Regards

kay899

**Comment by anteriovieira** [comment]
Perfect! 😃
