### ISSUE TITLE
Show audits in correct date order

### ISSUE THREAD

**Issue by kay899** [owen-it/laravel-auditing#153]
Hi,

would it be possible to show the Audits logs in the correct date order, e.g. latest as first, older at last?

Actually I'll get this order:

- Sabille updated an Address 44 minutes ago
- Sabille updated an Address 44 minutes ago
- Sabille updated an Address 16 minutes ago
- Sabille updated an Address 25 minutes ago

I would expect to have the 16 minutes entry at first and the 44 minutes as last ones.

Thanks

kay899

**Comment by anteriovieira** [comment]
Hi @kay899 , try

`$model->audits()->latest()->get()`

[Ref](https://laravel.com/docs/5.3/queries#ordering-grouping-limit-and-offset)

**Comment by kay899** [comment]
Yes, this is working.
Thanks
