### ISSUE TITLE
php artisan auditing:install not defined. v3.1.7

### ISSUE THREAD

**Issue by ikodota** [owen-it/laravel-auditing#154]
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "auditing:install" is not defined.                      
  Did you mean one of these?                                      
      migrate:install                                             
      auditing:table

**Comment by anteriovieira** [comment]
Hi @ikodota ,

What version are you using?

**Comment by ikodota** [comment]
3.1.7  
composer require owen-it/laravel-auditing

**Comment by ikodota** [comment]
I can't find 'InstallCommand.php' file  in installed packet's  ‘src/Console‘’ folder. but i found the file in your github Code. I tryed copy it to my composer packet. then use ‘php artisan list‘ command .  the problem remains unresolved.

**Comment by ikodota** [comment]
laravel 5.3

**Comment by anteriovieira** [comment]
@ikodota , try please

`composer remove owen-it/laravel-auditing`

`composer require owen-it/laravel-auditing`

`composer dump-autoload`

**Comment by anteriovieira** [comment]
@ikodota , I'm sorry, it was my mistake. It's not really in the version.

I do not know how this can happen.

I'm going to release a new version.

**Comment by anteriovieira** [comment]
Thanks for your note, the new version is v3.1.8

**Comment by ikodota** [comment]
@anteriovieira  thanks.

**Comment by gioramies** [comment]
Hi.
I'm having the same issue with version 3.1.10
Help me please.
