### ISSUE TITLE
Auditing logs always show every field I keep track of

### ISSUE THREAD

**Issue by Cannonb4ll** [owen-it/laravel-auditing#156]
I only want to show the custom message fields that have actually changed.

![Image](https://d3vv6lp55qjaqc.cloudfront.net/items/0N0l250c440H1g0B132m/%5B2e7ab178f790f18ae34bbec7c3ab87b4%5D_Image%25202016-11-23%2520at%25202.39.45%2520p.m..png?X-CloudApp-Visitor-Id=2342373&v=2d3eb8bb)

In this case I have only changed description, my auditing log in DB also only shows the key description in `new` and `old` rows. But it is still showing the messages for the other keys which have not been touched.

What am I doing  wrong?

My custom messages look like this:

```
    public static $auditCustomFields = [
        'title'  => 'The title was defined as "{new.title||getNewTitle}"',
        'description'  => 'The description was defined as "{new.description||getNewDescription}"',
        'url'  => 'The URL was defined as "{new.url||getNewUrl}"',
        'slack_webhook'  => 'The slack webhook was defined as "{new.slack_webhook||getNewSlackWebhook}"',
        'discord_webhook'  => 'The discord webhook was defined as "{new.discord_webhook||getNewDiscordWebhook}"',
        'ip_address' => 'Registered from the address <code>{ip_address}</code>'
    ];
```

**Comment by quetzyg** [comment]
Hi @Cannonb4ll,

You're not doing anything wrong, since this is how the package currently behaves.
I already spoke about this to @anteriovieira, and we'll eventually address this in a future version.

**Comment by Cannonb4ll** [comment]
Thank you for explaining, I was already breaking my head on this issue. Hope this gets resolved soon, or at least configurable.

**Comment by anteriovieira** [comment]
Hi @Cannonb4ll , 

Let's try to solve this as soon as possible.

But you can create a workaround for now. Take a look at this issue https://github.com/owen-it/laravel-auditing/issues/152

Thank you for reporting.
