### ISSUE TITLE
Oracle reserved words - Column issues

### ISSUE THREAD

**Issue by elogicmedia** [owen-it/laravel-auditing#165]
Hi,

I'm trying to use your plugin while also using this plugin to connect to oracle: https://github.com/yajra/laravel-oci8

The issue I have run into is "new" and "old" are reserved words so they can't be used within the table columns. 

Is there a way around this?

Thanks

**Comment by anteriovieira** [comment]
Hi @elogicmedia , 

yes, you can use the feature Auditor and modify the model Auditing or create a new.

**Comment by anteriovieira** [comment]
Hello @elogicmedia , 

You can disregard my comment above, we will change the attribute names in version 4.0.0

**Comment by elogicmedia** [comment]
Within Auditable.php I changed the columns as follows:

`        return $this->transformAudit([
            'id'             => (string) Uuid::uuid4(),
            **'old_data'**            => $this->cleanHiddenAuditAttributes($this->oldData),
            **'new_data'**            => $this->cleanHiddenAuditAttributes($this->newData),
            'type'           => $this->auditType,
            'auditable_id'   => $this->getKey(),
            'auditable_type' => $this->getMorphClass(),
            'user_id'        => $this->auditUserId,
            'route'          => $this->auditCurrentRoute,
            'ip_address'     => $this->auditIpAddress,
            'created_at'     => $this->freshTimestamp(),
        ]);`

From that I then get the following errors:

> ErrorException in helpers.php line 747:
preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

> in helpers.php line 747
> at HandleExceptions->handleError('2', 'preg_replace(): Parameter mismatch, pattern is a string while replacement is an array', 'C:\www\iplex_service_feedback\vendor\laravel\framework\src\Illuminate\Support\helpers.php', '747', array('search' => '\?', 'replace' => array('4da27bae-3e16-426d-98b3-caecaafa3fa6', array('sort_order' => '1'), array('sort_order' => '2'), 'updated', '1', 'App\Position', '1', 'http://local.service_feedback/edit_position', '127.0.0.1', '2016-11-28 06:14:16'), 'subject' => 'insert into isf_audits (id, old_data, new_data, type, auditable_id, auditable_type, user_id, route, ip_address, created_at) values (4da27bae-3e16-426d-98b3-caecaafa3fa6, ?, ?, ?, ?, ?, ?, ?, ?, ?)', 'value' => array('sort_order' => '1')))

Changing it back to mysql and it works again. Any idea what may be going on here?

Thanks

**Comment by quetzyg** [comment]
Hi @elogicmedia,

The name change shouldn't make a difference, since `old`, `old_data`, `new` and `new_data` will always be arrays. You're probably trying to do something else in your code that you're not showing us.

MySQL also has `new` as a reserved word, as you can see [here](https://dev.mysql.com/doc/refman/5.5/en/keywords.html), but  Oracle is probably stricter about it and doesn't let you create a table/columns using reserved words.

As @anteriovieira said, this issue will be fixed in the next major version, so you can either stick with MySQL for the time being or try to see if Oracle can be set to a less stricter mode.

**Comment by elogicmedia** [comment]
I have just tried using **old_data** and **new_data** with Mysql and I get the same above issue, changing it back to old and new on mysql and I don't get the error anymore.

So it seems to me the column rename is an issue for both databases?

Thanks

**Comment by quetzyg** [comment]
You might need to change other parts of the package in order for that to work properly.

I suggest you wait a couple of days until we sort out this issue on `master`.

**Comment by elogicmedia** [comment]
I ended up getting this to work on oracle. I had to do the following:

Auditable.php
`    public function toAudit()
    {
        return $this->transformAudit([
            'id'             => (string) Uuid::uuid4(),
            '**olddata**'            => $this->cleanHiddenAuditAttributes($this->oldData),
            '**newdata**'            => $this->cleanHiddenAuditAttributes($this->newData),
            'type'           => $this->auditType,
            'auditable_id'   => $this->getKey(),
            'auditable_type' => $this->getMorphClass(),
            'user_id'        => $this->auditUserId,
            'route'          => $this->auditCurrentRoute,
            'ip_address'     => $this->auditIpAddress,
            'created_at'     => $this->freshTimestamp(),
        ]);
    }`

AND

Auditing.php
`    protected $casts = [
        '**olddata**' => 'json',
        '**newdata**' => 'json',
    ];`

It was the protected $casts field names causing my preg_replace error.

Thanks

**Comment by quetzyg** [comment]
Closing this issue, since this has been fixed in the next major version.
