### ISSUE TITLE
Auditable With Eloquent\Model in standalone

### ISSUE THREAD

**Issue by Lo5t** [owen-it/laravel-auditing#169]
Is it possible or rather more specific how, to use Auditable  in standalone mode without Laravel.
I am using Slim framework and I can use Eloquent\Models but if I try and use Auditable I get 

> Details
Type: RuntimeException
Message: A facade root has not been set.
File: /vagrant/vendor/illuminate/support/Facades/Facade.php
Line: 234
Trace

#0 /vagrant/vendor/owen-it/laravel-auditing/src/Auditable.php(425): Illuminate\Support\Facades\Facade::__callStatic('runningInConsol...', Array)
#1 /vagrant/vendor/owen-it/laravel-auditing/src/Auditable.php(425): Illuminate\Support\Facades\App::runningInConsole()
#2 /vagrant/vendor/owen-it/laravel-auditing/src/Auditable.php(80): CheckOut\Models\CheckOut::isAuditEnabled()
#3 [internal function]: CheckOut\Models\CheckOut::bootAuditable()
#4 /vagrant/vendor/illuminate/database/Eloquent/Model.php(323): forward_static_call(Array)
#5 /vagrant/vendor/illuminate/database/Eloquent/Model.php(309): Illuminate\Database\Eloquent\Model::bootTraits()
#6 /vagrant/vendor/illuminate/database/Eloquent/Model.php(296): Illuminate\Database\Eloquent\Model::boot()
#7 /vagrant/vendor/illuminate/database/Eloquent/Model.php(277): Illuminate\Database\Eloquent\Model->bootIfNotBooted()
#8 /vagrant/vendor/illuminate/database/Eloquent/Model.php(630): Illuminate\Database\Eloquent\Model->__construct()
#9 /vagrant/src/routes.php(330): Illuminate\Database\Eloquent\Model::all()

**Comment by quetzyg** [comment]
Hi @Lo5t,

That's a new use case we didn't thought about before. The new version in the making doesn't have a facade anymore, but it still relies on a few Laravel internals to work (Config, App, Filesystem, etc).

I'm not promising anything at this stage, but I'll see what can be done in that regard. Still you do have to bear in mind that the name of the project is Laravel Auditing, not Eloquent Auditing ;)

Thanks for the suggestion!

**Comment by quetzyg** [comment]
We decided to close this issue, since the package is dependant on Laravel features.

**Comment by anteriovieira** [comment]
As Quetzy said

> I'm not promising anything at this stage, but I'll see what can be done in that regard. Still you do have to bear in mind that the name of the project is Laravel Auditing, not Eloquent Auditing ;)

 let's look at this more forward.

**Comment by samuca-renewed** [comment]
It is forward enough ? 😁 🇧🇷
