### ISSUE TITLE
Exclude querystring parameters from route column

### ISSUE THREAD

**Issue by marcroberts** [owen-it/laravel-auditing#174]
I'm using Socialite to login via Facebook and create a remember_token for the user, this creates an audit entry for the change of `remember_token` however the long callback URL is causing this error:

```
SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255) (SQL: insert into "audits" ("id", "old", "new", "type", "auditable_id", "auditable_type", "user_id", "route", "ip_address", "created_at") values (aaf7d681-6232-4564-b136-abcbfe737266, {"remember_token":""}, {"remember_token":"MV0r0V0sUNInK7GltbXnudI5lxLYvRfDUT2zJgLZZcVYAxRR17us6R89awVJ"}, updated, 22995, App\User, 22995, http://xxxxxx.dev/auth/facebook/callback127.0.0.1code=AQ*SNIP**xx&state=xx**SNIP**xx, 2016-12-14 17:51:49, ?))
```

It looks like there are a couple of issues here:

1) The URL being used is actually too long (I've trimmed the long random strings out of it above), because of the querystring parameters. Should/could these be ignored?

2) The question mark in the URL appears to be being interpreted as a statement parameter with the IP address being replaced in to it. If the querystring is going to remain (and the data field increased in size to cope with it) what can we do about this?

Versions:
laravel-auditing: 3.1.10
laravel/framework: 5.3.26
PHP: 7.0.13

**Comment by anteriovieira** [comment]
Hi @marcroberts ,

By default, [columns of type string](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Schema/Blueprint.php#L464) is defined with 255 character 

I suggest you [change the column type route to text](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Schema/Blueprint.php#L475).

@quetzyg Let's fix this for next version.

**Comment by quetzyg** [comment]
Hello @marcroberts,
1) That's an easy fix. You just have to change the column type from `VARCHAR(255)` to `TEXT`. We'll make `TEXT` as the default in the next version.

2) I'm not sure I understand what's happening. Can you be a bit more clear, please?

**Comment by marcroberts** [comment]
1. I have done that for now, but there's a lot of useless querystring data being added that isn't useful (in the instance above, the code and state for the facebook callback are huge and pointless to store). Is there any way to exclude/ignore the querystring parameters from being inserted in this column?

2. This was an issue with the rendering of the error message I think. Obviously the database is doing it correctly, but in the error message it was inserting the IP address (127.0.0.1) in the middle of the URL in place of the `?` instead of as the next parameter. Please ignore this.

**Comment by quetzyg** [comment]
Hi again @marcroberts,
1) There are two ways to get rid of the query string. You either **a)** transform the Audit data before being stored using the `transformAudit()` [method](http://www.laravel-auditing.com/docs/3.1/transform-audit), or **b)** use a [method](http://www.laravel-auditing.com/docs/3.1/customizing) to transform the data when presenting it to the user.

Personally, I would use the second option, since you never know when you might need to analyse the original data).

2) Ignored :)

**Comment by marcroberts** [comment]
Thanks @quetzyg 

I'll look at these. Would you consider implementing (or accepting a pull request for) a config option to globally remove the query string before being saved?

**Comment by quetzyg** [comment]
Since there are ways to transform the data (when storing and when displaying), I wouldn't add such feature, but @anteriovieira might have a different opinion about that.

**Comment by anteriovieira** [comment]
@marcroberts let's keep it the way it is for now. We can think of something in version v4, 

In versions prior to v4 we will only do bug fix.

**Comment by marcroberts** [comment]
Okay, thanks. I'll use `transformAudit()` for now and keep an eye out for v4 developments
