### ISSUE TITLE
How to change the Auth Guard 

### ISSUE THREAD

**Issue by kalidasweb** [owen-it/laravel-auditing#175]
how to change this Auth Guard ? its fixed one so we can't apply any other 
```
  protected function getLoggedInUserId()
    {
        try {
            if (Auth::check()) { 
                return Auth::user()->getAuthIdentifier();
            }
        } catch (\Exception $e) {
            return;
        }
    }

```

**Comment by quetzyg** [comment]
Hi @kalidasweb,

Yeah, the way the `User` gets resolved in version `3.x` is kind of fixed. I'm not sure if @anteriovieira wants to change that behaviour, but in the next version you can define your resolver in the configuration file as a `callable`.

If you're not afraid of using the latest `master` branch, go right ahead. The implementation is pretty much done. The only thing left doing is the documentation and tests.

**Comment by kalidasweb** [comment]
Thank for response @quetzyg 

OK i will try :+1:

**Comment by kalidasweb** [comment]
Stucked  : Type error: Argument 1 passed to OwenIt\Auditing\AuditableObserver::created() must be an instance of OwenIt\Auditing\Contracts\Auditable, instance of App\User given

**Comment by quetzyg** [comment]
Your `User` model has to implement the `OwenIt\Auditing\Contracts\Auditable` contract.

Do something like:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class User extends Model implements AuditableContract;
{
    use Auditable;

    // ...
}
```

**Comment by kalidasweb** [comment]
Its not generating migration file :(

**Comment by kalidasweb** [comment]
Finally i have created the table from the insert query and its working :) but have some bugs thanks lot any way 

```
CREATE TABLE `audits` (
  `id` char(36) COLLATE utf8_unicode_ci NOT NULL,
  `auditable_id` int(10) unsigned NOT NULL,
  `auditable_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `old_values` text COLLATE utf8_unicode_ci,
  `new_values` text COLLATE utf8_unicode_ci,
  `user_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `url` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `event` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `audits_auditable_id_auditable_type_index` (`auditable_id`,`auditable_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

```
