### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by lukejoyce** [owen-it/laravel-auditing#178]
Just wondering if the next version will be compatible with Laravel 5.4 given the new [Container changes](https://laravel.com/docs/master/upgrade#upgrade-5.4.0). If so, any idea of when this could be? Thanks

**Comment by quetzyg** [comment]
Hi @lukejoyce,

The only `bind()` usage is through a `singleton()` call in the `AuditingServiceProvider` class and as you can [verify](https://github.com/owen-it/laravel-auditing/blob/master/src/AuditingServiceProvider.php#L61), we're not using leading slashes in the argument being passed.

Even version `3.1` of this package doesn't use leading slashes, as you can see [here](https://github.com/owen-it/laravel-auditing/blob/3.1/src/AuditingServiceProvider.php#L58).

**Comment by lukejoyce** [comment]
Awesome, thanks!
