### ISSUE TITLE
Transition to dataType from text to json

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#179]
For fields old and new.

**Comment by quetzyg** [comment]
Can you be a bit more specific on what you want/report?

**Comment by rorc** [comment]
In MySQL 5.7 appeared datatype json. So, maybe worth store data in this native type instead of `text`?

**Comment by quetzyg** [comment]
We have to cater for more RDBMS than just MySQL 5.7, so that change won't happen in the nearest future.
