### ISSUE TITLE
[Resolved] Class OwenIt\Auditing\Auditing not found

### ISSUE THREAD

**Issue by anteriovieira** [owen-it/laravel-auditing#18]
Problem solved, if someone can test I thank you.

**Comment by anteriovieira** [comment]
@wallauschek , @juniorb2ss , @lmtorres , @ricardotomim , @resmall Please, test the latest available version.  Thanks!

**Comment by lmtorres** [comment]
Solved

**Comment by anteriovieira** [comment]
Thank you my friend, I have helped.

**Comment by ricardotomim** [comment]
Resolvido, grato.
