### ISSUE TITLE
Issues trying to create custom auditors in 3.1 and custom audit driver in 4.1

### ISSUE THREAD

**Issue by jschlies** [owen-it/laravel-auditing#180]
I wish to create a second  custom auditor/custom audit driver in addition to the default database. 
In 3.1, I follow http://www.laravel-auditing.com/docs/3.1/auditors but think there are additional steps. Can someone point out more detailed doc or a working example? seem to die in manager trying to create driver "throw new InvalidArgumentException("Driver [$driver] not supported.");". 

In 4.0, I find instability. Getting "Fatal error: Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use in /home/vagrant/repos/toto/vendor/owen-it/laravel-auditing/src/AuditableObserver.php on line 5".

**Comment by jschlies** [comment]
Never mind. Figured out Ineed to refer to custom with full namepsace

**Comment by wyred** [comment]
I'm having the same problem. How did you fix it?
