### ISSUE TITLE
Sentinel Authentication

### ISSUE THREAD

**Issue by dominicmuse** [owen-it/laravel-auditing#181]
So am using Sentinel and have tried to overwrite the default auth as stated on issue 40

namespace App;
use OwenIt\Auditing\Auditing;

```
class Post extends Auditing 
{
    // ...
    protected function getUserId()
    {
        try {
            if ($user = Sentinel::check()) {
                return $user->id;
            }
        } catch (\Exception $e) {
            return;
        }
    }
}

```
but the user id is still not inserted.Please help identify what could be the issue

**Comment by quetzyg** [comment]
Hi @dominicmuse,

Give the latest (still in development) version a go.
```sh
composer require owen-it/laravel-auditing 4.0.x-dev
```
It's easier to configure `User` resolvers.

The [documentation](http://www.laravel-auditing.com/docs/master/general-settings) is up to date with the latest code and there's an example on how to achieve what you want.

**Comment by dominicmuse** [comment]
oh nice, Lemme give it a try. Thanks mate

**Comment by dominicmuse** [comment]
the installation via composer is still throwing errors. So when can we have a more stable version of the  same?

**Comment by quetzyg** [comment]
I'm unable to help you without seeing what's happening.

**Comment by dominicmuse** [comment]
Updating dependencies (including require-dev)
  - Removing owen-it/laravel-auditing (3.1.10)
  - Installing owen-it/laravel-auditing (dev-master e2aa311)
    Cloning e2aa3119b69a9ac453ba9b5f824b51df8aa5f1e3
    Failed to download owen-it/laravel-auditing from source: Failed to clone https://github.com/owen-it/laravel-auditing.git, git was not found, check that it is installed and in your PATH env.

'git' is not recognized as an internal or external command,
operable program or batch file.

    Now trying to download from dist
  - Installing owen-it/laravel-auditing (dev-master e2aa311)
    Downloading: 100%

Writing lock file
Generating autoload files

**Comment by dominicmuse** [comment]
Thats composer installation

**Comment by quetzyg** [comment]
The issue has nothing to do with the package being unstable.
If you read the output, you'll see that you don't have `git` installed on your system, so the package source install fails.

Composer then does a `dist` install, which seems to do the trick, but then it fails to write the `composer.lock` file.

Try this command instead: `composer require owen-it/laravel-auditing 4.0.x-dev --prefer-dist`

**Comment by dominicmuse** [comment]
FatalThrowableError in AuditableObserver.php line 17: Type error: Argument 1 passed to OwenIt\Auditing\AuditableObserver::created() must be an instance of OwenIt\Auditing\Contracts\Auditable, instance of App\Customer given

**Comment by quetzyg** [comment]
You should read the [documentation](http://www.laravel-auditing.com/docs/master/introduction).

**Comment by dominicmuse** [comment]
So i have followed the steps on the documentation to the latter. The initial version 3.1 works well but doesn't include the user id when using Sentinel. As for the version 4.1, it throws the error

`FatalThrowableError in AuditableObserver.php line 17: Type error: Argument 1 passed to OwenIt\Auditing\AuditableObserver::created() must be an instance of OwenIt\Auditing\Contracts\Auditable, instance of App\User given`

Thats when i follow the same steps included on the documentation

**Comment by dominicmuse** [comment]
Ok sorry, works like a charm.found my mistake. THANKS for the help!!
