### ISSUE TITLE
Default audits to be returned ordered most recently first

### ISSUE THREAD

**Issue by alexdover** [owen-it/laravel-auditing#184]
Me again!

I am returning the audits for an object and think it would be worth ordering them by the created date.

I think it would be as simple as this:

    public function audits()
    {
        return $this->morphMany(Auditing::class, 'auditable')->orderBy('created_at', 'desc');
    }

in the DatabaseAudits trait

I'd be happy to put this in a pull request if it helps.

**Comment by quetzyg** [comment]
Hi @alexdover,

Thanks for the suggestion, but I think we should leave it to the user to decide by which column and in which order the results should be returned.

You can easily achieve what you want with:
```php
        return $someModel->audits()
            ->orderBy('created_at', 'DESC')
            ->get();
```

@anteriovieira, what are your thoughts?

**Comment by anteriovieira** [comment]
@alexdover  , feel free to send us a pull request.

@quetzyg seems to me interesting behavior.

**Comment by quetzyg** [comment]
This feature will be present in the next version.
