### ISSUE TITLE
How to use in Model Relationships?

### ISSUE THREAD

**Issue by silverbux** [owen-it/laravel-auditing#185]
Hi, how can i use this on model relationships? 
for example i have categories and products, for products implementation is quite straight forward.
but what if i want to audit on the category level.

**Comment by quetzyg** [comment]
I don't follow what you're saying. Can you provide a better explanation to what you want to achieve? Are you referring to **many-to-many** relations?

**Comment by silverbux** [comment]
sorry, yep many-to-many relations.
on the first example i was able to get audits on products, but not all the audits of a product that is under a category

**Comment by quetzyg** [comment]
Keeping track of changes in **many-to-many** relations isn't currently supported.
Also, there's already an open issue about the subject, so I'm marking this as closed.

Check #58
