### ISSUE TITLE
Possibility to accept / deny changes

### ISSUE THREAD

**Issue by victorlap** [owen-it/laravel-auditing#186]
Hello, is there currently a possibility to accept or deny the changes made? Or is this easy to implement with a custom Auditor?

**Comment by quetzyg** [comment]
Hello @victorlap,

When you talk about accepting/denying changes, I'm going to assume you mean the Eloquent `Model` being audited and not the `Audit` itself.

The development version (4.x) of this package uses the `created`, `updated`, `deleted`, `restored` events, so when the auditing starts, the model has already been modified.

The current (3.1) and previous versions work a bit different, so you could potentially do what you want, although it's not its purpose.

This package is for logging purposes only and we're gonna keep it that way. What you're asking can be achieved by [validating](https://laravel.com/docs/5.4/validation) the data even before you hit the model, or using an [Observer](https://laravel.com/docs/5.4/eloquent#observers) that handles the `saving` event.

These tips should help you out n what you're looking for.
