### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by rafalau** [owen-it/laravel-auditing#189]
Hi, I need Help.
Model:
`<?php
namespace App\Models\Painel;

use OwenIt\Auditing\Auditable;
use Illuminate\Database\Eloquent\Model;

class Auditoria extends Model{
    use Auditable;
    protected $table = 'audits';
}`

Controller:
`<?php

namespace App\Http\Controllers\Painel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use \App\Models\Painel\Auditoria;

class AuditoriaController extends Controller {

    public function getIndex(){
        $audits = Auditoria::find(1)->audits;
        dd($audits);
        //return view('painel.auditoria.index', compact('audits'));
    }
}`

Return: Trying to get property of non-object

Auditing v 3.1 and Laravel 5.2

What am I doing wrong? Thank you very much in advance!

**Comment by quetzyg** [comment]
In which line is that happening?

**Comment by rafalau** [comment]
Hi, tks for help!
![teste](https://cloud.githubusercontent.com/assets/15903589/22422959/68f24c08-e6d6-11e6-8aa9-159c04488323.jpg)
![captura de tela 2017-01-30 as 10 24 03](https://cloud.githubusercontent.com/assets/15903589/22422961/70b27cc4-e6d6-11e6-950a-66ab56f97f06.png)
![captura de tela 2017-01-30 as 10 21 08](https://cloud.githubusercontent.com/assets/15903589/22422966/775261f2-e6d6-11e6-9b85-637724e84494.png)

**Comment by quetzyg** [comment]
Well, it seems `Auditoria::find(1)` returns `null`, so that's why you can't get to the `audits` attribute, since it doesn't exist.

**Comment by quetzyg** [comment]
I'm gonna mark this issue as closed, since this is more a PHP/Laravel debugging 101, not an actual issue with the package.

**Comment by rafalau** [comment]
Tanks
