### ISSUE TITLE
In 3.1 version is there $auditEnabled property?

### ISSUE THREAD

**Issue by thiagoaos** [owen-it/laravel-auditing#190]
In 3.1 version is there $auditEnabled property?
I didn't see in documentation. Is there a respective property or way to disable audit in a child model?

**Comment by quetzyg** [comment]
Hi @thiagoaos,

Can you explain a bit more about your use case? What are you trying to do, exactly?

**Comment by thiagoaos** [comment]
I have a BaseModel class 

`
namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable;

use Carbon\Carbon;

class BaseModel extends Model
{
    use Auditable;

    protected $auditEnabled  = true;
    // Clear the oldest audits after 50 records.
    protected $auditLimit = 50;
    // Specify what actions you want to audit.
    protected $auditableTypes = ['created', 'updated', 'deleted', 'saved', 'restored'];
    // Fields that you do NOT want to audit.
    protected $dontKeepAuditOf = ['password'];

    protected $casts = [];

    protected $dateFormat = 'Y-m-d H:i:sO';

    protected $dontFilterAttributesInDinamicQuery = ['password'];

    public function getDontFilterAttributesInDinamicQuery()
    {
        return $this->dontFilterAttributesInDinamicQuery;
    }
}
`

And all my models inherits of BaseModel.
But can be some model that i don't want to audit. In this case i change in that specify model $auditEnabled to false.

**Comment by quetzyg** [comment]
Try removing the `use Auditable;` from your base class/model and add it to each extending class you wish to audit. That should do what you want.

**Comment by quetzyg** [comment]
Marking as closed. See update to the previous reply.
