### ISSUE TITLE
Updated command do not record in audits table

### ISSUE THREAD

**Issue by rafalau** [owen-it/laravel-auditing#195]
Hi, Im using Laravel 5.2 and Auditing 3.1.  
When updating a post, only the USERS table writes the UPDATED action. The other tables do not. Below are sample images:

My USER model - UPDATED works fine
![captura de tela 2017-02-15 as 18 44 06](https://cloud.githubusercontent.com/assets/15903589/22994644/cf243560-f3ae-11e6-9556-81dd63b56557.png)

My NEWS Model - UPDATED do not record in audits table:
![captura de tela 2017-02-15 as 18 46 41](https://cloud.githubusercontent.com/assets/15903589/22994723/266991f8-f3af-11e6-84b3-12e7a2c2807b.png)

**Comment by rafalau** [comment]
Works with ->save();
Dont work with ->update();

**Comment by quetzyg** [comment]
Hi @rafalau 

Try using the development version:
```sh
composer require owen-it/laravel-auditing 4.0.x-dev
```
And let me know if the issue still persists.

You'll have to do minor changes to your code. Check the latest [documentation](http://www.laravel-auditing.com/docs/master/general-settings) if you have any doubts.

**Comment by rafalau** [comment]
Hi!
I followed the next steps:
1 - composer require owen-it/laravel-auditing 4.0.x-dev
2 - Add the service provider: OwenIt\Auditing\AuditingServiceProvider::class,
3 - Run: php artisan auditing:install
4 - migrate de data base

5 - Configure my Model:
![1](https://cloud.githubusercontent.com/assets/15903589/23081388/bc7fecd6-f53b-11e6-9d21-12e21f8e642e.png)

And the issue persists!
Works with ->save();
Dont work with ->update();

See My Update Comand (Dont record comand UPDATE in AUDITS DATABASE ):
![captura de tela 2017-02-17 as 18 07 57](https://cloud.githubusercontent.com/assets/15903589/23081469/1356a8d8-f53c-11e6-9538-c3a67a3bb7a8.png)

Se my Save Comand (Works fine)
![3](https://cloud.githubusercontent.com/assets/15903589/23081522/6328c5ee-f53c-11e6-9a18-7718c00c2783.png)

**Comment by lauri911** [comment]
Maybe this?

https://laravel.com/docs/5.4/eloquent

When issuing a mass update via Eloquent, **the saved and updated model events will not be fired** for the updated models. This is because the models are never actually retrieved when issuing a mass update.

**Comment by quetzyg** [comment]
@rafalau, do the logs show anything at all? 

What happens if you [listen](http://www.laravel-auditing.com/docs/master/events) for the `auditing` / `audited` events? Do they fire regardless of the Eloquent event (`saved`, `created`, `updated`) that started the audit process?

**Comment by anteriovieira** [comment]
Hi @rafalau , 

This may be the same as https://github.com/owen-it/laravel-auditing/issues/139#issuecomment-257004656

This type of query does not trigger events in laravel: `$model->where(...)->update(...)`

You will probably have to find the record, make the changes, and then save. 

Or force an audit log.

**Comment by rafalau** [comment]
Hi, How do I force an audit log?

**Comment by rafalau** [comment]
Hello, Quetzyg. Just like I said anteriovieira, $model->where(...)->update(...) does not trigger events in laravel.

**Comment by anteriovieira** [comment]
@quetzyg, could you provide an example of how @rafalau  can force an update audit?

**Comment by anteriovieira** [comment]
@rafalau , take a look [here](http://www.laravel-auditing.com/docs/master/auditor), maybe you can help. I can not create a test example now, but I think @quetzyg will be able to help you later.

**Comment by rafalau** [comment]
Okay, thank you so much for help.

**Comment by quetzyg** [comment]
As @anteriovieira mentioned, the way you're updating the model won't trigger the `updated` event, which in turn won't execute an audit.

I would suggest to update your code from:
```php
$this->model->where('id', $id)->update($dadosForm);
```
to what you have on the second code you show, but with a slight change:
```php
$dados = $this->model->find('id', $id);
$dados->update($dadosForm);
```
This should work, but it could still be improved. You should think about using model binding on the routes, so you don't have to query around to get the actual model. The model should just be passed to the `postEditar()` method.

And while the documentation has examples on how to use the [Auditor](http://www.laravel-auditing.com/docs/master/auditor) directly, you shouldn't need to if you play by the rules.

**Comment by rafalau** [comment]
Friends, I do not know how to express my gratitude. It's working perfectly. Here's what the final code looks like:
![captura de tela 2017-02-22 as 09 47 39](https://cloud.githubusercontent.com/assets/15903589/23212167/3aa82eba-f8e4-11e6-8eb4-8d7187704a8d.png)

**Comment by anteriovieira** [comment]
Thanks @rafalau , thank you for your confidence in our package. And I also thank @quetzyg  for his beautiful work.

**Comment by karmendra** [comment]
How do I Audit If I have a million records to update?
