### ISSUE TITLE
error when route is longer than 250 char

### ISSUE THREAD

**Issue by tunele** [owen-it/laravel-auditing#198]
There's an error when route is longer than 250 char, for example because of a many ulr vars.
I think that the route value might be truncated to a maximum of 250. Anyways, I think that an audit error should not affect the proper behaviour of the app. Or at least the plugin should provide a configuration option: break on audit error true or false.

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'route' at row 1

**Comment by quetzyg** [comment]
Hi @tunele,

If you work with huge URL's, that's something you'll have to account for. Just update the migration and increase the `VARCHAR` value or change the type to `TEXT`.

This issue has been already discussed [here](https://github.com/owen-it/laravel-auditing/issues/174) so I'll mark this as closed.
