### ISSUE TITLE
Precende Rule on AuditingTrait

### ISSUE THREAD

**Issue by shinodaluk** [owen-it/laravel-auditing#2]
Hi, i'm having this problem when trying to use the package in 5.1.

Project\Core\Admin\User and OwenIt\Auditing\AuditingTrait define the same property ($dontKeep) in the composition of Project\Core\Admin\User. However, the definition differs and is considered incompatible. Class was composed

**Comment by anteriovieira** [comment]
Hello shinodaluk, try this:
```php
use OwenIt\Auditing\Auditing;
class User extends Auditing 
{
     // ....
}
```
Currently we are having this problem, but I'm solving.

**Comment by anteriovieira** [comment]
The updates will not impact on your code. Logo will soon be corrected.

**Comment by anteriovieira** [comment]
@shinodaluk ,  were made some corrections, try running your code again.
