### ISSUE TITLE
Option dontKeepLogOf being ignored?

### ISSUE THREAD

**Issue by swimlappy** [owen-it/laravel-auditing#20]
Hello,

I implemented this package in a project of mine.  Very nice, easy to setup and worked right away.  Good stuff!

I noticed that it was logging the ```password``` field when I was creating a user, so I added that field to the ```dontKeepLogOf``` config option.  I still see that field showing up in the logs.  I tried this option on other models and the same behavior is there, it still writes to the log any field I ask it to ignore.  Here is my ```User``` model for reference, what might I be missing?

```
namespace app;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use OwenIt\Auditing\AuditingTrait;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract,
                                    SluggableInterface
{
    use Authenticatable, Authorizable, CanResetPassword, SluggableTrait, HasRolesAndAbilities, AuditingTrait;

    /**
     * Fields we DON'T want to register with auditing.
     */
    protected $dontKeepLogOf = ['password', 'remember_token'];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';
```

Do you have any suggestions as to what I might be doing incorrectly?  I am running ```Laravel Framework version 5.1.26 (LTS)``` and in my composer.json, I've required ```"owen-it/laravel-auditing": "^2.1"```.

Thanks!

**Comment by anteriovieira** [comment]
Hello my friend, thank you for your contribution. It was not your fault, but already corrected and took advantage to make some improvements.

The current version is ```v2.1.5```, use ```composer update owen-it/laravel-auditing``` to upgrade your version. Thanks for being part of this team, anything can call here.

**Comment by swimlappy** [comment]
Ah, that did work, sort of.  I upgraded from ```v2.1.4``` to ```v2.1.5``` and when I create a new user, the password field is no longer showing up in the log.  However, I deleted that user as a test and the log entry does show the password field.  Should that field be ignored for all operations?

**Comment by anteriovieira** [comment]
When removing the User, the skipped fields should not appear, this is what is happening?

**Comment by swimlappy** [comment]
Yes that is correct.  It appears when I remove the user.  The original issue of it appearing when the user is added has been fixed..

**Comment by anteriovieira** [comment]
@swimlappy you can test the version ```2.1.6```?

**Comment by swimlappy** [comment]
It is working now, thanks for the quick fix!

**Comment by anteriovieira** [comment]
I thank you for your help.
