### ISSUE TITLE
 AuditableContract not defined

### ISSUE THREAD

**Issue by juanpscotto** [owen-it/laravel-auditing#201]
Hi, just tried the new version the 4.0 and i'm getting an error trying to implement the interface.

use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

it does not exists!

Thanks

**Comment by quetzyg** [comment]
Hi @juanpscotto,

There is indeed an issue with the `4.0.0` tag, which references an older version of the code.

Thank you for your feedback!

**Comment by quetzyg** [comment]
Problem solved.

**Comment by juanpscotto** [comment]
Thanks! Yes realized now
