### ISSUE TITLE
Im trying to use, but i get this error. Please assist me.

### ISSUE THREAD

**Issue by hafizhassan** [owen-it/laravel-auditing#203]
ErrorException in AuditableObserver.php line 41:
Argument 1 passed to OwenIt\Auditing\AuditableObserver::updated() must be an instance of OwenIt\Auditing\Contracts\Auditable, instance of App\User given

what is the problem?

**Comment by quetzyg** [comment]
The problem is that the `User` model isn't implementing the `Auditable` contract. Please follow the [documentation](http://www.laravel-auditing.com/docs/4.0/introduction).

**Comment by hafizhassan** [comment]
thank you. my mistake. i didnt implementing the Auditable. thank you. it work like hell ;)
