### ISSUE TITLE
Model Configuration Problem

### ISSUE THREAD

**Issue by xdrakosha** [owen-it/laravel-auditing#205]
According to your documentation in order to exclude some fields from auditing I need to add this to my model: 

`protected $auditExclude = ['category_id'];`

but this give me the error:

> App\Post and OwenIt\Auditing\Auditable define the same property ($auditExclude) in the composition of App\Post. However, the definition differs and is considered incompatible. Class was composed

**Comment by quetzyg** [comment]
Hi @xdrakosha,

I'm looking into the issue. Thanks for your feedback.

**Comment by xdrakosha** [comment]
Ok . Tell me if you need some additional info.
