### ISSUE TITLE
Audit presentation

### ISSUE THREAD

**Issue by hafizhassan** [owen-it/laravel-auditing#206]
i tried to display the record.

**this is my model.**
namespace App;
use OwenIt\Auditing\Models\Audit as AuditModel;
class Audit extends AuditModel
{  }

**this is my controller** 
public function index()
{   
   $audits = Audit::all();
   return view('audit.index', compact('audits'));
 }

**this is the blade**
<ul>
    @forelse ($audits as $audit)
    <li>
        @lang('post.updated.metadata', $audit->getMetadata())

        @foreach ($audit->getModified() as $attribute => $modified)
        <ul>
            <li>@lang('post.'.$audit->event.'.modified.'.$attribute, $modified)</li>
        </ul>
        @endforeach
    </li>
    @empty
    <p>@lang('post.unavailable_audits')</p>
    @endforelse
</ul>

**when run it show** 
FatalErrorException in Audit.php line 167:
Call to a member function hasGetMutator() on null

what did i miss?
thank for the attention. thank you.

**Comment by quetzyg** [comment]
Have a look at the documentation, more specifically the [Getting Audits](http://www.laravel-auditing.com/docs/4.0/getting-audits) section.

**Comment by quetzyg** [comment]
Basically, you should get `Audit` records through a Model:

```php
$audits = $someModel->audits();
```
rather than calling `all()` from the `Audit` model itself.

**Comment by hafizhassan** [comment]
thank. ive miss something.

**Comment by mikebronner** [comment]
I was running into the same issue. Is there a way to get all audit entries? I have an admin page that show all updates, regardless of model.

**Comment by amendozaaguiar** [comment]
> i tried to display the record.
> 
> **this is my model.**
> namespace App;
> use OwenIt\Auditing\Models\Audit as AuditModel;
> class Audit extends AuditModel
> { }
> 
> **this is my controller**
> public function index()
> {
> $audits = Audit::all();
> return view('audit.index', compact('audits'));
> }
> 
> **this is the blade**
> 
> @forelse ($audits as $audit)
> * @lang('post.updated.metadata', $audit->getMetadata())
>   ```
>       @foreach ($audit->getModified() as $attribute => $modified)
>       <ul>
>           <li>@lang('post.'.$audit->event.'.modified.'.$attribute, $modified)</li>
>       </ul>
>       @endforeach
>   </li>
>   @empty
>   <p>@lang('post.unavailable_audits')</p>
>   @endforelse
>   ```
> 
> **when run it show**
> FatalErrorException in Audit.php line 167:
> Call to a member function hasGetMutator() on null
> 
> what did i miss?
> thank for the attention. thank you.

Gracias, andaba buscando un error, pero con tu post ya se como puedo solucionarlo, muchas gracias.

**Comment by hafizhassan** [comment]
> > i tried to display the record.
> > **this is my model.**
> > namespace App;
> > use OwenIt\Auditing\Models\Audit as AuditModel;
> > class Audit extends AuditModel
> > { }
> > **this is my controller**
> > public function index()
> > {
> > $audits = Audit::all();
> > return view('audit.index', compact('audits'));
> > }
> > **this is the blade**
> > @forelse ($audits as $audit)
> > 
> > * @lang('post.updated.metadata', $audit->getMetadata())
> >   ```
> >       @foreach ($audit->getModified() as $attribute => $modified)
> >       <ul>
> >           <li>@lang('post.'.$audit->event.'.modified.'.$attribute, $modified)</li>
> >       </ul>
> >       @endforeach
> >   </li>
> >   @empty
> >   <p>@lang('post.unavailable_audits')</p>
> >   @endforelse
> >   ```
> > 
> > **when run it show**
> > FatalErrorException in Audit.php line 167:
> > Call to a member function hasGetMutator() on null
> > what did i miss?
> > thank for the attention. thank you.
> 
> Gracias, andaba buscando un error, pero con tu post ya se como puedo solucionarlo, muchas gracias.

i dont understand ;D
