### ISSUE TITLE
Configurable Audit Model

### ISSUE THREAD

**Issue by Kaylakaze** [owen-it/laravel-auditing#211]
There should be a way to declare a custom Audit model. Since it extends from the default Eloquent model, it is currently incompatible with MongoDB. Simply changing which Model it "use"s worked with no problems, but editing vendor files is generally not a good idea.

**Comment by quetzyg** [comment]
Hi @Kaylakaze,

I'm assuming you changed the model being extended in the `Audit` class?
What's the class/package you're using for MongoDB?

**Comment by Kaylakaze** [comment]
I changed the from Illuminate\Eloquent\Model to Jenssegers\Mongodb\Eloquent\Model. My thought was it'd be easy enough for the end user to make their own copy of Audit in their app folder and change it how they need to and reference that in the config.

**Comment by quetzyg** [comment]
This issue should now be fixed in `master`. Try it out and let me know how it went. I'll close the issue once I get positive feedback.

I'll have to update the documentation, but what needs to be done is:

```php
<?php
namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;
use OwenIt\Auditing\Audit as AuditTrait;
use OwenIt\Auditing\Contracts\Audit as AuditContract;

class Audit extends Model implements AuditContract
{
    use AuditTrait;

    /**
     * {@inheritdoc}
     */
    public $timestamps = false;

    /**
     * {@inheritdoc}
     */
    protected $guarded = [];

    /**
     * {@inheritdoc}
     */
    protected $dates = [
        'created_at',
    ];

    /**
     * {@inheritdoc}
     */
    protected $casts = [
        'old_values' => 'json',
        'new_values' => 'json',
    ];
}
```

This is for you too, @bsormagec!

**Comment by quetzyg** [comment]
Actually, I might be missing a few more things, hold on.

**Comment by quetzyg** [comment]
OK, so...

Besides implementing an `Audit` class, like the previous example, you'll have to define the implementation you want to use in the configuration, like so:
```php
return [
    // ...

    'implementation' => App\Models\Audit::class,

    // ...
];
```
Don't forget to try the latest code in `master`.

Also, I have done a [pull request](https://github.com/owen-it/laravel-auditing-doc/pull/31) to update the documentation, so at some point that will be available too.

**Comment by quetzyg** [comment]
Marking issue as solved.
