### ISSUE TITLE
Exception occurred when triggering event that is not auditable

### ISSUE THREAD

**Issue by yeelok** [owen-it/laravel-auditing#212]
I have set $auditableEvents to only audit on update
`    protected $auditableEvents = [
        'updated'
    ];`

after that, when I create the eloquent modal it throws this below exception
`A valid audit event must be set`

**Comment by quetzyg** [comment]
Has the `$this->auditEvent` value been set? Have you followed the examples in the documentation? What are you doing exactly? The information provided is not enough to help you.

**Comment by yeelok** [comment]
Yes, i just want to only create audit when updating the model.
I haven't touch on the package source, so the $this->auditEvent is set as null
I have only add the $auditableEvents array in my model

**Comment by quetzyg** [comment]
Yes, you already said that. Can you show the actual code you're using?

**Comment by yeelok** [comment]
This is my model class
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Test extends Model implements AuditableContract
{
    use Auditable;

    protected $auditableEvents = [
        'updated',
    ];
}
```


This is the script to trigger the exception
```
$test = new \App\Test();
$test->save();
```

**Comment by quetzyg** [comment]
Working on a fix.
