### ISSUE TITLE
Can't cache config

### ISSUE THREAD

**Issue by bram1028** [owen-it/laravel-auditing#213]
The framework will fail to boot when you cache the config with the new resolver closure:
```
...
  'user' => [
        'model'    => App\User::class,
        'resolver' => function () {
            return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
        },
    ],
...
```
compiles to:
```
...
    'user' => 
    array (
      'model' => 'App\\User',
      'resolver' => 
      Closure::__set_state(array(
      )),
    ),
...
```

**Comment by quetzyg** [comment]
Hello @bram1028,

Yeah, a `Closure` in a config can't be cached, the same way that a `Closure` in a route. It's the price to pay for flexibility, I guess.

If you have an idea on how to overcome this issue, feel free to discuss.

I'll close this for now, though.

**Comment by bram1028** [comment]
A static method on the user model?

**Comment by quetzyg** [comment]
The documentation will be updated shortly, but meanwhile here's what you have to do:

Update the resolver configuration to use a FQCN instead of a `callable`:
```php
return [
    'user' = [
        'resolver' => App\User::class,
    ],
];
```
Implement the `OwenIt\Auditing\Contracts\UserResolver` interface on a class (`User` model, for instance):
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use OwenIt\Auditing\Contracts\UserResolver;

class User extends Model implements AuditableContract, UserResolver
{
    use Auditable;

    /**
     * {@inheritdoc}
     */
    public static function resolveId()
    {
        return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
    }

    // ...
}
```

**Comment by bram1028** [comment]
Well, I know that will work great, but I'm having some other trouble with ``config::cache`` now. It's not seeing the changes to the audit config and is still caching the old closure. Changes to other config files are being cached fine.

Thank you for this change!

**Comment by bram1028** [comment]
Found it! I didn't catch the filename change with v4...
