### ISSUE TITLE
Upgrade from 3.1 to 4.0

### ISSUE THREAD

**Issue by bekour** [owen-it/laravel-auditing#218]
Hi. Here's a snippet to migrate your exisiting audit log while upgrading from 3.1 to 4.0
It can save you some time.

    public function up()
    {
        Schema::table('audits', function(Blueprint $table)
        {
            $table->dropPrimary('id');
            $table->dropColumn('id');
        });
        Schema::table('audits', function (Blueprint $table) {
            $table->bigIncrements('id')->first('event');
            $table->renameColumn('type', 'event');
            $table->renameColumn('old', 'old_values');
            $table->renameColumn('new', 'new_values');
            $table->renameColumn('route', 'url');
        });
    }

    public function down()
    {
        Schema::table('audits', function (Blueprint $table) {
            $table->string('id', 36)->change();
            $table->renameColumn('event', 'type');
            $table->renameColumn('old_values', 'old');
            $table->renameColumn('new_values', 'new');
            $table->renameColumn('url', 'route');
        });
    }

**Comment by quetzyg** [comment]
Thanks for this @bekour! We'll include it in the documentation under the (soon to be added) Upgrading section.

**Comment by quetzyg** [comment]
Fixed in this [pull request](https://github.com/owen-it/laravel-auditing-doc/pull/22/).
