### ISSUE TITLE
Argument 1 passed to OwenIt\Auditing\AuditableObserver::created() must be an instance of 

### ISSUE THREAD

**Issue by riverajefer** [owen-it/laravel-auditing#219]
Hi good day.
I have the following error.

Argument 1 passed to OwenIt\Auditing\AuditableObserver::created() must be an instance of OwenIt\Auditing\Contracts\Auditable, instance of App\Models\Areas given

My Model

```
<?php
namespace App\Models;

use OwenIt\Auditing\Auditable;
use Illuminate\Database\Eloquent\Model;


class Areas extends Model
{
    use Auditable;
    .....
```
________________________

I hope you can help me .
thank you very much

**Comment by quetzyg** [comment]
Please refer to the documentation and make sure you follow the examples before creating a new issue.
This particular one has been covered a few times already (#181, #203, #207).

There's a basic example in the [introduction](http://www.laravel-auditing.com/docs/4.0/introduction).

**Comment by riverajefer** [comment]
Thank you very much.

My solution:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Auditable;
**use OwenIt\Auditing\Contracts\Auditable as AuditableContract;**


class Areas extends Model **implements AuditableContract
{**
    use Auditable;
```

**Comment by bthiban** [comment]
Carefully Read the documentations, you missed something definitely.

http://laravel-auditing.com/docs/9.0/model-setup
