### ISSUE TITLE
No changes to model data but audit log entry is created

### ISSUE THREAD

**Issue by wyred** [owen-it/laravel-auditing#221]
When a model is saved but no changes in data, and entry in the audits table is created, with the old_values and new_values being just []

Is this behavior intended?

And if so, is there a way to make it log only when there are changes?

Thanks!

![2017-03-29 15 48 36](https://cloud.githubusercontent.com/assets/432325/24444006/82a42ec0-1497-11e7-9236-4fae9f08d31d.png)

**Comment by anteriovieira** [comment]
Hi @wyred , this does not look like the default behavior. You can provide an example code?

**Comment by wyred** [comment]
Hi @anteriovieira ,

The code I use to trigger the above is just:

    $content = \App\Content::find(1);
    $content->save();

I tried it again but with a different model and it didn't happen. The only difference between these two models is that the one with the problem is using https://github.com/dimsav/laravel-translatable .

**Comment by anteriovieira** [comment]
Ping @quetzyg

**Comment by wyred** [comment]
Updating laravel-translatable to v7 does not fix the problem.

**Comment by quetzyg** [comment]
Hi @wyred, 

This is an issue with the [dimsav/laravel-translatable](https://github.com/dimsav/laravel-translatable) package, more specifically in the [Translatable.php](https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php) trait.

The [save()](https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php#L204) method event fire logic does not make sense:

```php
            if (count($this->getDirty()) > 0) {
                // If $this->exists and dirty, parent::save() has to return true. If not,
                // an error has occurred. Therefore we shouldn't save the translations.
                if (parent::save($options)) {
                    return $this->saveTranslations();
                }
                return false;
            } else {
                // If $this->exists and not dirty, parent::save() skips saving and returns
                // false. So we have to save the translations
                if ($saved = $this->saveTranslations()) {
                    $this->fireModelEvent('saved', false);
                    $this->fireModelEvent('updated', false);
                }
                return $saved;
            }
```

As you can see from the code fragment, the `updated` event is fired when no changes were made to the main model. Raise an issue with the package maintainer so he can apply the fix where appropriate.

I'm marking this issue as closed now.

**Comment by wyred** [comment]
@quetzyg Ok, thanks!

**Comment by wyred** [comment]
Just in case anyone else has the same problem, here's what I did.

Create a new driver using the console command: `./artisan make:audit-driver NoEmptyAudits`

This will create a new file: `app/AuditDrivers/NoEmptyAudits.php`

In audit(), add the lines:

        $changes = $model->toAudit();

        if (empty($changes['old_values']) and empty($changes['new_values'])) {
            return null;
        }

        return Audit::create($changes);

As for prune(), you can just copy the same code inside vendor/owen-it/laravel-auditing/src/Drivers/Database.php
