### ISSUE TITLE
User with UUID

### ISSUE THREAD

**Issue by rafael-franca** [owen-it/laravel-auditing#223]
**System**
SO: Windows Server 2012 R2
IIS 8.0
PHP Version: 7.0.15
SQL Server 2012 using Microsoft PHP drivers for SQL Server (version 4.1.3)

Laravel version: 5.4.18
UUID (webpatser/laravel-uuid) version: 2.0.1
Auditing (owen-it/laravel-auditing) version: 4.0

**Message Error**
"SQLSTATE[22018]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server] Conversion failed when converting the nvarchar value '88592790-1f19-11e7-a652-57e61d0cf532' to data type int. (SQL: insert into [audits] ([old_values], [new_values], [event], [auditable_id], [auditable_type], [user_id], [url], [ip_address], [created_at]) values ([], {"username":"usuario","first_name":"Rafael","middle_name":"","last_name":"Fran\u00e7a","departamento":"Administra\u00e7\u00e3o","cargo":"Diretor","email":"email@hotmail.com","password":"","business_id":"40C1D420-1F19-11E7-8F44-474A05AD6C56","id":"88592790-1f19-11e7-a652-57e61d0cf532"}, created, 88592790-1f19-11e7-a652-57e61d0cf532, App\User, , http://localhost/account/register, 177.208.178.47, 2017-04-11 21:46:58.000))"

**Context**
When I use UUID (by webpastser) I receive the following error. When I disable Auditing, it's OK. This error only occurs in the SQL Server, I already tested it on MySQL and it's OK!

**PS**
For work in MySQL, I change "user_id" to 'uuid' in the migrate called Audits.

**Comment by quetzyg** [comment]
The default migration creates the users table with the `user_id` column as `int`, not `varchar`. You'll have to update your table to reflect this use case in order for it to work.

**Comment by rafael-franca** [comment]
@quetzyg I do not think I made the problem too clear. My `user_id` is a `UUID`, so I can not use an `int`. And as I mentioned above, in MySQL it works normally, the problem only occurs in SQL Server.

**Comment by quetzyg** [comment]
The error message you have submitted states: `Conversion failed when converting the nvarchar value '88592790-1f19-11e7-a652-57e61d0cf532' to data type int`.

Which means, the `audits` table has the `user_id` column with a type of `INT`, not `NVARCHAR`. Unless I'm missing something obvious?

**Comment by rafael-franca** [comment]
Exact. But, my migrate `audits` table:
```
Schema::create('audits', function (Blueprint $table) {
            $table->increments('id');
            $table->uuid('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users');
            $table->string('event');
            $table->morphs('auditable');
            $table->text('old_values')->nullable();
            $table->text('new_values')->nullable();
            $table->string('url')->nullable();
            $table->ipAddress('ip_address')->nullable();
            $table->timestamp('created_at');
});
```
And, in SQL Server Management Studio, I verified `user_id` in my table `audits` has `NVARCHAR(191)`.

That is, where is converting from `NVARCHAR` to `INT`?

**Comment by rafael-franca** [comment]
I found the cause of the problem.

The Laravel Auditing was trying to insert the information not in the `user_id`, but in the `auditable_id`.

Just change the migrate to the following:
```
Schema::create('audits', function (Blueprint $table) {
            $table->increments('id');
            $table->uuid('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users');
            $table->string('event');
            $table->uuid('auditable_id');
            $table->string('auditable_type');
            $table->text('old_values')->nullable();
            $table->text('new_values')->nullable();
            $table->string('url')->nullable();
            $table->ipAddress('ip_address')->nullable();
            $table->timestamp('created_at');
});
```
Please, if possible, add this information to the documentation to help other users in the future.

Thanks.

**Comment by AhSem** [comment]
Hi, I would like to create the 'audits' table with uuid as the primary key instead of incrementing id. When I do that, how am I supposed to create the uuid when inserting into the 'audits' table?

**Comment by quetzyg** [comment]
Hi @AhSem,

The easiest way I can think of, is using an observer. Try the following:

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use OwenIt\Auditing\Models\Audit;
use Ramsey\Uuid\Uuid;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Audit::creating(function (Audit $model) {
            $model->id = Uuid::uuid4();
        });
    }
 
    // ...
}
```

**Comment by AhSem** [comment]
Thank you @quetzyg , this works nicely.
