### ISSUE TITLE
[Feature request] Please add browser user agent to audit log

### ISSUE THREAD

**Issue by ivuorinen** [owen-it/laravel-auditing#224]
Currently the package contains everything that one could hope and works perfectly keeping log what has changed and who made the change. Thank you!

Why add Browser user agent? Adding the information could for example help debug problems when dealing with JavaScript based operations.

In one of my projects users create data structures with JavaScript based designer, and there has been few cases when something strange has happened and this package logged it perfectly. Now to prevent the problem from happening again, I've had to contact the user and request details which they rarely know how to get. Adding the browser user agent could drastically speed up error detection and fixing.

Thank you for considering this feature request.

**Comment by anteriovieira** [comment]
Hi @ivuorinen , feel free to send us a pull request 😉

**Comment by adam-devapp** [comment]
+1
