### ISSUE TITLE
Getting related attribute for old_values

### ISSUE THREAD

**Issue by DonovanChan** [owen-it/laravel-auditing#227]
I'm adding display values for foreign keys like was shown in the the docs.

```php
    public function transformAudit(array $data)
    {
        if (Arr::has('new_values.role_id')) {
            Arr::set($data, 'new_values.role_name',  $this->role->name);
        }

        return $data;
    }
```

I'd like to display the previous value in my views as well. I'm assuming the best way to do this is to add the previous value to the old_values array.

```php
    public function transformAudit(array $data)
    {
        if (Arr::has('new_values.role_id')) {
            Arr::set($data, 'new_values.role_name',  $this->role->name);
            Arr::set($data, 'old_values.role_name',  '??? role name using original foreign key ???');
        }

        return $data;
    }
```

Is there a way to leverage a relation to retrieve a related value once the foreign key is dirty? Or is there a better way to go about it?

Thanks.

**Comment by quetzyg** [comment]
Off the top of my head, wouldn't `Role::find($data['old_values']['role_id'])->name` work?

**Comment by DonovanChan** [comment]
Yes. I think I'll do that. I was hoping there was some way to use the relation defined in my model so that I could avoid specifying the key field. But I suppose it's academic since the key is already being referenced in the conditional. Thanks.
