### ISSUE TITLE
Laravel 5.2 config('auth.model') is gone

### ISSUE THREAD

**Issue by SERVANT14** [owen-it/laravel-auditing#23]
I noticed this after upgrading. OwenIt\Auditing\Log model has a relation that expects this to exist.

Here's the change for 5.2:
https://github.com/laravel/laravel/commit/8414d45cdc351e495016bc19ba2821a5d76c494e#diff-3fc9d8e570780c4eb337c6f860b1e8e0L22

It looks like it moved here: https://github.com/laravel/laravel/blob/develop/config/auth.php#L70

Here's the relationship in the Log model:
https://github.com/owen-it/laravel-auditing/blob/master/src/Log.php#L52

I'm not sure the proper way to get at this now, just thought I'd bring it up.

**Comment by anteriovieira** [comment]
Thank you @SERVANT14 , I'll check.

**Comment by anteriovieira** [comment]
Added the configuration file auditing, for now we solve our problems, but we have to mention in the documentation as well. This can be a good alternative, since in the future we may need more settings.

Fixed in PR https://github.com/owen-it/laravel-auditing/pull/24.
