### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by 1e4** [owen-it/laravel-auditing#231]
On the [Installation](http://www.laravel-auditing.com/docs/4.0/installation) page, the link to "Read more about it in the Package Options." is broken.

It should link to 
http://www.laravel-auditing.com/docs/4.0/general-settings
not
http://www.laravel-auditing.com/docs/4.0/general-settings.md

**Comment by anteriovieira** [comment]
Fixed.

Thanks!
