### ISSUE TITLE
Everything breaks after install

### ISSUE THREAD

**Issue by jaminscript** [owen-it/laravel-auditing#234]
After installing this package my Laravel installation breaks. After redownloading a fresh copy to try this again, it also breaks. The error I get is as follows:

`[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Closure::__set_state()`

These are the steps I followed:

Step 1: `composer require owen-it/laravel-auditing`

Step 2: Add `OwenIt\Auditing\AuditingServiceProvider::class,` to my `config/app.php` inside the `providers` section.

Step 3: Clear the cache because Laravel doesn't know about this new package `php artisan config:cache`. Not doing this step obviously results in errors.

Step 4: Final step: `php artisan auditing:install`

Step 5: Report to this repo as it spews out the above issue.

<img width="457" alt="broken" src="https://cloud.githubusercontent.com/assets/2616473/25597839/44d01b92-2f25-11e7-9d46-e1892197b3a0.PNG">

Any ideas?

**Comment by quetzyg** [comment]
Hi @jaminscript,

I did the following steps, but could not reproduce such error:

Create a new project:
```sh
create-project --prefer-dist laravel/laravel blog
```

Install the package:
```sh
cd blog
composer require owen-it/laravel-auditing
```

Add `OwenIt\Auditing\AuditingServiceProvider::class` to the providers `array` in `config/app.php`.

Publish the default configuration file:
```sh
php artisan auditing:install
```
Get this output:
![auditing-install](https://cloud.githubusercontent.com/assets/1413966/25611658/cc9f7d16-2f1f-11e7-94f9-50cdd1c79a6a.png)

**Comment by sjmarve** [comment]
Also having the same issue in laravel 5.4. Because of this part in the `config/audit.php`: 
` 'user' => [
        'model'    => App\User::class,
        'resolver' => function () {
            return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
        },
    ],`
`php artisan config:cache` is causing the creation of the following in `cache/config.php`:

`...
array (
    'user' => 
    array (
      'model' => 'App\\User',
      'resolver' => 
      Closure::__set_state(array(
      )),
    ),
    'default' => 'database',
    'drivers' => 
    array (
      'database' => 
      array (
        'table' => 'audits',
        'connection' => NULL,
      ),
    ),
    'console' => true,
  ),
...`

which is causing the error: 
`Error: Call to undefined method Closure::__set_state()`

**Comment by quetzyg** [comment]
Use a FQCN instead of a closure. See [here](http://www.laravel-auditing.com/docs/4.0/general-settings).
