### ISSUE TITLE
Update 4.0.4 Breaks Migrations

### ISSUE THREAD

**Issue by mikebronner** [owen-it/laravel-auditing#235]
The update to the migration stub file broke things for existing installs. A second update stub should probably be created, and auditing:install updated such that it will publish the update stub with the user agent.

**Comment by quetzyg** [comment]
Hi @mikebronner,

There's a [pull request](https://github.com/owen-it/laravel-auditing-doc/pull/26) for the documentation repository with upgrade instructions for `4.0.4` and other minor stuff.

Thanks for reporting the issue, this one slipped.

**Comment by quetzyg** [comment]
The [updated documentation](http://www.laravel-auditing.com/docs/4.0/upgrading) is now online.

**Comment by mikebronner** [comment]
Thanks :) Any thoughts on making an upgrade command to augment the install command? I don't have time right now, but would consider working on a PR for it sometime in the future.

**Comment by quetzyg** [comment]
I wouldn't lose sleep over it.
