### ISSUE TITLE
Closure in Configuration file generate problem with config:cache

### ISSUE THREAD

**Issue by Belphemur** [owen-it/laravel-auditing#237]
Laravel can't cache a closure correctly when in the config file.

The user->resolver would be better to a method of a class and use the container to call it than put a closure into it.

As a closure, laravel can't cache it.

Ps: I didn't see any warning about this in the documentation.

**Comment by quetzyg** [comment]
Not wanting to sound like a jerk, but did you at least made the effort to [read](http://www.laravel-auditing.com/docs/4.0/general-settings) the [documentation](http://www.laravel-auditing.com/docs/4.0/troubleshooting) or search for [similar](https://github.com/owen-it/laravel-auditing/issues/234) [issues](https://github.com/owen-it/laravel-auditing/issues/213)?

Thought so...

**Comment by Belphemur** [comment]
@quetzyg Darn, I missed the troubleshooting part.

Sorry ...

**Comment by scs75** [comment]
This totally screw up the the installation process.
Putting closure in config file is utter misdesign. A config file should be a declarative thing, not a functional process. Remnant of spaghetti php.

**Comment by quetzyg** [comment]
![dyer](https://user-images.githubusercontent.com/1413966/27177985-47c30298-51c0-11e7-94c7-9d69645d81d7.jpg)

Can you, @scs75 ?
