### ISSUE TITLE
Doesn't work with API routes?

### ISSUE THREAD

**Issue by gleman17** [owen-it/laravel-auditing#241]
Just installed it with Laravel 5.4.  Works great with the app (the web routes), but when I make an API call the auditing doesn't happen.  Am I missing something?

**Comment by quetzyg** [comment]
Yeah, you're missing:
- The code you're using to store data when accessing the web routes
- The code you're using to store data when accessing the API endpoints
- Other relevant/useful information

I know you want help, but what's the point of opening an issue without any of the above?

**Comment by gleman17** [comment]
I didn't include it because the code is exactly the same.  Here's the test case I was using:

web.php:

```php
Route::group(['middleware' => ['web']], function () {       
        Route::get('/testuseraudit', function() {
                $audit_count_start = \App\Audit::count();               
                $user = \App\User::first();
                $user->hire_date = Carbon::now()->toDateTimeString();
                $user->save();
                $audit_count_end = \App\Audit::count();                
                if ($audit_count_start == $audit_count_end) {
                    echo "This doesn't work";
                } else {
                    echo "This works!";
                }
        });
```
api.php:
```php
Route::group([ 'middleware' => 'auth:api'], function () {        
        Route::get('/testuseraudit', function() {
                $audit_count_start = \App\Audit::count();
                $user = \App\User::first();
                $user->hire_date = Carbon::now()->toDateTimeString();
                $user->save();
                $audit_count_end = \App\Audit::count();
                if ($audit_count_start == $audit_count_end) {
                    echo "This doesn't work";
                } else {
                    echo "This works!";
                }               
        });
```

A simple "No, you're not missing anything, the package doesn't treat the routes differently" would have been sufficient.  It turns out that I had a bug in the API auth code that was not letting the Auth::user() function work correctly.  Maybe this will save some other poor soul several hours.
