### ISSUE TITLE
How to implement owen-it/laravel-auditing in a model

### ISSUE THREAD

**Issue by mike23v** [owen-it/laravel-auditing#242]
I want to create an audit trail in my model. I already installed owen-it/laravel-auditing package via Composer. My question is that how can I implement it in my Model or controller. Please see my code for controller and Model below. Thanks

My Controller :

```
<?php

namespace App\Http\Controllers;

use App\Events\Test;
use App\Letter;
use App\Notifications\LetterNotification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Validator;

class LetterController extends Controller
{
    public function viewLetter()
    {
        return view('welcome');
    }

    /**
     * Saves email into database
     *
     * @param  array  $data
     * @return Letter
     */
    protected function create(array $data)
    {
        $letter = Letter::create([
            'email' => $data['email']
        ]);
        $this->letterNotify($letter);

        return $letter;
    }

    /**
     * Validates email
     */
    public function createLetter(Request $request)
    {
        $this->validate($request,[
            'email' => 'required|email|max:255|unique:letters'
        ],[
            'email.required' => 'Email is required.',
            'email.unique' => 'Already registered.',
            'email.email' => 'Please put a valid Email address'
        ]);

        $this->create($request->all());

        return redirect('/')->with('info','You are now registered.');
    }

    protected function letterNotify($letter)
    {`enter code here`
        Notification::send($letter, new LetterNotification($letter));
    }


}
```
For my Model:

```
<?php

namespace App;

use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Letter extends Model implements AuditableContract
{
    use Notifiable;

    use Auditable;

    protected $fillable = ['email'];

    protected $table = 'letters';
}
```

**Comment by quetzyg** [comment]
The `Letter` model seems to be fine and while I'm not a fan of having business logic in controllers, the `createLetter()` and `createLetter()` methods look OK too. What is the problem, exactly? Doesn't it work?

**Comment by mike23v** [comment]
Hi quetzyg,

My problem is that how can I implement audit trail using the said package? I'm already done installing the said package. Do you have any step by step demo using the laravel-auditing version 4.0? Thanks

**Comment by quetzyg** [comment]
Yes, the [documentation](http://www.laravel-auditing.com/docs/4.0) has examples on how to set up (you already did that) and examples on how to fetch audits and other stuff.

There's also a [troubleshooting ](http://www.laravel-auditing.com/docs/4.0/troubleshooting) section which you should check in case of trouble.

I'm marking this as closed, since this is not an issue with the package itself, but more of a support request.

**Comment by mike23v** [comment]
Hi quetzyg,

Yes, you can closed it. Thanks
