### ISSUE TITLE
Fails on non-integer primary keys

### ISSUE THREAD

**Issue by mikebronner** [owen-it/laravel-auditing#243]
I occasionally use non-inter primary keys, mainly for lookup-tables, which is causing the audit record insert to fail with `Invalid text representation: 7 ERROR:  invalid input syntax for integer: "sdfsdfasdfsdf" in ...`.

Is there a workaround or fix for this? Thanks! (I checked the documentation, but didn't see anything about this there.)

**Comment by quetzyg** [comment]
You'll have to update the `audits` table to accommodate that need. I assume you're referring to the `user_id`? Just change it to string/uuid and you should be good to go. Let us know it went.

**Comment by mikebronner** [comment]
Haha -- now you tell me :) I already went in and converted all the lookup tables to use unsigned integer PKs. I'll test it on  the next project I work on.

This wasn't for the user table, but other tables, it was the `audible_id` field. Could I make a PR to make that string by default? Will that hurt the index performance?

Thanks!
~Mike

**Comment by quetzyg** [comment]
Hey Mike,

The `audits` table has to reflect the column `id` types for each `Auditable` model you've got. Be it string/uuid or integer, as long as it matches your other tables you should be fine.

As mentioned in the [documentation](http://www.laravel-auditing.com/docs/4.0/troubleshooting), the base migration covers most use cases, but it's not written in stone. It's up to the developer to change the default column types (`id`, `user_id`, `auditable_id`, `url`, `user_agent`) if needed.

I'll close this issue once I update the documentation for the `auditable_id` case.

**Comment by mikebronner** [comment]
Thanks for the response. I just want to clarify something you said:

>Be it string/uuid or integer, as long as it matches your other tables you should be fine.

Are you saying it **must** match? In that case would it still break for those tables that have integer primary keys if I set `auditable_id` to string? Just wanting to make sure I understand the requirements. :) Thanks again!

**Comment by quetzyg** [comment]
Hi @mikebronner,

I guess you could have the `auditable_id` as `VARCHAR(255)`, even if the column types in other tables are `BIGINT`. The other way around wouldn't work, though. I tend to use the same column type for ids across my database, to avoid any issues. Also, I tend to use foreign keys, so if you're thinking of doing the same, you'll definitely have to use the same type, not a mix of string/integer.

Hope that makes sense.

**Comment by quetzyg** [comment]
The documentation has been updated.
