### ISSUE TITLE
Executing audit when need

### ISSUE THREAD

**Issue by reazul-islam** [owen-it/laravel-auditing#246]
I am using 4.0 version in Laravel 5.4
It works fine when I configure by default:
Here is my Controller: 
```
public function update($lang,$company,$id,CommonRequest $request)
    {
        try {
            $branch= Branch::where('code',$id)->where('company_id',COMPANY_ID)->first();
            $branch->update([
                'code' => $request->code,
                'name'=>$request->name,
                'updated_by'=> Auth::user()->user,
            ]);
            if ($audit = Auditor::execute($branch)) {
                Auditor::prune($branch);
            }
        }
        catch (\Exception $e){
             return $e;
        }
    }
```
In documentation  http://www.laravel-auditing.com/docs/4.0/auditor here told that , if I keep blank $auditableEvents =[] so it will works. but If I keep blank it do nothing. but If I keep as like this 
protected $auditableEvents = ['deleted','created','updated']; so It works but insert also a empty row. 

If I delete this code so it works fine. 
```
            if ($audit = Auditor::execute($branch)) {
                Auditor::prune($branch);
            }

```
But I want to execute audit when I need , that means when a user wants to keep track only then the auditing code will work.

**Comment by quetzyg** [comment]
First of all, what are you trying to achieve, exactly? Why are you explicitly calling the `Auditor`?

**Comment by reazul-islam** [comment]
Actually I need enable the audit log system  when user wants. 
For example: I have two Model Post & Product.  log system depend on user wish. If any user wants to keep log of Post Model so he can, or If any user wants to keep log of Product Model so he can do that. 
I mean I want to put a condition in controller if that condition true then execute the Auditor. 

i.e: 
```
$logEnable=true; //this variable will set from DB 
if($logEnable){
//Then Execute Auditor
}
```

**Comment by quetzyg** [comment]
To achieve what you want, I would probably override the `getAuditableEvents()` method in the `Auditable` trait and return an `array` with whatever events the `User` has set in the table.

**Comment by reazul-islam** [comment]
**It works!** I follow this way. Actually I overwrite the protected $auditableEvents  = array();
The controller like this : 
```
$branch= Branch::where('code',$id)->where('company_id',COMPANY_ID)->first();
            $branch->setEvent('updated'); //this is conditional . call when user wants to execute log
            $branch->update([
                'code' => $request->code,
                'name'=>$request->name,
                'updated_by'=> Auth::user()->user,
            ]);
```
Model Like this: 
```
protected $auditableEvents  = array();
public function setEvent($event){
        $this->auditableEvents=[$event];
    }
```

**Comment by quetzyg** [comment]
Cool. If it works, I'm closing the issue.

**Comment by saber13812002** [comment]
how can i run my custom event when Auditing Laravel fired.?
