### ISSUE TITLE
Class Not Found Error After Schema Change

### ISSUE THREAD

**Issue by mikebronner** [owen-it/laravel-auditing#247]
When renaming or removing classes that were previously audited, it breaks the audit history when outputting all audits: 

```php
$audits = (new AuditModel)->orderBy('created_at', 'DESC')->paginate(100);
```

The problem seems to be somewhere in the `auditable()` method of the Audit model, but not quite sure what needs to be updated to check if the audited class exists or not. I would like to submit a PR for this, and welcome any thoughts or ideas you have on this. :)

Thinking there should be a check before `return $this->morphTo()`.

**Comment by quetzyg** [comment]
Hi @mikebronner,

If you change the class name, or move it to another namespace, you should update the records for it in the `audits` table. If they're still relevant, of course! If not, there's no point in keeping data that no longer makes sense and you don't care about.

Also, you should check Laravel's [morphMap](https://laravel.com/docs/5.4/eloquent-relationships#polymorphic-relations) feature for polymorphic relations, to avoid just what you described.

I don't see this as an issue with the package, but with the application using it.
Having said that, I'm gonna close this issue.

Cheers!

**Comment by mikebronner** [comment]
@quetzyg I don't quite agree. Over the lifecycle of a product, things change as it evolves. This package should handle those changes gracefully, and not error out. I will definitely read up on the morphMap feature, but not sure that is the solution.

**Comment by quetzyg** [comment]
Yeah, products evolve, I get that. But data also has to evolve, don't you think?

Currently you describe two scenarios:
**1)** You have data that **can still be relevant**, as long as you update the `auditable_type` column, yet you don't want to;
**2)** You have data with **no relevance**, because the class type has been deleted altogether and you don't want to get rid of that data;

If what you propose is to just ignore that data, you might as well get rid of it, since you don't seem to have interest in it.

For **1)** you can just do:
```php
DB::table('audits')->where('auditable_type', 'App\Model\Old')->update(['auditable_type' => 'App\Model\New']);
```
And for **2)**:
```php
DB::table('audits')->where('auditable_type', 'App\Model\Deleted')->delete();
```

The `morphMap` is a solution when you rename classes, but it won't work for deletes.

**Comment by mikebronner** [comment]
Hi @quetzyg, you're right, it might be an issue of expectations. I see auditing as a snapshot in time regardless of past or future. Something that I can refer to years from now if I have to.

Changing the entries in the audit log to match the current model configurations means I am altering history. (I'm speaking purely on a procedural level, not specific to Laravel Auditing). 

Its probably a matter of semantics as to what you want to do with the audit log entries: 
- are you concerned about being relevant to current functionality
- or are you concerned about tracking exactly what happened any given moment

My initial thought for ignoring the information was to get around the error, then figuring out a way to display it without loading the original model that no longer exists (which might not be possible).

I can see the point being made that the purpose of this package is only to display current relevant data, and not historical data that no longer matches up with current models, requiring the developer to make some database updates, which is where my expectation probably needs some adjusting. :)

I have renamed the models in question in the auditing table and have moved on successfully. I will have to see what the client expects down the road. If they expect a complete historic audit trail regardless of changes, perhaps a database-level audit log would be more appropriate, something that just makes entries as metadata, and does not care about models in any way.

Thanks for taking the time to discuss this. :)

**Comment by dhampik** [comment]
This issue has more sense now when Laravel 8 [introduces](https://laravel.com/docs/8.x/releases#models-directory) a new dedicated `Models` directory. There are some good points in the comments, however, it might make sense to add information about the proper way to migrate models from one place to another to the official documentation.

PS. my main concern about using the DB update is that the table could be huge and the update could take quite a while.
