### ISSUE TITLE
no data inserted into audit table .

### ISSUE THREAD

**Issue by KhairulAzmi21** [owen-it/laravel-auditing#248]
i have followed documentation but nothing insert in my audit table . 

I remove semicolon after AuditableContract , because laravel says its an error :

class Post extends Model implements AuditableContract;

**Comment by quetzyg** [comment]
Have you read the [troubleshooting](http://www.laravel-auditing.com/docs/4.0/troubleshooting) section?
What exactly are you doing? Where's the code? You do realise that without proper information no one is able to help you, right?

Also, thanks for pointing out the semicolon typo in the documentation examples, it's fixed now.
