### ISSUE TITLE
3rd Table Auditing

### ISSUE THREAD

**Issue by sonesay** [owen-it/laravel-auditing#25]
Hi there, can someone provide examples of enabling audits on 3rd table changes? I am trying to use the attach() and detach() method on the parent object but these changes to the 3rd table go untracked. 

Any help appreciated thanks

**Comment by anteriovieira** [comment]
Hi @sonesay ,

do you can show us your example?

I shall be happy to assist you.

**Comment by sonesay** [comment]
HI  there. 

I have a user('users') and group('groups') model. there is a 3rd table which has no model and used to create a one to many relationship between user and groups 'users_groups'

In my model 
-------------------------------------------------
$groups = is_array($request['groups']) ? $request['groups'] : array();
                foreach ($user->groups as $g) { // Remove groups no posted
                    if (!in_array($g->id, $groups)) {
                        $user->groups()->detach($g->id);
                    }
                }
                foreach ($groups as $g) { // Add groups posted
                    if (!$user->groups->find($g)) {
                        $user->groups()->attach($g);
                    }
                }

**Comment by anteriovieira** [comment]
In this case you would like to audit user and group? or only user?

```php
    // our models

    use Illuminate\Database\Eloquent\Model;

    class User extends Model {
        //...
    }

    class Group extends Model {
        //...
    }

    class ExGroup extends Model {
        //...
    }
```

or something like that:

```php
    // audited user data.
    [
        'old_values' => [
            'name' => 'anterio',
            'groups' => []
        ],
        'new_values' => [
            'name' => 'anterio.silva',
            'groups' => [ 8, 4, 9, 3 ]
        ],
    ]
```

**Comment by sonesay** [comment]
Hi Anteriovieira

I am currenly auditing my User model successfully. The problem I am facing here is the link between user and group is done via the 'users_groups' table. I will eventually audio the Group table as well but I think I wont have an issue because it seems to work failry easy for user. 

So back to my problem with the 3rd table. I do not store the users group association in the user table. This is done by the  users_groups table.

mysql> desc users_groups;
+----------+------------------+------+-----+---------+----------------+
| Field    | Type             | Null | Key | Default | Extra          |
+----------+------------------+------+-----+---------+----------------+
| id       | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| uid      | int(11)          | NO   | MUL | 0       |                |
| group_id | int(11)          | NO   | MUL | 0       |                |
+----------+------------------+------+-----+---------+----------------+

Does this make sense?

**Comment by anteriovieira** [comment]
Hi @sonesay ,
I'm sorry for the delay, I am seeing this more calmly. And my time is very short. But I have not forgotten you.

**Comment by sonesay** [comment]
Thank you. I'm sure there would be many out there with similar requirements.

Regards
Sone

**Comment by anteriovieira** [comment]
Hi @sonesay ,
Have you had any progress on this issue?
I did not have success.

**Comment by anteriovieira** [comment]
Hi @sonesay ,

It has not yet support the 3rd table, but I'm studying this case. If you have any suggestions I will be grateful with your help.

Thank you for reporting :)

**Comment by anteriovieira** [comment]
Hi @sonesay , I will implement this feature, you want to help me?

**Comment by sonesay** [comment]
Sure I can try. I'm still new to Laravel so I wont know as much as you do.

**Comment by anteriovieira** [comment]
We have to know how [eloquent](https://laravel.com/api/5.2/Illuminate/Database/Eloquent.html) works. We will study their methods and see the what he can provide us.
