### ISSUE TITLE
Cannot cache config

### ISSUE THREAD

**Issue by manniL** [owen-it/laravel-auditing#250]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.24
| Package version   | latest
| PHP version       | 7.0.y

#### Actual Behaviour

I wanted to cache the config as usual but because of the closure

```
    /*
    |--------------------------------------------------------------------------
    | User Model & Resolver
    |--------------------------------------------------------------------------
    |
    | Define the User model class and how to resolve a logged User ID.
    |
    */
    'user' => [
        'model'    => App\User::class,
        'resolver' => function () {
            return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
        },
    ],
```

it renders artisan and the laravel app unusable.

#### Expected Behaviour

No problems when using `php artisan config:cache`

#### Steps to Reproduce

Use `php artisan config:cache`

#### Possible Solutions

Remove the closure :P

**Comment by quetzyg** [comment]
Oh for fuck's sake, not this again. Mate, I've spent quite an amount of time properly documenting the package. Why would it be easier to create a new issue and wait for a reply, than doing a simple search, either in the GitHub [issues](https://github.com/owen-it/laravel-auditing/issues?utf8=%E2%9C%93&q=is%3Aissue%20cache%20config) or the [troubleshooting](http://www.laravel-auditing.com/docs/4.0/troubleshooting) section.

**Comment by manniL** [comment]
Sorry @quetzyg ^.^#
