### ISSUE TITLE
How to add custom event or use on custom function

### ISSUE THREAD

**Issue by maulikrajput** [owen-it/laravel-auditing#252]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.x.y
| Package version   | 4.x.y
| PHP version       | 5.x.y|7.x.y

#### Actual Behavior
i implementing this package in my laravel project i can see that all the event that working fine and getting logging(inserted) in audit table and working fine all crud operation.

#### Expected Behavior
i have other method like print,send email , approve order etc.how to enable audit logging on that functions.

**Comment by quetzyg** [comment]
The issue template was added for a reason. I have no idea what you're doing (I see no code), what you're getting (no actual behaviour or errors) or what exactly you're expecting (what you wrote doesn't help).

Update the issue, following the guidelines or I'll be forced to mark it as closed.
