### ISSUE TITLE
How to dynamically audit a model in a package

### ISSUE THREAD

**Issue by eComEvo** [owen-it/laravel-auditing#253]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.3.31
| Package version   | 4.0.6
| PHP version       | 7.1.6

I'm trying to audit a model in a package without having to hard code the auditing trait into the package's different models.

When a value changes on one of the package's models, it fires an event. When I catch that event, I want to pass the model to the Audit facade to audit the change but when I do I get an `Argument 1 passed to OwenIt\Auditing\Auditor::execute() must implement interface OwenIt\Auditing\Contracts\Auditable` exception.

Is there a way to perform an audit without having the trait on the model?

This is what I tried that didn't work:
```
if ($audit = Auditor::execute($model)) {
     Auditor::prune($model);
}
```

**Comment by quetzyg** [comment]
Hi @eComEvo,

The `Auditable` trait saves you from writing all the boilerplate in each model you want to audit, and for a model to be auditable, you have to implement the `OwenIt\Auditing\Contracts\Auditable` interface, otherwise it won't work (hence the exception you got).

If you want the auditing functionality, why don't you want to implement the interface and use the trait?

**Comment by eComEvo** [comment]
Because I don't want to make the Auditing package a permanent addition to the other package if I don't have to. I'd rather manually push the audit to the DB thru an event that leaves the original package unchanged.

**Comment by quetzyg** [comment]
So you want all the benefits of the package without depending on it?

**Comment by eComEvo** [comment]
No, I want to be able to dynamically use the benefits of the Auditing package without having to fork another package I want to audit because it keeps its models internal.

**Comment by quetzyg** [comment]
What you ask isn't currently possible and doesn't make sense with the way this package works.

The package needs to know what attributes should be audited. Do timestamps get audited, too? And how do you want to store/get audit records if you don't even set the model as `Auditable`? The polymorphic relation won't work.

Are you also using `Eloquent` in a dynamic fashion when you need to read/write to the database?
