### ISSUE TITLE
Unable to get audit records for a model

### ISSUE THREAD

**Issue by grafikkaos** [owen-it/laravel-auditing#254]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.3.31
| Package version   | 4.0.4
| PHP version       | 7.1.4

#### Actual Behaviour

Getting the following errors when trying to list audit records for a model.

Call to undefined method Illuminate\Database\Query\Builder::audits()

#### Expected Behaviour

Should be getting a list of audits for a model

#### Steps to Reproduce

Model:
```
class UserMeds extends Model implements AuditableContract
{
    use Auditable;

    protected $connection = 'sqlsrv_userdb';

    protected $table = 'Meds';

    protected $primaryKey = 'MedId';

    protected $fillable = [
        'PatientId',
        'Name',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

}
```

Controller
```
public function edit($id)
    {
        $patient = Patient::find($id);
        $medication = $patient->meds()->latest();

        dd($medication->audits());
    }
```

Am I missing something here?
Any ideas would be appreciated.

**Comment by quetzyg** [comment]
Show us the `Medication` model.

**Comment by grafikkaos** [comment]
I do get a result from your code.  Worst case scenario, I can just write a query to get the information that I need.

And yes, I am using different databases for the UserMeds and the Audit as this is how the current system is setup.

**Comment by grafikkaos** [comment]
After a bit of digging around and testing, it looks like using the latest() method on an Eloquent model does not work with Auditing.

I ended up writing this:

```
UserMeds::where('PatientId', 1)->orderBy('created_at', 'desc')->first()->audits()
```

And that gave me the result I was looking for.

**Comment by quetzyg** [comment]
Well, that's most likely the issue, then. When you invoke `dd($medication->audits());`, you're basically saying to fetch the audit records stored in database **A**, related to a model that is stored in database **B**. Have you tried setting up the database connection setting in the config?

**Comment by quetzyg** [comment]
Ahh, ok. That does make sense, since the `latest()` will only define the sort order.
```php
    public function latest($column = 'created_at')
    {
        return $this->orderBy($column, 'desc');
    }
```

You can just do:
```
UserMeds::where('PatientId', 1)->latest()->first()->audits();
```

Since your issue is solved, I'm gonna mark this as closed.
