### ISSUE TITLE
Hope this can be use for multi auth

### ISSUE THREAD

**Issue by codeitlikemiley** [owen-it/laravel-auditing#255]
I see that you Only Have one Option of User Model...

Also the The database is hard coded for user_id

hope you can make it use polymophic relationship

make it editorable_id and editorable_type

then make the config accept an array of Model define in your auth provider...

for example i have 3 provider user , employee and client...

either we pass an array or pass a closure to determine the correct Model 

then change the getLoggedInUserId to be use for multiple guard...

I think its doable

**Comment by quetzyg** [comment]
Hi @codeitlikemiley,

This request seems very specific for your needs, and while it's definitely possible to implement, I can't see a good reason to do so.

Why do you have three different `User` types that rely in different tables for basic information (`id`)? Couldn't you use the same approach you're suggesting to be implemented?

Have a `User` model and three (`userable_id`, `userable_type`) models (`Admin`, `Employee`, `Client`).
It would also make your life easier.

PS: also, use the issue template next time, it's there for a reason.

**Comment by dhcmega** [comment]
I also have 2 guards and user tables. They barely share fields, as one is a user from a remote system, with no email or name. The usual user has all the regular fields, so I 2 tables.
Just a case in which there is a need for more than one user table.
Thanks! I like the package.

**Comment by quetzyg** [comment]
@dhcmega, if the two `User` tables share some fields, the easiest way would be to use a polymorphic relationship and be done with it.

If you want to keep things as they are, you'll have to do your own [Audit implementation](http://www.laravel-auditing.com/docs/5.0/audit-implementation) to support what you need.
