### ISSUE TITLE
Can't get user name in metadata 

### ISSUE THREAD

**Issue by marianperca** [owen-it/laravel-auditing#264]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.27
| Package version   | 4.0.7
| PHP version       | 5.6.31

#### Actual Behaviour

`$audit->getMetadata()` has:
```php
[
"audit_id" => 2
"audit_event" => "updated"
"audit_url" => "..."
"audit_ip_address" => "..."
"audit_user_agent" => "..."
"audit_created_at" => "..."
"user_id" => 1
]
```

#### Expected Behaviour

`$audit->getMetadata()` to contain other user related fields, like user name, user email.

#### Steps to Reproduce

Display metadata for any audit.

#### Possible Solutions

Seems like `if ($this->relationLoaded('user')) {` in OwenIt\Auditing\Models\Audit.php fails.
Am I doing something wrong?

**Comment by quetzyg** [comment]
Please, use the issue template. It's there for a reason!

**Comment by quetzyg** [comment]
What's the output of `dd($audit->user);` ?

**Comment by marianperca** [comment]
The output is:

```php
User {#202 ▼
  #fillable: array:3 [▼
    0 => "name"
    1 => "email"
    2 => "password"
  ]
  #hidden: array:2 [▼
    0 => "password"
    1 => "remember_token"
  ]
  #connection: "mysql"
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:7 [▼
    "id" => 1
    "name" => "John Doe"
    "email" => "email@mail.com"
    "password" => "..."
    "remember_token" => null
    "created_at" => "..."
    "updated_at" => "..."
  ]
...
}
```

**Comment by quetzyg** [comment]
The `User` is fetched correctly. What does your `User` model look like? And how are you getting the `Audit` instance?

**Comment by marianperca** [comment]
Here is how the `User` class looks like:
```php
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

Here is the config setup:
```php
'user' => [
        'model'    => App\Models\User::class,
        'resolver' => function () {
            return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
        },
    ],
```

And here is an audit example that doesn't contain user info:
```php
$draw = Draw::find(26);
dd($draw->audits()->first()->getMetadata());
```
Thanks for your help!

**Comment by quetzyg** [comment]
If you try
```
$draw = Draw::find(26);
$audit = $draw->audits()->first()->load('user');
dd($audit->getMetadata());
```

Does it work?

**Comment by marianperca** [comment]
Yes, works fine with `->load('user')`. Thanks!
