### ISSUE TITLE
Is it possible to manually create a log?

### ISSUE THREAD

**Issue by lsobral** [owen-it/laravel-auditing#270]
| Q                 | A
| ----------------- | ---
| Bug?               |no
| New Feature?       |no
| Framework         | Laravel
| Framework version | 5.1
| Package version   | 4
| PHP version       | 5.6

Is it possible to create a log manually after a user downloads a file or views a page or any action that does not make changes to the database?

Example:
`Auditing::created ($log); // $log is an array`

Thanks

**Comment by quetzyg** [comment]
Hi @lsobral,

The [Auditor](http://www.laravel-auditing.com/docs/4.1/auditor) seems to be what you want.

**Comment by quetzyg** [comment]
I'm closing this issue, but feel free to comment if you still need help.

**Comment by jonstavis** [comment]
It looks like this method has since been removed?  Is there any current way to manually create a log?
