### ISSUE TITLE
Symphony Class Not Found Exception in Laravel Auditing

### ISSUE THREAD

**Issue by helderjosex** [owen-it/laravel-auditing#271]
I get this error and I have no idea why: [Symfony\Component\Console\Exception\CommandNotFoundException] There are no commands defined in the "auditing" namespace.

Version 4.1
Laravel: 5.4.28

Please whats not in the documentation? What step am i missing?

**Comment by quetzyg** [comment]
Use the issue template, I won't answer questions otherwise.
