### ISSUE TITLE
Symphony Class Not Found Exception in Laravel Auditing

### ISSUE THREAD

**Issue by helderjosex** [owen-it/laravel-auditing#273]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.28
| Package version   | 4.1
| PHP version       | 5.6.4

I get this error and I have no idea why: [Symfony\Component\Console\Exception\CommandNotFoundException] There are no commands defined in the "auditing" namespaced

Please whats not in the documentation? What step am i missing?

**Comment by quetzyg** [comment]
I'm not sure why people keep removing parts of the issue template, but anyways...

Have you [registered the service provider](http://www.laravel-auditing.com/docs/4.1/installation)?

**Comment by helderjosex** [comment]
Yes,

This problem happens when I run the command: php artisan auditing: install

And also does not create the file config / audit.php

**Comment by quetzyg** [comment]
Please, provide more information on what you're doing. How can i reproduce the issue?

Hint:
https://www.youtube.com/watch?v=lRkAT1AI1Zo
