### ISSUE TITLE
Upgrading to 4.1.0 throws Exception

### ISSUE THREAD

**Issue by bram1028** [owen-it/laravel-auditing#274]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.28
| Package version   | 4.1.0
| PHP version       | 7.1.5

#### Actual Behaviour

After upgrading to 4.1.0, an exception is thrown when getting the audits for existing audit records because the new `updated_at` is `NULL`.

```
Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::serializeDate() must implement interface DateTimeInterface, null given, called in C:\[REDACTED]\vendor\owen-it\laravel-auditing\src\Audit.php on line 91
```

#### Expected Behaviour

No exceptions :)

#### Steps to Reproduce

Set all audit record's `updated_at` to `NULL`

#### Possible Solutions

Documentation should be updated to specify this or the code should be updated to handle `NULL` values. It's a simple enough data fix for the end user:

```sql
UPDATE audits SET updated_at = created_at WHERE updated_at IS NULL;
```

On a side note, why is this column needed?

**Comment by quetzyg** [comment]
Hello @bram1028,

The documentation does in fact have that information in the [upgrading](http://www.laravel-auditing.com/docs/4.1/upgrading) section, you probably just missed it.

The new version allows extending other model classes besides `Illuminate\Database\Eloquent\Model`, and having the `updated_at`, means less boilerplate when implementing the `OwenIt\Auditing\Contracts\Audit` interface.

So you don't need to have this:

```php
    /**
     * {@inheritdoc}
     */
    public $timestamps = false;

    /**
     * {@inheritdoc}
     */
    protected $dates = [
        'created_at',
    ];
```
in your `Audit` implementation, anymore.

I'm aware that an `Audit` record _shouldn't_ be modified, but the fact is, it can. So with an `updated_at` column you might be able to see if a record has been modified in some way.

I'll mark this as closed now.

**Comment by bram1028** [comment]
I double-checked the upgrade guide. I don't see any mention of updating existing audit records, just adding the nullable `updated_at` column.

**Comment by quetzyg** [comment]
Oh, snap! You're absolutely right.

The documentation has been updated with the missing instructions.
