### ISSUE TITLE
String unicode values in the audits table.

### ISSUE THREAD

**Issue by ned-painless** [owen-it/laravel-auditing#275]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 4.x.y
| PHP version       | 5.x.y|7.x.y

#### Actual Behaviour

Unicode values are being stored in the audits table as UTF 16.

#### Expected Behaviour

Unicode values to be stored as unicode.

#### Steps to Reproduce

Insert/update an auditable model with a unicode value.

**Comment by quetzyg** [comment]
Hi @ned-painless,

What does your `config/database.php` look like, more specifically the `mysql` charset/collation section?
The default 5.4 has:
```php
'mysql' => [  
        // ...
	'charset' => 'utf8mb4',
	'collation' => 'utf8mb4_unicode_ci',
        // ...
],
```
In any case, you'll have to update your table's charset/collation to support whatever characters you're trying to store.

**Comment by ned-painless** [comment]
my config for audit db 
'audit-db' => [
            'driver' => 'mysql',
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
            'options' => array(PDO::MYSQL_ATTR_LOCAL_INFILE => true,)

I have committed the host, port, database , username and password.

**Comment by githubgobi** [comment]
Create Database with utf8_general_ci

**Comment by quetzyg** [comment]
@githubgobi, that's what he apparently has.

@ned-painless, in any case, it's a matter of changing to a charset/collation that supports whatever characters you're trying to store.

I would suggest `utf8mb4` / `utf8mb4_unicode_ci`.

Closing the issue, as this isn't an issue with the library itself.

**Comment by ned-painless** [comment]
@quetzyg  But the characters get stored properly in the other tables with utf8_unicode_ci.

**Comment by quetzyg** [comment]
So what exactly is the problem, then?

You fail to provide proper examples. Do all unicode characters get stored in a funny format, or just a subset? Can you provide actual examples of what's happening? Otherwise it's just guesswork. Do the characters still display correctly once retrieved from the database? Give me something I can work with.

Make an effort, mate.
