### ISSUE TITLE
Audits are not created.

### ISSUE THREAD

**Issue by gtmeteor** [owen-it/laravel-auditing#277]
Laravel: v5.4.28
Package: v4.1.0
PHP: 5.6.30 

#### Actual Behaviour

No logs are created.

#### Expected Behaviour

Logs to be created.

#### Steps to Reproduce

````<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Store extends Model implements AuditableContract
{
    use SoftDeletes;
    use Auditable;

    protected $fillable = [
        'name', 'type'
    ];

}

Controller:

public function update(Request $request, Store $store)
    {
        Validator::make($request->all(), [
            'name' => 'required|min:3|max:16|unique:stores,name,'.$store->id,
            'type' => 'required|max:16',
        ])->validate();

        $store->update( $request->input() );
        return Store::with('users')->get();
    }

public function destroy(Store $store)
    {
        $store->delete();
        return Store::with('users')->get();
    }
````

Neither of the methods create a log entry.

**Comment by githubgobi** [comment]
In Controller 
**Add namespace** 
use OwenIt\Auditing\Facades\Auditor;

**You Put this code below $store->update($request->input());**

if ($audit = Auditor::execute($store)) {
                    Auditor::prune($store);
                    }

**Comment by gtmeteor** [comment]
:/ sooo... basically you're suggesting that instead of a Trait that works out of the box, I have to add custom code for each controller + the trait itself :/ that's hardly practical...

**Comment by quetzyg** [comment]
@gtmeteor, the code you provided seems to be correct. Any other thing we should be aware of?

@githubgobi, while your suggestion might work, like @gtmeteor said, it's not the most practical to use. Also, it's stated in the [documentation](http://www.laravel-auditing.com/docs/4.1/auditor) that it's not the best approach.

**Comment by gtmeteor** [comment]
@quetzyg, no, that is all. It's a standard resourceful **make:controller** generated code.

**Comment by quetzyg** [comment]
That's a rather odd situation. Have you followed all the [installation](http://www.laravel-auditing.com/docs/4.1/installation) steps from the documentation? Has the service provider been registered? Have you generated the `audits` table migration and ran the migrate command?

Not sure what else to ask at this stage.

**Comment by gtmeteor** [comment]
Apparently I had a project that used ^4.0 as dependency... and had an old migration file, which didn't have `user_agent` field. I didn't see the error as my JSON responses still worked to some extent... 
just needed to fix the migration... I however for people who update from 4.0 to 4,1 this is a breaking change...

**Comment by quetzyg** [comment]
Yeah it's a breaking change, which is properly [documented](http://www.laravel-auditing.com/docs/4.1/upgrading).

Marking this as solved.

**Comment by reals79** [comment]
Sorry, i am solved this.
In my model was present function __constructor
This was the problem.
