### ISSUE TITLE
problem when use auditable to get softdelete data

### ISSUE THREAD

**Issue by Lostvincent** [owen-it/laravel-auditing#278]
| Q                 | A
| ----------------- | ---
| Framework         | Laravel
| Framework version | 5.4
| Package version   | 4.1
| PHP version       | 7.0.10

#### Actual Behaviour

When i code for log part, i use Audit model to get the data. Then when i try to show the list, i can not get the data if the auditable object has been softdelete.

#### Expected Behaviour

example i wish:

|  ID  |  modified object name   |    action   |  etc  
| --- | ------------------------ | -------- | -----
|  1    |    my article                     |   created |   ....  
|  2    |    my article                     |   deleted |   ....  

but actually:

|  ID  |  modified object name   |    action   |  etc  
| --- | ------------------------ | -------- | -----
|  1    |                                         |   created |   ....  
|  2    |                                         |   deleted |   ....  

Data source:
Audit::where(xxx, xxx)->with('user', 'auditable')->xxx

I can get nothing from deleted object(data still at DB),only the info from audits table could been shown.

#### Steps to Reproduce
Just use Model with SoftDeletes and Auditable, create an object and then delete it.
Then the log part can not show the info if the current item has been softdeleted.

Exactly, the data at audits table is ok, but the data from the softdeleted item's source table can not be get.

#### Possible Problems
Code like this at audits Model:
```
public function auditable()
    {
        return method_exists($this->morphTo(), 'isForceDeleting') ? $this->morphTo()->withTrashed() : $this->morphTo();
    }
```

but when i add
```
dd(method_exists($this->morphTo(), 'isForceDeleting'))
```
before return.
And i always get `false` whether the model has `use softDeletes` or not.

**Comment by quetzyg** [comment]
Hi @Lostvincent,

I'm a bit confused with your explanation, so help me out here.

Are you saying that when you soft delete a model, the `old_values` and `new_values` are [empty](https://github.com/owen-it/laravel-auditing/issues/263), or are you saying that the soft deletes models cannot be fetched without using the `withTrashed()` query scope?

**Comment by Lostvincent** [comment]
Re @quetzyg :

I think the latter is closer.

Samply say, I can not fetch data by use $audit->auditable->xxx if soft deletes.
In other words, I think `method_exists($this->morphTo(), 'isForceDeleting')` may has no effect.

**Comment by quetzyg** [comment]
If you have soft deleted models, you'll just have to use `$audit->auditable()->withTrashed()->get()`, then.

**Comment by Lostvincent** [comment]
Sorry to bother you so long, I just do some research and realized the auditable() function in audit model is not comes with origin package.
Especially the `method_exists()` is add by an other guys of my project, and I was told it comes from the package a few days ago when I find the problem, so I just want to let you know the function has no effect at that time.

Now there is no problem, really sorry for this issue, and you can close whenever you want.

btw, the mistake function is the code I shown at first comment.
