### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by fridzema** [owen-it/laravel-auditing#281]
| Q                 | A
| ----------------- | ---
| Bug?                           yes
| New Feature?            no
| Framework                Laravel
| Framework version   5.4.30
| Package version       4.1.1
| PHP version              7.1.7

#### Actual Behaviour

This is the error when i call $project->audits()->with('user')->get()

    Class name must be a valid object or a string

    protected function newRelatedInstance($class)
    {
        return tap(new $class, function ($instance) {
            if (! $instance->getConnectionName()) {
                $instance->setConnection($this->connection);
            }
        });
    }

Also have tried things like with(User::class), with('App\User'), load('user) as expected nothing helps:(

#### Expected Behaviour

I want to get the user object from the audit

#### Steps to Reproduce

I have my config adjusted to use config:cache

this is what i made of it:

audit.php

    'user' => [
        'resolver' => App\User::class,
    ],

User.php
    
    use Auth;
    use Config;
    use Illuminate\Foundation\Auth\User as Authenticatable;
    use Illuminate\Notifications\Notifiable;
    use OwenIt\Auditing\Auditable;
    use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
    use OwenIt\Auditing\Contracts\UserResolver;
    use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
    use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
    
    class User extends Authenticatable implements HasMediaConversions, AuditableContract, UserResolver
    {
        use Notifiable;
        use HasMediaTrait;
        use Auditable;
    
        protected $hidden = [
            'password', 'remember_token',
        ];
        protected $fillable = [
            'name', 'email', 'password', 'avatar',
        ];
        protected $casts = [
            'settings' => 'array',
        ];
    
        // Config:cache fix Laravel Audition
        public static function resolveId()
        {
            return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
        }
    

Except for getting the user the package works perfectly!

I hope anyone can help me out with this?

**Comment by quetzyg** [comment]
Hi @fridzema,

The `UserResolver` implementation looks correct, although that shouldn't be an issue when fetching already existing `Audit` records.

What's the `User` class namespace, `App\User`? I can't tell from the code you pasted.

Try checking what value is being passed to the `newRelatedInstance()` method:

```php
protected function newRelatedInstance($class)
{
    dd($class); // <-- like so

    return tap(new $class, function ($instance) {
        if (! $instance->getConnectionName()) {
            $instance->setConnection($this->connection);
        }
    });
}
```

**Comment by fridzema** [comment]
Namespace is indeed App\User.
If i do a dd i get "OwenIt\Auditing\Models\Audit"

**Comment by quetzyg** [comment]
The `dd()` output seems alright.

Can you `dump()` instead of `dd()` ? There may be more calls with other values that are omitted because you're exiting on the first one.

Also, what does your entire `audit.php` config file look like?

**Comment by fridzema** [comment]
When i do a dump i get 
    "OwenIt\Auditing\Models\Audit"
    null

    <?php
    /**
     * This file is part of the Laravel Auditing package.
     *
     * @author     Antério Vieira <anteriovieira@gmail.com>
     * @author     Quetzy Garcia  <quetzyg@altek.org>
     * @author     Raphael França <raphaelfrancabsb@gmail.com>
     * @copyright  2015-2017
     *
     * For the full copyright and license information,
     * please view the LICENSE.md file that was distributed
     * with this source code.
     */
    
    return [
    
        /*
        |--------------------------------------------------------------------------
        | Audit implementation
        |--------------------------------------------------------------------------
        |
        | Define which Audit model implementation should be used.
        |
         */
    
        'implementation' => OwenIt\Auditing\Models\Audit::class,
    
        /*
        |--------------------------------------------------------------------------
        | User Keys, Model & Resolver
        |--------------------------------------------------------------------------
        |
        | Define the User primary and foreign keys, Eloquent model and ID resolver
        | class.
        |
         */
    
        'user' => [
            'resolver' => App\User::class,
        ],
    
        /*
        |--------------------------------------------------------------------------
        | Default Driver
        |--------------------------------------------------------------------------
        |
        | The default audit driver used to keep track of changes.
        |
         */
    
        'default' => 'database',
    
        /*
        |--------------------------------------------------------------------------
        | Audit Drivers
        |--------------------------------------------------------------------------
        |
        | Available audit drivers and respective configurations.
        |
         */
        'drivers' => [
            'database' => [
                'table' => 'audits',
                'connection' => null,
            ],
        ],
    
        /*
        |--------------------------------------------------------------------------
        | Audit Console?
        |--------------------------------------------------------------------------
        |
        | Whether we should audit console events (eg. php artisan db:seed).
        |
         */
    
        'console' => false,
    ];

**Comment by quetzyg** [comment]
Your configuration has the following missing:
```php
'user' => [
    'model'    => App\User::class, // <- this
    'resolver' => App\User::class,
],
```

**Comment by fridzema** [comment]
Wow its working, you made my day! 

Really appreciate your fast response and support ;)
