### ISSUE TITLE
Ability to tag audits

### ISSUE THREAD

**Issue by garygreen** [owen-it/laravel-auditing#283]
It would be nice if you could 'tag' the audits for models, that way you can group similar relations and pull down all the audits for that tag.

E.g. lets assume you have a `Product` model which has a `prices` relation for specifying varying different prices in different currencies, or a `features` relation specifying different features / configuration for the products - if you could get all the audits for the product in one go it would be cool.

Code examples:

```php
$product = Product::find(1);
$audits = Audit::tagged('product-' . $product->getKey())->paginate(50);
```

To tag versions, you can add a function on your model, which get's called when an audit is created so it knows how to tag it:

```php
class Product extends Model {

  public function tagAudit(Audit $audit)
  {
    return 'product-' . $this->getKey();
  }

```

Supporting multiple tags for a model could be an option, too.

**Comment by quetzyg** [comment]
Hi @garygreen,

The idea sounds good, but the examples you have don't really give it merit. What I mean by this is that the tag you're creating isn't adding value to the `Audit` record, it's just a variation of information we already have.

You can achieve the same functionality with:
```php
Audit::where('auditable_type', Product::class)->andWhere('auditable_id', 1)->paginate(50);
```

Thoughts?

**Comment by garygreen** [comment]
@quetzyg what if you have 5 different relations that you want to pull down the information for? So you have a products page and you want to display all the audits for that product, and it's relations.

At the moment, you would have to do `where('auditable_type', Product::class)->andWhere('auditable_id', 1)` for every relation - this isn't too pretty. Also, it's not particulary efficient, as opose to just having a `tag` field which is indexed and can easily be looked up.

I've created my own basic versioning system and use the same technique and it's massively simplified the way we can pull down all related tagged-information for a given model and sped things up.

**Comment by quetzyg** [comment]
Well, from what you suggest we have to make those ugly queries anyway, because you'll have create tags with the `ProductFeature` and `ProductPrice` ids each time you audit a `Product`. The only difference is that instead of querying when fetching `Audit` records, you do it on creation, or am I missing something?

**Comment by garygreen** [comment]
It looks like your not fulling understanding the implications of having to resort to those queries and how simple it is to overcome by categorising your audits on time of creation. Doing that once is far more efficient rather than performing expensive and complicated queries everytime you want to display audits for all related models. Tagging data is not a foreign concept.

**Comment by quetzyg** [comment]
>It looks like your not fulling understanding the implications of having to resort to those queries and how simple it is to overcome by categorising your audits on time of creation.

Yeah, you're right. I'll add this in the next minor version. Meanwhile, I'll keep this issue open.

Thanks, for the suggestion!

**Comment by quetzyg** [comment]
This issue has been addressed and the tagging feature will be available in version 5.0. This will be closed once the new version comes out.

**Comment by quetzyg** [comment]
V5 is gonna be tagged this tuesday during [Laravel Lisbon // S01E01](https://www.meetup.com/Laravel-Lisbon/events/245137268/), closing issue and considering it solved.

**Comment by daniel-gomes-sociomantic** [comment]
We have the same problem and also solved it with all those queries like @garygreen mentioned, so it's great to see this feature was implemented, well done! :+1:

**Comment by daniel-gomes-sociomantic** [comment]
Is there no friendlier way to get audits by tag than something like:
```php
Audit::where(DB::raw("FIND_IN_SET('TAG', tags)"), '>', 0)->get();
```
?

**Comment by quetzyg** [comment]
Doesn't something like this
```php
Audit::where('tags', 'LIKE', '%foo%')->get();
```
work?

**Comment by daniel-gomes-sociomantic** [comment]
what if you have tags `foo` and `food`? :-) 

anyway, what I wrote covers any possible case, I'm just saying maybe it would be nice for the library to provide an easy way to get audits by tag?

**Comment by quetzyg** [comment]
Well, you would have to explicitly look for what you want and use the exact string without `%`, then.

In regards to having an easy way to get audits by tag, you'll have to implement your own Query Scope to suit your needs, because I have no idea how each one is gonna use the `tags` column and it's hard to cater for everyone.

Eloquent should be flexible enough for anyone using this package.

**Comment by Jeffreiht** [comment]
Quiero utilizar el auditing tags, pero no entiendo bien como hacerlo, no tienen algun video donde expliquen como se hace
