### ISSUE TITLE
Call to undefined method Closure::__set_state()

### ISSUE THREAD

**Issue by terrylow** [owen-it/laravel-auditing#284]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.32
| Package version   | 4.1.2
| PHP version       | 7.1.7

#### Actual Behaviour

Received this exception from terminal `Call to undefined method Closure::__set_state()`

and these from page
Fatal error: Uncaught ReflectionException: Class config does not exist in /home/vagrant/code/calibration/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752

ReflectionException: Class config does not exist in /home/vagrant/code/calibration/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752

Once received this error, required to remove /bootstrap/cache/config.php file in order to recover from the errors.

#### Steps to Reproduce

 issue a `php artisan config:cache` command

After some debug, it seem https://github.com/owen-it/laravel-auditing/blob/4.1/config/audit.php#L42-L44 is trigger the errors, once the config is cached, resolver turn into the following

```php 'resolver' => 
      Closure::__set_state(array(
      )),
````

**Comment by nerijunior** [comment]
At the config/audit.php I changed:

    'resolver'    => function () {
        return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
    },

to:

    'resolver'    => (Auth::check()) ? Auth::user()->getAuthIdentifier() : null,

And now everything works

**Comment by terrylow** [comment]
@nerijunior  it is not working here, get a runtime exception ` A facade root has not been set.`

at the time we issue command from commandline, no user is authenticated, maybe thats why the cached config is empty

**Comment by quetzyg** [comment]
There's at least four previous tickets about this (#213, #234, #237, #250) and two separate entries in the documentation about the `User` resolver [here](http://www.laravel-auditing.com/docs/4.1/general-settings) and in the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) section.
