### ISSUE TITLE
Domain Expired, Docs Inaccessible

### ISSUE THREAD

**Issue by AdenFraser** [owen-it/laravel-auditing#286]
Website domain has expired, docs inaccessible.

**Comment by the94air** [comment]
Yea, facing the same problem

**Comment by hailwood** [comment]
As a temporary fix you can [view the google cached version](google.com/search?q=cache%3Ahttp%3A%2F%2Fwww.laravel-auditing.com%2Fdocs%2F4.1).

**Comment by KarimGeiger** [comment]
Looks like they've moved to Heroku:

http://laravel-auditing.herokuapp.com/docs/4.1

**Comment by quetzyg** [comment]
Sorry about that, everyone. 😞 

Like @KarimGeiger pointed out, you can use the Heroku address for now.
@anteriovieira, please take care of this.

**Comment by anteriovieira** [comment]
Sorry about that, everyone.

We're already solving.

**Comment by anteriovieira** [comment]
Domain stabilized, thank you all.
