### ISSUE TITLE
Documentation is quite confusing

### ISSUE THREAD

**Issue by KarimGeiger** [owen-it/laravel-auditing#287]
Hi there,

just wanted to let you know about my first thoughts of your documentation at http://laravel-auditing.herokuapp.com/docs/4.1

The moment I got there, I thought "why am I on the Laravel documentation?" Then I noticed the different logo and different text. The next thing I saw was the version "4.1" on the upper right. As Laravel is on version 5.4 right now, I thought "is this the Laravel version, or the package version?".

I hope you see where I'm going with this. I do see why you were choosing this design and I like the idea behind that, but I'm pretty sure it will confuse people who aren't that familiar with Laravel. Same goes with the navigation. What happens if I press on "Home"? Will I get to the Laravel home or the package home? Also, what Community am I accessing? Laravel or package? Also, the footer: Is this an official package, as the only name there appears to be Taylor Otwell.

So, my suggestion would be: Try using a different design for your documentation. Or at least adjust the menu, version and color to make the difference between the Laravel documentation and the plugins documentation a bit more clear. People should immediately be able to distinct your docs from the official ones.

Oh, and... maybe you don't want to confuse people with AngularJS either? Picking another logo might be a good idea as well.

**Comment by quetzyg** [comment]
Thanks for your suggestions @KarimGeiger. We'll keep this open until the changes are made.

**Comment by jesephan** [comment]
@KarimGeiger I agree with you the documentation is like a combination of Laravel and Angular. However I admin this package is so awesome. Credits to the author and maintainers :)

**Comment by juanvillegas** [comment]
I disagree: I believe using a similar theme and organization of the topics is great for laravel related projects. Specially because the Laravel doc style is so great, why not reuse it in the entire ecosystem? Vuejs is doing a similar thing: both official and non official projects (at least the most important ones) try to stick to the same colors, design and content organization as the main vuejs docs.

I agree on the logo though, its so Angular-ish.

**Comment by ctf0** [comment]
the package have soooo much potential, but the god dam fucken maze like docs ruins the whole thing

**Comment by quetzyg** [comment]
Maze like docs?

**Comment by anteriovieira** [comment]
@ctf0 , we're working on it.

**Comment by anteriovieira** [comment]
The final art 😃 

![2017-09-29_14h41_23](https://user-images.githubusercontent.com/1490347/31028443-6052e398-a524-11e7-9224-35020171961e.png)

**Comment by KarimGeiger** [comment]
Much better now! But are you sure that this documentation is copyright by Taylor Otwell (footer)?

**Comment by anteriovieira** [comment]
@KarimGeiger , It was my mistake.

**Comment by ctf0** [comment]
@anteriovieira up until now, thanx for renaming the sidebar links to follow the page title name except for configuration which creates confusion for the user.

if u want to keep the current naming, at least change the current active link color.

also imho i think it would be more user friendly if the docs were more of
- intro
- installation
- configuration
- usage

UX is all about following patterns that users are accustomed to.

**Comment by anteriovieira** [comment]
@ctf0 , good observation. 

I can not work on it now, if anyone can do it for me I'll be very grateful.

**Comment by anteriovieira** [comment]
> if u want to keep the current naming, at least change the current active link color.

<p align="center">
   <img src="https://user-images.githubusercontent.com/1490347/31296529-08f78afa-aab9-11e7-8603-0a1e8236de02.png">
</p>

> imho i think it would be more user friendly if the docs were more of
>
> - intro
> - installation
> - configuration
> - usage

The settings are not initially required, only in specific cases, for this reason it has been added below.

I am closing this issues by understanding that it has been resolved.
