### ISSUE TITLE
Small Documentation Suggestion

### ISSUE THREAD

**Issue by adamberryhuff** [owen-it/laravel-auditing#288]
| Q                 | A
| ----------------- | ---
| Bug?              |no
| New Feature?    |  yes
| Framework        | Laravel
| Framework version | 5.x.y
| Package version   | 4.x.y
| PHP version    |   5.x.y

#### Actual Behaviour
Under the "Troubleshooting" section of your documentation when you cover "Auditing Not Working" it is worth noting that audits also don't log if you are making active record updates via Tinker. Clearly this isn't an issue but it could save developer time knowing this off the bat so they prototype by making model updates through a controller via HTTP.

#### Expected Behaviour
If some sort of audit logging worked through Tinker it would be an option. Another is to update to the documentation to mention this.

#### Steps to Reproduce
Make a model update through Tinker.

#### Possible Solutions
See "Expected Behavior"

**Comment by quetzyg** [comment]
Logging should happen, as long a you have auditing enabled for [console](https://github.com/owen-it/laravel-auditing/blob/4.1/config/audit.php#L82).

**Comment by adamberryhuff** [comment]
I see, I must have overlooked that. Works great, thanks!

**Comment by quetzyg** [comment]
No problem, mate.
