### ISSUE TITLE
Prevent Audit if old_values and new_values are both empty

### ISSUE THREAD

**Issue by jesusephan** [owen-it/laravel-auditing#292]
Hi, 

I'm currently using your package in our project, Is there  a way to prevent auditing when old_values and new values are both empty? Just for example during login Laravel will try to update remember_token and since I included this to $auditExclude property, It will still create a audit record with empty old and new values. 

Great package overall :)

Thanks

**Comment by quetzyg** [comment]
This has already been discussed in #263, you can cancel an audit using [events](http://www.laravel-auditing.com/docs/4.1/audit-events).

Use the issue template next time.
