### ISSUE TITLE
FatalThrowableError in Model.php line 282: Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::__construct() must be of the type array, object given, called in 

### ISSUE THREAD

**Issue by akalerp** [owen-it/laravel-auditing#293]
| Q       getting error when added the package          | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 4.x.y
| PHP version       | 5.x.y|7.x.y

#### Actual Behaviour

Describe the behaviour you're experiencing. Do not just copy and paste a random error message and expect help.

#### Expected Behaviour

Describe the behaviour you're expecting.

#### Steps to Reproduce

List all the steps needed to reproduce the issue you're having. Make sure to include code (affected models, configurations),
any screenshots and/or other resources that may help us understand what's going on.

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by quetzyg** [comment]
You realise that when I say to use the issue template, you have to fill it with relevant information and not just leave the placeholders, right?
