### ISSUE TITLE
Disable logging before saving changes to model

### ISSUE THREAD

**Issue by jozeflambrecht** [owen-it/laravel-auditing#296]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.3
| Package version   | 4.1.2
| PHP version       | 7.x.y

#### Actual Behaviour

Audit logging when saving changes to model.

#### Expected Behaviour

Feature to disable logging before saving (for specific functions in the model).

#### Possible Solutions

Could there be an extra parameter or property to disable the log function?
$model-save()->disableAudit();

**Comment by daniel-gomes-sociomantic** [comment]
I'd also be interested in this feature for testing purposes.

@jozeflambrecht did you close the issue because you found a solution?

**Comment by quetzyg** [comment]
This subject has been fairly discussed in the last days (#263, #309).

The following observer should do what you want:
```php
Audit::creating(function (Audit $model) {
    if (app()->environment('testing')) {
        return false;
    }
});
```

**Comment by daniel-gomes-sociomantic** [comment]
thanks @quetzyg !

**Comment by daniel-gomes-sociomantic** [comment]
another solution could be calling `$model->unsetEventDispatcher()` before saving, but that might have unintended effects on other non-auditing events that might have been fired (just leaving it here for completeness)
