### ISSUE TITLE
I need save audit logs in another BD

### ISSUE THREAD

**Issue by angelomr** [owen-it/laravel-auditing#30]
How configure laravel-auditing for save log in another BD.

Example:
My Model is save data in a connection: mysql.

I have save log in another connection (mysql2).

Is possible?

**Comment by angelomr** [comment]
I have edit Log Model in 'vendor/owen-it/laravel-auditing/src/Log.php" with this code:
protected $connection = 'mysql2';

IF update laravel-audit, this is update.

Have other config?

**Comment by anteriovieira** [comment]
Hello @angelomr ,

Not in the moment. But we can implement. Send us your suggestion by the pull request. is important that the connection name is in the auditing configuration file.

I'll think of something.

**Comment by anteriovieira** [comment]
Hello @angelomr ,

Now you can set the data base to record logs. :smile: 

```php
// config/auditing.php

return [
    // ...
    'connection' => 'Outher_database',
    
];
```
> From version v2.2.0

**Comment by LexBel-co** [comment]
Hello @angelomr 

I have a similar situation, in my app i have some models that must be save their audits through 'mysql' connection, this is the main database, and this works fine.

But i have some others models that must save their audits through other connection, tenant database, called 'tenantConn', and in this cases does not work.

I have tried changing the config at run time inside the model through public static function boot or through the constructor:

`public static function boot(){
    Config::set('audit.drivers.database', array(
        'table'         => 'audits',
        'connection'    => 'tenantConn'
    ));
}`

Also tried with a custom driver, but nothing works.

I only need save this other audits in a different database.

**Thank you in advance.**

**Comment by anteriovieira** [comment]
cc @quetzyg

**Comment by quetzyg** [comment]
Hi @LexBel-co,

What I'm about to suggest hasn't been tested.

In the `Audit.php` trait, can you replace
```php
    /**
     * {@inheritdoc}
     */
    public function getConnection()
    {
        return static::resolveConnection(Config::get('audit.drivers.database.connection'));
    }
```

with
```php
    /**
     * {@inheritdoc}
     */
    public function getConnectionName()
    {
        return $this->connection ?? Config::get('audit.drivers.database.connection');
    }
```

And comment/remove `public function getConnection();` from `src/Contracts/Audit.php`.

Then, set the connection value in the config before auditing and see if it works.

**Comment by LexBel-co** [comment]
Hi @quetzyg 

I made the changes you suggested, but it does not work.

With the models of the main database works, but the tenant models don't.

Any other advice?

Thank you again.

**Comment by LexBel-co** [comment]
Hi @quetzyg

Sorry by my last response, but i had an error in my code, your suggestion works Great!!!

The problem was in the boot method of the model, where i forgot add `parent::boot();`, after add this, the code works...

But i have a question... You suggestion implies to modify files into de OwenIt\Auditing Package, and if i update it that changes will be lost, how can i implement that changes to avoid lose them

**Comment by LexBel-co** [comment]
Hi @quetzyg 

Finally, there's no need to change any of the files inside the Package.

The solution was very simple, in the model or TenantModel (in my case), i only needed to add this code:

```
public static function boot(){
    parent::boot();
    Config::set('audit.drivers.database', array(
        'table'       => 'audits',
        'connection'  => 'tenantConn'
    ));
}
```

Thank you so much for the time and your help.

**Comment by quetzyg** [comment]
If there's no need to change, even better. I just assumed it wouldn't work, so I suggested the change to see if it made a difference.

But if that's the case, glad it works.
