### ISSUE TITLE
Empty record if modified field not present in $auditInclude

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#303]
Library creates empty record http://joxi.ru/EA4pyLjcDMQZxA if modified field are not present in `$auditInclude` property.

**Comment by quetzyg** [comment]
Closing due to issue submission [rules](http://www.laravel-auditing.com/docs/4.1/problems) not being followed. Also, this has already been discussed in #263 and #292.

**Comment by rorc** [comment]
Dude, how about add option `$saveEmptyAudit = false` except of this:
>Still, if you don't want to store empty old/new arrays, you can create a listener for the auditing event and cancel the audit.

**Comment by quetzyg** [comment]
>Dude, how about just add option $saveEmptyAudit = false except of creating Listener?

No.

**Comment by rorc** [comment]
Why? I guess its frequently used task, and will be easier just set this option...

**Comment by quetzyg** [comment]
This is an auditing package, so while some data might not have changed, it doesn't mean you should get rid of all metadata. Read the paragraph above the one you quoted.

**Comment by mdiazr2000** [comment]
Hi I will like to expose my solution for this using listener

The best solution is to use a listener than a custom driver because the custom driver always has to return and audit object so using listener if you return in Auditing event false this prevents to save audit in database.

Well I create a Listerner named Auditing Listener

```
namespace App\Listeners;

use OwenIt\Auditing\Events\Auditing;
use OwenIt\Auditing\Exceptions\AuditingException;

class AuditingListener
{
   
    /**
     * Handle the Auditing event.
     *
     * @param Auditing $event
     * @return bool
     * @throws AuditingException
     */
    public function handle(Auditing $event)
    {
        $data = $event->model->toAudit();
        if (empty($data['old_values']) && empty($data['new_values'])) {
            return false;
        }
        return true;
    }
}

```

And in EventSeviceProvider in property listen put this:

` protected $listen = [
        'OwenIt\Auditing\Events\Auditing' => [
            'App\Listeners\AuditingListener',
        ],
    ];`
