### ISSUE TITLE
Inconveniences with transformAudit

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#304]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5.3
| Package version   | 4.1.2
| PHP version       | 7.0.1

#### Actual Behaviour
Context `$this` in `transformAudit` method contains old model values, so, i have to use something like this `OrderStatus::find(array_get($data, 'new_values.status_id'))->name`, except of just using `$this->status->name` (its docs example, who will save old value in `new_values`).
#### Steps to Reproduce
```php
public function transformAudit(array $data)
{
    if (array_has($data, 'new_values.status_id')) {
        $newStatus = OrderStatus::find(array_get($data, 'new_values.status_id'));
        array_set($data, 'new_values.status_name', $newStatus->name);
    }

    return $data;
}
```
#### Possible Solutions
Running `transformAudit` after model updated/created/etc.

**Comment by quetzyg** [comment]
Can you please follow the issue creating [rules](http://www.laravel-auditing.com/docs/4.1/problems)?

**Comment by rorc** [comment]
Done :)

**Comment by quetzyg** [comment]
>**Possible Solutions**
>Running `transformAudit` after model updated/created/etc.

As you can see in the [documentation](http://www.laravel-auditing.com/docs/4.1/audit-transformation), the point of this method is to transform data before it gets stored.

>If needed, the Audit data can be transformed before being stored.


How about the following:
```php
public function transformAudit(array $data)
{
    $data['old_values']['status_name'] = OrderStatus::find($this->getOriginal('status_id'))->name;

    $data['new_values']['status_name'] = OrderStatus::find($this->getAttribute('status_id'))->name;

    return $data;
}
```
Does it work?

**Comment by rorc** [comment]
Yea, its ok, fix this in docs :)
