### ISSUE TITLE
Question - suitable for json column?

### ISSUE THREAD

**Issue by elamotte** [owen-it/laravel-auditing#305]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 4.1
| PHP version       | 7

Hi, first of all thanks for this package looks very promising!

I have a table, let's say "project" which contain data in a json column (each project depends from a differents schema so I need to store the datas in json).

I want to integrate Auditing but I would like to be able to watch the change inside the json directly.

I guess that I will have my whole json change in old & new attributes... Maybe not very optimized and I'll have to do a diff on read.

Maybe it's possible to do it properly with a custom driver?

**Comment by quetzyg** [comment]
Hi @elamotte,

Yeah, currently even the smallest change in a JSON structure would store the whole object in old and new.
I guess this really depends on what exactly your use case is. You might want to see the full object, or just what changed. To be able to suit your needs, you shouldn't need a new custom driver, just do your diff logic in the [transformAudit()](http://www.laravel-auditing.com/docs/4.1/audit-transformation).

PS: Please, use the issue template next time.

**Comment by elamotte** [comment]
Oh didn't see that, this is excatcly what I was looking for thanks a lot! I'll give it a shot!

P.s : sorry for template I updated first post.
