### ISSUE TITLE
Question: how i can customize format for dates?

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#306]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.3
| Package version   | 4.1.2
| PHP version       | 7.0.1

### Question
How i can customize format for audit dates `updated_at` and `created_at` without pain?

### Description
I try this:
```php
use Jenssegers\Date\Date;
use OwenIt\Auditing\Models\Audit as AuditOriginal;

class Audit extends AuditOriginal
{
    public function getUpdatedAtAttribute()
    {
        return Date::parse($this->attributes['updated_at'])->format('j F в H:i');
    }
}
```
But got error http://joxi.ru/p27LNavc0D0LoA

**Comment by rorc** [comment]
Ok, i owerload `serializeDate` method:
```php
    protected function serializeDate(\DateTimeInterface $date)
    {
        return \Date::parse($date)->format('j F в H:i');
    }
```
Its ok?

**Comment by quetzyg** [comment]
What's wrong with `$audit->created_at->format('j F в H:i')` ?

**Comment by rorc** [comment]
I have to use `Jenssegers\Date\Date` for translation.

**Comment by quetzyg** [comment]
I never used such thing, so you'll have to elaborate on what exactly is happening. Also, you said that you overloaded the `serializeDate()` method. Did that work?

**Comment by rorc** [comment]
Yea, its work =)

**Comment by quetzyg** [comment]
In that case I'm gonna close this.
