### ISSUE TITLE
Retreiving all audits for a collection

### ISSUE THREAD

**Issue by yamenarahman** [owen-it/laravel-auditing#308]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | may be
| Framework         | Laravel
| Framework version | 5.4
| Package version   | 4.1
| PHP version       | 7.1

Within the basic example in the docs I can retreive audits and eager load them for a specific model like a post as follow:
`$post->audits;`
`$post->with('audits');`

Now what if I want to get audits on a collection of posts ? is there something like this:
`Post::audits()->get();`
`$user->posts->audits;`

Again to be clear I don't want to associate audits with post model, I want to get an audits collection based on the model like above which returns an error like that
`Undefined property: Illuminate\Database\Eloquent\Relations\HasMany::$audits`

**Comment by quetzyg** [comment]
What you can do is filter by type, to get everything:
`Audit::where('auditable_type', Post::class)->get();`

**Comment by yamenarahman** [comment]
Thanks, so I need to create that Audit model right ?

**Comment by quetzyg** [comment]
Mate, the `Audit` model already exists.

**Comment by yamenarahman** [comment]
Thanks for your time.
