### ISSUE TITLE
Improve OwenIt\Auditing\Events\Auditing

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#309]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5.3
| Package version   | 4.1.2
| PHP version       | 7.0.1

### Description
Now in `AuditingListener` few data for analysing model.
In order to prevent store empty audit (without changed data) i have to write custom function.
I guess this feature is most popular. So, can we improve auditing event by adding new method `getModified` or property `isModified`?
```php
class AuditingListener
{
    public function handle(Auditing $event)
    {
        return $this->isModified($event);
    }

    protected function isModified(Auditing $event)
    {
        return collect($event->model->getDirty())
            ->forget($event->model->getAuditExclude())
            ->forget($event->model->getUpdatedAtColumn())
            ->isNotEmpty();
    }
}
```
### Possible solution
```php
class AuditingListener
{
    public function handle(Auditing $event)
    {
        return $event->model->getAuditModifiedData()->isNotEmpty();
        //or
        return $event->model->isModified();
    }
}
```

**Comment by quetzyg** [comment]
Due to the way `Eloquent` works, there can be false positives. Check the **Attributes are considered modified, when they're not** entry in the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) section.

So the diff approach you're proposing, won't work as expected sometimes.

**Comment by rorc** [comment]
I updated issue.

**Comment by quetzyg** [comment]
You might as well check if the `new_values` and `old_values` are empty and act accordingly, no need to create a collection, add stuff to it, apply a filter and check if it's empty.

**Comment by rorc** [comment]
Can we just add my method in core?

**Comment by quetzyg** [comment]
No, because I don't like that implementation.

This should achieve what you want:
```php
Audit::creating(function (Audit $model) {
    if (empty($model->old_values) && empty($model->new_values)) {
        return false;
    }
});
```

Just register that in the `boot()` method of the `AppServiceProvider`, for example.

**Comment by rrhyne** [comment]
`Audit::creating(function (Audit $model) {
            if (empty($model->old_values) && empty($model->new_values)) {
                return false;
            }
        });`

When adding to AppServiceProvider, that call results in "Class 'App\Providers\Audit' not found". How can I resolve the Audit calss from the service provider?

**Comment by quetzyg** [comment]
You'll have to import the class, by adding `use OwenIt\Auditing\Models\Audit;` at the top of the class.

**Comment by mdiazr2000** [comment]
Hi I will like to expose my solution for this using listener

The best solution is to use a listener than a custom driver because the custom driver always has to return and audit object so using listener if you return in Auditing event false this prevents to save audit in database.

Well I create a Listerner named Auditing Listener

```
namespace App\Listeners;

use OwenIt\Auditing\Events\Auditing;
use OwenIt\Auditing\Exceptions\AuditingException;

class AuditingListener
{
   
    /**
     * Handle the Auditing event.
     *
     * @param Auditing $event
     * @return bool
     * @throws AuditingException
     */
    public function handle(Auditing $event)
    {
        $data = $event->model->toAudit();
        if (empty($data['old_values']) && empty($data['new_values'])) {
            return false;
        }
        return true;
    }
}

```

And in EventSeviceProvider in property listen put this:

` protected $listen = [
        'OwenIt\Auditing\Events\Auditing' => [
            'App\Listeners\AuditingListener',
        ],
    ];`
