### ISSUE TITLE
Wrong format date when created

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#310]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.3
| Package version   | 4.1.2
| PHP version       | 7.0.1

#### Actual Behaviour
Saving date field with format `Y-m-d 00:00:00`

#### Expected Behaviour
Saving date field with format `Y-m-d`

#### Steps to Reproduce
Create any record, having date field.

**Comment by quetzyg** [comment]
This doesn't seem to be an issue with the package.

**Comment by rorc** [comment]
MySQL field type is `date`,
In model `$dates = ['date']`;
```php
class AuditingListener
{
    public function handle(Auditing $event)
    {
        dump($event->model->date); //already wrong value 2017-01-10 00:00:00
    }
}

Order::create([
    'date' => Request::input('date'); //2017-01-10
]);
```
After this, `new_values` has `2017-01-10 00:00:00`

**Comment by quetzyg** [comment]
That's an Eloquent issue, which has been documented in the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) section.

**Comment by rorc** [comment]
Can we solve this problem automatically at core level?
Before or after calling method `transformAudit` run code like that:
```php
if (isset($this->casts[$key]) && $this->casts[$key] == 'date') {
    return Carbon::parse($value)->toDateString();
}
```

**Comment by rorc** [comment]
Now have to use many crutches before save audit, for example:
```php
if (isset($this->casts[$key]) && $this->casts[$key] == 'date') {
    return Carbon::parse($value)->toDateString();
}
```
And before output, for example:
```php
if ($value instanceof \DateTime && $value->toTimeString() == '00:00:00') {
    return $value->toDateString();
}
```

**Comment by quetzyg** [comment]
Sorry, I'm not gonna fix upstream issues here. If they say it's an expected behaviour, we should keep it consistent. Bump the upstream issue and propose a fix there, not here.

**Comment by rorc** [comment]
Ok ) Thank you for your sympathy )
