### ISSUE TITLE
Error when new_values or old_values is null

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#313]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.9
| Package version   | 4.1.3
| PHP version       | 7.0.1

#### Actual Behaviour
Error in file `owen-it\laravel-auditing\src\Audit.php` at line 104.
#### Expected Behaviour
I use `json` type for `new_values` and `old_values` and if they empty (`[]`) i convert it to null.
#### Possible Solutions
Before foreach `new_values` and `old_values` check they on empty.

**Comment by quetzyg** [comment]
>I use json type for new_values and old_values and if they empty ([]) **i convert it to null**.

I guess you're to blame.

Closing this.
