### ISSUE TITLE
Prune and execute not working

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#314]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.9
| Package version   | 4.1.3
| PHP version       | 7.0.1

### Description
```php
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Facades\Auditor;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Revise extends Model implements AuditableContract
{
    use Auditable;

    protected $auditableEvents = ['updated'];
}

$revise = Revise::create([
    'order_id' => 1,
    'bar_id' => 2,
    'admin_id' => 3,
    'report_id' => 4,
    'status_id' => 5
]);

Auditor::execute($revise);
Auditor::prune($revise);
```
No records was created.

**Comment by rorc** [comment]
Tryied to set `$revise->setAuditEvent('created');` before `execute`, same result.

**Comment by quetzyg** [comment]
It doesn't work like that, so that's an expected result.

In the [Auditor](http://www.laravel-auditing.com/docs/4.1/auditor) section, you can read following:
>Usually, **there's no need to use it directly**, since the AuditableObserver takes care of things for us.

**Comment by rorc** [comment]
So, for what not working example in Auditor section?

**Comment by quetzyg** [comment]
What are you trying to achieve?

**Comment by rorc** [comment]
I wanted customizing inserting audit.
Transfered this think to event.

**Comment by quetzyg** [comment]
I'm not sure what you mean by that, but [RTFM](http://www.laravel-auditing.com/docs/4.1/audit-drivers).

**Comment by rorc** [comment]
Ok, thanks.

**Comment by rorc** [comment]
By the way. Adding audit manually useful for pivot table, before call attach/detach/sync.
For example (pseudocode):
```php
$bar = tap(Bar::find(1))->update([...]);
$bar->new_values->put('items', $bar->items()->sync()) //this will not trigger any events
Audit::execute($bar);
```
