### ISSUE TITLE
Bugs with mySql json type and cast attribute to collection

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#315]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.9
| Package version   | 4.1.3
| PHP version       | 7.0.1

### Description:
There is mysql json field type `phones`.
There is model `Bar`:
```php
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Bar extends Model implements AuditableContract
{
    use Auditable;

    protected $casts = ['phones' => 'collection'];
}
```
When i update `phone` field:
```php
$phones = [111, 222];

Bar::update(compact('phones'));
```
`old_values` is `{phones: ["111", "222"]}` (with space between numbers).
`new_values` is `{phones: ["111","222"]}`  (without space between numbers).
And stored phone field value in mysql is `["111", "222"]` (with space).

And If i save again and again (without change any numbers), i will store and store new audit...

**Comment by quetzyg** [comment]
Somewhat related to #297 .

**Comment by rorc** [comment]
Probably its mysql issue. Mysql storing data in json field with spaces between comma.
If i change field type to text, or change casts from collection to array, all becomes ok.
