### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::check()

### ISSUE THREAD

**Issue by mike23v** [owen-it/laravel-auditing#316]
| Q                 | A
| ----------------- | ---
| Bug?              | not sure
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.36
| Package version   | 4.0
| PHP version       | 7.0.13

#### Actual Behaviour

I'm having the following error 
   "Call to undefined method Illuminate\Database\Query\Builder::check()"
when using the said package.

This is what I've tried so far in my model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\UserResolver;

class Library extends Model implements AuditableContract, UserResolver
{
    use Notifiable;

    use Auditable;

    protected $fillable = ['email'];

    protected $table = 'libraries';

    public static function resolveId()
    {
        return User::check() ? User::user()->getAuthIdentifier() : null;
    }
}
```

**Comment by quetzyg** [comment]
Hi @mike23v,

As you can see in the **Resolver** part of the [documentation](http://www.laravel-auditing.com/docs/4.1/general-settings), the resolver uses `Auth`, like so:

`return Auth::check() ? Auth::user()->getAuthIdentifier() : null;`

When in doubt, always check the [docs](http://www.laravel-auditing.com/docs/4.1). 😉

**Comment by mike23v** [comment]
Hi @quetzyg ,

It something to do in the config/audit.php

'user' => [
        'primary_key' => 'id',
        'foreign_key' => 'user_id',
        'model'       => App\User::class,
        'resolver'    => App\User::class,
    ],

When I try to change the 'resolver' to 

       'resolver'    => function () {
            return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
        },

it works fine. I believed you made some fix about this.

**Comment by quetzyg** [comment]
Please, read the documentation. It's all [there](http://www.laravel-auditing.com/docs/4.1/general-settings).

**Comment by mike23v** [comment]
@quetzyg , Thanks for your help.
