### ISSUE TITLE
Eloquent increment/decrement dont affects audit?

### ISSUE THREAD

**Issue by rorc** [owen-it/laravel-auditing#317]

**Comment by quetzyg** [comment]
[Rules](http://www.laravel-auditing.com/docs/4.1/problems), follow them.

**Comment by rorc** [comment]
Done)

**Comment by quetzyg** [comment]
Mate, you're constantly ignoring our issue submission [rules](http://www.laravel-auditing.com/docs/4.1/problems), creating issues about things that have either been [previously discussed](https://github.com/owen-it/laravel-auditing/issues?q=is%3Aissue+is%3Aclosed), or things that are already present  in the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) section.

Apparently the message wasn't clear enough, so I'll make it clear. Another submission like this one, will get you blocked from this repository.

In regards to the issue, read the first entry in the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) section, or see #139, #195, #240.

**Comment by rorc** [comment]
Ok, sry 😔

**Comment by rorc** [comment]
So, how i can insert audit after increment?
Do it manually are impossible (see https://github.com/owen-it/laravel-auditing/issues/314)
Should i do raw query? `Audit::create([...])`

**Comment by quetzyg** [comment]
```php
$model = Model::find($someId);

$model->update([
    'sum' => $model->sum + 10,
]);
```

Should do what you want.

**Comment by quetzyg** [comment]
If you really want to use `Model::increment('sum', 10);` you'll have to trigger the `updated` event manually so that the auditing can kick in.

**Comment by rorc** [comment]
How?
I tried following:
```php
$report->increment('sum', 10);
$report->save(); //or $report->update()
`old_values` and `new_values` are empty now, so no data for audit.
```
