### ISSUE TITLE
Mark all fields as nullable and do not force 'auditable_id' to be a integer

### ISSUE THREAD

**Issue by rogervila** [owen-it/laravel-auditing#319]
| Q                 | A
| ----------------- | ---
| Bug?              | It depends
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5.4
| Package version   | 4.1.3
| PHP version       | 7.1.9

#### Actual Behaviour

Sometimes I need to audit actions from a non-registered user, and I use UUID as a primary key on some models.

#### Expected Behaviour

I get mysql errors from the package, since it expects 'auditable_id' to be a integer, and the user_id to be "not null".

#### Steps to Reproduce

1 - Change the primary key of any model:

```php
protected $primaryKey = 'uuid';
``` 

2 - Call eloquent `create` function from a non-authorized route.

```php
MyModel::create([...]);
``` 

#### Possible Solutions

Mark all fields as nullable and do not force 'auditable_id' to be a integer.

**Comment by quetzyg** [comment]
Check the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) section. There are examples for what you need.
