### ISSUE TITLE
Allow defining Auditable Event Attributes Method Name

### ISSUE THREAD

**Issue by daniel-gomes-sociomantic** [owen-it/laravel-auditing#320]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.4.19
| Package version   | 4.1.3
| PHP version       | 7.0.15

#### Actual Behaviour

When setting custom events for auditing via the `auditableEvents` property, it is not possible to define the attributes method name.

#### Possible Solutions

Since different events might have their attributes handled the same way, it would be nice to be able to define the `auditableEvents` property values as either:
* Values without keys (like currently), in which case the usual `audit<AuditEvent>Attributes` method would be called.
* Values with keys, in which case the value would be the name of the method to call.

Example:

```php
public $auditableEvents = [
    'created',
    'updated',
    'deleted',
    'restored',
    'myEvent1' => 'auditCustomAttributes',
    'myEvent2' => 'auditCustomAttributes'
];
```

Just a thought, feel free to discard as not so important :-)

Either way, the [documentation](http://www.laravel-auditing.com/docs/4.1/behavior-settings) should be updated to explain the name of the method which gets called for non-standard events.

**Comment by quetzyg** [comment]
Very good suggestion @daniel-gomes-sociomantic! This will definitely be something for version 5, so watch this space.

Keeping this open.

**Comment by daniel-gomes-sociomantic** [comment]
PR for this in https://github.com/owen-it/laravel-auditing/pull/324

**Comment by quetzyg** [comment]
Fixed via #324

**Comment by andreshg112** [comment]
Is it possible to do this in the latest version? @anteriovieira

**Comment by anteriovieira** [comment]
Hi @andreshg112 , I'm currently involved with other projects and I'm not taking time to devote to laravel-auditing. But I'm open to pull request.
