### ISSUE TITLE
GetModified is returning an arrayed deleted_at

### ISSUE THREAD

**Issue by filtration** [owen-it/laravel-auditing#325]
| Bug?              | yes
| New Feature?      | no
| Framework         | Larave
| Framework version | 5.5
| Package version   | latest
| PHP version       |7.1

#### Actual Behaviour

So i am getting the modified data like so;

```
	@forelse($activity->getModified() as $key => $value)
		<tr>
			<td><strong>{{ $key }}</strong></td>
			<td class="danger">{{ $value['old'] ?? 'n/a' }}</td>
			<td class="success">{{ $value['new'] ?? 'n/a' }}</td>
		</tr>
	@empty
		<tr>
			<td class="alert alert-info" colspan="3">
				{{ __("Nothing has been modified") }}
			</td>
		</tr>
	@endforelse
```

Which is causing an error:

> htmlspecialchars() expects parameter 1 to be string, array given

For the deleted_at section

This is the data it is returning

```
{  
   "id":4,
   "user_id":1,
   "market":"test",
   "amount":"72.52",
   "fee":"0.02",
   "cost":"69782.00",
   "price":"943.00",
   "beforefee":"74.00",
   "method":"buy",
   "coin":"123",
   "ip":"1234",
   "deleted_at":{  
      "date":"2017-10-09 21:37:59.093538",
      "timezone_type":3,
      "timezone":"UTC"
   }
}
```

Is it possible to just get the delete_at date rather than the timezone etc? Or can I empletment that any way?

#### Expected Behaviour

I am getting the audit via the id, to display solo

**Comment by quetzyg** [comment]
See if casting to string works:
```php
<td class="danger">{{ (string) $value['old'] ?? 'n/a' }}</td>
<td class="success">{{ (string) $value['new'] ?? 'n/a' }}</td>
```

**Comment by quetzyg** [comment]
Closing as no reply for more than a week.
