### ISSUE TITLE
Feature: Audit trail management dashboard

### ISSUE THREAD

**Issue by ymslavov** [owen-it/laravel-auditing#327]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5.*
| Package version   | 4.*.*
| PHP version       | 7.1.*

#### Expected Behaviour

This is more of an idea I'd like to put out there and see if it would pique your interest so I can start working on it.

Having an audit trail is awesome and provides a nice way to enforce accountability. But it is viewed by many devs/product owners as a support functionality in case the shit hits the fan and the company needs to identify who threw the shit in the first place.

I'd like to change that and empower accountability officers to easily browse the audit trail and proactively identify issues with access, permissions, etc. I believe a small dashboard, based on VueJs would be a great (optional) addition to the package - similar to what Laravel Horizon did with the Redis queue management console. I envision ways to tabulate and filter the audit trail by model, actor and even by changed fields in order to identify sensitive areas of a system - e.g. "let me check who has been updating the user accounts recently...oh shit, who's given John permissions to do that, he's just a janitor?!"

Let me know what you think.

**Comment by quetzyg** [comment]
I like the idea of a dashboard and I reckon @anteriovieira has had a similar idea for some time.
However, I think it should be a separate package, not to be bundled with this one.

**Comment by ymslavov** [comment]
Yes, a separate package indeed sounds like the way to go. I'd love to hear @anteriovieira's thoughts and see if he's had any functionality planned out yet. If not, we can start drafting some initial wireframes.

**Comment by anteriovieira** [comment]
Hi @ymslavov , Your initiative is very good. we already have a [repository](https://github.com/owen-it/laravel-auditing-activity), and my thoughts are pointed to laravel-horizon.

You are invited to embark on this journey in our team.

**Comment by shanecp** [comment]
I think the repository link is broken.

**Comment by quetzyg** [comment]
@shanecp, It's just empty, atm :)

**Comment by quetzyg** [comment]
Closing this. Move the conversation to the appropriate [repository](https://github.com/owen-it/laravel-auditing-activity). 😉
