### ISSUE TITLE
Allow auditing on models where the primary key isn't an integer called ID

### ISSUE THREAD

**Issue by djekl** [owen-it/laravel-auditing#331]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.19
| Package version   | v4.1.4
| PHP version       | 7.1.11

#### Actual Behaviour

I am wanting to use this package with a model where I am using a UUID as the primary key, and another where my primary key is not ID and again isn't an integer

#### Expected Behaviour

Hoping to audit these models

#### Steps to Reproduce

Create a new model with a primary key that isn't called ID and isn't an unsigned integer or an integer.

**Comment by quetzyg** [comment]
Have you read the [documentation](http://www.laravel-auditing.com/docs/4.1/troubleshooting) ?

**Comment by djekl** [comment]
Yes, and it mentions using UUID as a `user_id`, but not for a different model.

For example I have a user, book, and category.
`user_id` - `unsignedInteger`
`book_id` - `uuid`
`category_code` - `string` (this is a slug)

How would I go about auditing the `book` and `category` models?

**Comment by quetzyg** [comment]
So what's stopping you from changing the id column from `integer` to `string` ?

**Comment by djekl** [comment]
@quetzyg its not immediately obvious thats all that was needed. Because you always reference the `user_id`, it lead me to the assumption that this was only for the users table.

**Comment by quetzyg** [comment]
As you can imagine, we can't predict/document all use cases, but as the documentation states, you're free to change the schema to suit your needs, so a little experimentation is all it takes.
