### ISSUE TITLE
User agents coming from facebook mobile browser are longer than 255 char

### ISSUE THREAD

**Issue by bounds** [owen-it/laravel-auditing#337]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.36
| Package version   | 4.0.5
| PHP version       | 7.1

#### Actual Behaviour

If the user agent comes from facebook's webview on safari, it is appended with facebook meta-data that causes it to exceed 255 characters. PDO error if the migration uses a `$table->string('user_agent')`

Had to modify my column to `VARCHAR(1000)` to be safe.

#### Expected Behaviour

Doesn't crash because of a sufficient migration suggestion in the docs.

#### Steps to Reproduce

1. Link yourself to your web address via facebook somehow ("only me" post)
2. Open the URL through the facebook iOS app and perform an action that propagates an audit
3. 500 exception (generally)

#### Possible Solutions

Increase the suggested `string` migration size. I don't think any `TEXT` based datatypes are necessary. Probably overkill.

**Comment by quetzyg** [comment]
This has been discussed in #174, #198, #238 and #302 (at least). There's a reference to this in the [troubleshooting](http://www.laravel-auditing.com/docs/4.1/troubleshooting) section of the documentation and a [commit](https://github.com/owen-it/laravel-auditing/commit/b0a4eeecbd45a75c4bab2fb857dcb4e6c411dc66).
