### ISSUE TITLE
Move default auditableEvents from getAuditableEvents() to configuration file

### ISSUE THREAD

**Issue by vyacheslav-kara** [owen-it/laravel-auditing#339]
| Q                 | A
| ----------------- | ---
| Bug?                  | no
| New Feature?    | yes
| Framework         | Laravel|Lumen
| Framework version | 5.5.0
| Package version   | 4.1.0
| PHP version       | 7.1

#### Actual Behaviour

Auditing always listens for all 4 events (created, updated, deleted, restored), but I need it to detect only some of the events, as I do not want to add it in all my models. Could we move the array (with events) from getAuditableEvents method to the configuration file?

#### Possible Solutions

Could we move the array (with events) from getAuditableEvents() method to the configuration file?

**Comment by quetzyg** [comment]
Fixed in #342
