### ISSUE TITLE
Update migration.

### ISSUE THREAD

**Issue by FooBarQuaxx** [owen-it/laravel-auditing#34]
I think the migration for the audit log table should be updated to use the configuration table name. Something like`Schema::create(config('auditing.table'), function() {...});` and `Schema::drop(config('auditing.table'));'`.

**Comment by anteriovieira** [comment]
I had done it, but then gave up the idea. Because it is against the concept of migration.

Initially the table is named logs, if we need to change the table name should create a new migration.
