### ISSUE TITLE
UnexpectedValueException Invalid User resolver, callable or UserResolver FQCN expected

### ISSUE THREAD

**Issue by simplenotezy** [owen-it/laravel-auditing#346]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 4.1
| PHP version       | 7.1.10

#### Actual Behaviour

I am trying to create a model, but I can't. The following error occours:

        throw new UnexpectedValueException('Invalid User resolver, callable or UserResolver FQCN expected');

#### Expected Behaviour

The model should be created.

#### Steps to Reproduce

Install the lastest version and create a model.

**Comment by ctf0** [comment]
i think this is what u r looking for http://www.laravel-auditing.com/docs/4.1/general-configuration Resolver
