### ISSUE TITLE
use medium/large text instead of text

### ISSUE THREAD

**Issue by ctf0** [owen-it/laravel-auditing#350]
| Q                 | A
| ----------------- | ---
| New Feature?      | yes

https://github.com/owen-it/laravel-auditing/blob/9393107248dc0fb24e89cafef9229caf027670d3/database/migrations/audits.stub#L35-L36

Text columns are not good incase you have something like data:uri, so using any of the other types would give more freedom and will avoid error  `the value is too long for old_value / new_value`

i can send a PR if u prefere to.

**Comment by quetzyg** [comment]
We've been over this in #174, #198, #238, #302 and #307 (at least). There's a reference to this in the [Audit Migration](http://www.laravel-auditing.com/docs/master/audit-migration) section of the documentation.

Just change your migration and be done with it.
