### ISSUE TITLE
Audit schedules

### ISSUE THREAD

**Issue by ibrunotome** [owen-it/laravel-auditing#351]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.5.5
| Package version   | 4.x.y
| PHP version       |7.1.8

Hi, first, thanks for the package. I just have one question, how to enable auditing with schedule jobs? In my tests it only works with an authenticated user, but I want to enable it when a schedule change a model.

**Comment by quetzyg** [comment]
Hi @ibrunotome,

You'll have to enable auditing from the console in the [configuration](http://www.laravel-auditing.com/docs/master/general-configuration).

**Comment by ibrunotome** [comment]
Sorry, I forgot to say that I already have enabled the auditing from the console. Here is my scenario:

- The user create a process, so package make the auditing successfully in this case.
- Some minutes later, the schedule starts a job in background, controlled by the Laravel Horizon, and this job may be update to Completed or stay in Processing. So i see in the audits that this last part wasn't audited when the update ocurres.

Still about the console configuration, I have to reload something?

Thanks for the support.

**Comment by ibrunotome** [comment]
Oh, I just run the php artisan cache:clear and service php-fpm restart and all is auditing right now. My fault, sorry for spend your time 👍
