### ISSUE TITLE
Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use

### ISSUE THREAD

**Issue by jinder-singh** [owen-it/laravel-auditing#359]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 5.4
| Package version   | 5.0
| PHP version       | 5.6

#### Actual Behaviour
I'm having this error 'Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use at line 17 of AuditableObserver.php' when implementing Auditable interface on Model'
--
```php
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
class Note extends Model implements Auditable
{
   use \OwenIt\Auditing\Auditable;
}
```

**Comment by quetzyg** [comment]
Version 5.0 requires PHP 7.0.13+
