### ISSUE TITLE
Laravel Auditing not trigger if i use ->update()

### ISSUE THREAD

**Issue by ivanchen** [owen-it/laravel-auditing#36]
Hei,
i report you about my problem, laravel Auditing not triggered if i use:
`Model::find(1)->update($array);`

REAL CODE from me is something like this:
`$variant->update($variantParams['general']);
$variant->touch();`

and Auditing will work if i change code like this:
`foreach ($variantParams['general'] as $key => $value) {
       $variant->$key = $value;
}
$variant->save();`

Correct me if i wrong.. 
Thanks..

**Comment by anteriovieira** [comment]
Hello @ivanchen ,

I will analyze, thank you for reporting.

**Comment by anteriovieira** [comment]
Hello @ivanchen , sorry for the delay in answering it

I tried it here
```php
User::find(2)->update(['name' => 'anterio.silva']);
```

```php
array:1 [▼
  0 => array:14 [▼
    "id" => 5
    "user_id" => null
    "owner_type" => "App\User"
    "owner_id" => 2
    "old_value" => array:1 [▼
      "name" => "Dr. Garnett Bartell Sr."
    ]
    "new_value" => array:1 [▼
      "name" => "anterio.silva"
    ]
    "type" => "updated"
    "created_at" => "2016-03-22 00:24:48"
    "updated_at" => "2016-03-22 00:24:48"
    "custom_message" => "Not defined custom message!"
    "custom_fields" => []
    "elapsed_time" => "1 second ago"
    "user" => null
    "owner" => array:5 [▶]
  ]
]
```

here it worked.

**Comment by eullercristian** [comment]
I have the same problem, i am using a package from repositories, https://github.com/andersao/l5-repository, there is any reason for the packet not is loggin the update? Follow my code: 

`
$data = $request->all();
 $this->repo->update($data, $id);`

**Comment by whereisjefe** [comment]
@eullercristian did you ever get this figured out?
