### ISSUE TITLE
Audited Data appears to be encoded encoded in utf-16

### ISSUE THREAD

**Issue by ned-painless** [owen-it/laravel-auditing#360]
| Q                 | A
| ----------------- | ---
| Bug?              | ?
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.3.y
| Package version   | 5.0
| PHP version       | 7.1.4

#### Actual Behaviour

Audited data appears to be stored encoded in utf-16.
sample audit 
`{"criteria_id":2,"is_checked":true,"application_id":111,"value":"\u07a6\u0790\u078b\u07a6\u0790\u078b","id":127}`

#### Expected Behaviour

`{"criteria_id":2,"is_checked":true,"application_id":111,"value":"ަސދަސދ","id":127}`

**Comment by quetzyg** [comment]
Thanks for the report, @ned-painless.

The package itself doesn't do the encoding, it just uses the cast functionality Eloquent offers to convert an `array` to a JSON string for both `old_values` and `new_values`.

The issue at hand is located [here](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L647), when calling [json_encode()](http://php.net/manual/en/function.json-encode.php), which escapes Unicode characters by default.

The solution would be to pass [JSON_UNESCAPED_UNICODE](http://php.net/manual/en/json.constants.php), but you'll have to take it [upstream](https://github.com/laravel/framework) and suggest some kind of configuration that you can set and that gets picked up by that method.
