### ISSUE TITLE
Class 'OwenIt\Auditing\Str' not found

### ISSUE THREAD

**Issue by nicopenaredondo** [owen-it/laravel-auditing#361]
Hi, Any reasons why I keep having this error ? I've already reinstall this package and it keeps showing up. I'm currently using 2.4.5

**Comment by quetzyg** [comment]
- Use the issue template;
- We don't support versions below 4.1 anymore;
- You're probably missing a `use Str;`

**Comment by nicopenaredondo** [comment]
*You're probably missing a use Str;* Upon checking the library. There is no "Str" used in the class.
