### ISSUE TITLE
Compatible with https://github.com/jenssegers/laravel-mongodb

### ISSUE THREAD

**Issue by medspec** [owen-it/laravel-auditing#362]
Hi, 

Would it be possible to make this package compatible with the mongdb driver? Or is the best solution to fork?

**Comment by mmodler** [comment]
Welche tabelle?


Mit freundlichen Grüssen,

Martin Modler
-- 

-----------------------------------
Webformatik Internetagentur
Wallgraben 9
04668 Grimma
-----------------------------------
Tel.:   +49 3437 9997440
Fax.:   +49 3437 9997443
www.webformatik.de
-----------------------------------
Inhaber: Martin Modler
USt.-Id.Nr. DE251275358
-----------------------------------

Am 20.12.2017 um 16:09 schrieb medspec:

**Comment by quetzyg** [comment]
Closing this because the [issue reporting rules](http://www.laravel-auditing.com/docs/5.0/problems) were not followed and you didn't even bother to read the [documentation](http://www.laravel-auditing.com/docs/5.0/audit-implementation).
