### ISSUE TITLE
Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use

### ISSUE THREAD

**Issue by maddevious** [owen-it/laravel-auditing#363]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.2
| Package version   | 5.0.2
| PHP version       | 7.0.26

#### Actual Behaviour

Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use in /Users/jmorgan/PhpstormProjects/ppdirect-api/vendor/owen-it/laravel-auditing/src/AuditableObserver.php on line 17

#### Expected Behaviour

To not receive the error above.

#### Steps to Reproduce

Setup the model as described in documentation.  Here is a sample:

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable;
use App\Library\HelperManager;
use App\Traits\FindTrait;
use App\Traits\UserTrait;

class Article extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable, SoftDeletes, FindTrait, UserTrait;

```

#### Possible Solutions

It seems like AuditableObserver.php is using Auditable which already exist.

**Comment by quetzyg** [comment]
Are you sure you're on PHP 7.0.26?

**Comment by maddevious** [comment]
Yes.

PHP 7.0.26 (cli) (built: Dec  2 2017 13:12:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by quetzyg** [comment]
The version used in Travis CI is `PHP 7.0.22 (cli) (built: Aug 17 2017 15:55:02) ( ZTS )` and it works just fine. Version **5.0.2** was released to prevent this issue, since only in version 7.0.13 this was [fixed](http://bugs.php.net/66773).

Are you able to run the tests and do they pass?

If you use the following code, does it work?

```php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;
use App\Library\HelperManager;
use App\Traits\FindTrait;
use App\Traits\UserTrait;

class Article extends Model implements AuditableContract
{
    use \OwenIt\Auditing\Auditable, SoftDeletes, FindTrait, UserTrait;
}
```

There was a similar issue opened a few weeks ago, which was solved by using version **7.0.13**. If you say you're already on **7.0.26**, I'm not sure what else to tell you.

What are you using, `php-fpm` ? Can you tell me the version?

**Comment by quetzyg** [comment]
I'm unable to reproduce this and I haven't heard from you since, so I'm closing this.

**Comment by jeremykes** [comment]
I am using Laravel 10.1 and PHP 8.1 and what I did to fix the issue was using @quetzyg snippet above;

```
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class User extends Authenticatable implements AuditableContract
{
    use HasApiTokens;
    use HasFactory;
    use Notifiable;
    use \OwenIt\Auditing\Auditable;

    protected $auditInclude = [
        'name',
        'email',
    ];
```

This removed the error for me.
