### ISSUE TITLE
Type error in Auditable.php in laravel-lumen 5.5 when run command in console "php artisan db:seed".

### ISSUE THREAD

**Issue by aminoacide** [owen-it/laravel-auditing#367]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.5 (master)
| Package version   | 5.5
| PHP version       | 7.1

#### Actual Behaviour

 Type error: Return value of App\Data::resolveIpAddress() must be of the type string, null returned in Auditable.php line 293

#### Expected Behaviour

To not receive the error above.

#### Steps to Reproduce

I have been configured for auditing from laravel-lumen (http://www.laravel-auditing.com/docs/5.0/general-configuration) documentation. I follow instruction step by step.

Step 0. I'm on "Resolver" in section in laravel-auditing general-configuration, I have added following line..

```
namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Auth\Authenticatable;
use Laravel\Lumen\Auth\Authorizable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Support\Facades\Auth;

use OwenIt\Auditing\Contracts\Auditable;
use OwenIt\Auditing\Contracts\UserResolver;

class User extends Model implements Auditable, UserResolver
{
    use \OwenIt\Auditing\Auditable;

   
    public static function resolveId()
    {
        return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
    }

   
}
```

Step 1. And I went to given Console section in documentation..and I just edited in config/audit.php file..
```

return [
    'user' = [
        'resolver' => App\User::class,
    ],
];

```
Step 2. Now I have done with Auditable-Configuration from (http://www.laravel-auditing.com/docs/5.0/auditable-configuration) documentation..

```

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class Data extends Model implements Auditable
{ 
 use \OwenIt\Auditing\Auditable;
/*
Some Codes Here :) 

*/
}

```
Step 3. And finally done with all Configuration according to given documentation. But when I run command (php artisan data:fetch ) in console to fetch data in my DB, it gives following error...
 
Type error: Return value of App\Data::resolveIpAddress() must be of the type string, null returned in Auditable.php line 293

#### Possible Solutions
It may be return 'console'.
Return value of App\Data::resolveIpAddress() must be of the type string that may be "console". 

Thanks for issue#364 :)
And also thanks in advance for this :)

**Comment by quetzyg** [comment]
Hi @aminoacide,

Sorry, I saw this and then I forgot to reply. What other changes have you made, besides what you've documented here? Usually, if you audit from the command line, you should get `127.0.0.1`, not `null`.

What about this part?
```
/*
Some Codes Here :) 

*/
```

What are you actually doing?

**Comment by quetzyg** [comment]
Regardless of what the issue was, from version 6 onward, you're able to implement your own IP Address resolver to suit your needs.
