### ISSUE TITLE
'Id' not found when model is retrieval contains ->select()

### ISSUE THREAD

**Issue by TzviCons** [owen-it/laravel-auditing#368]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.4.7
| Package version   | 5.0.3
| PHP version       | 7.1.
#### Actual Behaviour

I'm updating a model with the following code which should work.
```
$model = MyModel::where('relation_id', $request->input('relation_id'))
    ->select('field')
    ->first();
//do stuff
$success = $model->update($data);
```

   The audits table remains empty and an error is thrown: 
    `PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'auditable_id' cannot be null in /path/to/vendor/illuminate/database/Connection.php:449`
#### Expected Behaviour

I'm expecting a row in the audits table reflecting $data along with old_values

#### Steps to Reproduce

Just use any model you have on hand and query the table with a ->select

#### Possible Solutions

When I remove the ->select() section it works okay.

My guess is that the id of the table row is not properly ascertained unless it is retrieved in the SELECT. There should be a way of obtaining the data as Lumen is able to create an UPDATE statement for it.

**Comment by quetzyg** [comment]
Well, if you're excluding a model attribute that's needed to create a new `Audit` record, I guess it explains:

`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'auditable_id' cannot be null in /path/to/vendor/illuminate/database/Connection.php:449`

>When I remove the ->select() section it works okay.

There you go, then.

>My guess is that the id of the table row is not properly ascertained unless it is retrieved in the SELECT. 

Well...

```php
$model = MyModel::where('relation_id', $request->input('relation_id'))
    ->select('id', 'field')
    ->first();
```
