### ISSUE TITLE
Request flag to use HTTP_X_FORWARDED_FOR in audit logs.

### ISSUE THREAD

**Issue by snapple42** [owen-it/laravel-auditing#369]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      |yes
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 4.1.y
| PHP version       | 7.0

#### Actual Behaviour

When generated auditing logs, the IP from a load balancer is used. It's always an internal IP.

#### Expected Behaviour

If a "HEADER" is defined, possibly use that to pull the proper IP out of the request (HTTP_X_FORWARDED_FOR)

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.
```php
    protected function resolveIpAddress(): string
    {
      $header = Config::get('audit.header');  
      return $header?Request::header($header):Request::ip();
    }

```

**Comment by snapple42** [comment]
Slight Mod:

```php
    protected function resolveIpAddress()
    {
        $header = Config::get('audit.header');  
        $ip = $header?Request::header($header):Request::ip();
        return $ip?$ip:Request::ip();
    }
```

**Comment by quetzyg** [comment]
Hi @snapple42,

You could always do that yourself, by overriding the `resolveIpAddress` method with what you suggested.

What do you reckon?

**Comment by quetzyg** [comment]
In version 6, you'll be able to implement your own resolvers for IP/User Agent/URL/User.
