### ISSUE TITLE
"Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use"

### ISSUE THREAD

**Issue by IgorDePaula** [owen-it/laravel-auditing#371]
| Q                 | A
| ----------------- | ---
| Bug?              yes
| New Feature?      no
| Framework         Laravel
| Framework version | 5.5.31
| Package version   | 5.0.1
| PHP version       7.0.10

#### Actual Behaviour

Describe the behaviour you're experiencing. Do not just copy and paste a random error message and expect help.

"Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use"

#### Expected Behaviour
None, its work
Describe the behaviour you're expecting.
On run the sysm, I receive this message:

"Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use"

#### Steps to Reproduce
Install the package and run the system

![erro laravel](https://user-images.githubusercontent.com/2833993/35077454-a43692f0-fbe4-11e7-9376-5fc5e644b804.png)

#### Possible Solutions

Separete the namespaces or another named the coflicting classes.

Has trait named Auditable on namespace root, on AuditableOberver use another classe with same name.  Alias the classes/traits is a good idea.

**Comment by IgorDePaula** [comment]
Now, is another class

![erro laravel 2](https://user-images.githubusercontent.com/2833993/35078456-7ea4ee10-fbe9-11e7-950a-5993c105056e.png)

**Comment by quetzyg** [comment]
This has been discussed in #354. You have to upgrade to PHP 7.0.13.
