### ISSUE TITLE
Auditable trait. Failed resolveUserAgent when User-Agent is empty

### ISSUE THREAD

**Issue by dominikveils** [owen-it/laravel-auditing#372]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5
| Package version   | v5.0.3
| PHP version       | 7.x.y

#### Actual Behaviour

PHP7 type error (return value) is thrown when request missing `User-Agent` header.

#### Expected Behaviour

Expected to get empty `User-Agent`, not null or exception

#### Steps to Reproduce

Make http request without User-Agent header and save Auditable model.

#### Possible Solutions

Explicity typecast to `(string)` return value of `resolveUserAgent` and other functions in `Auditable` trait.

**Comment by quetzyg** [comment]
Thanks for reporting this @dominikveils, I'll fix it ASAP.

**Comment by quetzyg** [comment]
In version 6, the default User Agent resolver won't have this issue.

**Comment by quetzyg** [comment]
While version 6 isn't released, I've tagged version 5.0.4, which addresses this problem.
