### ISSUE TITLE
Double insert on table when using created trait

### ISSUE THREAD

**Issue by JakePerillano** [owen-it/laravel-auditing#373]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.28
| Package version   | 4.x.y
| PHP version       | 7.1.10

#### Actual Behaviour
double insert on audits table

#### Expected Behaviour
inserts only once

Describe the behaviour you're expecting.

#### Steps to Reproduce
create a trait, use Auditable trait on new trait
trigger audit event by adding a record

**Comment by quetzyg** [comment]
You'll have to show the code you're using, that description isn't enough.

**Comment by TzviCons** [comment]
My duplicate https://github.com/owen-it/laravel-auditing/issues/299

**Comment by quetzyg** [comment]
I'm unable to reproduce the error.

```php
<?php

namespace App;

trait Foo
{
    use \OwenIt\Auditing\Auditable;
}
```

Using this trait in a model, and I'm getting expected results (as in, only one `Audit` record, not two).

**Comment by AbbyJanke** [comment]
I seem to have this issue, If the new trait you create is called "Auditable" and `uses` "OwenIt\Auditing\Auditable" trait it duplicates it.

Example Code:

```php
<?php

namespace Cord\Clients\app\Models\Traits;

use OwenIt\Auditing\Auditable as OwenItAuditable;
use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
use OwenIt\Auditing\Facades\Auditor;
use DB;

trait Auditable
{

    use OwenItAuditable;
    use PivotEventTrait;

    public static function boot()
    {
        parent::boot();

        static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
          //$audit = Auditor::execute($model);
        });

        static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            //
        });

        static::pivotDetaching(function ($model, $relationName, $pivotIds) {
            //
        });

        static::pivotDetached(function ($model, $relationName, $pivotIds) {
            //
        });

        static::pivotUpdating(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            //
        });

        static::pivotUpdated(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            //
        });
    }
```

My reason for extending is the fact that I want to audit pivot changes to and I have a hackish way using https://github.com/fico7489/laravel-pivot By changing the name of my new trait from "Auditable" to literally anything else it only inserts once. 

So your test wouldn't cause any issue @quetzyg because its not called "Auditable"

**Comment by quetzyg** [comment]
So what's the issue, then? Just call it something else.

**Comment by AbbyJanke** [comment]
Not saying its a major issue, just saying thats what the issue. I can't figure out why it would save twice when i'm only calling it to be used once. I've never had a plugin do that so just wanted to share the reason why it is for others mostly.

**Comment by quetzyg** [comment]
The only reason I can see is the event being fired twice, which would then store twice.

**Comment by yllndritb** [comment]
> I seem to have this issue, If the new trait you create is called "Auditable" and `uses` "OwenIt\Auditing\Auditable" trait it duplicates it.
> 
> Example Code:
> 
> ```
> <?php
> 
> namespace app\Traits;
> 
> use OwenIt\Auditing\Auditable as OwenItAuditable;
> use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
> use OwenIt\Auditing\Facades\Auditor;
> use DB;
> 
> trait Auditable
> {
> 
>     use OwenItAuditable;
>     use PivotEventTrait;
> 
>     public static function boot()
>     {
>         parent::boot();
> 
>         static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
>           //$audit = Auditor::execute($model);
>         });
> 
>         static::pivotAttached(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
>             //
>         });
> 
>         static::pivotDetaching(function ($model, $relationName, $pivotIds) {
>             //
>         });
> 
>         static::pivotDetached(function ($model, $relationName, $pivotIds) {
>             //
>         });
> 
>         static::pivotUpdating(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
>             //
>         });
> 
>         static::pivotUpdated(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
>             //
>         });
>     }
> ```
> 
> My reason for extending is the fact that I want to audit pivot changes to and I have a hackish way using https://github.com/fico7489/laravel-pivot By changing the name of my new trait from "Auditable" to literally anything else it only inserts once.
> 
> So your test wouldn't cause any issue @quetzyg because its not called "Auditable"

Can you please share more about the solution you use with laravel-pivot to keep track of pivot table changes because I had no success.Can you pleas share your code?
