### ISSUE TITLE
[Feature] differentiate between delete & force delete

### ISSUE THREAD

**Issue by ctf0** [owen-it/laravel-auditing#375]
| Q                 | A
| ----------------- | ---
| New Feature?             | yes
| Framework         | Laravel
| Framework version | 5.5.32
| Package version   | 5.0.3
| PHP version       | 7.2.1

atm laravel doesnt differentiate between delete & force delete as in both ways you will get the same events `delete / deleting` so maybe the audit package can support this by checking when adding a record for deleted models ex
```php
static::deleted(function($model){
    if(is_null($model->withTrashed()->find($model->id))) {
       // item was force deleted
    }
}
```

so in that case we can have a new column of `deleted_at` in the audit table to indicate that this item is a force deleted item.

this won't affect the current usage except for those who needs to do some ops depend on the model state ex.https://github.com/ctf0/Odin or having a UI that shows the app wide activities.

**Comment by quetzyg** [comment]
I can't say I see a need for this. You could always implement it yourself using the `transformAudit()` method. Check [here](http://www.laravel-auditing.com/docs/5.0/audit-transformation).

PS: dude, you should totally read the **whole** documentation first, before opening tickets left and right.

**Comment by ctf0** [comment]
reading the docs have nothing to do with suggesting an enhancement, thanx anyway.
