### ISSUE TITLE
[Feature] optimize the user relation call

### ISSUE THREAD

**Issue by ctf0** [owen-it/laravel-auditing#376]
| Q                 | A
| ----------------- | ---
| New Feature?             | yes
| Framework         | Laravel
| Framework version | 5.5.32
| Package version   | 5.0.3
| PHP version       | 7.2.1

atm the package auto load the user relation on each record call, which means if we used `Audit::all()` to get all the records to build a UI that list all the app activities, we also going to make as much calls to the db as the records in the audit table.

for example 
- if the audit table hold 100 row
  + it means we will have 101 call
    + 1 for the audit table call
    + 100 for the user relation

so maybe the package can internally use caching to cache the user resolve call, so even when calling those 100, it only gets executed once instead of each time we view the `Audit::all()` results.

also because the package already listen to the model events, so invalidating the user cache will be very easy to achieve.
<br>

> ### on a side note

aside from that i don't know what might be the use case of it specially that all the data can be accessed normally like any other model ex.`$audit->ip` but why the `getMetadata()` have the user records ?
```
  "audit_id" => 1
  "audit_event" => "created"
  "audit_url" => "console"
  "audit_ip_address" => "127.0.0.1"
  "audit_user_agent" => "Symfony/3.X"
  "audit_tags" => []
  "audit_created_at" => "2018-01-28 16:12:13"
  "audit_updated_at" => "2018-01-28 16:12:13"
  "user_id" => 1
  "user_name" => "Rossie Casper"
  "user_email" => "runte.marcella@example.net"
  "user_is_active" => false
  "user_last_login" => null
  "user_created_at" => "2018-01-28 16:12:13"
  "user_updated_at" => "2018-01-28 16:12:42"
```

and how to avoid that so the meta data is only the audit records, so the above become
```
  "audit_id" => 1
  "audit_event" => "created"
  "audit_url" => "console"
  "audit_ip_address" => "127.0.0.1"
  "audit_user_agent" => "Symfony/3.X"
  "audit_tags" => []
  "audit_created_at" => "2018-01-28 16:12:13"
  "audit_updated_at" => "2018-01-28 16:12:13"
```

**Comment by quetzyg** [comment]
`Audit::with('user')->get()` ?

**Comment by ctf0** [comment]
awesome, now only the `getMetadata()`

**Comment by quetzyg** [comment]
>awesome, now only the getMetadata()

If you don't want to audit the `User`, just create a resolver that returns `null`. That will get you the `Audit` data with just a `user_id` attribute with a `null`value.

>btw using `$this->audits()->with('user')->get()` or `$this->audits()->get()` gives the same result except with the relation i get extra calls.

I'm not sure I understand your problem, since the `->with('user')` should solve the N+1 problem you're having (see [here](https://laravel.com/docs/5.5/eloquent-relationships)).

Also bear in mind that an `Audit` is just an Eloquent model, so use it like so.

**Comment by ctf0** [comment]
> If you don't want to audit the User, just create a resolver that returns null. That will get you the Audit data with just a user_id attribute with a nullvalue.

i do want to audit the user, i just dont want its data to show up in where it shouldnt, maybe there could be a way to override the `getMetadata()` method instead ?

**Comment by quetzyg** [comment]
Mate, it's an `array`, just use the data you want and leave out the rest.
