### ISSUE TITLE
New values are being placed into sub-arrays and serialized

### ISSUE THREAD

**Issue by mikemike** [owen-it/laravel-auditing#379]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 5.0.3
| PHP version       | 7.1.8

#### Actual Behaviour

I'm using `updateOrCreate()` statically.  The audit log is updated.  `old_values` is correct, `new_values` is populated with incorrect data.  I'm seeing sub-arrays being created, even though that's not what I am passing.

I suspect this is caused by `updateOrCreate`.

Some sample data:

old_values:
`{"price":"102.0000","cost_price":"27.0000","minimum_sale_price":"56.0000","tax_rate":"20.0"} `

new_values:
`{"price":{"0":"999"},"cost_price":{"0":"99"},"minimum_sale_price":{"0":"99"},"tax_rate":{"0":"20"}}`

The actual values themselves on the price table are updated correctly.

#### Expected Behaviour

I'd expect the new data to be in the `new_values`.

#### Steps to Reproduce

It's quite difficult to show this in context, as there's a lot going on in the script, but the problem line is this:

```
Price::updateOrCreate(
    [
        'territory_id' => 1, 
        'master_product_id' => 1,
        'currency_id' => 1,
    ],
    [
        'price' => 999,
        'cost_price' => 99,
        'minimum_sale_price' => 99,
        'tax_rate' => 20,
    ]
);
```

#### Possible Solutions

I've taken a look at the code but struggling to see what could be causing this.  One possible cause is the `isDirty()` call, which isn't necessarily applicable as I'm calling this statically.

**Comment by quetzyg** [comment]
Sorry, I'm unable to reproduce such error.

**Comment by quetzyg** [comment]
@mikemike, you'll have to provide more info on what's going on before the `updateOrCreate()` call.

**Comment by quetzyg** [comment]
Sorry mate, but without further data, I can't help you. Like I said earlier, I'm unable to reproduce the issue you're having with the information you have provided. Feel free to comment and add more information if you're still having problems and I'll reopen this.

**Comment by eugenevdm** [comment]
@mikemike

> I'm using updateOrCreate() statically. The audit log is updated.

I'm using updateOrCreate() statically but it's simply not working. Is there anything special you had to do to get it working?

**Comment by mikemike** [comment]
We re-wrote our code to not used `updateOrCreate()`, which got everything to work as expected.  The application is quite complex though, so it's possible it was related to something we changed in our model's boot methods or something, but given this is now 3 years old it's hard for me to check, sorry.

**Comment by eugenevdm** [comment]
@mikemike cool thanks for the reply, once I saw your post and knew it was possible I dug deeper and found this switch which sorted us out because we need auditing in the Artisan commands

```php
/*
    |--------------------------------------------------------------------------
    | Audit Console
    |--------------------------------------------------------------------------
    |
    | Whether console events should be audited (eg. php artisan db:seed).
    |
    */

    'console' => true,
```
