### ISSUE TITLE
Audits not working when processing an event from a job

### ISSUE THREAD

**Issue by yamenarahman** [owen-it/laravel-auditing#381]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 4.1
| PHP version       | 7.1

#### Actual Behaviour

I updated a model from a controller and from a job.

#### Expected Behaviour

Audits should record both, however it records only what happens in controller not in job.

**Comment by quetzyg** [comment]
Have you read the configuration [documentation](http://www.laravel-auditing.com/docs/5.0/general-configuration)?

**Comment by yamenarahman** [comment]
If I hadn't read the docs it's supposed not to work at all, But I'm telling you that it's working from a controller not from a job.

**Comment by quetzyg** [comment]
From the documentation:
>Eloquent events that are fired when running in the console, are **not** audited by default.
