### ISSUE TITLE
Updating model via Eloquent relationship does not audit model changes

### ISSUE THREAD

**Issue by brynj-digital** [owen-it/laravel-auditing#383]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.34
| Package version   | 5.0.4
| PHP version       | 7.1.7

#### Actual Behaviour

I have a model instance that I'm then using to reference and update the attributes of an Eloquent relationship. Updates work fine, but are not logged by the package.

#### Expected Behaviour

I would expect the model which is referenced by the Eloquent relationship to have all changes logged. 

#### Steps to Reproduce

I have Customer model that has a one to many relationship `addresses()`, with CustomerAddress. I am updating existing customer addresses with:

`$customer->addresses()->where('id', $address_id)->update($address);` 

This works, but no changes are logged. Both my Customer and CustomerAddress models implement Auditable and use the Auditable trait.

If I explicitly find the required instance of my CustomerAddress, and update this, the changes get logged. This works, basically:

`CustomerAddress::findOrFail($address_id)->update($address);`

**Comment by quetzyg** [comment]
Read the [troubleshooting](http://www.laravel-auditing.com/docs/5.0/troubleshooting) section of the documentation. You'll know why it doesn't work.
