### ISSUE TITLE
Invalid User Resolver

### ISSUE THREAD

**Issue by ahmadsopian311** [owen-it/laravel-auditing#385]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.3.31
| Package version   | 5.0
| PHP version       | 7.1.11

#### Actual Behaviour

I want to implement the laravel Auditing on my website, but it's error with message "Invalid UserResolver Implementation"
anyone can help?

My model
![image](https://user-images.githubusercontent.com/6296619/36003268-c9b7a1cc-0d5f-11e8-89de-d10fcacfe7d8.png)

My User Model
![image](https://user-images.githubusercontent.com/6296619/36003284-de52c8fa-0d5f-11e8-9ad6-daeec8bfe39b.png)

My Audit Config
![image](https://user-images.githubusercontent.com/6296619/36003298-f19e0e92-0d5f-11e8-86d9-ecaff81f1d83.png)

**Comment by quetzyg** [comment]
At first glance, from the screenshots you've posted everything seems to be OK (apart from a typo on the `MasterLevelPatient` model, where you have `$tabel`, which should be `$table`).

What other info can you provide?
Also, can you fill the PHP/Framework/Package versions in the table, please?

**Comment by ahmadsopian311** [comment]
@quetzyg already change the typo, and edit the table. the error still coming out

**Comment by quetzyg** [comment]
Yes, I know. Still a typo, though.

What's the file system path to the `User` class? What other information can you provide?

**Comment by quetzyg** [comment]
While the code you've posted looks OK, you failed to provide more information. The `Invalid UserResolver Implementation` exception is thrown when the FQCN you used in the resolver configuration does not implement the `UserResolver` interface, so I'm gonna go with an issue on your end.

Feel free to comment if you have more info.
