### ISSUE TITLE
www.laravel-auditing.com works, but laravel-auditing.com does not

### ISSUE THREAD

**Issue by wunc** [owen-it/laravel-auditing#386]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel

#### Actual Behaviour

Clicking on the link to the website in your `readme.md` (or typing laravel-auditing.com into the browser) leads to a connection timeout.

However, www.laravel-auditing.com (note the www) resolves correctly and works.

#### Expected Behaviour

Clicking on the link in your readme should go to your website :)

#### Possible Solutions

Either (a) modify the links in the readme and associated docs to include the www subdomain or (b) adjust the DNS entries so that it works both with and without the www.

**Comment by quetzyg** [comment]
Thanks for the heads up @wunc.

I've assigned this one to you, @anteriovieira 😉

**Comment by anteriovieira** [comment]
Hi @wunc , try to access http://laravel-auditing.com/ please

**Comment by quetzyg** [comment]
Looks fine, now!
