### ISSUE TITLE
Audit records created while it shouldn't

### ISSUE THREAD

**Issue by ronnievisser** [owen-it/laravel-auditing#388]
| Q                 | A
| ----------------- | ---
| Bug?              yes
| New Feature?      no
| Framework         Laravel
| Framework version | 5.4.36
| Package version   | v6.0.0
| PHP version       | 7.1.9

#### Actual Behaviour

Audit records are created even when $auditInclude field are not updated. it's creating records with empty json object in new and old fields

#### Expected Behaviour

No records should be created

#### Steps to Reproduce

Update fields of a model that you are not watching and save. A record is created while is shouldn't

#### Possible Solutions

Check if the json object to insert in new value atuall has data

**Comment by quetzyg** [comment]
Hi @ronnievisser,

The issue template clearly states that code that reflects what you're actually doing, should be provided. Models, configuration, etc.

**Comment by quetzyg** [comment]
Issue template rules were not met.
