### ISSUE TITLE
[Question] Create log in controller

### ISSUE THREAD

**Issue by marcelogarbin** [owen-it/laravel-auditing#389]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 6
| PHP version       | 7

#### Question

Is there a method for manually creating a log?

Ex.: Create a log when the user login or logoff or when accessing a particular method that is in the controller.

**Comment by quetzyg** [comment]
Have a look at the [Auditor](http://www.laravel-auditing.com/docs/6.0/auditor), or I guess you could just create an `Audit` manually via `Audit::create([ ... ]);`

**Comment by quetzyg** [comment]
Let us know if that helped. I'll close this ticket, but feel free to continue commenting.

**Comment by quetzyg** [comment]
Also, here's a related issue #270
