### ISSUE TITLE
error auditing non int-keyed entities

### ISSUE THREAD

**Issue by maurocordioli** [owen-it/laravel-auditing#392]
| Q                 | A
| ----------------- | ---
| Bug?              | yes( border line)
| New Feature?      | maybe
| Framework         | both
| Framework version | 5.*
| Package version   | 6.
| PHP version       | 7

#### Actual Behaviour
auditing an entity with a primary key not integer, results in e sql error
inserting the filed "auditable_id"

#### Expected Behaviour

not experiencing the sql error

#### Steps to Reproduce
define en entity with primary key for example string varchar(50)
define the entity ad auditable
create or update the entity

#### Possible Solutions
provide a auditKey member di the autitable object that casts the key to a uniform format ( a string)

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by quetzyg** [comment]
A solution for this is in the documentation, so no point in having this issue open.
