### ISSUE TITLE
problema com chave estrangeira dos old_values e new_values

### ISSUE THREAD

**Issue by sotnaspina** [owen-it/laravel-auditing#393]
Prezados,

Como faço para recuperar/exibir um registro de relacionamento belongsTo().

Exemplo: 
O getModified() retorna:
array:9 [▼
  "menus_id" => array:1 [▼
    "new" => "5"
  ]
  "name" => array:1 [▶]
  "icon" => array:1 [▶]
  "color" => array:1 [▶]
  "route" => array:1 [▶]
  "enable" => array:1 [▶]
  "updated_at" => array:1 [▶]
  "created_at" => array:1 [▶]
  "id" => array:1 [▶]
]

e eu gostaria de exibir o nome do relacionamento do atributo "menus_id" em vez do id.

estou usando com o arquivo de tradução:
return [
    // ...
    'unavailable_audits' => 'Nenhuma auditoria disponível',

    'created'            => [
        'metadata' => 'Em :created_at, :user_name [:ip_address] criou o registro via :model',
        'modified' => [
            'menus_id' => 'O menu <strong>:new</strong> foi criado.',
            'name'   => 'O nome <strong>:new</strong> foi criado.',
            'icon'   => 'O icone <strong>:new</strong> foi criado.',
        ],
    ],
    // ...
];

não sei se a explicação ficou clara.

Grato!

**Comment by quetzyg** [comment]
É favor de seguir as regras para submissão de problemas.

**Comment by quetzyg** [comment]
Closed due to not following the rules.

**Comment by sotnaspina** [comment]
@quetzyg foi mal, conseguiu achar aqui. http://laravel-auditing.com/docs/5.0/audit-transformation
