### ISSUE TITLE
Testing with sqlite database - cannot create `audits` table

### ISSUE THREAD

**Issue by denitsa-cm** [owen-it/laravel-auditing#394]
| Q                 | A
| ----------------- | ---
| Bug?              | not sure
| New Feature?      | no
| Framework         | Larave
| Framework version | 5.5.5
| Package version   | 6.0.1
| PHP version       | 7.2

#### Actual Behaviour

I am running phpunit testing with `sqlite` and `:memory:` as database. 

However, I cannot get the `audits` table created correctly for some reason and getting an error 

`Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1 no such table: audits`

when I run a test that has a model with audits. Removing the auditing from the model allows the test to pass successfully. 

#### Expected Behaviour

I would like to have the `audits` table created during testing with an sqlite database.

#### Steps to Reproduce

...

#### Possible Solutions

New to Laravel, so not sure I can suggest any solutions, but rather asking for some help :)

**Comment by quetzyg** [comment]
Hi @denitsa-cm,

The problem is that you're trying to use Doctrine to access an SQLite in memory database created from a database connection using the Laravel QueryBuilder/Eloquent.

And that is not possible using `:memory:` databases. Use a file instead:

```php
    'connections' => [
        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],
        // ...
    ];
```
