### ISSUE TITLE
Add Masked Fields Support

### ISSUE THREAD

**Issue by desertfoxmb** [owen-it/laravel-auditing#395]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 6.0.1
| PHP version       | 7.0.1

#### Actual Behaviour

No field masking allowed

#### Desired Behaviour

Add the ability to have a masked fields property. The desired behavior would be to still include the field in the audit (unless it was in the exclude list) but to mask it. Additionally it may be good to have a configuration for "MaskAllButLastXChars" which would take the number of characters to leave exposed.

For example, with something like a social security or credit card number, supposing MaskAlLButLastXChars = 4, replace the new/old values with ***1234. It would still be clear that the value was in the change set but information security wouldn't be violated.

**Comment by desertfoxmb** [comment]
No worries, thanks for getting back when you did. I'm glad you think that idea is useful. Great job on the project. Easy to implement and easy to customize data that's saved if necessary.

**Comment by quetzyg** [comment]
This feature is now available in `master`. Will tag soon, once the documentation is updated.
