### ISSUE TITLE
[Feature] Add the ability to clean old records

### ISSUE THREAD

**Issue by ttomdewit** [owen-it/laravel-auditing#397]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.5.32
| Package version   | 6.0
| PHP version       | 7.1.4

#### Actual Behaviour

_There is currently no behavior that reflects the requested feature._

#### Expected Behaviour

I would like to request a feature that will clean old records, similar to Spatie's [Laravel Activitylog](https://github.com/spatie/laravel-activitylog) (_[view reference](https://github.com/spatie/laravel-activitylog/blob/master/src/CleanActivitylogCommand.php)_).

#### Steps to Reproduce

_There are currently no steps to reproduce._

#### Possible Solutions

I would like to work with you on a Pull Request that adds similar functionality to this package much like Spatie's implementation (_[view reference](https://github.com/spatie/laravel-activitylog/blob/master/src/CleanActivitylogCommand.php)_).

I would like to suggest creating a Console command that I can periodically run to get rid of all data that is no longer required. Within the configuration file we'd store the amount of days we'd like to store the data we're collecting.

#### Note

Please note that I'm fully aware it might not be exactly what this package entails. It's for storing a trail, a trail starts somewhere and most people would want to know and view the activity from start-to-finish. Having said that, I don't think this will be a breaking change, but more a "nice to have" addition. I'd love to hear your thoughts.

**Comment by quetzyg** [comment]
You can already set how many `Audit` records you want to keep per `Auditable` model. See the [Auditable Configuration](http://www.laravel-auditing.com/docs/6.0/auditable-configuration), more specifically the **threshold** part.

**Comment by ttomdewit** [comment]
Thank you for your reply, sorry I missed this.

**Comment by quetzyg** [comment]
No problem, mate.
