### ISSUE TITLE
Feature: Audit Tags with attribute replacing and field selection

### ISSUE THREAD

**Issue by daniel-gomes-sociomantic** [owen-it/laravel-auditing#398]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.x.x
| Package version   | 6.x.y
| PHP version       | 7.x.y

#### Actual Behaviour

It is allowed to define a Model's Tags as simple strings.

#### Suggested Behaviour

I've implemented these two things locally that I think other Laravel Auditing users could benefit from:

Attribute Replacing
-------------

This would allow tokens like `{attribute}` in the tag names, which would be replaced by the model's `attribute` value when generating the tags. This is helpful for grouping the audits of a main model and its related models together, by having the related model's audits tagged with the main model's ID, eg:

**Main entity**: 
```php
public function generateTags(): array
{
    return ['entity_{id}'];
}
```

**Related entity:**
```php
public function generateTags(): array
{
    return ['entity_{parent_id}'];
}
```

Field Selection
-------------

This would allow tags to define what model fields they should be applied to, with the the tags being applied only if the specified fields are dirty. This can be helpful to have changes done to different fields within the same model tagged with different tags, eg:

```php
public function generateTags(): array
{
    return [
        'tag_all_fields',
        'tag_some_fields' => [
            'field1',
            'field2'
        ]
    ];
}
```

Meaning that `tag_all_fields` would be applied to all changes done to the model whereas `tag_some_fields` would only apply for changes done to the `field1` and `field2` model fields.

If there is interest, I could probably come up with a PR for this.

**Comment by quetzyg** [comment]
Hey @daniel-gomes-sociomantic , thanks for your suggestions.

The attribute replacement would be kind of cool, but at the end of the day, this
```php
public function generateTags(): array
{
    return ['entity_{id}'];
}
```
would be the same as

```php
public function generateTags(): array
{
    return [
        'entity_'.$this->id, // or "entity_{$this->id}" or sprintf('entity_%s', $this->id)
    ];
}
```
without having to do string replacement and resolving attributes.

In regards to your field selection proposal, again, depends on the logic the user wants, and while it may be nice to have tagging only for dirty fields or anything, eventually someone will show up needing a different business logic, so I just leave the implementation up to the user.

The only thing that is expected from the `generateTags()` method is an `array` being returned, so it can be converted to a CSV. The logic to generate such `array` is up to the user.

Thoughts?

**Comment by daniel-gomes-sociomantic** [comment]
> The attribute replacement would be kind of cool, but at the end of the day, this
> would be the same as
> without having to do string replacement and resolving attributes.

true, but have a look down there as to why this isn't possible for my case.

> In regards to your field selection proposal, again, depends on the logic the user wants, and while it may be nice to have tagging only for dirty fields or anything, eventually someone will show up needing a different business logic, so I just leave the implementation up to the user.

Fair enough.

The thing is, to implement the kind of logic I need I overwrote the `generateTags()` method on another trait of my own, so that my `generateTags()` with the "special" logic can be shared by all of my models. However, this means that it can't rely on `$this->attribute` anymore, so to achieve this I invented an `$auditTags` property where I put the tags in the format I suggested and which my `generateTags()` reads and parses as needed in order to return the `array` of tag names that Auditing expects.

The problem I see is that my trait is "extending" the Auditing trait, which is not a very nice design. True, I could leave the `generateTags()` method in the actual models and get it to call a method that does the tag-parsing as I need it, but I'd like to avoid having to call that method manually on every model...

The second problem is that my trait (and the library's `Auditable` trait, for that matter) relies on methods like `getAttributes()` or `getDirty()` which are _supposed_ to exist since the trait is _supposed_ to be used in Eloquent models, but there's no actual guarantee of that, meaning the trait's dependencies aren't very clearly defined. This is probably more a problem related to traits themselves than the design here, though.

As for a solution to my problem... I don't really know :-) If `generateTags()` would receive the model being audited as a parameter it would solve the second problem (since the parameter could be type-hinted to a Model and therefore ensured to have `getAttributes()` etc) but it would look weird since on the typical scenario, `generateTags()` is implemented inside the Model and therefore, as you said, can simply use `$this`. And this still would force me to "extend" the trait or have to call a tag-parsing method on every model's `generateTag()`.

I understand you don't want to add my perhaps too specific logic to the library, which makes total sense, so if nothing of what I wrote looks usable to you, no biggie, I'll just keep it locally. But the main idea is, it would be cool if the library would allow easily "extending" the tag logic.

**Comment by quetzyg** [comment]
>I overwrote the generateTags() method on another trait of my own, so that my generateTags() with the "special" logic can be shared by all of my models. However, this means that it can't rely on $this->attribute anymore

Sure you can. If you look at the `Auditable` trait, you'll notice that I'm using `$this->` to access lots of `Eloquent` properties.

>The second problem is that my trait (and the library's Auditable trait, for that matter) relies on methods like getAttributes() or getDirty() which are supposed to exist since the trait is supposed to be used in Eloquent models, but there's no actual guarantee of that, meaning the trait's dependencies aren't very clearly defined. This is probably more a problem related to traits themselves than the design here, though.

I'm with you on that one, and in that regard, I'm gonna update the traits, so that they have the needed methods defined as abstract.

While your problem may not be completely solved with this, it will probably improve your internal implementation/logic.

**Comment by daniel-gomes-sociomantic** [comment]
> Sure you can. If you look at the Auditable trait, you'll notice that I'm using $this-> to access lots of Eloquent properties.

Well yes, that works when the `generateTags()` is defined inside a model. But in my case it's meant to be generic so that it can handle the special logic, and is therefore implemented in a trait shared by all models, so it won't be able to rely on `$this->` anymore.

> I'm with you on that one, and in that regard, I'm gonna update the traits, so that they have the needed methods defined as abstract.
> 
> While your problem may not be completely solved with this, it will probably improve your internal implementation/logic.

cool, cheers!

Guess I'll close the issue as there's nothing further to discuss, thanks!
