### ISSUE TITLE
Question about casts/accessors in audit values

### ISSUE THREAD

**Issue by daniel-gomes-sociomantic** [owen-it/laravel-auditing#399]
| Q                 | A
| ----------------- | ---
| Bug?              | ?
| New Feature?      | no
| Framework         | none
| Framework version | none
| Package version   | `master@2d2160c`
| PHP version       | 7.0.25

#### Actual Behaviour

When getting an Audit `$audit->new_values` the values don't have their casts/accessors applied to them (unlike mutators).

#### Expected Behaviour

The casts/accessors should be applied to the old/new fields.

#### Steps to Reproduce

Create a model like:
```php
class SomeModel extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;

    public $table = 'some_model';

    protected $casts = [
        'casted_field' => 'string',
    ];

    protected $fillable = [
        'casted_field',
        'accessor_field',
        'mutator_field',
    ];

    public function getAccessorFieldAttribute($value): string
    {
        return (string) $value;
    }

    public function setMutatorFieldAttribute($value)
    {
        $this->attributes['mutator_field'] = (string) $value;
    }
}
```

With a database migration like:
```php
public function up()
{
    Schema::create('some_model', function (Blueprint $table) {
        $table->increments('id');
        $table->string('casted_field');
        $table->string('accessor_field');
        $table->string('mutator_field');
        $table->timestamps();
    });
}
```

And a test like:
```php
public function itWillApplyCastAndAccessorToAuditNewField()
{
    $this->app['config']->set('audit.events', [
        'created',
    ]);

    $model = new SomeModel([
        'casted_field' => 55,
        'accessor_field' => 123,
        'mutator_field' => 666
    ]);
    $model->save();

    $audit = Audit::first();
    $newFields = $audit->new_values;

    // this will pass
    $this->assertSame("666", $newFields['mutator_field']);

    // both of these will fail
    $this->assertSame("55", $newFields['casted_field']);
    $this->assertSame("123", $newFields['accessor_field']);
}
```

#### Possible Solutions

I had a look at the `Audit` trait and got a bit lost as to how/when are the audit values formatted with casts/accessors, since some code in it does do that correctly. 
So for instance, this in the test  makes it work:
```php
$audit->getMetadata();

// both of these will now pass
$this->assertSame("55", $audit->getDataValue('new_casted_field'));
$this->assertSame("123", $audit->getDataValue('new_accessor_field'));
```
And also this:
```php
$modified = $audit->getModified();
$this->assertSame("55", $modified['casted_field']['new']);
$this->assertSame("123", $modified['accessor_field']['new']);
```

But there doesn't seem to be a straightforward way to get an Audit's old and new values with the accessor and casts applied to them.
I also got it working by adding a method like this to the `Audit` trait:
```php
public function getNewData(bool $json = false, int $options = 0, int $depth = 512)
{
    if (empty($this->data)) {
        $this->resolveData();
    }

    $new = [];

    foreach ($this->new_values as $key => $value) {
        $value = $this->getDataValue('new_'.$key);

        $new[$key] = $value instanceof DateTimeInterface
            ? $this->serializeDate($value)
            : $value;
    }

    return $json ? json_encode($new, $options, $depth) : $new;
}

```

**Comment by daniel-gomes-sociomantic** [comment]
Another perhaps simpler way to get the old/new values from `getModified()`:
```php
private function getModifiedValues(Audit $audit)
{
    $modified = $audit->getModified();

    $old = [];
    $new = [];

    foreach ($modified as $field => $fieldValues) {
        if (isset($fieldValues['old'])) {
            $old[$field] = $fieldValues['old'];
        }

        if (isset($fieldValues['new'])) {
            $new[$field] = $fieldValues['new'];
        }
    }

    return [
        'old' => $old,
        'new' => $new,
    ];
}
```

Are developers supposed to be doing something like this, or is there an easier way?

**Comment by quetzyg** [comment]
@daniel-gomes-sociomantic, the behaviour you're describing is intended.

So, data will be stored in its original form (for instance, `1` instead of `TRUE`), and it will be cast accordingly via the `getDataValue()`, as you very well described.

If you want to fetch everything with the casts applied in one go, instead of one by one, use the `getMetadata()` or `getModified()` methods.

@fernandocoronatomf what `json_encode()` are we talking here, the one in the `getModified()` ?

**Comment by quetzyg** [comment]
@daniel-gomes-sociomantic, @fernandocoronatomf, you guys wanna comment, or shall I consider this issue closed?

**Comment by daniel-gomes-sociomantic** [comment]
all good from my side I guess, thanks for clarifying it

**Comment by fernandocoronatomf** [comment]
@quetzyg Sorry for the delay....
I am trying to use this package again but all my id fields are stored as binary fields...
So for example, id and project_type_id, when added to new_values will fail because those fields are json_encode by the package...

Is there anyway I can skip this?

**Comment by quetzyg** [comment]
Skip as in, [excluding](http://www.laravel-auditing.com/docs/7.0/auditable-configuration) those fields?

**Comment by fernandocoronatomf** [comment]
No, sorry.
What happens is that all my id fields are binary...
So I need to convert them before it is saved, otherwise when the field is saved (it is stored as json) it fails because of binary values..

Is this the best approach??

```
public function transformAudit(array $data): array
    {
        if ($data['id']) {
              $data['id'] = convertToStringId($data['id']);
        }
        return $data;
    }
```

Something like this?

**Comment by quetzyg** [comment]
That could work, but I'll address this in #423 once I get the time.
