### ISSUE TITLE
Trait 'OwenIt\Auditing\AuditingTrait' not found

### ISSUE THREAD

**Issue by wallauschek** [owen-it/laravel-auditing#4]
A aplicação funciona perfeitamente em ambiente de desenvolvimento, subo para o servidor de produção, rodo a migrate e nada!
Trait 'OwenIt\Auditing\AuditingTrait' not found

**Comment by anteriovieira** [comment]
@wallauschek não compreendi muito bem qual seu problema, se possível nos passe mais detalhes para que possamos resolver este problema o mais breve possível . Mas de ante mão verifique se os arquivos do pacote laravel-auditing estão no diretório ``` vendor/owen-it ```, verifique também se o comando composer install funcionou corretamente no seu servidor de produção.  

Caso esteja tudo ok, tente ``` composer remove owen-it/laravel-auditing && composer require owen-it/laravel-auditing ```

**Comment by wallauschek** [comment]
Não existia erro algum na aplicação e sim no meu server.
Após dar um dump-autoload -o para otimizar os PSRs.
Apanhando e aprendendo...

**Comment by anteriovieira** [comment]
rsrs perfeito, fico feliz que esteja dando tudo certo. Precisando pode contar conosco.

**Comment by juniorb2ss** [comment]
Também ocorre o problema comigo. É preciso rodar o `dump-autoload -o` toda vez que faz a instalação de um novo pacote, é necessário analisar.

**Comment by lmtorres** [comment]
I'm having the same issue. I have to run ```composer dump-autoload -o``` every time a new package is installed, and even when I run artisan commands.

**Comment by anteriovieira** [comment]
@lmtorres  this should not happen, I will check the cause and correct the problem.

@juniorb2ss  sorry, tested and did not see the error again what made me think that the error would have been corrected because the latest changes. But I will analyze.

**Comment by anteriovieira** [comment]
Does anyone have any idea what it might be?

**Comment by juniorb2ss** [comment]
tomorrow I will investigate the problem

**Comment by anteriovieira** [comment]
Thank @juniorb2ss , I am also investigating. Anything you can send a PR.

**Comment by anteriovieira** [comment]
Just did some tests here starting a laravel application from the beginning.

Laravel installed (ok)
Installed laravel-auditing (ok)
Tested laravel-auditing the model user (ok)
I installed several packages (ok)
Performed composer update (ok)
Laravel-auditing test (ok)

I'm using version 1.0-dev composer

**Comment by lmtorres** [comment]
Just wanted to add that everything works with composer update --no-scripts tag. This is my scripts section:
``` javascript
"scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
```

**Comment by anteriovieira** [comment]
Seems to be related to artisan, I will analyze. thank you @lmtorres

**Comment by ricardotomim** [comment]
Comigo acontece o mesmo problema.Só resolve com composer dump-autoload -o

**Comment by anteriovieira** [comment]
If possible, please test this example and add packages to see if the error occurs. [Spark Auditing Demo](https://github.com/owen-it/spark-auditing)

**Comment by anteriovieira** [comment]
I created the application from scratch and added several packages and it worked as expected.

**Comment by ricardotomim** [comment]
Não entendi, foi resolvido ? pois continuo com o mesmo problema.

**Comment by anteriovieira** [comment]
@ricardotomim ,  remova seu arquivo composer.lock, atualize seu composer, execute o composer update e verifique se o erro persiste.

**Comment by ricardotomim** [comment]
Ok, anteriovieira, estarei testando e qualquer coisa aviso, grato

**Comment by anteriovieira** [comment]
Obrigado @ricardotomim

**Comment by ricardotomim** [comment]
Após as seguir as instruções, problema continua
![capturar](https://cloud.githubusercontent.com/assets/5711325/11342633/79499e04-91ef-11e5-9382-a88497496754.PNG)

**Comment by anteriovieira** [comment]
Perdão @ricardotomim , esqueci de falar. Remova o pacote laravel-auditing ```composer remove owen-it/laravel-auditing``` e em seguida remova as referências nas classe que esta usando. Vamos resolver este problema, mas eu preciso da sua ajuda porque isso não acontece nos meus testes.

**Comment by anteriovieira** [comment]
Depois faça a instalação do pacote novamente.

**Comment by ricardotomim** [comment]
@anteriovieira estarei fazendo esta semana, abs.

**Comment by anteriovieira** [comment]
Ok, vou testando aqui também.

**Comment by resmall** [comment]
Esse problema acontece com certa frequencia pra mim. Pra citar um caso, usei o generator do Jeffrey Way pro Laravel 5.1 pra criar uma migration. Logo depois de criado acesso minha aplicação e ocorre esse problema. Executo o `composer dump-autoload -o` e volta a funcionar. A migration em questão alterava a estrutura de uma tabela.

**Comment by anteriovieira** [comment]
Olá @resmall , qual a versão do auditing vocẽ esta usando? 

A última versão do auditing esta com correção no namespace, acredito que isso era a fonte dos erros.

**Comment by resmall** [comment]
Olá @anteriovieira , desculpe a demora em retornar. Estou usando a versão 2.1.

**Comment by anteriovieira** [comment]
Tudo bem @resmall , esses últimos dias fiz uma correção que corrigiu o problema. Tente fazer ```composer update owen-it/laravel-auditing``` isso deve atualizar sua versão e corrigir o problema. A versão mais atual é ```v2.1.4```, gostaria de ter seu feedback. Qualquer coisa chama aqui.

**Comment by resmall** [comment]
Acredito que eu já tenha atualizado os pacotes em algum momento anterior, não me dei conta de que o pacote tinha sido atualizado. O importante é que de fato não tive mais problemas. Fiz um teste agora e não voltou a ocorrer. Obrigado!

**Comment by anteriovieira** [comment]
:smiley:  :+1:
