### ISSUE TITLE
Why Owen It Audit 6.0 show me Auditable because the name is already in use

### ISSUE THREAD

**Issue by TholthoeunChansovann** [owen-it/laravel-auditing#400]
i try using Audit 6.0 with my laravel 5.4 but it not work and show me error like this. How i can fix it? Thank you help me.
![audit](https://user-images.githubusercontent.com/12667706/37698532-f00d97c0-2d15-11e8-9ae0-836ca7477e29.JPG)

**Comment by anteriovieira** [comment]
Hi @TholthoeunChansovann , can you provide a code example?

**Comment by quetzyg** [comment]
Please, use the issue template @TholthoeunChansovann .

Also, this has been covered a few times already, at least in #371, #354.

Closing.
