### ISSUE TITLE
Relations don't work when using MongoAudit

### ISSUE THREAD

**Issue by sptdigital** [owen-it/laravel-auditing#406]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6
| Package version   | 6.x
| PHP version       | 7.1.y

#### Actual Behaviour

When the Laravel application has a different Database driver to the Audit database driver, the relation fails to work.

#### Expected Behaviour

For the audits relationship to return all results.

#### Steps to Reproduce

Setup a Laravel application using MySQL for Eloquent and MongoDB for this package, when you use the relation $this->audits() it will always return an empty collection.

#### Possible Solutions

It appears to me that the issue lies in the Auditable trait. It uses the function `Illuminate\Database\Eloquent\Concerns\HasRelationships\morphMany` rather than `Jenssegers\Mongodb\Eloquent\HybridRelations\morphMany`.

**Comment by quetzyg** [comment]
>It appears to me that the issue lies in the Auditable trait. It uses the function Illuminate\Database\Eloquent\Concerns\HasRelationships\morphMany rather than Jenssegers\Mongodb\Eloquent\HybridRelations\morphMany.

But that's something that you have to define in your models.

The `Auditable` trait is to be used from a class extending an `Eloquent` compatible class (Illuminate, Jenssegers, ...), which must implement the `morphMany()`.

If you're getting the **Illuminate** `morphMany()` instead of the **Jenssegers** one, something else is up.

**Comment by sptdigital** [comment]
The model is extending Illuminate and the Audit Model is extending Jessengers.

This means it uses the Illuminate morphMany rather than the Jessengers morphMany.

If I add the Jessengers implementation of morphMany to the Auditable trait it starts returning the results. Is there a cleaner way to do this?

Thanks

**Comment by quetzyg** [comment]
Ah, OK. I got it now. I can't say there's a cleaner way for doing it like that. If you want to use different Eloquent implementations concurrently, you'll have to deal with the relations yourself.

**Comment by sptdigital** [comment]
Ok, thank you for your help.
