### ISSUE TITLE
Use case : Moderation of data and approvals

### ISSUE THREAD

**Issue by SkyKOG** [owen-it/laravel-auditing#407]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel|Lumen

Hi everyone! 

Thanks for the wonderful plugin. I read here in this article that `laravel-auditing` can be used to manage model diffs and audit presentation. Can this concept be used to manage moderation for a given model? 

My exact use case is that a user would modify a blog article from our frontend which gets published. Another user might choose to make amends to this article. A moderator needs to approve these amends to trigger a change in the original article thereby causing the original article to be updated with the new version. 

Can this use case be implemented? currently we are using a dummy copy to maintain duplicates until an admin approves. 

Thanks 
-Akash

**Comment by quetzyg** [comment]
Hi @SkyKOG

The way this package works, doesn't currently allow for the use case you have described. Mainly because the audits are created once a model is modified (which you only want, after a user approves the change).

But let me think about it.

**Comment by SkyKOG** [comment]
Thanks, @quetzyg! looking forward.

**Comment by quetzyg** [comment]
There seems to be quite a few [packages](https://packagist.org/?q=eloquent%20approva&p=0) that do just that. Gonna mark this as solved.
