### ISSUE TITLE
Eloquent Update Not Being Tracked

### ISSUE THREAD

**Issue by adil853** [owen-it/laravel-auditing#408]
| Q                 | A
| ----------------- | ---
| Bug?              | yes|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.0.4
| Package version   | 6.x.y
| PHP version       | 7.1.8

#### Actual Behaviour

On updating eloquent model using update functionality, the model is not being tracked as updated in audit table i.e. 
self::where('id',$id)->update(['name' => $name]);
in this case, there is no entry in audit table saying that model with this id has been updated

#### Expected Behaviour

It should tracked as updated model in audit table

#### Steps to Reproduce

self::where('id',$id)->update(['name' => $name]);

#### Possible Solutions

This problem is solved when model is updated using eloquent save
i.e. 
$objectToUpdate = self::find($id);
$objectToUpdate->name = $name;
$objectToUpdate->save();

**Comment by quetzyg** [comment]
#139, #195, #240, #317 and so on...
