### ISSUE TITLE
Value of 0 (zero) gets stripped

### ISSUE THREAD

**Issue by olds463** [owen-it/laravel-auditing#41]
> old_value: {"desc":"test","enable_hostcheck":0}
> new_value: {"desc":"testies","enable_hostcheck":"1"}

When using $logCustomFields any value with 0 in the JSON element will get removed from the output display from the blade template.

**Comment by scs75** [comment]
Same problem here.
The numeric and string 0 casts to FALSE in Log.php line 185.

**Comment by anteriovieira** [comment]
Sorry for the delay https://github.com/owen-it/laravel-auditing/commit/f3ffa30390c59af22c354ea8a313ba3050502882 .
