### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by mankowitz** [owen-it/laravel-auditing#410]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 6.0
| PHP version       | 7.0.23

#### Actual Behaviour

I'm using windows 10 and mySQL. When migrating the database, I get this

```
C:\>php artisan migrate

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `audits` add index `audits_auditable_id_auditable_type_index`(`auditable_id`, `auditable_type`))

In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

```

#### Expected Behaviour

No errors

#### Steps to Reproduce

This is a clean install on my system, errors on `php artisan migrate`

#### Possible Solutions

`auditable_id` has length of 10 and `auditable_type` has max length of 255, so you would think that this would be less than 1000 characters, but my default collation is `utf8mb4_unicode_ci` which means that each character is 4 bytes, thus exceeding the maximum. 

There are several solutions I can think of.

`SET @@global.innodb_large_prefix = 1;`

changes the key length to 3072 bytes, which should be enough, but users may not have permission to change that on a public server.

```sql
alter table `audits` add index `audits_auditable_id_auditable_type_index`(`auditable_id`, `auditable_type`(50))
```

shortens the index length, but may not be what we want.

Finally, if utf is not needed, specifying the collation as latin_ci may be a good option.

**Comment by quetzyg** [comment]
Hi @mankowitz,

If you're setting a different charset/collation, you'll have to take that into account. Given there's no need to have `utf8mb4_unicode_ci` for the `auditable_*` columns, you could instead set that to `utf8_unicode_ci`, instead.

**Comment by quetzyg** [comment]
I'm gonna close this ticket, assuming it's solved.
