### ISSUE TITLE
Fetching all the modified data

### ISSUE THREAD

**Issue by amoghzz** [owen-it/laravel-auditing#411]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.x.y
| Package version   | 6.x.y
| PHP version       | 7.x.y

Have been trying to implement Laravel auditing for the first time. And I have followed the installation procedure as per the documentation. Successfully able to add the auditable data in the audits table.

#### Expected

My requirement: Considering there is one row in user table and it had been modified 5 time by different users. Is there any possible way to fetch all the modifed data?? Is there predefined funtion as LAST and ALL functions are not working.

**Comment by quetzyg** [comment]
Use the issue template or this issue will be closed.

**Comment by amoghzz** [comment]
I'm sorry but may I know what is the issue template and how do i add it?

**Comment by quetzyg** [comment]
The point of the issue template, is to avoid the team to ask basic questions, like: what is happening, what do you expect to happen instead, actual code, potential solutions you may think of, etc.

Care to update the issue, again?
