### ISSUE TITLE
Optional Location Logging

### ISSUE THREAD

**Issue by tankerkiller125** [owen-it/laravel-auditing#413]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?     |yes
| Framework         | Laravel
| Framework version | 5.6.13
| Package version   | 6.0.2
| PHP version       | 7.2.0

#### Expected Behaviour

It would be nice to use the IP information to get a broad general location of where an event took place. This could be done using the free maxmind geoip database or some other IP to location database.

**Comment by quetzyg** [comment]
I'm gonna close this issue, but feel free to comment if needed.
