### ISSUE TITLE
class that has composite key produce error

### ISSUE THREAD

**Issue by aqualaguna** [owen-it/laravel-auditing#416]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.4.y
| Package version   | 6.0.0
| PHP version       | 7.0.1

#### Actual Behaviour

i get this error actualy in my project

> array_key_exists(): The first argument should be either a string or an integer
at Model->getKey()
in Auditable.php (line 250)

i implement it in my class that has composite key as primary
>class PurchaseDetail extends Model implements AuditableContract
{
	use HasCompositeKey, Auditable;
	public $timestamps = false;
	protected $primaryKey = ['purchase_id','item_id','unit_id'];
}

#### Expected Behaviour

auditable_id : multi primary 

#### Possible Solutions

making the class model not composite primary instead using id with auto increment. this solution may cause duplicate in some record.

**Comment by quetzyg** [comment]
I'm unaware of Eloquent supporting composite keys.

**Comment by quetzyg** [comment]
Closing due to lack of information.
