### ISSUE TITLE
Keeping track of audit for multiple table from DB

### ISSUE THREAD

**Issue by amoghzz** [owen-it/laravel-auditing#417]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6
| Package version   | 6.1
| PHP version       | 7.2.2

#### Actual Behaviour

As per the document I have set up the package and integrated it in User model.
And it is working fine

#### Expected Behaviour

Now I want to integrate it in other model to track the auditing for that model related table.

#### Steps to Reproduce

Used namespace 
and then interface
Tried manipulating table form my form
Also defined model in audit.php page
'lounges' => [
        'primary_key' => 'id',
        'model'       => App\Lounges::class,
    ],

#### Possible Solutions

Kindly please let me know what changes are required to be done to fix this issue

**Comment by quetzyg** [comment]
Sorry, what's the issue again?

**Comment by amoghzz** [comment]
Want to keep track of multiple tables in audits table(Like on very CRUD operations it has to be stored in audits table).
But as per the generic configuration I am only able to track audits for User table and I need audits for my other table called Lounge.

Thanks in advance.

**Comment by quetzyg** [comment]
Have you tried applying what you did in the `User` model to the `Lounge` one?

**Comment by amoghzz** [comment]
Yes I did

**Comment by quetzyg** [comment]
So, what's the issue then? Also, provide code, since saying it doesn't work isn't exactly helpful.
