### ISSUE TITLE
Audit Presentation, Translation

### ISSUE THREAD

**Issue by Dewbud** [owen-it/laravel-auditing#418]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6.0
| Package version   | 6.1.0
| PHP version       | 7.2.2

#### Actual Behaviour

When using translations in blade as described in the documentation "Audit Presentation" an error is thrown by `Illuminate/Support/Str.php` because it expects a string and an array is given.

#### Expected Behaviour

What's described in the docs. [http://laravel-auditing.com/docs/6.1/audit-presentation](url)

#### Steps to Reproduce
In blade template
```
@lang("audit.{$audit->event}.metadata", $audit->getMetadata())
```
Translation key
```
'metadata' => 'Updated by :user_name on :audit_created_at',
```

#### Possible Solutions

The 'audit_tags' key is an array, removing it solves the issue.
```
 @php
$meta = $audit->getMetadata();
unset($meta['audit_tags']);
@endphp
@lang("audit.{$audit->event}.metadata", $meta)
```

I'm not sure why the translation is trying to translate every key in the given array instead of just the ones in the given line.

Removing the array key that isn't a string solves the issue, though it's a little cumbersome.

**Comment by quetzyg** [comment]
Hi @Dewbud,

Thanks for reporting this. I'll work on a solution so that the tags don't interfere with the `trans()` / `@lang()` usage.
