### ISSUE TITLE
Show only changed fields

### ISSUE THREAD

**Issue by olds463** [owen-it/laravel-auditing#42]
how can you display only fields that have changed in blade template?

if you define fields in $logCustomFields and using your blade template, custom messages for fields that were not updated still show :(

thanks

edit example:

```php 
public static $logCustomFields = [
        'desc'  => 'The desc was defined as {new.desc}',
        'enable_hostdiscovery'  => 'enable_hostdiscovery set to  {new.enable_hostdiscovery}',
        'enable_hostcheck'  => 'enable_hostcheck set to  {new.enable_hostcheck}',
    ];
```

 old_value: {"desc":"testing"}
 new_value: {"desc":"testing 2"}

output in blade

> The desc was defined as testing 2 
enable_hostdiscovery set to 
enable_hostcheck set to

**Comment by anteriovieira** [comment]
Hi @olds463 ,

Sorry for the delay in responding.

You can show me all your model?

**Comment by olds463** [comment]
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Presenters\SubnetsPresenter;
use Laracodes\Presenter\Traits\Presentable;
use OwenIt\Auditing\AuditingTrait;

class Subnets extends Model
{
    use Presentable, AuditingTrait;

    public static $logCustomFields = [
        'desc'  => 'The desc was defined as {new.desc}',
        'enable_hostdiscovery'  => 'enable_hostdiscovery set to  {new.enable_hostdiscovery}',
        'enable_hostcheck'  => 'enable_hostcheck set to  {new.enable_hostcheck}',
    ];
    protected $presenter = SubnetsPresenter::class;

    protected $table = 'ipman_subnets';

    protected $fillable = [
       'network', 'mask', 'desc', 'enable_hostdiscovery', 'enable_hostcheck',
    ];

    protected $guarded = ['network', 'mask'];
}
```

**Comment by anteriovieira** [comment]
Thank you, at the moment I'm a little busy. But today I see this to you.

**Comment by olds463** [comment]
Thank you... not sure if this was by design or I did something wrong..

**Comment by anteriovieira** [comment]
How is your blade template?

**Comment by olds463** [comment]
same as in your readme.md

i just tried on another model and it happens there too, all fields listed in $logCustomFields display no matter if they were changed or not.

**Comment by olds463** [comment]
Thank you, this is what I wanted. 

Perhaps add this to the docs?

**Comment by anteriovieira** [comment]
Hi @olds463 , I do not think necessary, this is more a matter of taste for each programmer. I believe that each one will have a particularity in its logic. :)

**Comment by wunc** [comment]
As an example of matter of taste, I'm doing it this (slightly different) way:

```html
...
<ul>
	@forelse(array_intersect_key($log->customFields, $log->new) as $details)
		<li>{{ $details }}</li>
	@empty
		<li>{{ dump($log->new) }}</li>
	@endforelse
</ul>
...
```

The `array_intersect_key()` reduces the `customFields` array to only those that have changed fields. This way, the `@empty` gets used when there are no custom fields defined for the changed fields, rather than no custom fields defined at all.
