### ISSUE TITLE
How i do force Audit for whereIn clause?

### ISSUE THREAD

**Issue by kalaiarasen** [owen-it/laravel-auditing#422]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel 
| Framework version | 5.6.20
| Package version   | 6.1.1
| PHP version       | 7.2.3

#### Actual Behaviour

Hi, Im using array collection to update the database. im using wherein clause which is not firing the updated event

#### Expected Behaviour

I would like to fire updated event for audit using whereIn clause.

#### Steps to Reproduce

$table = Table::whereIn('id', $request->json()->all())
            ->update(['stage' => 'NOMINATION']);

#### For Solution

Unfortunately i have 60 functions like this to update the stage. i found that if i use where instead of where in the updated event is firing but i cant perform that for multiple id together.
i tried most of the possibilities to make it work yet i cant move forward.
So i would like to request for a solution to force whereIn clause to fire updated event in owen it or similar solution. Thanks

**Comment by kalaiarasen** [comment]
@quetzyg Hi ive updated the issue.

**Comment by quetzyg** [comment]
The only way I see this happening is to using a [high order message](https://laravel.com/docs/5.6/collections#higher-order-messages):

```php
$table = Table::whereIn('id', $request->json()->all())->get()->each->update([
    'stage' => 'NOMINATION',
]);
```

**Comment by quetzyg** [comment]
This has already been discussed (at least) in #139, #195, #240, #317, #408

**Comment by kalaiarasen** [comment]
Thanks alot @quetzyg it is working
