### ISSUE TITLE
Option to discard empty updates

### ISSUE THREAD

**Issue by SebastianS90** [owen-it/laravel-auditing#424]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.6.22
| Package version   | 7.0.0
| PHP version       | 7.2.5

#### Actual Behaviour

Calling `$model->touch()` creates an update audit entry, even if the `audit.timestamps` configuration is set to `false`.

#### Expected Behaviour

No audit entry is created.

#### Steps to Reproduce

Configure `audit.timestamps = false` (the default) and do `User::first()->touch();`.
Now do `Audit::orderBy('id', 'desc')->first()` and you will see that there is an audit entry with
```
     old_values: "[]",
     new_values: "[]",
```

Additional way to trigger empty audits: Use the `$auditExclude` property on the model and update only excluded attributes. 

My usecase is that I do not audit updates to the `last_login` attribute of a user, because I have a log for login actions somewhere else. But every login still clutters up the audit table with empty updates.

#### Possible Solutions

Provide an option to not create an audit entry if `$old` and `$new` are both empty.

**Comment by quetzyg** [comment]
>Calling `$model->touch()` creates an update audit entry, even if the `audit.timestamps` configuration is set to `false`.

The `audit.timestamps` configuration only tells if the timestamp values should be included in the `Audit` or not.

This has been discussed before (#303, #263, #292)

[This](https://github.com/owen-it/laravel-auditing/issues/263#issuecomment-330695869) should do what you want.

**Comment by quetzyg** [comment]
The [reason](https://github.com/owen-it/laravel-auditing/issues/263#issuecomment-313486772) being:

>Bear in mind that there's also other data in the `Audit`, like the `event`, `user_id`, `url`, `ip_address` or `user_agent`, so that might still be useful for accountability purposes.

**Comment by quetzyg** [comment]
The [troubleshooting](http://www.laravel-auditing.com/docs/7.0/troubleshooting) section of the documentation has been updated to reflect this (see entry at the bottom).

**Comment by SebastianS90** [comment]
Thanks for the pointer to the `creating` event of the `Audit` itself. I tried using the `Auditing` event, but that doe snot have the necessary information inside.

I'll put your code snippet into the `boot` method of my custom `Audit` model. That is probably better than some unrelated Service Provider.

**Comment by quetzyg** [comment]
Any place will do, but I guess the `Audit`'s `boot()` method also makes more sense. I'll update the docs.
