### ISSUE TITLE
Eloquent / Audit bug: JSONB whitespace causing excessive updates

### ISSUE THREAD

**Issue by andzandz** [owen-it/laravel-auditing#427]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.3.28
| Package version   | 5.0.1
| PHP version       | 7.0.10

I realise this is an old version; but we have projects on Laravel 5.3. I simply ran the `composer require` command as documented.

#### Actual Behaviour

Audit rows are always added to the table when a model with a JSONB field is edited and  saved, even if the array content (before `json_encode`) is unchanged.

#### Expected Behaviour

Audit rows should only be added to the table when content of JSONB fields have changed, regardless of automatically generated whitespace in the JSON.

#### Steps to Reproduce

Just trying this package, I've noticed audit rows are getting added to the audits table every time my model is saved, if a JSONB field is edited with the same, unchanged value. We are using PostgreSQL.

Editing a text field with unchanged content does not cause this.

My migration is: (I called it spike_things for the moment, just for testing)

```
Schema::create('spike_things', function (Blueprint $table) {
    $table->increments('id');
    $table->text("name");
    $table->jsonb('content')->nullable();
    $table->timestamps();
});
```

So in my application, if I do this multiple times:

```
$thing = SpikeThing::where([
    'id' => $id
])->get()[0];

$thing['content'] = json_encode([
    'field1' => 'bar1',
    'field2' => 'bar2',
    'field3' => 'bar3',
    'field4' => 'bar4',
]);
$thing['name'] = 'name1';
$thing->save();
```

I notice that an audit row is always saved. If I edit the `name` field with unchanged content however, there is no audit row saved.

If I `dd` my model object ->toArray(), I can see that the JSON content is

`{"field1": "bar1", "field2": "bar2", "field3": "bar3", "field4": "bar4"}`

However, json_encode function does not include any whitespace:

`{"field1":"bar1","field2":"bar2","field3":"bar3","field4":"bar4"}`

In fact, if I do this:

```
$thing = SpikeThing::where([
    'id' => $id
])->get()[0];

$thing['content'] = '{"field1": "bar1", "field2": "bar2", "field3": "bar3", "field4": "bar4"}';
$thing['name'] = 'name1';
$thing->save();
```

Then no audit row is saved. Seems that Eloquent or PostgreSQL is adding in all those extra space characters, and deems the content to have changed.

As our models are saved every day (we generate them from XML feeds) this would stuff the table with lots of excess data.

If there is some simple solution or workaround for this, please let us know.

Cheers
Andy K, IFP Ltd

**Comment by quetzyg** [comment]
This reminds me of #315. I don't know who exactly is to blame, if the RDBMS or the ORM, but this package is just using Eloquent's `getDirty()` method. Whatever we get from it, is what we use.

**Comment by andzandz** [comment]
Okay, thanks for the reply Quetzy. Makes sense. I've upgraded to version 7 and still happening. If there is any interest in fixing it, before saving the audit, it could `json_decode` the old and new values and compare them.

For the moment we have made a workaround in our model's `save` function, using `disableAuditing()` before to saving our JSONB field, then copying our JSON into a text field, `enableAuditing()` then calling `save()`. As no extra whitespace is added to text fields, it audits correctly.

**Comment by quetzyg** [comment]
>I've upgraded to version 7 and still happening.

Yeah, the logic hasn't changed much from earlier versions.

>If there is any interest in fixing it, before saving the audit, it could `json_decode` the old and new values and compare them.

This should be fixed upstream, if this is even considered  bug by them, that is.

**Comment by quetzyg** [comment]
I'll mark this as wontfix and I'm gonna close, but feel free comment, specially if you happen to escalate this to https://github.com/laravel/framework/.
