### ISSUE TITLE
N + 1 queries executed

### ISSUE THREAD

**Issue by younus93** [owen-it/laravel-auditing#428]
| Q                 | A
| ----------------- | ---
| Bug?              | no|
| New Feature?      | no|
| Framework         | Laravel|
| Framework version | 5.6
| Package version   | 7.0
| PHP version       | 7.2

#### Actual Behaviour

When I am displaying out the list of audits, the number of queries executed keeps increasing as per the number of audit records present. 

#### Expected Behaviour

The ability to eager load and solve the n+1 problem. 

#### Steps to Reproduce

Display the list of audits using the below blade code. 
```
@forelse ($audits as $audit)
    <li>
        <b>{{ $audit->user->name }}</b> {{ $audit->event }} this <b>{{ $model }}</b> record {{ $audit->created_at->diffForHumans() }}
        @foreach ($audit->getModified() as $attribute => $modified)
            @if($audit->event == 'updated')
                <ul>
                    <li>The <strong>{{ $attribute }} </strong> has been modified from <strong>{{ $modified['old'] }}</strong> to <strong>{{ $modified['new'] }}</strong></li>
                </ul>
            @endif
        @endforeach
    </li>
@empty
    <p>No modifications available</p>
@endforelse
```

@forelse ($audits as $audit) triggers the n+1 issue. 

Debugbar Images : 
<img width="549" alt="screen shot 2018-06-05 at 4 51 18 pm" src="https://user-images.githubusercontent.com/4537724/40973195-ff9312b8-68e0-11e8-8fa5-17fc7f3ce963.png">

![screen shot 2018-06-05 at 4 52 47 pm](https://user-images.githubusercontent.com/4537724/40973228-202f23ea-68e1-11e8-9b21-54896b444f15.png)

Output 
![screen shot 2018-06-05 at 4 51 34 pm](https://user-images.githubusercontent.com/4537724/40973227-2002a662-68e1-11e8-9a8a-63e23c346fdf.png)

**Comment by quetzyg** [comment]
What exactly is stopping you from eager loading?

**Comment by younus93** [comment]
I don't understand how to eager load.
I have done $post->load('audits') and $post->audits()->with('user')->get(). 
But here, when I display the audits from the post, `posts` database is getting queried

**Comment by quetzyg** [comment]
Check the [documentation](https://laravel.com/docs/5.6/eloquent-relationships#eager-loading), since this is clearly an Eloquent issue, nothing to do with this package.

**Comment by younus93** [comment]
Hi, Thanks for your reply. I dont think this is an eloquent problem as when I eager load the `auditable` relationship, I still get N+1 queries executed. 
Please find below the images for reference. 

#### 1. Without Eager Loading
<img width="470" alt="screen shot 2018-06-06 at 11 02 09 am" src="https://user-images.githubusercontent.com/4537724/41018785-3a7e74a6-6979-11e8-92ca-d1f91fe743b9.png">

#### 2. With Eager Loading.
![screen shot 2018-06-06 at 11 02 43 am](https://user-images.githubusercontent.com/4537724/41018794-3e843b12-6979-11e8-9102-c40d2c44e3cc.png)



As you can see, the `approvals`  table is getting queried irrespective of eager loading the relationship.

Any suggestions on how to optimise this?

**Comment by quetzyg** [comment]
I'll be needing more info, like code, tables and relations you're working on.

**Comment by younus93** [comment]
Sorry, I made a mistake while using the package. 
I just needed to add the `auditable` relationship in the controller. 
Thanks for your help.!

**Comment by jeanali** [comment]
Hi @younus93  I have the same problem here! where should I put the exactly auditable relationship?

**Comment by younus93** [comment]
Hi @jeanali. I used something like `->with('audits.user', 'audits.auditable')` in my controller to eager load the audits. Maybe if you share your model / controller snippet, I can help u out on this.
