### ISSUE TITLE
Auditing in multi-tenancy apps

### ISSUE THREAD

**Issue by icemanblas** [owen-it/laravel-auditing#43]
Hi,

this package is awesome for regular applications and works as expected, but I have the following situation:

1. I have main DB connection that stores users, roles, permissions and, of course, logs.
2. The system creates separate DB for each new user, and when a given user is logged in, the application handles a second DB connection, corresponding to the auth user's table.
3. When I run DB seeders for predefined data in the tables (second connection) the system requires 'logs' table to be present in the user's database.
4. When logged user creates/updates a given record, the logging is done in the 'logs' table of the main DB connection.

So my question is, is it possible to avoid the need to define the 'logs' table in the second connection (user's database)?

I will provide more details if I wasn't so clear. 

Thanks in advance

**Comment by anteriovieira** [comment]
Hi @icemanblas , sorry for the delay in responding.

See if the database settings help you, if not the solution please provide more detail and example me about your problem.

--
##### Settings
https://github.com/owen-it/laravel-auditing#auditing-settings

**Comment by icemanblas** [comment]
Hi @anteriovieira,

I forgot about the auditing settings, which totally did it. Sometimes you need a hint to get the simplest job done. So, yeah, it did solve my problem.

Thanks a lot, cheers

**Comment by anteriovieira** [comment]
:smiley:  Very good, I'm happy to help.

**Comment by fernandocoronatomf** [comment]
@icemanblas I have a similar issue.

My app uses 2 connections

Users on common DB

Tag on tenant DB

When I set audit connection to common, any change on user is logged on the common audits table.

When I edit something on, say, a tag table, it would require to audit on the tenant connection.

What is the best way to have both models (on different connections) logged?
