### ISSUE TITLE
AuditableTransitionException

### ISSUE THREAD

**Issue by xyrintech** [owen-it/laravel-auditing#432]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 7.0
| PHP version       | 7.0

#### Actual Behaviour

Error on transitionTo()
{"message":"Expected Auditable id 55, got 55 instead","status_code":500}

It works completely fine on server but on production server. Both are ubuntu servers.

**Comment by quetzyg** [comment]
If you don't provide more information, I can't help you, so...

**Comment by xyrintech** [comment]
Please suggest what all information shall I share?
My concern is that if I am using transitionTo() on one server (say server A) it works, when I deploy it another server (say sever B) then this does not work. 

This gives an error {"message":"Expected Auditable id 55, got 55 instead","status_code":500}

Here 55 is the ID of the record which I want to restore.

**Comment by quetzyg** [comment]
>Please suggest what all information shall I share?

Whatever helps me, help you, don't you think? I have no idea what your code is, tables, models, etc.

**Comment by quetzyg** [comment]
Closing due to lack of information.

**Comment by chiiya** [comment]
This occurs when using SQLite as the database (fairly standard for testing), since values are returned as strings, meaning that the comparison:
```php
// The Audit must be for this specific Auditable model
if ($this->getKey() !== $audit->auditable_id) {
    throw new AuditableTransitionException(sprintf(
        'Expected Auditable id %s, got %s instead',
        $this->getKey(),
        $audit->auditable_id
    ));
}
```
will return true. Laravel automatically casts the id of a model to an integer, but the auditable_id won't be cast, so 1 !== "1". 
Not sure what an easy fix for this would be, since not everyone is going to be using auto-incrementing integer primary keys. Overriding the Audit implementation always works:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Audit extends Model implements \OwenIt\Auditing\Contracts\Audit
{
    use \OwenIt\Auditing\Audit;

    /**
     * {@inheritdoc}
     */
    protected $guarded = [];

    /**
     * {@inheritdoc}
     */
    protected $casts = [
        'auditable_id' => 'integer',  // This is important
        'old_values' => 'json',
        'new_values' => 'json',
    ];
}

```

**Comment by quetzyg** [comment]
Ha! I see, now. Yeah, that's a tricky one. Your suggestion might be the best way to accommodate for this issue.

Thanks a lot @xyrintech, I'll eventually update the documentation to cover this case.

**Comment by ManicMapple** [comment]
Has this ever been solved? The casts solution from @chiiya did not work for me (laravel 7, auditing v10.0.0)
