### ISSUE TITLE
Tags field is limited to 255 characters

### ISSUE THREAD

**Issue by andzandz** [owen-it/laravel-auditing#433]
Sorry to delete your placeholder issue text, but this is quite a simple issue.

The audits migration uses a `string` type, which Eloquent, by default, creates as a VARCHAR(255).

```
$table->string('tags')->nullable();
```

In some cases, in our systems, combinations of tags are longer than this. We have simply edited the audits migration in use in our system, but you may want to increase it.

**Comment by quetzyg** [comment]
That's fine. We'll keep the migration as is, but like stated in the [documentation](http://www.laravel-auditing.com/docs/7.0/audit-migration), you can customise the table as you see fit.

**Comment by andzandz** [comment]
Ah, thanks for the prompt response. 

Good point, the [docs](http://www.laravel-auditing.com/docs/7.0/audit-migration) do indeed have a note about the 255 character limit, but only for the URL and User Agent fields; perhaps we could mention the tags too.

**Comment by lk77** [comment]
i agree, this limitation could be documented
