### ISSUE TITLE
skip null to '' changes

### ISSUE THREAD

**Issue by huglester** [owen-it/laravel-auditing#434]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.y
| Package version   | 7
| PHP version       | 7.1

Hello,
when saving object, I get updates, that, for example:
null is chnaged to ''
or for example 0 is changed to 0.00

what is the best way to skip such 'changes' ? 

Than you

**Comment by quetzyg** [comment]
Using an observer should do the trick. Check the [troubleshooting](http://www.laravel-auditing.com/docs/7.0/troubleshooting).
