### ISSUE TITLE
Base table or view already exists: 1050 Table 'sessions' already exists

### ISSUE THREAD

**Issue by xoco70** [owen-it/laravel-auditing#44]
Hi, 

When I try to migrate, I get this error. This is due to that my system already has a sessions table.

I'm not sure how to fix it.

Tx for this nice plugin that saved me a lot of time!

**Comment by anteriovieira** [comment]
Hi @xoco70 , sorry, but I believe that this error has nothing to do with auditing, you probably already have this table in your database but it was not added in the migrations table. Remove the migration table entries and try again. :)

**Comment by xoco70** [comment]
ahh, ook, Tx!!!
