### ISSUE TITLE
Namespaced Models aren't audited

### ISSUE THREAD

**Issue by K-Leon** [owen-it/laravel-auditing#441]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | Newest
| Package version   | 7
| PHP version       | 7

#### Actual Behaviour

I've two groups of Models - some are residing in App\Models and some are residing in Shared\Models.

All audited Models in App work perfectly - the Models in Shared won't work. As soon as i move them everything starts to work again.

#### Expected Behaviour

Also Models in a different Namespace work.

#### Steps to Reproduce

Create a Model and move it to a different Top Level Namespace.

**Comment by quetzyg** [comment]
Please provide code in order for me to reproduce.

**Comment by quetzyg** [comment]
@K-Leon more information, otherwise I'll just close this.

**Comment by K-Leon** [comment]
I @quetzyg - I just tried to m ake a minimal repro and noticed that it is related to a bug introduced by me. I'm so sorry for wasting your time and thank you very much for your hard work on this project.

**Comment by quetzyg** [comment]
No problem, glad all works now.
