### ISSUE TITLE
Auditing every changes in every model

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [owen-it/laravel-auditing#443]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.6.35
| Package version   | 8.0
| PHP version       | 7.2.4

#### Actual Behaviour

I want to log login, logout, forgot password request, reset password, registration.

Also, I am using entrust for permissions and roles, so I also want to log when permission is assigned to a role, a role is assigned to a user, when permission or role is revoked etc.

#### Possible Solutions

It seems login, logout like operation has already events as described [here](https://laravel.com/docs/5.6/authentication#events), I have added listener to these events. So I think we only need to register those events to Audit.

but, I don't know how I can log them, Can you please help me? I tried adding auth.login, auth.logout to User model as protected
```
 $auditEvents = [
        'auth.login',
        'auth.logout',
    ];
```

But I believe that was not the correct way of doing it.

**Comment by quetzyg** [comment]
This package is triggered by Eloquent events only.

**Comment by PrafullaKumarSahu** [comment]
Hello @quetzyg, thank you for your kind reply,  How I can allow it to log other events? Is there any way you can suggest me, so that I will be able to achieve it?

**Comment by quetzyg** [comment]
Related: #389 #270

**Comment by crayolaeater12** [comment]
Can you provide an example of using the `Auditor` to manually create an audit log entry in the database?
