### ISSUE TITLE
Issue with upgrade to v8.0.1 and Lumen v5.7.1

### ISSUE THREAD

**Issue by mnlm** [owen-it/laravel-auditing#447]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.7.1
| Package version   | 8.0.1
| PHP version       | 7.2.10

#### Actual Behaviour

Upgrade from v7.0.1 to version v8.0.1. Bootstraping the application fails with `Error: Call to undefined function OwenIt\Auditing\config_path()`.

This helper function doesn't exist in the Lumen framework and is used here: https://github.com/owen-it/laravel-auditing/blob/v8.0.1/src/AuditingServiceProvider.php#L39. Change was made in 3a85fcbd3cbb556cc45831c83d74e5b7bea4b849.

#### Possible Solutions

Revert back to using `base_path()`.

**Comment by quetzyg** [comment]
Thanks for pointing this out @mnlm.

I think the `database_path()` helper isn't available either. Can you confirm?

**Comment by mnlm** [comment]
@quetzyg The `database_path()` helper does exist: https://github.com/laravel/lumen-framework/blob/v5.7.1/src/helpers.php

**Comment by quetzyg** [comment]
Alright, I'll sort this ASAP.

**Comment by quetzyg** [comment]
Fixed in version 8.0.2

**Comment by mnlm** [comment]
Works fine now. Thanks for the quick fix!
