### ISSUE TITLE
Recording IP and Route

### ISSUE THREAD

**Issue by crispossa** [owen-it/laravel-auditing#45]
Hi, would be awesome if there's a way to record the IP address of the currently connected user in the log.

Also, a record of the route would be welcome too!

Any thought in how to get this?

Thx.

**Comment by anteriovieira** [comment]
@crispossa, thank you for your suggestion ,

We had not thought of that, certainly is a great resource. We are open to suggestions and future pull request. 

I will also be thinking of something to implement.

If you have something in mind, feel free to send us a pull request.

**Comment by achillesp** [comment]
Hi, I have sent a pull request for adding this feature.
https://github.com/owen-it/laravel-auditing/pull/46

**Comment by anteriovieira** [comment]
Thank you @achillesp
