### ISSUE TITLE
ErrorExceptioncall_user_func() expects parameter 1 to be a valid callback, Only in production

### ISSUE THREAD

**Issue by bilygates** [owen-it/laravel-auditing#457]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7.*
| Package version   | 8.0
| PHP version       | 7.1.3

#### Actual Behaviour

The following behavior only occurs in production (heroku). In the development environment (ide cloud 9) the entire audit works correctly.

When I try to add or update a new company to my database, the error that I mention below is shown. I clarify that the record is inserted in the company table, but nothing is inserted in the audit table.

ERROR:

(1/1) ErrorExceptioncall_user_func() expects parameter 1 to be a valid callback, class 'OwenIt\Auditing\Contracts\Audit' does not have a method 'create' in Database.php line 19

at HandleExceptions->handleError(2, 'call_user_func() expects parameter 1 to be a valid callback, class \'OwenIt\\Auditing\\Contracts\\Audit\' does not have a method \'create\'', '/app/vendor/owen-it/laravel-auditing/src/Drivers/Database.php', 19,array('model' => object(Empresa), 'implementation' => 'OwenIt\\Auditing\\Contracts\\Audit'))
at call_user_func(array('OwenIt\\Auditing\\Contracts\\Audit', 'create'), array('old_values' => array('empresa_telefono' => '333'), 'new_values' => array('empresa_telefono' => '3334'), 'event' => 'updated', 'auditable_id' => 1, 'auditable_type' => 'App\\Models\\Empresa', 'user_id' => 1, 'user_type' => 'App\\User', 'url' => 'http://****.herokuapp.com/empresas/1?', 'ip_address' => '1***', 'user_agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36', 'tags' => null))in Database.php line 19
at Database->audit(object(Empresa))in Auditor.php line 69

[composer-json.txt](https://github.com/owen-it/laravel-auditing/files/2534886/composer-json.txt)

**Comment by quetzyg** [comment]
If it works on dev, but not on prod, I guess it's something with your setup.
Different PHP version, different dataset, ...
