### ISSUE TITLE
transformAudit throws 'must be compatible' exception

### ISSUE THREAD

**Issue by hiworlddev** [owen-it/laravel-auditing#461]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6.21
| Package version   | 8.0.3
| PHP version       | 7.2.9

#### Actual Behaviour

Hello, i get the following error message when i try to use the transformAudit method.

> Declaration of Vanguard\Models\Provider::transformAudit(array $data) must be compatible with OwenIt\Auditing\Contracts\Auditable::transformAudit(array $data): array

#### Expected Behaviour

Allow me to change the $data via the transformAudit method before saving it to db.

#### Steps to Reproduce

```
<?php

namespace Vanguard\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use OwenIt\Auditing\Contracts\Auditable;
use Auth;

class Provider extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    // ...
   
  public function transformAudit(array $data)
    {

        return $data;
    }
```

Thanks in advance.

**Comment by quetzyg** [comment]
This is not a bug, you're just not honoring the contract. If you look at the error message, you'll notice that `transformAudit(array $data)` is not the same as `transformAudit(array $data): array`.

**Comment by hiworlddev** [comment]
Thank you!
