### ISSUE TITLE
Multiple Users tables

### ISSUE THREAD

**Issue by kapitannwel** [owen-it/laravel-auditing#465]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | maybe?
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 8.0.4
| PHP version       | 7.0.0

#### Actual Behaviour

the app that was passed to me (created by other programmers) have users logging-in from **Users table.** and then there's an administrators using **Admins table**. when users are logged-in (Users table), the user_id and user_type are having values on audits table. but when the administrators are logged-in (Admins table), the user_id and user_type fields on audits table are null.

Can i have some kind of configuration wherein users logged-in using other tables (ex: admins table) can mimic the users logged-in using the default Users table so that the laravel-auditing package can recognize it?

#### Expected Behaviour

user_id and user_type on audits table should have values when users, from Users table, and administrators, from Admins table, are logged-in.

#### Steps to Reproduce

Users table = users logged-in using "email" and "password" fields
Admins table = administrators log-in using "username" and "password" fields

#### Possible Solutions

thank you in advance

**Comment by quetzyg** [comment]
Make sure the `Admin` user model implements the `\Illuminate\Contracts\Auth\Authenticatable` contract, since that's what the Auth [user resolver](https://github.com/laravel/framework/blob/9f313ce9bb5ad49a06ae78d33fbdd1c92a0e21f6/src/Illuminate/Auth/AuthManager.php#L53) will expect. If you're doing something different, you'll have to implement your own `UserResolver`, so have a look at the [Audit Resolvers](http://www.laravel-auditing.com/docs/8.0/audit-resolvers) section.

**Comment by quetzyg** [comment]
Probably, but that's something out of scope. This issue tracker is for package issues, not problems you have on your custom auth implementation.

You of all people should know what you have implemented in your project, so I'll leave it up to you to figure out.

**Comment by kapitannwel** [comment]
yeah, i believe you are right. it turned out that i have created my own code for my needs using the isdirty and getdirty. it's far perfect but ill settle with it, at least for now. more power to this package, nice job!
