### ISSUE TITLE
Migration stub inconsistant causing migration errors

### ISSUE THREAD

**Issue by lukesnowden** [owen-it/laravel-auditing#466]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 8.0.3
| PHP version       | 7.1

#### Actual Behaviour

Running `artisan vendor:publish --tag=migration` generates migration file with timestamp prefix.
Run the command again and it generates a new file with a different file name but the same class name.

#### Expected Behaviour

Describe the behaviour you're expecting.

Running `artisan vendor:publish --tag=migration` generates migration file with timestamp prefix of when it was first created (should be around the time this package was made public).

Running it again should not create new file and contents should only update if the `force` flag is used.

The above means no other package using the `--tag=migration` tag will work, ever. It will keep generating new file and getting error `Cannot declare class CreateAuditsTable, because the name is already in use` on publishing migrations from other packages.

#### Steps to Reproduce

see above

#### Possible Solutions

Take the timestamp generation off the publish method.

**Comment by quetzyg** [comment]
Consider passing the `--provider` flag, in order to only publish the migration you need, instead of publishing everything that has the `migration` tag registered.

**Comment by quetzyg** [comment]
You might just want to register the `migration` and not the `config`, so you still need tags.

If you read the [installation](http://www.laravel-auditing.com/docs/8.0/installation) section of the documentation, you'll see both cases covered.

Also, at least for me, running `php artisan vendor:publish --tag=migration` multiple times doesn't create a new file.

**Comment by lukesnowden** [comment]
Unless you have a different version, or stuck in a time loop (😆), it must create a new file. It uses the a full timestamp to create the file name which laravel will use to see if the file needs to be created or not:

```php
public function boot()
    {
        $config = __DIR__.'/../config/audit.php';
        $migration = __DIR__.'/../database/migrations/audits.stub';
        // Lumen lacks a config_path() helper, so we use base_path()
        $this->publishes([
            $config => base_path('config/audit.php'),
        ], 'config');
        $this->publishes([
            $migration => database_path(sprintf('migrations/%s_create_audits_table.php', date('Y_m_d_His'))),
        ], 'migrations');
        $this->mergeConfigFrom($config, 'audit');
    }
```

**Comment by quetzyg** [comment]
It's nice to know when the migration was created just by looking at the file name.

So, what about this, then:
```php
if (!class_exists('CreateAuditsTable')) {
    $this->publishes([
        $migration => database_path(sprintf('migrations/%s_create_audits_table.php', date('Y_m_d_His'))),
    ], 'migrations');
}
```

**Comment by lukesnowden** [comment]
Hmmm... I understand (kind off) why you're doing this but it is fundamentally flawed.

If I had a Blog Posts module which used your package and a Pages module which used your package, both developed independently by separate teams and and pulled into an application there would be conflicts as the class would exist in the same global namespace housed by 2 files with different names. If it used the correct convention then no error would occur.

**Comment by lukesnowden** [comment]
Ah, my bad, error report was incorrect sorry. Glad you can reproduce it though 👍

**Comment by parallels999** [comment]
> Ah, my bad, error report was incorrect sorry. Glad you can reproduce it though

Seems fixed
