### ISSUE TITLE
Cannot fetch relation when using alternative connection

### ISSUE THREAD

**Issue by fullstackfool** [owen-it/laravel-auditing#468]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7.14
| Package version   | 8.0.4
| PHP version       | 7.2.7

#### Actual Behaviour

When storing audits under a different database connection `$audit->auditable` or `$audit->user` attempts to attempts to retrieve the relation under the audit connection, as opposed to the default one set in `database.php`.

#### Expected Behaviour

Retrieval of the relation

#### Steps to Reproduce
audit.php:
```php
    'drivers' => [
        'database' => [
            'table'           => 'audits',
            'connection'      => 'mysql_audits',
        ],
    ],
```

Then:
`\OwenIt\Auditing\Models\Audit::first()->auditable`
`\OwenIt\Auditing\Models\Audit::first()->user`

#### Possible Solutions

Eager-loading the relation solves this issue, as does specifying `$connection` within the target relation model, but I feel the relationship should work without these steps. Updating to the below seems to solve it:

```php
    /**
     * {@inheritdoc}
     */
    public function auditable()
    {
        return $this->setConnection(Config::get('database.default'))->morphTo();
    }

    /**
     * {@inheritdoc}
     */
    public function user()
    {
        return $this->setConnection(Config::get('database.default'))->morphTo();
    }
```

Happy to make a PR if these are acceptable changes?

**Comment by quetzyg** [comment]
Hi @fullstackfool,

This was discussed just a few days ago in #463.

While the solution you're proposing works for you, it might not work for others, so we won't accept a PR.

You'll either have to eager load, or implement your own `Ledger` class with the changes you need in those two methods.

**Comment by fullstackfool** [comment]
> This was discussed just a few days ago in #463.

Apologies, I searched the previous discussions but missed #463
 
> While the solution you're proposing works for you, it might not work for others, so we won't accept a PR. 
> You'll either have to eager load, or implement your own `Ledger` class with the changes you need in those two methods.

Any change to open-source might potentially work for some and not others, are there any plans to resolve this issue in a non-conflicting way? 

At the moment the package supports an alternative connection, but partially breaks it's own relationships when that option is used.

**Comment by quetzyg** [comment]
>Any change to open-source might potentially work for some and not others, are there any plans to resolve this issue in a non-conflicting way?

Sorry, I didn't get the first part of the sentence. Like I said, you can sort this issue by following one of the suggestions I previously made.

>At the moment the package supports an alternative connection, but partially breaks it's own relationships when that option is used.

That's just how Eloquent and any other ORM works when you relate different tables from different database connections. It's not an exclusive of this package. Try using a different database for each of your models and see what happens.
