### ISSUE TITLE
Possible to Audit for Get Data?

### ISSUE THREAD

**Issue by wilson-young** [owen-it/laravel-auditing#470]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 6.x.y
| PHP version       | 7.x.y

Actual Behaviour
Is there any possible way to audit or log for the index() and show() in laravel eloquent request?

Expected Behaviour
is there posible to log show that from which link, browser etc like current log when updated/deleted/created. but it show that user has try to get data from database?

**Comment by quetzyg** [comment]
>Is there any possible way to audit or log for the **index()** and **show()** in laravel eloquent request?

`index()` ? `show()` ? Do I have to guess your code? Update the issue or I'll close it.

**Comment by wilson-young** [comment]
i mean the default Actions Handled By Resource Controller for laravel 
![image](https://user-images.githubusercontent.com/9879527/49357575-4be38f80-f702-11e8-9604-f3b2c623c88a.png)

**Comment by quetzyg** [comment]
Controllers have nothing to do with Eloquent events. Did you at least read the [documentation](www.laravel-auditing.com/docs/8.0/auditable-configuration)? What have you tried? What problems are you facing? Show us **CODE**!

This is why we have rules (**which you clearly disregarded**) for submitting issues, to avoid nonsense like this.

Such a time waste...

**Comment by sasokovacic** [comment]
@quetzyg actually it would be really useful to cover full CRUD and not just CUD... If you have ever build any large enterprise application then you know some companies want to also track read access to the resources not just modifications... So I would like to know if there is any possibility for this feature.. And please if you decide to answer my question, then do it in a constructive manner. I don't want to waste time for reading how stupid our questions are....

**Comment by quetzyg** [comment]
@sasokovacic If you check the [Auditable Configuration](http://www.laravel-auditing.com/docs/9.0/auditable-configuration), you'll be surprised to see that the feature you ask for already exists.

**PS:** I'm no longer a contributor on this project, since I started working on my own auditing package.
