### ISSUE TITLE
Trailing question mark in audit URLs

### ISSUE THREAD

**Issue by nordiago** [owen-it/laravel-auditing#471]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7.15
| Package version   | 8.0.4
| PHP version       | 7.2.5

#### Actual Behaviour

Currently, events fired via plain URLs without query strings are audited with a trailing question mark. A database entry may look like this:

`http://laravel.test/posts/create?`

#### Expected Behaviour

I would expect URLs without query strings to be represented cleanly.

#### Steps to Reproduce

In a fresh installation of Laravel and the Auditing package, with a simple Post model, hit the /post/create route and trigger a `created` event. This will generate an audit in the database with a trailing question mark in the URL field.

#### Possible Solutions

I believe this is due to an incorrect usage of `Request::fullUrlWithQuery([])` here:

https://github.com/owen-it/laravel-auditing/blob/825f576de946820e6e587ffa4e96b9bb70b5586b/src/Resolvers/UrlResolver.php#L19

If I'm not mistaken, this method is intended to append additional query string parameters to the request URL. To simply retrieve the current full URL with all existing parameters and avoid the trailing question mark issue, the following could be used instead:

`return Request::fullUrl();`

Please let me know if there's something I'm missing here. Otherwise, I would love to see this changed. Also, my apologies for being repetitive while trying to format this to the issue template. Thanks!

**Comment by nordiago** [comment]
Additionally, the [documentation regarding the URL Resolver](http://laravel-auditing.com/docs/master/audit-resolvers) points to `Request::fullUrl()` as a method of retrieving the current URL _without_ query string parameters. This is incorrect. The [Laravel documentation](https://laravel.com/docs/5.7/urls#accessing-the-current-url) suggests using `url()->current()` for this purpose, which calls `Request::url()` internally.

**Comment by quetzyg** [comment]
Thanks for taking the time @nordiago. You are correct!

Feel free to submit a pull request, if you like.

**Comment by nordiago** [comment]
Absolutely! Happy to help :)

**Comment by quetzyg** [comment]
You effort is appreciated. Thank you!
