### ISSUE TITLE
$model->audits does not return entries for external events

### ISSUE THREAD

**Issue by thitami** [owen-it/laravel-auditing#475]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature? | no
| Framework        | Laravel
| Framework version | 5.6.39
| Package version   | 8.0.4
| PHP version       | 7.1.19

#### Actual Behaviour

I find this package of great help and due to the lack of the `attach`, `detach` and `sync` events for pivot tables not being triggered I am using a 3rd party package to throw these events and then catch them.
This seems to be working, I am able to store the desirable data into the `audits` table with the new even types (I'm using `attached`, `detached`, `synced`).

My current issue is that when I am calling `$model->audits` I am getting all the entries related to created, updated, etc events but not the entries from event DB with values different than this package's defaults.

#### Expected Behaviour

I would expect that `$model->audits` would return all the related `audits` entries for the provided record including those of event type other than `created`, `updated`, etc.

#### Steps to Reproduce

In the AppServiceProvider.php, add this piece of code so to listen to all pivot tables related events.
```$saveManyToManyAudit = function ($event, $eventModel, $relation, $pivotIds, $pivotIdsAttributes) {
            $audit = new Audit();
            $audit->user_type = \App\Auth\User::class;
            $audit->user_id = Auth::check() ? Auth::user()->getAuthIdentifier() : null;
            $audit->event = $event;
            $audit->auditable_id = array_first($pivotIds);
            $audit->auditable_type = ucfirst(str_singular($relation)) . "::class";
            $audit->old_values = '';
            $audit->new_values = (count($pivotIdsAttributes) > 0) ? $pivotIdsAttributes : array_first($pivotIds);
            $audit->url = App::runningInConsole() ? 'console' : Request::fullUrl();
            $audit->ip_address = Request::ip();
            $audit->user_agent = Request::header('User-Agent');
            $audit->created_at = Carbon::now();
            $audit->save();
        };

        \Event::listen('eloquent.pivotAttached*', function ($eventName, array $data) use ($saveManyToManyAudit) {
            $saveManyToManyAudit('attached', $data['model'], $data['relation'], $data['pivotIds'],
                $data['pivotIdsAttributes']);
        });

        \Event::listen('eloquent.pivotDetached*', function ($eventName, array $data) use ($saveManyToManyAudit) {
            $saveManyToManyAudit('detached', $data['model'], $data['relation'], $data['pivotIds'],
                $data['pivotIdsAttributes']);
        });

        \Event::listen('eloquent.pivotSynced*', function ($eventName, array $data) use ($saveManyToManyAudit) {
            $saveManyToManyAudit('synced', $data['model'], $data['relation'], $data['pivotIds'],
                $data['pivotIdsAttributes']);
        });```

**Comment by verenzuela** [comment]
In which part of my AppServiceProvider should I use this code ...?
