### ISSUE TITLE
Delete not saving audit record

### ISSUE THREAD

**Issue by nbhatti** [owen-it/laravel-auditing#476]
Hi, I am using Laravel version 5.7 having Postgres as database server. Using laravel-auditing by owen-it version 8.0. I am trying to keep records of all soft deletes along with an audit trail of the query performed. For example, if someone edit a record, the old and new value is saved along with session info in audit table. This works fine, but when I delete a record from the table, (using my CRUD form), the record is deleted from the table but no entry gets saved in audit table.  I am already using the delete(); method to delete records. 

Is that a bug or intended behavior? I can provide more details as needed.

**Comment by quetzyg** [comment]
Follow the issue submission rules!

>I can provide more details as needed.

If you want to get help just release all the information you have.

**Comment by quetzyg** [comment]
Issue creation rules were ignored.
