### ISSUE TITLE
Useless storing of "empty" updates

### ISSUE THREAD

**Issue by jadamec** [owen-it/laravel-auditing#477]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no|
| Framework         | Laravel|Lumen
| Framework version | 5.7.16
| Package version   | latest
| PHP version       | 7.3.0

#### Actual Behaviour

After updating an attribute which is from $auditExclude, system stores an empty arrays in SQL. I think this is absolutely useless, just wasting of space and during audits's presentation you have to think of removing blank audits from collection.

#### Expected Behaviour

After updating an attribute which is from $auditExclude, system doesn't store anything. Thank do you think about it? :)

**Comment by quetzyg** [comment]
Already discussed in #424, #396, #303, #292, #263.
