### ISSUE TITLE
Skip Null Fields

### ISSUE THREAD

**Issue by lucassmacedo** [owen-it/laravel-auditing#478]
Hello! Such as skipping a field that is null after being filled. I want to keep only one log of changes without considering null values

**Comment by quetzyg** [comment]
Not quite sure what you're on about, but look at #477, #424, #396, #303, #292, #263.

**Comment by lucassmacedo** [comment]
@quetzyg when i have a register on database and a field with the null value or empy and i change this, i want skip, understand? i want save audit only when a field has a value and change to another value.. because i have a lot of deafult null values has are created with my tables..
