### ISSUE TITLE
Skip Null Fields on Old Value

### ISSUE THREAD

**Issue by lucassmacedo** [owen-it/laravel-auditing#479]
Hello! Such as skipping a field that is null after being filled. I want to keep only one log of changes without considering null values
Ex:

old_value = 
{"cursos_relevantes":null,"informatica":null}

new_values
{"cursos_relevantes":"test","informatica":"test"}

i want create a audit only if old_value fields are not null or empty

**Comment by quetzyg** [comment]
This is similar to the other issue (#478) you created.
