### ISSUE TITLE
Using audits table as Model 

### ISSUE THREAD

**Issue by sumandeveloperonrent** [owen-it/laravel-auditing#480]
| Q                 | A
| ----------------- | ---
| Bug?             | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6.3
| Package version   | 8.0
| PHP version       | 7.2.10

#### Actual Behaviour

I created one model for audits table as I want to retrieve data based on relationship between User model and audits, so I defined the relationship as

```
public function revisions()
{
        return $this->hasMany(Audit::class, 'id', 'user_id');
}
```

Tinker result
```
 App\User::find(3)->revisions
=> Illuminate\Database\Eloquent\Collection {#3079
     all: [],
   }
```
but there are 232 records for this users.

#### Expected Behaviour

There are 232 records for this users but i get null while running in tinker. There should come 232 records for this user.

#### Steps to Reproduce

Already described in original behaviour section.

**Comment by autumndev** [comment]
hey, your relationship is incorrect, i have the following and its working fine:

```
public function audits() : Audit
{
    return $this->hasMany(Audit::class, 'user_id', 'id')->latest();
}
```

**Comment by anteriovieira** [comment]
@sumandeveloperonrent look at  @autumndev 's code snippet.
