### ISSUE TITLE
Can this be used to approve or disapprove changes that were made?

### ISSUE THREAD

**Issue by ghost** [owen-it/laravel-auditing#481]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no

Ex: 
```php
class Book extends Model
{
   //
}  
```

1 - user "A" has created a book ( title, desc, etc).
2 - user "A" decided to delete a book or edit the book's title.
4 - then user "A" will wait for a an approval from admin for these changes.

Admin can approve or disapprove these changes:

1 - if admin approve , apply the new changes that were made.
2 - if admin dis-approve , don't apply new changes. ( restore old book's data ).

Is this possible with this package?

**Comment by LeonAlvarez** [comment]
http://laravel-auditing.com/docs/9.0/auditable-transition
