### ISSUE TITLE
Date fields are always recorded as changed

### ISSUE THREAD

**Issue by beard7** [owen-it/laravel-auditing#483]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7,12
| Package version   | 8.0
| PHP version       | 7.2.7
| Database       | SQL Server 2012   

#### Actual Behaviour

Audits are being recorded when a record is saved despite no changes. This is because database fields which are `date` are classed as being changed due to the extra time information as a result of the request attributes being cast.

This results in things like: `old_values: { "date": "2019-01-01" }, new_values: { "date": "2019-01-01 12:30:00.000" }`

#### Expected Behaviour

If the acutual data stored in the database is unchanged, no audit should be recorded.

#### Steps to Reproduce

Create database table with `date` field.
Add field to `$casts` array in Model to cast to `date`
Save a record and set date field to a date: eg. `2019-01-01`
Save the record, without changing any fields.
Audit is recorded: eg. `old_values: { "date": "2019-01-01" }, new_values: { "date": "2019-01-01 12:30:00.000" }`

**Comment by shahriar-b** [comment]
any workaround?

**Comment by AgelxNash** [comment]
So, I solved this task. But i don't like my way.

**Comment by jonagoldman** [comment]
The dates are transformed using different formats, old one is formatted using `'Y-m-d'` and new one using `Y-m-d H:i:s.u`. I think one way to fix this is to use [Accessors & Mutators](https://laravel.com/docs/5.8/eloquent-mutators#accessors-and-mutators) to correcly format the date before saving.

**Comment by AgelxNash** [comment]
@jonagoldman I Use [date mutators](https://laravel.com/docs/5.8/eloquent-mutators#date-mutators), but it's don't work

**Comment by jonagoldman** [comment]
@AgelxNash it is working for me. Have you tried the solution (for Laravel 5.5 and older) in the [troubleshooting](http://laravel-auditing.com/docs/8.0/troubleshooting) section?

**Comment by MortenDHansen** [comment]
This should no longer be an issue

**Comment by jrmypttrsn** [comment]
This is happening with all my date fields. All my old values are being recorded as YYYY-MM-DD and the new values are YYYY-MM-DD 00:00:00. It's really frustrating.

Using package v13.0.4 on a Laravel 9.1.8 app.
