### ISSUE TITLE
'OwenIt\Auditing\Contracts\Audit' does not have a method 'create'

### ISSUE THREAD

**Issue by fiermarin** [owen-it/laravel-auditing#485]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7.*
| Package version   | 8.0
| PHP version       | 7.1.3

#### Actual Behaviour

The following behavior only occurs in production (host). In the development environment (ide cloud 9) the entire audit works correctly.

When I try to add, update or insert a new company to my database, the error that I mention below is shown. I clarify that the record is inserted in the company table, but nothing is inserted in the audit table.

#### Error

call_user_func() expects parameter 1 to be a valid callback, class 'OwenIt\Auditing\Contracts\Audit' does not have a method 'create'

array:11 [▼
  "old_values" => []
  "new_values" => array:5 [▼
    "empresa_nombre" => "Prueba"
    "empresa_telefono" => "123456789"
    "empresa_estado" => "1"
    "empresa_ingreso" => "2019-02-04"
    "id" => 32
  ]
  "event" => "created"
  "auditable_id" => 32
  "auditable_type" => "App\Models\Empresa"
  "user_id" => 2
  "user_type" => "App\User"
  "url" => "http://****.*********.com/empresas?"
  "ip_address" => "190.64.86.74"
  "user_agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
  "tags" => null
]

**Comment by fiermarin** [comment]
Up

**Comment by MortenDHansen** [comment]
Sorry for the missing response. Please reopen if this is still relevant!
