### ISSUE TITLE
Can't seed database since v2.3.0

### ISSUE THREAD

**Issue by franciscojun** [owen-it/laravel-auditing#49]
Since the inclusion of route logging (https://github.com/owen-it/laravel-auditing/blob/master/src/AuditingTrait.php#L247), we can't run
`php artisan db:seed`
This is the exception raised:
`[Symfony\Component\Debug\Exception\FatalErrorException]`
`Call to a member function getName() on null`

**Comment by achillesp** [comment]
Didn't think about that :-)
The audit logs changes from db seeds too. Guess we need to check for that.
Would someone want to log seeds also? Maybe there could be some config option about this.

**Comment by anteriovieira** [comment]
Thank @franciscojun, I'll check it out today. :+1:

**Comment by lrpasquetto** [comment]
me too 

`[Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to a member function getName() on a non-object `

**Comment by tjcalma** [comment]
I have also the problem

[Symfony\Component\Debug\Exception\FatalErrorException] Call to a member function getName() on a non-object

**Comment by achillesp** [comment]
I have sent a suggestion - fix... hope there's no more problems with this  :-)

**Comment by anteriovieira** [comment]
We have a positive return of this issue? or is there another approach that we should know?

@franciscojun and lrpasquetto, it's alright?

**Comment by lrpasquetto** [comment]
@anteriovieira Perfect now 👍 :) Thanks mannnn!!!!!!! # @

**Comment by franciscojun** [comment]
Great approach! @achillesp solved the issue itself and added a valuable new config option, which is good for our use case, since we don't intend to log db seeds.  Thank you, guys!
