### ISSUE TITLE
Support Laravel 5.8

### ISSUE THREAD

**Issue by ThomHurks** [owen-it/laravel-auditing#491]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      |yes
| Framework         | Laravel|Lumen
| Framework version | 5.8
| Package version   | 8.0.4
| PHP version       | 7.2

#### Actual Behaviour

I cannot upgrade to Laravel 5.8 because Laravel-Auditing is depending on ```illuminate/filesystem 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* || 5.7.*```

#### Expected Behaviour

I can upgrade to Laravel 5.8

#### Steps to Reproduce

- Require Laravel ```5.8.*``` in ```composer.json```
- ```composer update```

#### Possible Solutions
Also depend on ```illuminate/filesystem``` version ```5.8.*``` assuming there are no breaking changes in that version, otherwise adjust for those breaking changes.

**Comment by anteriovieira** [comment]
Hi @ThomHurks, I'll look at it this week.

**Comment by ThomHurks** [comment]
Thanks a lot, @anteriovieira!

**Comment by CraigBSM** [comment]
Hi. @anteriovieira 

I see https://github.com/owen-it/laravel-auditing/pull/489 has been merged to master.

laravel-auditing is the last dependency package that needs support for Laravel 5.8 before we can upgrade to use 5.8 ourselves.

Do you have an estimation of when v9 is going to be released?

**Comment by anteriovieira** [comment]
Hi @CraigBSM, I'm doing some local tests, I'm going to release on Tuesday or Wednesday.

**Comment by CraigBSM** [comment]
@anteriovieira Thanks for the reply. Will keep an eye out for it over the next few days. Cheers.

**Comment by asivaneswaran** [comment]
Hey,

I wanted to know if you are still on schedule for a release today? :)

Thanks,

**Comment by CraigBSM** [comment]
`༼ つ ◕_◕ ༽つ GIVE v9!`

**Comment by Spodnet** [comment]
Does 9 support the laravel 5.8 pivot events using intermediate models ?

**Comment by anteriovieira** [comment]
Hi @Spodnet , I'm going to work on it this week, I just released version 5.8 support  so that it does not block updates to the projects that use the package.

**Comment by anteriovieira** [comment]
@ThomHurks `v9` released

**Comment by ThomHurks** [comment]
Thanks so much @anteriovieira!
