### ISSUE TITLE
Default value or how to set user_id if self registration

### ISSUE THREAD

**Issue by jadamec** [owen-it/laravel-auditing#492]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel|
| Framework version | latest
| Package version   | latest
| PHP version       | latest

#### Actual Behaviour

During user registration, columns `user_type ` and `user_id ` are NULL but they shouldn't be.

#### Expected Behaviour

By default, these two columns should have values of registrated user, so if the user with ID 16 creates new registration, the value `user_id ` should be its 16. Thanks.

**Comment by jadamec** [comment]
It even doesn' work when I set default values in database... Help, please.

**Comment by LeonAlvarez** [comment]
The user registration is done by guest user,so I think this is expected

**Comment by jadamec** [comment]
Thanks. Is possible to send data into Audit like after the registration? I mean data of registered user. Thanks.

**Comment by jadamec** [comment]
Fixed in AppServiceProvider.php

`Audit::creating(function (Audit $model) {
			if(!$model->user_type) {
				$model->user_type = "App\User";
				$model->user_id = 1;
			}
		});`
