### ISSUE TITLE
Auditing Login/Logout Events

### ISSUE THREAD

**Issue by Theodory** [owen-it/laravel-auditing#498]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      |yes
| Framework         | Laravel
| Framework version | 5.5.*
| Package version   | 4.1
| PHP version       | 7.3.1

I want to be able to audit login and logout events rather than created, updated, deleted and restored only.

**Comment by vpillinger** [comment]
You can write custom observers on Illuminate\Auth\Events\Login and Illuminate\Auth\Events\Logout and manually create audit records with a custom event type.

Please see:
https://laravel.com/docs/5.8/events#event-subscribers

However, what is missing is the ability to add custom event types.

**Comment by marufmax** [comment]
how we audit for custom event type?

**Comment by Theodory** [comment]
Inside the `Event` handler add `Audit Model` then log event activity inside Audit trail table

Eg.
 
```php
  $data = [
            'auditable_id' => auth()->user()->id,
            'auditable_type' => "Logged In",
            'event'      => "Logged In",
            'url'        => request()->fullUrl(),
            'ip_address' => request()->getClientIp(),
            'user_agent' => request()->userAgent(),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'user_id'          => auth()->user()->id,
        ];

        //create audit trail data
        $details = Audit::create($data);

```
