### ISSUE TITLE
Auditing fields Json in the Model.

### ISSUE THREAD

**Issue by romulo2735** [owen-it/laravel-auditing#500]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7.*
| Package version   | 8.*
| PHP version       | 7.2.*

I'm having trouble auditing some columns in my model. One of the columns is in `json` format, inside it I get values, however I wanted to know if I have to show in new_values the values that were only modified inside that field,...

**Comment by vpillinger** [comment]
In version 8.0, it shows the entire field as modified when one value is modified. So it does not do any breakdown/dive into the column. 

I do not know if that behavior changed in 9.0, but not all databases support JSON columns so they are essentially just fancy text columns.

**Comment by MortenDHansen** [comment]
As @vpillinger says, its essentially a textfield and though the json values are cast, it's treated as a single field by eloquent, and thus also by laravel-auditing
