### ISSUE TITLE
[NEW DRIVER] andreshg112/laravel-auditing-notifications

### ISSUE THREAD

**Issue by andreshg112** [owen-it/laravel-auditing#503]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.6.39
| Package version   | 8.0.4
| PHP version       | 7.2.12

I want to share the driver I've created for Laravel Auditing.
https://github.com/andreshg112/laravel-auditing-notifications

It allows you to send notifications with audit data instead of saving it to an accessible database. By default, it sends notifications through AWS SNS using the package lab123it/aws-sns.

If you have some microservices and want to have centralized auditing, this could be helpful.

**Comment by andreshg112** [comment]
@anteriovieira, If you think this is good enough, this could be mentioned in the Community Drivers section.
http://laravel-auditing.com/docs/8.0/audit-drivers

**Comment by parallels999** [comment]
the driver is outdated and inactive
