### ISSUE TITLE
Retrieve related audit records

### ISSUE THREAD

**Issue by cjd118** [owen-it/laravel-auditing#509]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8.x
| Package version   | 9.x
| PHP version       | 7.3.x

We have a database structure that includes a base table with common fields:

| Base               
| -----------------
| id
| title

| Child
| ---------------
| base_id
| color

Child model has:

```
    public function base()
    {
        return $this->belongsTo(Base::class);
    }
```

Is it possible to get a list of audit records that have affected both the child table and the base table?

**Comment by MortenDHansen** [comment]
(closing old issue) - v13 finally has a solution for this
https://www.laravel-auditing.com/docs/13.0/audit-custom
