### ISSUE TITLE
Closed for extension

### ISSUE THREAD

**Issue by camih** [owen-it/laravel-auditing#51]
The audit function in trait prepares the array to be saved, and also saves it. This breaks SRP and makes it quite impossible to extend. The preparation should be in a different function so that other info can be saved by extending the functions.

I need to add some more info to the log table so I created migration to add the new columns to database. I could only save the newly created fields just by completely overriding the audit function. This is not good as any other additions or changes to audit (like route and ip on new version) would need to be implemented on the extending one also.

Also, by having the call to Log::insert in the same function with the preparation of data, prevents me from being able to use a class that extends Log (and has more fields, maybe mutators) instead of the Log class.

**Comment by anteriovieira** [comment]
I agree with you, and I still think we can give more attention to what you said. What you said made me think of other things. One of them is to make more flexible use of the class log.

**Comment by anteriovieira** [comment]
New version available with your suggestions.

Version: [v2.3.3](https://github.com/owen-it/laravel-auditing/releases/tag/2.3.3)
