### ISSUE TITLE
existing cast for changed column throws error

### ISSUE THREAD

**Issue by bussnet** [owen-it/laravel-auditing#513]
| Q                 | A
| ----------------- | ---
| Bug?              | yes (it seems so)
| Framework         | Laravel
| Framework version | 5.4
| Package version   | 8.0.4
| PHP version       | 7.2.1

#### Actual Behaviour

`->getModified(true)` throws `Call to undefined method Illuminate\Database\Query\Builder::castAttribute()` if the Model has a cast of a changed attribute, because in `Audit::getFormattedValue()` the `hasCast()` check is true, but the
`$model->castAttribute()` (contained in the Model from the HasAttributes trait) is protected, so could not called from outside and the `model::__call()` forward the call to the `QueryBuilder`.

It's weired, because every 3 cases in this method should fail, because every
Model method (from HasAttributes trait) is protected in Laravel [5.4](https://laravel.com/api/5.4/Illuminate/Database/Eloquent/Concerns/HasAttributes.html#method_castAttribute) and also in [5.8](https://laravel.com/api/5.8/Illuminate/Database/Eloquent/Concerns/HasAttributes.html#method_castAttribute). 

Is there something I don't get or some Laravel magic should happen or is this code that never had worked?

Its hard to believe this had never worked, but I don't find a point that belongs to my setup and causes this behaviour.

#### Steps to Reproduce

Add a simple cast for a column which is changed and call `getModified()`.
``` # Model which is audited and $name is changed
    protected $casts = [
        'name' => 'string',
    ];
```

**Comment by ctf0** [comment]
same here :cry:

**Comment by parallels999** [comment]
8.x reaches his end of life, fixed on earlier versions
