### ISSUE TITLE
QueryException when attempting to insert user agent

### ISSUE THREAD

**Issue by markokeeffe** [owen-it/laravel-auditing#515]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 8.0.4
| PHP version       | 7.2

#### Actual Behaviour

The `user_agent` column of the `audits` table is currently a VARCHAR(255). The Auditable trait attempted to insert an audit with a user agent longer than 255 characters: "Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57 [FBAN/FBIOS;FBAV/205.0.0.33.115;FBBV/139225211;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/12.1.4;FBSS/2;FBCR/OPTUS;FBID/phone;FBLC/en_GB;FBOP/5;FBRV/140223113]"

This resulted in a QueryException "value too long for type character varying(255) (SQL: insert into "audits" ... )"

#### Expected Behaviour

Insert the audit entry without throwing an exception.

#### Steps to Reproduce

Set `User-Agent` header to "Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57 [FBAN/FBIOS;FBAV/205.0.0.33.115;FBBV/139225211;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/12.1.4;FBSS/2;FBCR/OPTUS;FBID/phone;FBLC/en_GB;FBOP/5;FBRV/140223113]" and create a record that has Auditable trait.

#### Possible Solutions

1. Truncate the string to the character limit.
2. Increase the length of the `user_agent` column? Might not be ideal for users with the package already installed.

**Comment by BMasquio** [comment]
I see that a new migration fixed the error increasing the size of the column `user_agent`. But should be interesting to give a solution for those who still have the old table. It can be a command to a migration that alters the column.

**Comment by parallels999** [comment]
Already fixed
https://github.com/owen-it/laravel-auditing/blob/031cce760f3479e37f0def10e5c3b534290b76db/database/migrations/audits.stub#L30
