### ISSUE TITLE
How to disabled in dev mode?

### ISSUE THREAD

**Issue by KelvynCarbone** [owen-it/laravel-auditing#523]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 6.x.y
| PHP version       | 7.x.y

#### Actual Behaviour
In dev mode a i need to disable all audits

#### Expected Behaviour
I search for enable config in audit.php, but i dont see this option

#### Possible Solutions
in audit.php create a option enable => env("AUDIT", false),

**Comment by KelvynCarbone** [comment]
The option enabled does't work:

<?php
/**
 * This file is part of the Laravel Auditing package.
 *
 * @author     Antério Vieira <anteriovieira@gmail.com>
 * @author     Quetzy Garcia  <quetzyg@altek.org>
 * @author     Raphael França <raphaelfrancabsb@gmail.com>
 * @copyright  2015-2018
 *
 * For the full copyright and license information,
 * please view the LICENSE.md file that was distributed
 * with this source code.
 */

return [
    'enabled' => true,
    /*
    |--------------------------------------------------------------------------
    | Audit Implementation
    |--------------------------------------------------------------------------
    |
    | Define which Audit model implementation should be used.
    |
    */

    'implementation' => \App\Entities\MongoAudit::class,

    /*
    |--------------------------------------------------------------------------
    | User Morph prefix & Guards
    |--------------------------------------------------------------------------
    |
    | Define the morph prefix and authentication guards for the User resolver.
    |
    */

    'user' => [
        'morph_prefix' => 'user',
        'guards'       => [
            'web',
            'api',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Audit Resolvers
    |--------------------------------------------------------------------------
    |
    | Define the User, IP Address, User Agent and URL resolver implementations.
    |
    */
    'resolver' => [
        'user'       => OwenIt\Auditing\Resolvers\UserResolver::class,
        'ip_address' => OwenIt\Auditing\Resolvers\IpAddressResolver::class,
        'user_agent' => OwenIt\Auditing\Resolvers\UserAgentResolver::class,
        'url'        => OwenIt\Auditing\Resolvers\UrlResolver::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Audit Events
    |--------------------------------------------------------------------------
    |
    | The Eloquent events that trigger an Audit.
    |
    */

    'events' => [
        'created',
        'updated',
        'deleted',
        'restored',
    ],

    /*
    |--------------------------------------------------------------------------
    | Strict Mode
    |--------------------------------------------------------------------------
    |
    | Enable the strict mode when auditing?
    |
    */

    'strict' => false,

    /*
    |--------------------------------------------------------------------------
    | Audit Timestamps
    |--------------------------------------------------------------------------
    |
    | Should the created_at, updated_at and deleted_at timestamps be audited?
    |
    */

    'timestamps' => true,

    /*
    |--------------------------------------------------------------------------
    | Audit Threshold
    |--------------------------------------------------------------------------
    |
    | Specify a threshold for the amount of Audit records a model can have.
    | Zero means no limit.
    |
    */

    'threshold' => 0,

    /*
    |--------------------------------------------------------------------------
    | Audit Driver
    |--------------------------------------------------------------------------
    |
    | The default audit driver used to keep track of changes.
    |
    */

    'driver' => 'database',

    /*
    |--------------------------------------------------------------------------
    | Audit Driver Configurations
    |--------------------------------------------------------------------------
    |
    | Available audit drivers and respective configurations.
    |
    */

    'drivers' => [
        'database' => [
            'table'      => 'audits',
            'connection' => 'audit',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Audit Console
    |--------------------------------------------------------------------------
    |
    | Whether console events should be audited (eg. php artisan db:seed).
    |
    */

    'console' => false,
];



(1/1) InvalidArgumentException$databaseName is invalid:
--

**Comment by KelvynCarbone** [comment]
![image](https://user-images.githubusercontent.com/5288360/59129369-0454ef00-8943-11e9-97c7-ed89d059e2cb.png)

![image](https://user-images.githubusercontent.com/5288360/59129385-1040b100-8943-11e9-8170-29f495886246.png)

**Comment by KelvynCarbone** [comment]
![image](https://user-images.githubusercontent.com/5288360/59129415-22baea80-8943-11e9-9535-2c0a79c46e00.png)

![image](https://user-images.githubusercontent.com/5288360/59129422-29496200-8943-11e9-85fe-46fb35b630cd.png)

**Comment by KelvynCarbone** [comment]
![image](https://user-images.githubusercontent.com/5288360/59130272-6151a480-8945-11e9-82f0-d55af672a8f0.png)
![image](https://user-images.githubusercontent.com/5288360/59130278-657dc200-8945-11e9-818e-bbdf191314b8.png)

**Comment by MortenDHansen** [comment]
This problem has been solved (enable/disable with env)
