### ISSUE TITLE
[Question] Possibility to create entry for every single change?

### ISSUE THREAD

**Issue by mrvnklm** [owen-it/laravel-auditing#529]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no|yes
| Framework         | Laravel

#### Actual Behaviour

.Auditable creates single entries with multiple changes

#### Expected Behaviour

Auditable creates a single entry for every change, even though `->save()` is called once after several changes

I was wondering if this would be possible? Perhaps also as an setting to turn on / off, because this would open up a lot more ways to use that package.

**Comment by ctf0** [comment]
this will create too many records, while you can still manipulate the output of the diff http://www.laravel-auditing.com/docs/master/audit-presentation

**Comment by hako-studio** [comment]
I have a situation where this is required. Is there a way to make this happen?

I'm limiting audits to 50 records per record, and we're allowing end users to rollback to a specific revision.

Some of our records are saving one field at a time on the fly, however some forms are saved in one go, and we need to have the records saved individually.

Any insight into this would be amazing.

Thanks.

**Comment by Peter-Krebs** [comment]
In your controller, couldn't you loop through the `$request` and call `save()` individually for every `$request->input()`. Shouldn't this create the multiple audits you want?

**Comment by MortenDHansen** [comment]
Please reopen if relevant, but this sounds like a case thats a bit on the edge. Maybe there are better ways to design the solution.
