### ISSUE TITLE
Does support Arabic language??

### ISSUE THREAD

**Issue by elia3229** [owen-it/laravel-auditing#530]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 7.0
| PHP version       | 7.2.9

#### Actual Behaviour

I tried to save an Arabic word in my model which auditing on it ... then it has done but in the audit, table save some strange characters like this "inheritor_name":"**_\u0627\u0628\u0646 \u0627\u0628\u0646_**"

#### Possible Solutions

I think the problem with json_encode !!!! if it is used in somewhere!!!!

**Comment by ctf0** [comment]
this is a font encoding issue, if u r testing on linux u need to install the arabic language package

this issue also affects the arabic text in url

**Comment by parallels999** [comment]
closed due to inactivity
