### ISSUE TITLE
Delete multiple rows using one command !!!

### ISSUE THREAD

**Issue by elia3229** [owen-it/laravel-auditing#531]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 7.0
| PHP version       | 7.2.9

#### Actual Behaviour

I deleted many rows using one command ..... 
those rows didn't save in the audit table !!
note: if I delete one row, Will be saved.
 
can you help me!!!
thanks a lot....

**Comment by jeescu** [comment]
@elia3229 From what I've experienced mass update / delete, won't log. You have to do it one by one.
I just created static methods on base model just to solve this. 🤦‍♂ 
```php
public static function saveMany($models)
{
        foreach ($models as $model) {
            self::create($model);
        }

        return $models;
}
```

**Comment by Peter-Krebs** [comment]
@elia3229 Can this be closed?

You need to call `->delete()` on a model instance.  
Audits are not saved in general if you use a query builder and execute it directly. You have to loop through the models as @jeescu has shown and call `->delete()` on them individually.

**Comment by MortenDHansen** [comment]
Solutions mentioned are the correct way to go.
