### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getArrayableAttributes()

### ISSUE THREAD

**Issue by jargij** [owen-it/laravel-auditing#532]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.45
| Package version   | 8.0.4
| PHP version       | 7.2.16-1

#### Actual Behaviour

When calling function `getModified()` on an Audit model, I get the following exception:
```
Call to undefined method Illuminate\Database\Query\Builder::getArrayableAttributes()
```
Only when user object is linked to the audit log. 

#### Expected Behaviour

I expect an array of changed column_names and an array in it with two indexes ['old'] and ['new']

#### Steps to Reproduce
0. Login as a user
1. Create a random Auditable Model;
2. Create a new record;
3. Update the record;
4. Try to cal `getModified()` function for each Audit object.

```
        $audits = $address->audits;
        foreach ($audits as $audit) {
            dump($audit->getModified());
        }
```

![Schermafbeelding 2019-07-04 om 14 54 05](https://user-images.githubusercontent.com/1433486/60668343-03dd4480-9e6c-11e9-90f4-4533762d920a.png)

#### Possible Solutions

The problem occurs only when User object is linked to the Audit object. 
Specifically on line 87 in src/Audit.php. It tries to call an protected function `getArrayableAttributes()` in trait `Illuminate\Database\Eloquent\Concerns\HasAttributes`.

Temporary workaround could be overriding the visibility of that function in the User model itself by adding this function:

```
    /**
     * @return array
     */
    public function getArrayableAttributes()
    {
        return parent::getArrayableAttributes();
    }
```

I just cannot imagine there's no one else having this issue.

**Comment by parallels999** [comment]
It seems to be working correctly in the current version
