### ISSUE TITLE
Issue in unit test case 

### ISSUE THREAD

**Issue by Harishferose** [owen-it/laravel-auditing#533]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8
| PHP version       | 7.2

#### Actual Behaviour

I am using this https://github.com/franzose/ClosureTable plugin in my project , so i need to make interface between the plugins(franzose and owen-it).

#### Expected Behaviour

Need to run the unit test case for the repository but when i run the test it displays the following error in facade.php . Closure tree should be audited.

**Comment by parallels999** [comment]
No idea whats do [franzose/ClosureTable](https://github.com/franzose/ClosureTable) and how to integrate that, need more research for sure
