### ISSUE TITLE
Use of bigIncrement for the audit table?

### ISSUE THREAD

**Issue by judgej** [owen-it/laravel-auditing#534]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes ?
| New Feature?      | no|yes ?
| Framework         | Lumen
| Framework version | 5.8.10
| Package version   | 9.2.0
| PHP version       | 7.3.7
| Database | MySQL 5.6.45

#### Actual Behaviour

Just installed and published the database migration. The audit table looks like this:

```php
        Schema::create('audits', function (Blueprint $table) {
            $table->increments('id');
            $table->string('user_type')->nullable();
            $table->unsignedBigInteger('user_id')->nullable();
            ...
```

Note the primary key is `increments` and not `bigIncrements`. The relationship to the users table is correctly an `unsignedBigInteger`. Laravel 5.8 uses `bigIncrements` for all its migrations by default, and for good reason - data can grow so fast, especially as the audit table logs changes across ALL audited tables, so far as I can see.

#### Expected Behaviour

Describe the behaviour you're expecting.

        Schema::create('audits', function (Blueprint $table) {
            $table->bigIncrements('id');

#### Steps to Reproduce

Just install it using the steps in the installation docs.

#### Possible Solutions

I'm going to change the migration by hand before running the migrate. It should be automatic - perhaps the migration stub can contain a replacement field for the primary key type, and link that to the Laravel version at least.

**Comment by MortenDHansen** [comment]
This has been fixed :)
