### ISSUE TITLE
owen-it/laravel-auditing

### ISSUE THREAD

**Issue by vinothr196** [owen-it/laravel-auditing#540]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 6.x.y
| PHP version       | 7.x.y

#### Actual Behaviour

Describe the behaviour you're experiencing. Do not just copy and paste a random error message and expect help.

#### Expected Behaviour

Describe the behaviour you're expecting.

#### Steps to Reproduce

List **all the steps** needed to reproduce the issue you're having.

Make sure to **include code** (affected models, configuration, ...).

Pastebins, screenshots and/or other resources that may help us understand what's going on, will also be appreciated.

In a nutshell, help us, help you.

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by vinothr196** [comment]
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'OwenIt\Auditing\AuditingServiceProvider' not found

any one give solution.

i mentioned it but it still pacakges are not updated

app.php
OwenIt\Auditing\AuditingServiceProvider::class,

Composer.json file

"owen-it/laravel-auditing": "^2.1"

**Comment by ultrono** [comment]
I'd advise filling in the issue template and just posting it with the placeholder text :) 

Can you not use a newer version? You're attempting to pull in 2.3, but the latest is now 9.3. I can;t see 2.1 mentioned within the repository.

Have you taken a look at the version explanation at https://github.com/owen-it/laravel-auditing#version-information?
