### ISSUE TITLE
laravel auditing working only on User model and not working on other models

### ISSUE THREAD

**Issue by matheenulla6** [owen-it/laravel-auditing#542]
I don't know why in User model it is tracking all events. But in another model, only the newly created record is tracking and not other things like deleting, updating it is not tracking.
Please help me, guys.

namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class Brands extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    use Notifiable;
    use HasRoles;

   protected $fillable = [
        'brand_name', 'brand_status'
    ];
    protected $auditInclude  = [
        'brand_name', 'brand_status'
    ];
 
    
}

**Comment by rosswilson252** [comment]
@matheenulla6 Is this happening when using your app via a browser or cli/testing?

**Comment by matheenulla6** [comment]
> @matheenulla6 Is this happening when using your app via a browser or cli/testing?

**Comment by matheenulla6** [comment]
> @matheenulla6 Is this happening when using your app via a browser or cli/testing?

Thank you for replying.
But the problem was I was using the query builder in other models so it was not working. If we use eloquent then it will work.
