### ISSUE TITLE
Support Laravel 6.0

### ISSUE THREAD

**Issue by forestia-dev** [owen-it/laravel-auditing#544]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 6.0
| Package version   | 9.2.0
| PHP version       | 7.3

#### Actual Behaviour

I can't upgrade to Laravel 6.0 because owen-it/laravel-auditing v9.2.0 requires illuminate/filesystem ^5.8

#### Expected Behaviour

Upgrading to 6.0

#### Steps to Reproduce

- Update laravel/framework to 6.0
- composer update

**Comment by divdax** [comment]
I made a PR. You can pull in #545

**Comment by erikn69** [comment]
+1 Please upgrade for Laravel 6.0

**Comment by asivaneswaran** [comment]
Any updates on this?
Only package that is delaying the upgrade....

**Comment by HeinHanekom** [comment]
We Urgently need this update as well please. :-)

**Comment by asivaneswaran** [comment]
I feel like this package is not maintained? @anteriovieira

**Comment by asivaneswaran** [comment]
@quetzyg @raphaelfranca

**Comment by quetzyg** [comment]
Hi @asivaneswaran,

Sorry, but I'm not a project contributor anymore, since I started working on my own auditing package.

**Comment by joelwmale** [comment]
@quetzyg does it share a similar configuration/api to this package? Looking for something that is actively maintained.

**Comment by marcelogarbin** [comment]
It seems that this package is abandoned or not? What is the difference to the [spatie/laravel-activitylog](https://github.com/spatie/laravel-activitylog) package?

**Comment by divdax** [comment]
@marcelogarbin activitylog from spatie is a simple log package. An alternativ could be https://github.com/VentureCraft/revisionable

**Comment by quetzyg** [comment]
> @marcelogarbin activitylog from spatie is a simple log package. An alternativ could be https://github.com/VentureCraft/revisionable

That's just a terrible suggestion.

**Comment by divdax** [comment]
@quetzyg i also don't like revisionable because lack of features and switched to auditing. But no one want to rely on a abandoned package... I hope someone will take care of this great package!

**Comment by marcelogarbin** [comment]
> @quetzyg i also don't like revisionable because lack of features and switched to auditing. But no one want to rely on a abandoned package... I hope someone will take care of this great package!

laravel-auditing this is a great package, but its maintenance is required. Who will be the administrator besides Raphael? This repository has some open pull requests. I am thinking of creating a fork and following a new project. But I'll wait a while longer.

**Comment by asivaneswaran** [comment]
> > @quetzyg i also don't like revisionable because lack of features and switched to auditing. But no one want to rely on a abandoned package... I hope someone will take care of this great package!
> 
> laravel-auditing this is a great package, but its maintenance is required. Who will be the administrator besides Raphael? This repository has some open pull requests. I am thinking of creating a fork and following a new project. But I'll wait a while longer.

If you ever do that, can you let me know please?

**Comment by PizzaTibe** [comment]
> > @quetzyg i also don't like revisionable because lack of features and switched to auditing. But no one want to rely on a abandoned package... I hope someone will take care of this great package!
> 
> laravel-auditing this is a great package, but its maintenance is required. Who will be the administrator besides Raphael? This repository has some open pull requests. I am thinking of creating a fork and following a new project. But I'll wait a while longer.

No need to fork, just use https://altek.gitlab.io/accountant

Been using it for few months. I just upgraded to Laravel 6 witout problems.

Plus, the many to many relacion suport is briliant.

**Comment by rappasoft** [comment]
@PizzaTibe I tried the package you suggested, and maybe i'm missing something but: It seems like that package does not record a before and after, just a list of properties that were changed and the 'after' change status.

Given, the relationship feature/signatures/rollback features are nice. But I still feel like it lacks the 'auditing' perspective if I don't know what it was changed from.

**Comment by marcelogarbin** [comment]
@anteriovieira @quetzyg @raphaelfranca 
Are you still managing this package? Thank's

**Comment by roldandvg** [comment]
> @anteriovieira @quetzyg @raphaelfranca
> Are you still managing this package? Thank's

We would like to know if this package is still supported or was definitely abandoned, since there are many who urgently require the update to Laravel 6. Thanks to the administrator who can answer any questions

**Comment by quetzyg** [comment]
> @anteriovieira @quetzyg @raphaelfranca
> Are you still managing this package? Thank's

I already answered that question a few comments back. I'm no longer a contributor to this package. I also didn't want to shameless plug, but @PizzaTibe has mentioned my package, so there you are.

**Comment by quetzyg** [comment]
> @PizzaTibe I tried the package you suggested, and maybe i'm missing something but: It seems like that package does not record a before and after, just a list of properties that were changed and the 'after' change status.
> 
> Given, the relationship feature/signatures/rollback features are nice. But I still feel like it lacks the 'auditing' perspective if I don't know what it was changed from.
> 
> Am I missing something?

Send me an email with any questions you have, since I don't want to hijack this issue to talk about other packages.

**Comment by rappasoft** [comment]
@quetzyg Will do, thanks.

**Comment by asivaneswaran** [comment]
@quetzyg I know you said you don't want to plug your package, but considering this package seems abandoned, I was wondering how easy it is to switch from this package to yours?

**Comment by johanvanhelden** [comment]
> @quetzyg I know you said you don't want to plug your package, but considering this package seems abandoned, I was wondering how easy it is to switch from this package to yours?

I'm interested in knowing this as well. Especially migrating the data from `laravel-auditing` to the new package.

**Comment by rappasoft** [comment]
@johanvanhelden I'll plug his package and give it a 👍. It took me all of 10 minutes to make the swap.

Here's all I did for mine: https://github.com/rappasoft/laravel-boilerplate/commit/8df12e26270f5c232e0a6ff1f9ef8006ade8ab00

**Comment by johanvanhelden** [comment]
> @johanvanhelden I'll plug his package and give it a +1. It took me all of 10 minutes to make the swap.
> 
> Here's all I did for mine: [rappasoft/laravel-boilerplate@8df12e2](https://github.com/rappasoft/laravel-boilerplate/commit/8df12e26270f5c232e0a6ff1f9ef8006ade8ab00)

Thank you for the diff @rappasoft ! How to go about migrating the existing data? Many of our projects have a history build up of audit events. And we can not loose those whilst making the switch.

**Comment by rappasoft** [comment]
Oh I was looking from the perspective of new projects. The table layout is mostly the same, however the way the data is stored is different. I'm not sure it would be too easy to migrate the existing data.

**Comment by asivaneswaran** [comment]
Yeah, it's more about migrating existing data...

**Comment by AdamKyle** [comment]
So its official? People should stop using this or someone should fork it and make it compatible with laravel 6?

**Comment by nuernbergerA** [comment]
@anteriovieira is this package still maintained?

**Comment by gilbertronaldo** [comment]
> @anteriovieira is this package still maintained?

up

**Comment by asivaneswaran** [comment]
@gilbertronaldo @nuernbergerA It seems that it's not maintained.

I think I will just fork this and update it myself.

**Comment by jblotus** [comment]
I just updated to laravel 6 and I'm still able to use this plugin. Is there a specific feature that is incompatible or bug that prevents it from working I should be aware of?

**Comment by Athuli7** [comment]
I've forked it and added support for Larvel v6.
Testing has not been implemented.
I've not refactored the namespace since I wanted it to be a drop-in replacement.
My intent is to refactor in the next month or so to my namespace but leaving the OwenIt namespace as an alias for a seamless migration.

https://packagist.org/packages/runacorp/laravel-auditing

**Comment by Athuli7** [comment]
I've forked it and added support for Larvel v6.
Testing has not been implemented.
I've not refactored the namespace since I wanted it to be a drop-in replacement.
My intent is to refactor in the next month or so to my namespace but leaving the OwenIt namespace as an alias for backward compatibility.

https://packagist.org/packages/runacorp/laravel-auditing

**Comment by anteriovieira** [comment]
I feel very personal, I am very busy on another project. I am looking for collaborators who can maintain the package If someone is willing to collaborate, look for me at email anteriovieira@gmail.com.

I'll be very grateful.

**Comment by roldandvg** [comment]
> I'm so sorry for the delay, I am very busy on another project. I am looking for collaborators who can maintain the package If someone is willing to collaborate, look for me at email [anteriovieira@gmail.com](mailto:anteriovieira@gmail.com).
> 
> I'll be very grateful.

Thank you very much for the effort to keep this great package

**Comment by ultrono** [comment]
To confirm, has support for Laravel 6 now been added i.e. https://github.com/owen-it/laravel-auditing/blob/v9.3.1/composer.json#L43-L45

If so, it may be worth closing/updating thiis issue.

**Comment by DSpeichert** [comment]
Laravel 6 is supported now :)

**Comment by anteriovieira** [comment]
Thanks, everyone I will look at the package whenever possible if I disappear calls me by the email informed above. 😄 👍
