### ISSUE TITLE
PDOException: SQLSTATE[HY000]: General error: 1 no such column: route

### ISSUE THREAD

**Issue by sebestenyb** [owen-it/laravel-auditing#55]
Hi

I'm trying to use the package in a blank Laravel project.
It fails in the unit tests with the following error:

```
1) ExampleTest::testBasicExample
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such column: route (SQL: CREATE TEMPORARY TABLE __temp__logs AS SELECT id, user_id, owner_type, owner_id, old_value, new_value, type, created_at, updated_at, route FROM logs)
```

I'm using:
```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "owen-it/laravel-auditing": "^2.3",
        "doctrine/dbal": "^2.5"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
```

The database used in the unit tests is an in-memory sqlite table.
The issue can be worked around by removing the following lines:

```
        Schema::table('logs', function (Blueprint $table) {
            $table->dropColumn('route');
            $table->dropColumn('ip');
        });
```

**Comment by anteriovieira** [comment]
Set audit console for true, I wonder if it helped.

```php
audit_console' => true,
```
https://github.com/owen-it/laravel-auditing/blob/master/config/auditing.php#L57

**Comment by HarveyDoom** [comment]
I ran into this exact problem. Migrations worked fine on mysql, but when unit testing in sqlite I had to make the following changes.

In the AddVoyagerUserFields migration change 
`Schema::table('logs', function (Blueprint $table) {
            $table->dropColumn('route');
            $table->dropColumn('ip');
        });`
to 
`Schema::table('logs', function (Blueprint $table) {
            $table->dropColumn(['route', 'ip']);
        });`

Make the same change in the add routes migration and you should be set
