### ISSUE TITLE
[Question] Get attribute changes (history) from audited model

### ISSUE THREAD

**Issue by scarneros** [owen-it/laravel-auditing#551]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8
| Package version   | 9.0
| PHP version       | 7.2

#### Expected Behaviour

I need the attribute changes (historical data) from audited model with it's updated_at datetime value.

For example, let's say I have a model called Review (this model has id, user_id, comment, score and other attributes) under audit. The user is able to only change the comment, and this situation is correctly recorded on audits table.

It's possible to get an array, or something similar, with old comments and it's datetime instead of the entire model?

**Comment by parallels999** [comment]
```php
$review = Review::with('audits')->find($ReviewId);
$audits = $review->audits;
// Or
$review = Review::find($ReviewId);
$audits = $review->audits()->get();
```
