### ISSUE TITLE
Usage as a Chat System (plus Seen by feature)

### ISSUE THREAD

**Issue by jadamec** [owen-it/laravel-auditing#553]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      |yes
| Framework         | Laravel
| Framework version | 5.8.35
| Package version   |latest
| PHP version       | 7.3.x

Hi guys, is possible to use this package as a Chat System (updated data + comments), please? Also my question is how hard is to implement "Seen by" feature? Thank you!

**Comment by MortenDHansen** [comment]
Hi. Sorry for the late response. 
For a chat, i would say no. A :"Seen by" feature should not be too cumbersome to make though.
