### ISSUE TITLE
Invalid UserResolver implementation

### ISSUE THREAD

**Issue by abraham-fernandez** [owen-it/laravel-auditing#556]
Laravel auditing 9

**Comment by bogordesaincom** [comment]
same issue

**Comment by PH7-Jack** [comment]
same issue

**Comment by GavG** [comment]
If you haven't done so already you may want to ensure that the config cache is clear:

`php artisan config:clear`

**Comment by den1n** [comment]
Just force update the audit.php file to an updated one.

```sh
php artisan vendor:publish --provider "OwenIt\Auditing\AuditingServiceProvider" --tag="config" --force
```
