### ISSUE TITLE
Can't fetch metadata (`getMetadata()`) from Audit model.

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [owen-it/laravel-auditing#563]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6
| Package version   | 7
| PHP version       | 7.2

#### Actual Behavior
the error show up when I run this code,
**code**
```
$audit = new \OwenIt\Auditing\Models\Audit();
dd($audit->getMetadata());
```
**error** 
```
Argument 1 passed to Illuminate\Database\Eloquent\Model::serializeDate() must implement interface DateTimeInterface, null given
```

I saw this issue already point out and the solution is change updated_at column to nullable, but `updated_at` column in my table are already nullable. 

This is table structure, you can see updated_at is nullable.
![image](https://user-images.githubusercontent.com/14541103/70043432-d51bf380-15ee-11ea-8946-d2587bf3094e.png)

**Comment by MortenDHansen** [comment]
Sorry for the late reply. 

`$audit = new \OwenIt\Auditing\Models\Audit();` does not create an audit record, it just creates the model. Unless there is a usecase i don't know of for it, i don't think it makes sense to support this. Feel free to create a pull request though!
