### ISSUE TITLE
Excluding a column still writes an entry even if there is no other data updated

### ISSUE THREAD

**Issue by fri3ndly** [owen-it/laravel-auditing#567]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8.0
| Package version   | 9.0
| PHP version       | 7.3

#### Actual Behaviour

Added an exclusion column on model:
```
protected $auditExclude = [
        'last_active_at',
    ];

```

A blank data entry is added to the audit table e.g. old_values = [], new_values = []

#### Expected Behaviour

Expecting this to not make an entry in the database if no data is updated - Only an excluded column is updated

**Comment by martin-arvisais** [comment]
Same here, any fix?

**Comment by jefc1111** [comment]
Also interested in this. I just migrated to this from a different package after upgrading my app to Laravel 6. All is great apart from this point! Cheers.

**Comment by tekook** [comment]
Still present in version 12.x

**Comment by cwilby** [comment]
May be possible to add logic to this function

```
    public function audit(Auditable $model): Audit
    {
        $implementation = Config::get('audit.implementation', \OwenIt\Auditing\Models\Audit::class);

        $audit = $model->toAudit();

        if ($audit['new_values'] === []) {
           return;
        }

        return call_user_func([$implementation, 'create'], $model->toAudit());
    }
```

**Comment by cwilby** [comment]
FYI I've created a PR to solve this issue.  If merged, you will soon be able to add `$createEmptyAudits = false` to your models to fix this issue.

**Comment by MortenDHansen** [comment]
v13 has a new implementation of the excludes and this should now be supported: See https://www.laravel-auditing.com/docs/13.0/auditable-configuration "Empty audits"
