### ISSUE TITLE
Missing casting on old_values

### ISSUE THREAD

**Issue by orim181** [owen-it/laravel-auditing#568]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7.25
| Package version   | 8.0.4
| PHP version       | 7.2.14

#### Actual Behaviour

The old values aren't casted but the new values are:
![image](https://user-images.githubusercontent.com/11587953/73098488-83d60500-3eb7-11ea-8976-d9e19da88b20.png)

#### Expected Behaviour

I expected a consistent behavior so, for example, having the old_values to be casted like the new_values.

#### Steps to Reproduce

1. In the eloquent model that implements Auditable, leverage Laravel's casting feature:
```
protected $casts = [
        'is_active' => 'boolean'
]
```
2. Simulate a change on that field and look at the audit table. You'll see inconsistent casting

#### Possible Solutions

I leveraged the `transformAudit` feature of the library and created the following trait to apply the casting on the old_values:
```
trait AuditRecordCastFix
{
    public function transformAudit(array $data): array {
        foreach ($data['old_values'] as $key => $value) {
            if($this->hasCast($key)) {
                $data['old_values'][$key] = $this->castAttribute($key, $value);
            }
        }
        return $data;
    }

}
```

..then referenced it on my eloquent models:
```
class Blah extends Model implements Auditable {
   // use \OwenIt\Auditing\Auditable;
   use \OwenIt\Auditing\Auditable, Traits\AuditRecordCastFix {
        Traits\AuditRecordCastFix::transformAudit insteadof \OwenIt\Auditing\Auditable;
    }
}
```

**Comment by orim181** [comment]
When I troubleshooted this, the issue is that the auditing library is populating OLD and NEW via this method in its `src\Auditable` class...
![image](https://user-images.githubusercontent.com/11587953/73100142-f85e7300-3eba-11ea-87c6-b64a2caf519b.png)

...but Laravel only casts `attributes` not the `original` properties.

**Comment by vitomeuli** [comment]
Similar problem for me, with 'date' fields.
My stack is much younger than the OP's:
- laravel/framework v7.5.2
- owen-it/laravel-auditing v10.0.0
- PHP 7.4.4

**Comment by christianbayer** [comment]
This occurs because the method is accessing the $original property directly. If it was using the getOriginal() method instead, the cast would be working.

**Comment by MortenDHansen** [comment]
Hi. This is a rather old issue, and i wonder if its still relevant. Notice that using the value stored in database columns new and old will require casting. This is by design and is not a bug. Using the audit model method ->getModified() should render the results as seen through casts. 

An upcoming version will be with a rewritten process for the content of old and new values in the audit table. Partly because there are some issues with basic json serialization and partly because Laravel itself now uses an ArrayObject approach which is better.
