### ISSUE TITLE
Model update not record in audits

### ISSUE THREAD

**Issue by gzai** [owen-it/laravel-auditing#575]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 6.15.1
| Package version   | 9.3
| PHP version       | 7.4.2

#### Actual Behaviour

Simple update is working, record in audits as updated.
```
public function update(OwnersRequest $request, $id)
{
        $validation = $request->validated();

        $model = Owners::findOrFail( $id );
        $model->code = $request->input('code');
        $model->name = $request->input(['name');
        $model->description = $request->input('description');
        $model->save();
}
```

Fast update is not working, no record in audits.
```
public function update(OwnersRequest $request, $id)
{
        $model = Owners::where('id', $id)
                ->update( $request->validated() );
}
```

So how same function update can record to audits ?

**Comment by callum-veloxcommerce** [comment]
If you do a fast update using **find()** instead of creating a query builder with **where()** it will work.

e.g.

`public function update(OwnersRequest $request, $id)
{
        $model = Owners::find($id)
                ->update( $request->validated() );
}`

**Comment by gzai** [comment]
@callum-veloxcommerce thank you, it's working.

**Comment by callum-veloxcommerce** [comment]
No problem!
