### ISSUE TITLE
Support Laravel 7

### ISSUE THREAD

**Issue by cwilby** [owen-it/laravel-auditing#578]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 7.x.x
| Package version   | 9.3.2
| PHP version       | 7.4.x

#### Actual Behaviour

`laravel-auditing` requires `"illuminate/filesystem": "^5.8|^6.0"`, which should be updated to include `|^7.0` if I'm not mistaken.

#### Expected Behaviour

Should be able to install this package in a new Laravel 7 project

#### Steps to Reproduce

```
git clone git@github.com:laravel/laravel.git
cd laravel
composer install
composer require owen-it/laravel-auditing
```

Output: https://pastebin.com/raw/HbfzuSpq

#### Possible Solutions

In `composer.json`, add `7.0` for `illuminate/filesystem`.

**Comment by vesper8** [comment]
@quetzyg @anteriovieira what a popular package this is! already 4 PRs providing support for Laravel 7 and it's only been out for like 2 days! Guess there are quite a lot of us using it and hoping we can upgrade soon once you add the support : ) 

many thanks!

**Comment by cwilby** [comment]
I closed my PR to focus on https://github.com/owen-it/laravel-auditing/pull/581.

@RossAHC has covered namespace resolution, deprecated features, and includes documentation changes.  It's ready to merge IMO.

**Comment by efriandika** [comment]
I use git repo on my composer.json as a temporary solution until the PR #581. has been merged:

```
...
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/RossAHC/laravel-auditing"
        }
],
"require": {
        ...
        "laravel/framework": "^7.0",
        ...
        "owen-it/laravel-auditing": "dev-laravel-7"
        ...
},
...
```

**Comment by davidjr82** [comment]
Hi! @anteriovieira 

Maybe you can choose some maintainers to be able to merge PRs so this package can go on when you are not plenty of time. I don't have enough knowledge of this package to maintain it, but maybe someone here would...

**Comment by bcorcoran** [comment]
Please merge the PR!

**Comment by nasrulhazim** [comment]
I don't mind to do the PR merges if you ok with it @anteriovieira

**Comment by cwilby** [comment]
Merged! 🙌
