### ISSUE TITLE
Controlling for mass/querybuilder updates/deletes?

### ISSUE THREAD

**Issue by themightychris** [owen-it/laravel-auditing#580]
Is there any good practice out there for checking and monitoring the use of mass update/delete via querybuilder in an application to limit changes being made that can't be captured in the audit mode? i.e. hooking or overriding into QueryBuilder to log use of mass update/delete for developer review at least? or an effective way to audit a codebase for their use?

**Comment by palypster** [comment]
Have you figure it out? We currently looking for the proper solution, too.

**Comment by MortenDHansen** [comment]
I would love to, but the package relies on the eloquent events. Maybe the best way to go is to mass-insert the delete events after mass deleting? 

After all, you may just use Audit::create([]) to insert whatever you need
