### ISSUE TITLE
How to insert separate entries while made bulk changes.array doest reflect in the table.

### ISSUE THREAD

**Issue by loguloga** [owen-it/laravel-auditing#586]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 6.x.y
| PHP version       | 7.x.y

#### Actual Behaviour

Describe the behaviour you're experiencing. Do not just copy and paste a random error message and expect help.

#### Expected Behaviour

Describe the behaviour you're expecting.

#### Steps to Reproduce

List **all the steps** needed to reproduce the issue you're having.

Make sure to **include code** (affected models, configuration, ...).

Pastebins, screenshots and/or other resources that may help us understand what's going on, will also be appreciated.

In a nutshell, help us, help you.

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by loguloga** [comment]
Hi, 
 I've used transformAudit to change the stored data, if I made bulk and I send multi indexed array it doesn't reflect, but if single dimension array it works well. So, please let me know how to make separate entries for bulk changes like $resArr[] below.

 public function transformAudit(array $data): array{
        $resArr = [];
        foreach ($data['new_values'] as $key => $val) { 
            if(in_array($key, $this->auditInclude) and $key != 'be_back__c' and $key != 'app_retail_user__c'){
                $checked = 'Stage Checked';
                $verfied = 'Stage Verified';
                $trimKey = strtok($key, '__c'); 
                $stage   = strtoupper($trimKey);    
                $stages =  ["x1hr","pdeal","pdem","wda","walk","appt","dopen", "demo","prop","dcls",
                            "deal","exit","closed_won","closed_lost"];
                $data['new_values']['action_user'] = Auth::user()->username;
                $data['user_type'] = Auth::user()->user_role_id;
                if(in_array($trimKey,$stages)){
                    $data['new_values']['action_taken'] = "$checked.[$stage]";
                    if( strpos( $key, 'mgr' ) !== false) {
                        $data['new_values']['action_taken'] = "$verfied.[$stage]";
                    }  
                }
            }
            $resArr[] = $data;
        }

**Comment by MortenDHansen** [comment]
Hi. This is an older issue. If still relevant, please provide a description of what you are trying to achieve, what you are getting and what you are expecting so i can try to reproduce
