### ISSUE TITLE
Can't refresh migration

### ISSUE THREAD

**Issue by ChristianGiupponi** [owen-it/laravel-auditing#59]
Hi, I have installed the package and published the migrations and configuration file but if I run:

    artisan migrate:refresh --seed

I get:

    [Symfony\Component\Debug\Exception\FatalThrowableError]
    Class 'AddFieldsToLogTable' not found

**Comment by anteriovieira** [comment]
Sorry for the delay.

Nothing found about it, if any error please let us know.

**Comment by atthakorn** [comment]
I  faced against issue either.   It is class not found exception.    Run the following command should help

`composer dump-autoload`
