### ISSUE TITLE
Config update for Sanctum

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [owen-it/laravel-auditing#590]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.x
| Package version   | 10.x
| PHP version       | 7.x

This isn't really a package issue, but felt like I should share since it took me a little to figure out.

If you are using [laravel/sanctum](https://github.com/laravel/sanctum), you will need to update the `config/audit.php` so that the appropriate guards are used.  `laravel-auditing` has the `api` guard enabled by default, but that guard has gone away and is replaced with `sanctum`

The following will configure `laravel-auditing` to work with `sanctum` correctly:
```
    'user' => [
        'morph_prefix' => 'user',
        'guards'       => [
            'web',
            'sanctum',
        ],
    ],
```

**Comment by wannymiarelli** [comment]
I banged my head to the wall for 2h due to this issue :D thank you man! It should be stated clearly in the docs.

**Comment by sys-auditing** [comment]
Thanks, well done.

**Comment by giagara** [comment]
thanks!!!!!!

**Comment by kinare** [comment]
Thanks soooo much

**Comment by MortenDHansen** [comment]
Hi, sorry for the late reply. 

We know of the issue, and are working on a solution (https://github.com/owen-it/laravel-auditing/pull/695)

**Comment by MortenDHansen** [comment]
Now guards that can't be resolved are skipped.

**Comment by ScottHanson1972** [comment]
Just stumbled across this. This has saved me loads of head banging. Thank you very much!!!

**Comment by towin98** [comment]
Muchas gracias, yo disque iba a implementar un nuevo Resolve, que buena aporte!!!!

**Comment by jeckgit** [comment]
Thank you so much ❤

**Comment by koutouodilon** [comment]
Thanks man. You saved my day.

**Comment by AchmadSu** [comment]
So helpful!

**Comment by Piusshungu** [comment]
Thank you so much, man

**Comment by RRosalia** [comment]
2025 and i banged my head to the wall aswell
