### ISSUE TITLE
Cant catch laravel sync and  updateOrCreate

### ISSUE THREAD

**Issue by amarkotha366** [owen-it/laravel-auditing#591]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 5.8.*
| Package version   | ^10.0
| PHP version       | 7.2.18

#### Actual Behaviour

Cant catch update or create event when using updateOrCreate with DB::transaction .Also can't catch event of sync.

Code using:
**$this->event Belongs to event model**
```


    public function postData(array $data){
        return $event = DB::transaction(function () use($data) {
            $events = $this->event->updateOrCreate(
                ['data_id' => $data['event_name']['data_id']],
                $data['data_id']

            );
            $syncData = [];
            foreach ($data['items'] as $items){
                $syncData[$items["event_products_id"]]=  ['quantity' => $items['quantity'],
                    'unit_price' => $items['unit_price'] ?? 0];
            }
            $events->Items()->sync($syncData);

            return $event;
        });
    }
```

#### Expected Behaviour

Should catch sync method and updateOrCreate action.

**Comment by MortenDHansen** [comment]
Not being able to Audit changes on pivot is not a bug. It's just not currently possible. The upcoming version will have support to do custom events. Maybe that will help
