### ISSUE TITLE
Auditing sync/attach/detach

### ISSUE THREAD

**Issue by SuperlativeEntity** [owen-it/laravel-auditing#597]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | maybe
| Framework         | Laravel
| Framework version | v7.21.0
| Package version   | v10.0.0
| PHP version       | 7.4.7

#### Actual Behaviour

Relational changes are not audited

#### Expected Behaviour

Relational changes are audited

#### Steps to Reproduce

Use any sync,attach or detach function.

#### Possible Solutions

Have a look at GeneaLabs/laravel-pivot-events

**Comment by Stijn98s** [comment]
As workaround, you can create a pivot class. you need to use `public $incrementing = true;` so the `auditable_id` is not null.

**Comment by MortenDHansen** [comment]
Version 13 will come with an option to register custom events that could be used to solve this case.

**Comment by MortenDHansen** [comment]
v13 has support for a way to solve this. Please see: https://www.laravel-auditing.com/docs/13.0/audit-custom
