### ISSUE TITLE
Login and logout

### ISSUE THREAD

**Issue by lsobral** [owen-it/laravel-auditing#6]
How to track users when they did a login or logout?
Thanks

**Comment by anteriovieira** [comment]
Hello @lsobral ,
You can add last_access column and automatically from the laravel-auditing will track your changes.

**Comment by anteriovieira** [comment]
Maybe it was not very clear in my answer.
The idea is to register the column last_access the date and time the user accessed the system in this way it will be recorded as a log. To view the log you can customize the message as follows:

```php
    public static $logCustomFields = [
         'last_access' => 'Last access on {elapsed_time}.'
    ];
```

**Comment by lsobral** [comment]
Hello @anteriovieira 

I created a Handler to work at login time by updating the date of last access and the User model and put your code snippet. The log has been successfully created, but without "Last access on ..." string. In any case it worked. Thank you.

**Comment by anteriovieira** [comment]
Olá, @lsobral detalhe este ultimo problema que você teve.
