### ISSUE TITLE
www.laravel-auditing.com Website Is Down

### ISSUE THREAD

**Issue by WDC** [owen-it/laravel-auditing#600]
The Heroku-hosted Laravel-Auditing.com website is currently down, reporting a Heroku error. 

For those looking for the documentation, you can use the [archive.org snapshot from May 30th](https://web.archive.org/web/20200314044327/http://www.laravel-auditing.com/docs/9.0/introduction).

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/1221004/89048947-7db95900-d31e-11ea-9d20-e9cc4b65aa15.png">

**Comment by jpickwell** [comment]
It appears to be back up.

**Comment by johnnyhuy** [comment]
It's back up but it looks like the cert is expired

**Comment by arunkumar339** [comment]
still shows heroku application error

**Comment by stefanledin** [comment]
Still down? But the package itself is still alive, right? ;) Came here from Laravel News :)

**Comment by Br3mah** [comment]
but I think you can still install it 
> composer require owen-it/laravel-auditing
