### ISSUE TITLE
Upgrade to support Laravel 8

### ISSUE THREAD

**Issue by Stajor** [owen-it/laravel-auditing#606]
owen-it/laravel-auditing 10.0.x-dev requires illuminate/console ^5.8|^6.0|^7.0

**Comment by naquiuddin** [comment]
Please do this.

**Comment by imran-itmajlis** [comment]
My team loves this package. But this is blocking us from upgrading to Laravel 8. Please upgrade.

**Comment by naquiuddin** [comment]
![image-downloads](https://user-images.githubusercontent.com/1978381/92510804-097da980-f22a-11ea-8074-789367f55145.png)

Here is screenshot for your reference.

**Comment by ajpsp5** [comment]
We love this package! We need this PR reviewed and merged for our team to upgrade to L8.

**Comment by josuelmm** [comment]
Hi, plis upgrade this package..

**Comment by NickBelhomme** [comment]
https://github.com/owen-it/laravel-auditing/pull/608

**Comment by NickBelhomme** [comment]
https://github.com/owen-it/laravel-auditing/pull/609

**Comment by NickBelhomme** [comment]
https://github.com/owen-it/laravel-auditing/pull/610

**Comment by NickBelhomme** [comment]
https://github.com/owen-it/laravel-auditing/pull/611

**Comment by alphaolomi** [comment]
+1

**Comment by gldrenthe89** [comment]
This issue can be closed now this is working form v11 and up
