### ISSUE TITLE
TravisCI status checks no triggered when a PR is submitted

### ISSUE THREAD

**Issue by rogervila** [owen-it/laravel-auditing#615]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | N/A
| Framework version | N/A
| Package version   | N/A
| PHP version       | N/A

#### Actual Behaviour

Pull Requests do not trigger TravisCI jobs when opened.

#### Expected Behaviour

Travis jobs should be executed when a PR is opened

#### Steps to Reproduce

1. Open a PR

Travis status checks are frozen with the orange circle

![image](https://user-images.githubusercontent.com/6053012/94817610-7802f100-03fd-11eb-9b99-ff820b4f0650.png)

![image](https://user-images.githubusercontent.com/6053012/94817385-3d995400-03fd-11eb-801b-ad04973302ab.png)

#### Possible Solutions

Review repository configuration (only available for the package maintainers)

**Comment by MortenDHansen** [comment]
Im discontinuing using the travis checks altogether. Github actions are going to suit us better
