### ISSUE TITLE
Versión 11.x no longer compatible with Laravel 7.x and lower

### ISSUE THREAD

**Issue by D4ni3lr** [owen-it/laravel-auditing#616]
| Q                 | A
| ----------------- | ---
| Bug?              | no . Edit, is not a bug.
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.x and lower
| Package version   | 11.x
| PHP version       | 7.x

#### Actual Behaviour

The PR #608 makes 11.x no longer compatible with Laravel 7.x due to $app was changed to $container after Laravel 8.x.

`Undefined property: OwenIt\Auditing\Auditor::$container`

#### Steps to Reproduce

Install 11.x in Laravel 7.x or lower

**Comment by backstageel** [comment]
I don't think it's a bug, because the change is to reflect changes made in the core framework.

So if you what to use lower Laravel version than 8.x, just stick with version 10.x of this package

**Comment by D4ni3lr** [comment]
I agree with you, but then composer.json and README hould point that 11.x is only compatible with Laravel > 8.x because "composer update"  is going to install 11.x in older Laravel projects.

**Comment by backstageel** [comment]
I tested version 11 on Laravel 7.28 and didn't get any errors

![image](https://user-images.githubusercontent.com/1692858/95020839-e2ba6380-066d-11eb-8e90-0b202673d619.png)

**Comment by D4ni3lr** [comment]
You are right, i have two Laravel instances using versions 5.8 and 7.x, and $container was introduced in 6.x so Laravel Auditing 11.x works perfectly in Laravel >= 6.x. That was my bad.

**Comment by nelson6e65** [comment]
I'm getting this error with version 11. Composer states Laravel 5.8 as compatible. I had to downgrade to version 10.

**Comment by parallels999** [comment]
> I'm getting this error with version 11

11? That one is not released yet
