### ISSUE TITLE
Laravel-Auditing with Sentinel

### ISSUE THREAD

**Issue by AstroBoy269** [owen-it/laravel-auditing#62]
We are trying to use laravel-auditng and so far everything seems to be working great except we're not getting any user information populated.  We use the Caralyst/Sentinel package for security so our User object extends `\Cartalyst\Sentinel\Users\EloquentUser`.  Any suggestions on what to check?

Error from the `laravel.log` file:
`local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Access level to OwenIt\Auditing\AuditingTrait::getUserId() must be public (as in class Cartalyst\Sentinel\Users\EloquentUser)' in /chsh/app/Objects/User.php:473`

Thanks in advance.

**Comment by tyteen4a03** [comment]
+1. Needs to be fixed.

**Comment by tyteen4a03** [comment]
There seems to be no provision to support Sentinel (or any other 3rd party packages) because it makes calls to the Auth package directly. See #65.

**Comment by anteriovieira** [comment]
Hello guys, first sorry for the absence. 

I will try to meet everyone as fast as possible. We are also open to pull request when they feel necessary.

For now maybe this can help https://github.com/owen-it/laravel-auditing/issues/40

**Comment by tyteen4a03** [comment]
You also need to change the function's name to something else, since it clashes with Sentinel's own function. For me, I've changed it to `getLoggedInUserId`.

**Comment by anteriovieira** [comment]
Cool, you can open a pull request please.

**Comment by anteriovieira** [comment]
Sorry for the delay https://github.com/owen-it/laravel-auditing/issues/40 .
