### ISSUE TITLE
Auditing User's teloquent model, or table

### ISSUE THREAD

**Issue by ErSoul** [owen-it/laravel-auditing#621]
| Q                 | A
| ----------------- | ---
| Bug?             yes
| New Feature?     yes
| Framework         Laravel
| Framework version 5.8.35
| Package version   6.x.y
| PHP version       7.x=2.31

Is there a way to audit the User Model, with laravel-auditing? I can audit all models, except that one.

**Comment by parallels999** [comment]
weird, it is working for me using 13.x

6.x reaches his end of life
