### ISSUE TITLE
Is there a way i can audit a model for particular user?

### ISSUE THREAD

**Issue by gulgulia17** [owen-it/laravel-auditing#622]
| Q                 | A
| ----------------- | ---
| Framework         | Laravel
| Framework version | 7.x
| Package version   | 11.0
| PHP version       | 7.3

#### Expected Behaviour

I'm auditing the Product model currently but I just want to audit the model when a specific user makes any change, is there any way I could achieve this?

#### Currently achieving by

Currently achieving by this solution by firing an event `OwenIt\Auditing\Events\Auditing` and then with the help of `Spatie Permissions` checking if the user has a certain role and if they don't I just return `false` as referred in the documentation.

#### Possible Solutions

It would be great if the Developer get the control to set the particular set of userID on Model as 
`protected $user_ids = [1,2,3]`;

#### Solutions Available
- [ ] NO

**Comment by gulgulia17** [comment]
> Q	A
> Framework	Laravel
> Framework version	7.x
> Package version	11.0
> PHP version	7.3
> #### Expected Behaviour
> I'm auditing the Product model currently but I just want to audit the model when a specific user makes any change, is there any way I could achieve this?
> 
> #### Possible Solutions
> It would be great if the Developer get the control to set the particular set of userID on Model as
> `protected $user_ids = [1,2,3]`;
> 
> #### Solutions Available
> * [ ]  NO

**Comment by parallels999** [comment]
What about a middleware, on session user, check the ids and do `Model::enableAuditing/disableAuditing`
example:
```php
namespace App\Http\Middleware;

use App\Models\YourModel;
use Closure;

class EnableAuditing{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next){
        $user=auth('api')->user();
        if (! $user) {
            $user=auth()->user();
        }

        YourModel::disableAuditing();
        if ($user && in_array($user->id, [1, 2, 3])) {
            YourModel::enableAuditing();
        }
        return $next($request);
    }
}
```
Closed for now, tag me for other options
