### ISSUE TITLE
Is there a way to audit the model relations?

### ISSUE THREAD

**Issue by dendihandian** [owen-it/laravel-auditing#628]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 8
| Package version   | 11
| PHP version       | 7.4

#### Actual Behaviour

created and updated behavior, relation values isn't audited.

#### Expected Behaviour

relation values to a model should be audited.

#### Steps to Reproduce

I'm working with User model with audit trait, the User model has n-n relation to Role model. How to audit the relation changes?

#### Possible Solutions

This is no bug, but a question. I don't know where to ask this, so I decided to open GitHub issue. I could delete this anytime when I found an answer or the solution.

**Comment by RaiserWeb** [comment]
I'm wondering the same. It would be good if the creation of a model, could track the creation of relationship, so the audit table knows the connected rows for each relationship. So `Audit::find('id')->with('relations')` could bring back all the rows in the table related to that single model create

**Comment by dendihandian** [comment]
I could always manually updated the audit after it created/updated, but I don't know how to make the audit always working even thought there is no change in the model but there was a change for the relation and it didn't record.

**Comment by petini96** [comment]
I need it, I am working to include this feature in my project, if I can I will publish it here or submit a pull request

**Comment by petini96** [comment]
Hi guys! I can audit my model relationships.
1) I make an abstract class that:
- extends Authenticatable (extended model)
- has a private array attribute called "children": filled with key and value, where key is any name and value is the same name as the relationship method.
- has a method that calls all data from the relationship model through the private attribute in the model (which extends this abstract class).
- having an event triggered when the model state is "excluding": the event receives and injects a model into its constructor. OBS: don't forget to register with provider

2) I created the event talked above and an listener that:
- call the method talked above(that get all relationship data ) from model
- uses two trait methods  from owen-it package: for set event "deleted" and to prepare model to audit
- it create register audit  

ABSTRACT CLASS
![image](https://user-images.githubusercontent.com/40781705/117352857-790d6c80-ae7d-11eb-8a3e-8522f07b360b.png)

MODEL
![image](https://user-images.githubusercontent.com/40781705/117353019-a528ed80-ae7d-11eb-81c9-5401e75a61f5.png)

EVENT
![image](https://user-images.githubusercontent.com/40781705/117353109-b83bbd80-ae7d-11eb-9316-3cd7ed0580e3.png)

LISTENER
![image](https://user-images.githubusercontent.com/40781705/117353152-c8539d00-ae7d-11eb-8c73-7e9d95310c92.png)

EVENT SERVICE PROVIDER
![image](https://user-images.githubusercontent.com/40781705/117353286-f0db9700-ae7d-11eb-8ba2-1e5c17d2b19b.png)

**Comment by caiowilson** [comment]
@petini96 Vinicius, não entendi muito bem o que você fez, se puder me explicar melhor em portugues mesmo ou tentar em inglês novamente.
What i got from what you said would accomplish (very laborously) an audit event to trigger in case of deletion. Am I correct?
I have a model that has some 'hasMany' realtions and a 'belongsTo'.
What i'm looking for is to fetch all changes in said model PLUS changes on related models.

ie(pseudocode):
ModelA->hasMany(ModelB)

if i fetch ModelA audits I not only get ModelA changes but also new and old values for ModelB changes.

**Comment by MortenDHansen** [comment]
Thank you for the great feedback in this question!
In essence, the package uses the eloquent events to audit changes to the model. The pivot/relations are not on the model and doesn't fire events, so some special magic is required. Version 13 will include an option to record custom events so that there is a way to add this behaviour where needed.

**Comment by MortenDHansen** [comment]
v13 has support for a way to solve this. Please see: https://www.laravel-auditing.com/docs/13.0/audit-custom

**Comment by clwilliams8** [comment]
Does the new [Audit Custom](https://www.laravel-auditing.com/docs/13.0/audit-custom) stuff work only for morphToMany relationships? What about HasOne relationships?

**Comment by caiowilson** [comment]
Last time I used, one to one and one to many worked perfectly. 6 months agora I'd say.

**Comment by bartukocakara** [comment]
Yalan konuşma @caiowilson kandırma milleti morph harici kullanılmıyor
