### ISSUE TITLE
Track audits conditionally - How to track audits just when a certain condition is verified? 

### ISSUE THREAD

**Issue by davide-casiraghi** [owen-it/laravel-auditing#629]
| Framework         | Laravel
| Framework version | 7.24
| Package version   | 11.0
| PHP version       | 7.4

I'm using Spatie model status and I need to track the audits just after this condition is verified.

`$model->hasEverHadStatus() == 'submitted'`

What is the best practice to archive this?

**Comment by parallels999** [comment]
Maybe on creating
```php
public static function boot(){
    parent::boot();
    self::creating(function($model){
        if(!$model->hasEverHadStatus() == 'submitted') {
           self::disableAuditing();
        }
    });
    self::created(function($model){
       self::enableAuditing();
    });
}
```
