### ISSUE TITLE
auditable_type does not reflect the correct path of the model

### ISSUE THREAD

**Issue by ramonpego** [owen-it/laravel-auditing#632]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.30.3
| Package version   | v10.0.0
| PHP version       | 7.4.3

#### Actual Behaviour

on `OwenIt\Auditing\Models\Audit` the `auditable_type` is returning `"App\Model\Foo"` and I can't change

#### Expected Behaviour

Describe the behaviour you're expecting.
You should be returning `App\Models\Foo` as all models are in the "Models" folder within the app

#### Steps to Reproduce

I looked in the code, something about configuring the default models folder, but I didn't find anything like that.

![image](https://user-images.githubusercontent.com/6185157/105707386-9da68f80-5ef1-11eb-9244-6ea17282bf5a.png)

**Comment by ramonpego** [comment]
up

**Comment by DevBodin** [comment]
Can't say for sure if this will resolve your particular issues, but I'd recommend using Laravel's MorphMap instead of letting the _type field default to the namespaced class name. It'll save you a lot of trouble if you ever reorganize/rename any of your models.

**Comment by erikn69** [comment]
`auditable_type` shows the model namespace, not the path of folders
