### ISSUE TITLE
Using Auditor::execute($model) records empty audit log

### ISSUE THREAD

**Issue by benoanwar** [owen-it/laravel-auditing#633]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel|Lumen
| Framework version | 8.2.1
| Package version   | 12.0
| PHP version       | 8.0.0

#### Actual Behaviour
Using the Facade "use OwenIt\Auditing\Facades\Auditor;" (Audit::execute($model)) the log is recorded in the table but with old and new values as empty arrays. The normal update, store etc are recorded correctly and automatically

#### Expected Behaviour

 Calling Audit::execute($model); should add audit log to the database with the new values and old values correctly as it is already called from the observer.

#### Steps to Reproduce

My model implements Auditable and "\OwenIt\Auditing\Auditable;" trait with no changed settings other than the default. 
  $operator->update($updatedData);
        if ($audit = Auditor::execute($operator)) {
            Auditor::prune($operator);
        }
i am trying to use this document http://www.laravel-auditing.com/docs/9.0/auditor
#### Possible Solutions
I don't have a suggestion, I have managed to add events for attaching pivots etc.. and i want to add audits to this event.

**Comment by justcallmegrey** [comment]
im having the exact same problem, much appreciated if someone can help

**Comment by MortenDHansen** [comment]
Hi, i cannot speak for the issue of the explicit call of the Auditor, not without more information at least, but as for recording pivot attach there is a solution coming in version 13 (see [Audit pivot](https://www.laravel-auditing.com/docs/13.0/audit-custom)) which should target the use case.

PR #684

**Comment by MortenDHansen** [comment]
v13 has support for a different way to register audits - please see if https://www.laravel-auditing.com/docs/13.0/audit-custom solves the issue
