### ISSUE TITLE
Time to fix your website

### ISSUE THREAD

**Issue by AdamKyle** [owen-it/laravel-auditing#639]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | N/A
| Framework version | N/A
| Package version   | N/A
| PHP version       | N/A

#### Actual Behaviour

![Screen Shot 2021-03-27 at 3 02 19 PM](https://user-images.githubusercontent.com/188563/112734787-898d0780-8f0d-11eb-9488-6201d6831011.png)

#### Expected Behaviour

Website should work.

#### Steps to Reproduce

Follow the link to your website or google search it

#### Possible Solutions

Possible fix your website? :P

**Comment by nicopenaredondo** [comment]
agree.

**Comment by henriquecm** [comment]
It's back

**Comment by henriquecm** [comment]
It's down again

**Comment by AdamKyle** [comment]
It cant be that hard to keep a site up can it?

**Comment by vicenterusso** [comment]
the website itself is opensource.. if it's some info you are looking for

**Comment by chriskonnertz** [comment]
Still down...

**Comment by federicogodan** [comment]
you can access an cached version at https://web.archive.org/web/20200628025516/http://www.laravel-auditing.com/docs/9.0/installation or clone the website repo and start it on your machine at least as a temporary fix

**Comment by MortenDHansen** [comment]
Thanks for notifying. As it is working now, issue is closed 👍
