### ISSUE TITLE
Auditing won't work when using Livewire

### ISSUE THREAD

**Issue by berwynn** [owen-it/laravel-auditing#641]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.0
| Package version   | 10.0
| PHP version       | 7.4

#### Actual Behaviour

Upon using Livewire, any event that is fired through it, e.g. create. The event is not being registered by the audit.

#### Expected Behaviour

Creating a new entry e.g. a lead through Livewire, it should be caught by the audit and added accordingly.

#### Steps to Reproduce

After a form is filled out to create a lead, this code is being called upon: 
```public function submitForm() {
        $validated = $this->validate();

        //Manually set defaults
        $validated['lead_type'] = 'Manual';
        $validated['is_approved'] = 1;
        $validated['rating'] = $this->rating;

        if ($validated['lead_temp'] == 'Temp') {
            $validated['lead_temp'] = 'Default';
        }

        if ($validated['lead_status_id'] == 0) {
            $validated['lead_status_id'] = '1'; //default set to unassigned
        }

        //Manually set IDs
        $validated['company_id'] = auth()->user()->company_id;
        $validated['flag_alert_id'] = 1;
        $validated['campaign_id'] = 1;
        $validated['quote_id'] = 1;
        $validated['quote_data_id'] = 1;
        $validated['form_id'] = 1;
        $validated['form_data_id'] = 1;
        $validated['number_id'] = 1;
        $validated['email_id'] = 1;

        if(!empty($validated['user_id']) || $validated['user_id'] == 0) {
            $validated['user_id'] = auth()->user()->id;
        }
        else {
            $validated['user_id'] = $this->user_id;
        }

        $leadID = Lead::create($validated)->id;

        if(!empty($this->products)){
            $this->linkProductsToLeads($leadID);
        }

        if(!empty($this->files)){
            $this->uploadFiles($leadID);
        }

        $this->resetForm();

        session()->flash('snack-success', 'Lead successfully created!');
        $this->dispatchBrowserEvent('success-shown');
    }
```

Where "$leadID = Lead::create($validated)->id" will not show up in the database.

#### Possible Solutions

I have no idea how to sort this issue, when using a normal Laravel based creation via a controller in this case LeadsController, the lead would show up in the audits table. Other parts of the system that go through JS Ajax and hit an endpoint work absolutely fine, seems to be a Livewire specific issue.

**Comment by MortenDHansen** [comment]
I am using the package myself with a Livewire setup and do not experience problems. Please get back to reopen if this is still an issue so i can help sort it out :)

**Comment by oussama166** [comment]
I have the same issue like @berwynn . When I try to update my user model, the audit feature doesn't track or register the modifications.

**Comment by parallels999** [comment]
@oussama166 Some test or a repository on a fresh installation showing the problem is necessary
