### ISSUE TITLE
Auditing not working on relationship updates

### ISSUE THREAD

**Issue by aligajani** [owen-it/laravel-auditing#642]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 6.18
| Package version   | 9.00
| PHP version       | 7.3.2

#### Actual Behaviour

`$salon->services()->update(['service_should_auto_confirm' => $request->realtime_mode ?? 0]);`

When I run the above code, all services that belong to the salon are updated. 

#### Expected Behaviour

I expect the changes to services to show up in the audited table, but they don't which is weird.

**Comment by ordago** [comment]
>When issuing a mass update via Eloquent, the saving, saved, updating, and updated model events will not be fired for the updated models. This is because the models are never actually retrieved when issuing a mass update.

https://laravel.com/docs/8.x/eloquent#mass-updates

**Comment by Paula2001** [comment]
okay so what's the solution for this ?

**Comment by bianchi** [comment]
> okay so what's the solution for this ?

Make a loop over services and inside de loop:

```
$service->service_should_auto_confirm = $request->realtime_mode ?? 0;
$service->save();
```

**Comment by MortenDHansen** [comment]
As stated in the answers, this package observes the eloquent events. When performing mass-updates or similar actions that doesn't dispatch events, there is no way to audit it since the models are not actually being touched. The solution is to use ->each() on a collection or doing the actions in a for loop.
