### ISSUE TITLE
3rd party authentication package support

### ISSUE THREAD

**Issue by tyteen4a03** [owen-it/laravel-auditing#65]
Right now, this package assumes that the user is using the built-in Laravel Authentication package. This should not be assumed; the configuration should allow for the developers to use other authentication plugins (such as Sentinel)

**Comment by quoka** [comment]
\config\auditing.php
```
    /*
    |--------------------------------------------------------------------------
    | Authentication Model
    |--------------------------------------------------------------------------
    |
    | When using the "Eloquent" authentication driver, we need to know which
    | Eloquent model should be used to retrieve your users. Of course, it
    | is often just the "User" model but you may use whatever you like.
    |
    */

    'model' => App\User::class,
```

**Comment by tyteen4a03** [comment]
That has nothing to do with the fact that this package is making hardcoded calls to the `Auth` package.

**Comment by anteriovieira** [comment]
https://github.com/owen-it/laravel-auditing/issues/62

**Comment by anteriovieira** [comment]
Sorry for the delay https://github.com/owen-it/laravel-auditing/issues/40 .
