### ISSUE TITLE
Custom/Manual Ad-hoc Logging (or non-Eloquent Model Logging)

### ISSUE THREAD

**Issue by RomanoCodes** [owen-it/laravel-auditing#652]
| Q                 | A
| ----------------- | ---
| Bug?              | no|
| New Feature?      | yes
| Framework         | Laravel|

I have an application using logging for Eloquent models which is working well, however I am curious if there are any ways to also add support for transactions happening with Query Builder? I sense the core of this application focuses on Eloquent models, thus, a way around this would be to be able to generate/insert log events (ad-hoc) from controllers where builder is used.

Thanks in advance!

**Comment by MortenDHansen** [comment]
You might simply create a new record for the Audit table like any other record. It won't interfere. Fill in model and id and it should behave similar to anything created by the package itself 😄 

```
        Audit::create([
            'user_type' => '',
            'user_id' => '',
            'event' => '',
            'auditable_type' => '',
            'auditable_id' => '',
            'old_values' => '',
            'new_values' => '',
            'url' => '',
            'ip_address' => '',
            'user_agent' => '',
            'tags' => '',
        ]);
```

Currently the logic us built around Eloquent and currently i don't think it's on the roadmap to change that.
