### ISSUE TITLE
http://www.laravel-auditing.com/ is down

### ISSUE THREAD

**Issue by warksit** [owen-it/laravel-auditing#658]
http://www.laravel-auditing.com/ is down

 An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by redbeavermedia** [comment]
Second that

**Comment by waska14** [comment]
Same here :)

**Comment by ElielFC** [comment]
Mesmo problema aqui. 😞

**Comment by pheadeaux** [comment]
today again!

**Comment by commadelimited** [comment]
The site is still down, but for those who might be looking for the docs, you can still read them by checking out the documentation repo:
https://github.com/owen-it/laravel-auditing-doc/blob/master/documentation.md

**Comment by MortenDHansen** [comment]
> The site is still down, but for those who might be looking for the docs, you can still read them by checking out the documentation repo: https://github.com/owen-it/laravel-auditing-doc/blob/master/documentation.md

That's the a-level workaround! 

The site is working now, so ill go ahead and close the issue 😃
