### ISSUE TITLE
Laravel-Auditing is not working without any errors

### ISSUE THREAD

**Issue by atig3r** [owen-it/laravel-auditing#663]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7
| Package version   | Latests
| PHP version       | 7.3.26
------------------------------------

Hello , I've recently installed this package and configured everything with guide but some how it's not working!
By it's not working I mean it's not adding anything to database , I really don't know what is wrong with my configs but I've checked everything with guide 3 times and everything is correct but... I don't know

**config/audit.php:**

```
<?php

return [

    'enabled' => env('AUDITING_ENABLED', true),

    'implementation' => OwenIt\Auditing\Models\Audit::class,

    'user' => [
        'morph_prefix' => 'user',
        'guards'       => [
            'web',
            'api',
        ],
    ],

    'resolver' => [
        'user'       => OwenIt\Auditing\Resolvers\UserResolver::class,
        'ip_address' => OwenIt\Auditing\Resolvers\IpAddressResolver::class,
        'user_agent' => OwenIt\Auditing\Resolvers\UserAgentResolver::class,
        'url'        => OwenIt\Auditing\Resolvers\UrlResolver::class,
    ],

    'events' => [
        'created',
        'updated',
        'deleted',
        'restored',
        'gold_mailed' => 'goldMailed',
        'invited' => 'clientInvited',
    ],

    'strict' => false,

    'timestamps' => false,

    'threshold' => 0,

    'driver' => 'session',

    'drivers' => [
        'eloquent' => [
            'table'      => 'audits',
            'connection' => null,
        ],
    ],

    'console' => true,
];
```

**My model that I want to audit:**

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

use App\Models\Expansion;
use App\Models\Audit;

class Setting extends Model implements Auditable
{
    protected $table = 'settings';

    use \OwenIt\Auditing\Auditable;


    protected $fillable = [
      'expansion_id', 'season', 'advertiser_app', 'pvp_app', 'raid_app', 'version'
    ];

    protected $auditInclude = [
       'expansion_id', 'season', 'advertiser_app', 'pvp_app', 'raid_app', 'version'
   ];

    public function Expansion()
    {
      return $this->hasOne(Expansion::class, 'id', 'expansion_id');
    }
}
```

I don't know what infos do you need but I think this is enough

Can someone please help me? this is urgent for me :'(

**Comment by fhferreira** [comment]
+1

**Comment by MortenDHansen** [comment]
Hi. Sorry for the not so urgent response. Is the issue resolved?

**Comment by fhferreira** [comment]
In my case no.

**Comment by fhferreira** [comment]
@MortenDHansen in my case we are using the latest version 6.20.* and I follow the install like the tutorial said using the traits, but the "audit" is not triggered and no errors appears.

![image](https://user-images.githubusercontent.com/140686/153758159-442d1a8c-9197-4e92-8fc4-b2ba274131b0.png)

**Comment by MortenDHansen** [comment]
> @MortenDHansen in my case we are using the latest version 6.20.* and I follow the install like the tutorial said using the traits, but the "audit" is not triggered and no errors appears.
> 
> ![image](https://user-images.githubusercontent.com/140686/153758159-442d1a8c-9197-4e92-8fc4-b2ba274131b0.png)
> 

Oh, that's and oldie. I'll try and set it up tonight to see if i can find out what is wrong.

**Comment by fhferreira** [comment]
Thanks mate.

**Comment by atig3r** [comment]
> > In my case no.
> 
> Please help me understand the setup i need to test to identify the problem. 😊

Yes fixed for me and it was because of the way I was calling the eloquent
I can't remember how I was calling it before but if you send your controller code I can help you

**Comment by fhferreira** [comment]
I followed this: http://www.laravel-auditing.com/docs/9.0/installation

**Comment by MortenDHansen** [comment]
> I followed this: http://www.laravel-auditing.com/docs/9.0/installation

Also, please show the snippet where you are performing the action which you expect an audit from 😊

**Comment by fhferreira** [comment]
the most simple example:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class User extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;

    // ...
}
```

**Comment by MortenDHansen** [comment]
I need to see the update/save code. So where you call the `$user->save()`. The code where we should expect the audit to happen 😊

**Comment by fhferreira** [comment]
![image](https://user-images.githubusercontent.com/140686/154136674-e4c87898-d692-49e7-ac5a-84fd7582ab66.png)
![image](https://user-images.githubusercontent.com/140686/154136781-5e356bbe-6dc5-48a3-a92e-f797eccb51a9.png)
![image](https://user-images.githubusercontent.com/140686/154136870-c27ed4d5-f871-4653-9984-895aabb9c313.png)

just that, a simple object model update.
