### ISSUE TITLE
track updats occured through relationship

### ISSUE THREAD

**Issue by mohamedmahmoudkamel** [owen-it/laravel-auditing#666]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | *
| Package version   | *
| PHP version       | *

#### Actual Behaviour

Given the following code:
```
$driver->orders()->update(['status' => 'SUCCESSFUL']);
```
It should track updates occured to orders through the relationship.

#### Possible Solutions

Isn't it possible to extend laravel query builder and override the update function and trigger an event with the changes ?

**Comment by erikn69** [comment]
`$driver->orders()->update();` is a bulk update,

if you want trigger event must be
 ```php
$driver->orders()->each(function($model){ $model->update(['status' => 'SUCCESSFUL']); });
```
but it has performance cost

**Comment by MortenDHansen** [comment]
This package observes the eloquent events. When performing mass-updates or similar actions that doesn't dispatch events, there is no way to audit it since the models are not actually being touched. The solution described by @erikn69 is the way to solve this issue.
