### ISSUE TITLE
Have an issue with array casting Columns

### ISSUE THREAD

**Issue by ParthiBarath** [owen-it/laravel-auditing#668]
I click the update button without any changes in any fields but the array casting fields are updated automatically without changing the key values but it interchanging every time I click the update button it creates new row in audits table like the below

![old values column](https://user-images.githubusercontent.com/67301613/143067317-ff1aae2a-a050-41ae-a3bc-1bdf8154d52a.PNG)
old value column
![new values column](https://user-images.githubusercontent.com/67301613/143067394-3f6f56ea-a1ab-4c61-bd02-ff5aaf586421.PNG)
new value column

**Comment by benjivm** [comment]
Ahh, yes, this is actually the same problem I'm having #672 with casting `AsArrayObject::class`, hopefully they can patch soon.

**Comment by MortenDHansen** [comment]
Hi - there has been an update now concerning the AsArrayObject cast. I suspect this is not really a cast problem, but i am going to need more info to try and replicate the issue.

If still relevant, please help me by describing what is happening so that i can try to reproduce.
