### ISSUE TITLE
Use uuid to replace id

### ISSUE THREAD

**Issue by od3n** [owen-it/laravel-auditing#67]

**Comment by anteriovieira** [comment]
Hi @od3n  thanks for you contribution. Could you provide a use case for this?

**Comment by anteriovieira** [comment]
Hi @od3n , the cast to string solve your problem for now?

**Comment by ralphschindler** [comment]
What is the use case for using UUID over auto-inc id?  It seems that UUID should be opt-in behavior to me.

**Comment by anteriovieira** [comment]
Hello @ralphschindler , how do you suggest we do that?
