### ISSUE TITLE
[PHP 8.1] Deprecation message

### ISSUE THREAD

**Issue by robsontenorio** [owen-it/laravel-auditing#670]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 8.73
| Package version   | 12.0
| PHP version       | 8.1

#### Actual Behaviour

```
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/app/vendor/owen-it/laravel-auditing/src/Auditable.php on line 423
```

#### Expected Behaviour

No warning message.

#### Steps to Reproduce

Just save any model to fire auditing.

#### Possible Solutions

Type hint suggest methods as described on deprecation message.

**Comment by repat** [comment]
Could you please fix @anteriovieira  :)
