### ISSUE TITLE
JSON column displays same data for new and old

### ISSUE THREAD

**Issue by benjivm** [owen-it/laravel-auditing#672]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.77.1
| Package version   | 12.0.0
| PHP version       | 8.0.11

#### Actual Behaviour

Modifications to a model's JSON column records the same audit data (new and old).

#### Expected Behaviour

Display only changed data.

#### Steps to Reproduce

Use the `AsArrayObject` cast and modify a value in a model's JSON :

```php
$model->json = [];
$model->save();

$model->json = ['foo' => ['bar, 'baz']];
$model->save();
```

Use `$model->getModified()`:

```
array:1 [▼
  "json" => array:2 [▼
    "new" => Illuminate\Database\Eloquent\Casts\ArrayObject {#1872 ▼
      -storage: array:1 [▼
        "foo" => array:2 [▼
          0 => "bar"
          1 => "baz"
        ]
      ]
      flag::STD_PROP_LIST: false
      flag::ARRAY_AS_PROPS: false
      iteratorClass: "ArrayIterator"
    }
    "old" => Illuminate\Database\Eloquent\Casts\ArrayObject {#1872 ▼
      -storage: array:1 [▼
        "foo" => array:2 [▼
          0 => "bar"
          1 => "baz"
        ]
      ]
      flag::STD_PROP_LIST: false
      flag::ARRAY_AS_PROPS: false
      iteratorClass: "ArrayIterator"
    }
  ]
```

#### Extremely painful workaround

```php
$new = $this->new_values;
$old = $this->old_values;

$newJson = json_decode($new['json'], true);
$oldJson = json_decode($old['json'], true);

unset($new['json']);
unset($old['json']);

$newValues = array_merge($new, $newJson);
$oldValues = array_merge($old, $oldJson);
```

### Edit
This is caused by the `AsArrayObject` cast. Using something like `(array) $model->$jsonColumn` could solve it??

**Comment by MortenDHansen** [comment]
Hi, i can't seem to reproduce/understand the problem. 
I have tried the following simple setup:

```
$variousData = VariousData::create([
    'title' => 'Test title',
    'json_content' => json_encode([])
]);

$variousData->json_content = json_encode(['a' => 'b', 'c' => 'd']);
$variousData->save();
dd($variousData->audits()->skip(1)->first()->getModified());
```

Output is the expected:
```
array:1 [
  "json_content" => array:2 [
    "new" => "{"a":"b","c":"d"}"
    "old" => "[]"
  ]
]
```

If this is still an issue, can you help me reproduce the problem?

**Comment by benjivm** [comment]
Add this cast to your `VariousData` model:

```php
protected $casts = [
    'json_content' => AsArrayObject::class
];
```

Then you'll encounter the issue.

The `AsArrayObject` cast is required for property mutation on JSON columns, here are the [Laravel Docs](https://laravel.com/docs/8.x/eloquent-mutators#array-object-and-collection-casting) on it.

**Comment by MortenDHansen** [comment]
I see :) - that one is new since 8.28 and i haven't had a use for it yet so it wasn't on my mind.

Thanks for clarifying. Ill look into it 😄

**Comment by benjivm** [comment]
Yes when I first opened the issue I didn't realize that was the cause, but then I saw another issue that made it clear. I tested it by removing the cast and it did indeed work, so it's just a specific issue with that cast.

Thank you!
