### ISSUE TITLE
Historylog workflow

### ISSUE THREAD

**Issue by Cannonb4ll** [owen-it/laravel-auditing#68]
Hello,

How does the $historyLimit actually work, lets say I have a model with 500 logs and $historyLimit = 500, what happens after any action has been taken, it just stops logging? I think it would be nice if it deletes the oldest row in the logs table.

**Comment by anteriovieira** [comment]
Sorry for the delay.

This really should be the behavior, thank you.

Available from version v2.3.7

https://github.com/owen-it/laravel-auditing/blob/master/README.md#configuration-optional
