### ISSUE TITLE
Custom UserResolved problem "Invalid UserResolver implementation"

### ISSUE THREAD

**Issue by muratkose1126** [owen-it/laravel-auditing#697]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 8.x
| Package version   | 13
| PHP version       | 7.4

![Screenshot_1](https://user-images.githubusercontent.com/46588118/157727797-d256b30a-a6d0-4b46-ba0f-3de9253ae651.png)

dokümantasyonda bu şekilde gösterilmiş yazılımda aynı şekilde yaptım çalışmadı. biraz inceledikten sonra App klasörünün öncesine "/" işareti koymadığım için Illuminate/support içerisinde arıyor bu nedenle çalışmıyordu. "/" işaretini koyduktan sonra çalışmaya başladı. 

![Screenshot_2](https://user-images.githubusercontent.com/46588118/157727813-4b1ea948-ddff-46b9-94bb-c9b343d8dcfd.png)

bu şekilde sorunum çözüldü belki aynı durumla karşılaşanlar olabilir diye oluşturdum.

**Comment by MortenDHansen** [comment]
I cannot read what you have written 🙁

**Comment by muratkose1126** [comment]
I was told in the documentation to write App/Resolvers/UserResolver in the config/audit.php file, I couldn't get it to work that way

**Comment by muratkose1126** [comment]
When I typed /App/Resolvers/UserResolver in config/audit.php it worked.

**Comment by muratkose1126** [comment]
I do not know English. I wrote it with translation. I hope you understand.

**Comment by MortenDHansen** [comment]
Thats ok. 🙂  - happy you got it to work!
