### ISSUE TITLE
Is it ok to have `$auditEvent` protected when using customAudit?

### ISSUE THREAD

**Issue by r0lodex** [owen-it/laravel-auditing#698]
https://github.com/owen-it/laravel-auditing/blob/1ec0aabc97d660292679ff1045a1369b11c68912/src/Auditable.php#L34

I've come across the error `Unable to handle "" event, () method missing` when trying to use `AuditCustom`. I think it should be a public property.

**Comment by r0lodex** [comment]
#699

**Comment by MortenDHansen** [comment]
You are totally right! - It looks like a typing mistake 😞  

Good catch! - thanks!
