### ISSUE TITLE
Documentation about upgrading 

### ISSUE THREAD

**Issue by vicenterusso** [owen-it/laravel-auditing#711]
The documentation to ugprade from version 9 to 10 and 10 to 12 doesn't exists. Both displays the upgrade to version 8

https://laravel-auditing.com/docs/10.0/upgrading
https://laravel-auditing.com/docs/12.0/upgrading

**Comment by MortenDHansen** [comment]
Hi, we are aware. Sadly the team at the time didn't create the instructions, and though it would be nice, i don't think it is going to happen 😞
