### ISSUE TITLE
Need to log updated record's primary key with changed data

### ISSUE THREAD

**Issue by prabathchanakadpl** [owen-it/laravel-auditing#715]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 9.x.y
| Package version   | 13.x.y
| PHP version       | 8.x.y

Hi, this is not a bug, I am facing this problem when doing the update, I want to log the updated values with the table id (primary key).
How can I achieve that? I am new to this package, please help.

ex:- when I update a record it will log the updated values. That's totally fine. But I need to log the updated record's primary key too

#### Current Behaviour
Old Values  {"balance":"0.00"}
new Vaue {"balance":1000}

#### Expected Behaviour

Old Values  {"id":2,"balance":"0.00"}
new Vaue {"id":2,"balance":1000}

please help.!!!

**Comment by PaolaRuby** [comment]
Read documentation, there is the answer

**Comment by erikn69** [comment]
https://laravel-auditing.com/guide/audit-transformation.html
