### ISSUE TITLE
How to change what user_type gets, since I use polymorphic relationships for user roles

### ISSUE THREAD

**Issue by guilhermecostam** [owen-it/laravel-auditing#716]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.75
| Package version   | 13.0
| PHP version       | 8.1.6

#### Actual Behaviour

In my system I have roles for my users. The user table is related to a table called user_roles, in it goes the user_id, the role (student, admin, teacher...) and the 'roleable_id' (id of the table the role refers to).
My problem is that I want to receive in the audits records the role of the user who made the change in the model. With the default configuration it always comes 'user' in user_type, but I want that if, for example, the user who made something is a student, the user_type is also a 'student'.

#### Possible Solutions

I am not sure, but I believe that to achieve this I should make some modification here in the audit config:
```php
    'user'      => [
        'morph_prefix' => 'user',
        'guards'       => [
            'web',
            'api'
        ],
        'resolver'     => OwenIt\Auditing\Resolvers\UserResolver::class
    ],
```

**Comment by PaolaRuby** [comment]
Use relations and joins
