### ISSUE TITLE
Error User Model - Auditable not found

### ISSUE THREAD

**Issue by wbetalleluzd** [owen-it/laravel-auditing#718]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 9.17.0
| Package version   | 13
| PHP version       | 8.1.2

#### Actual Behaviour

Error en User Model.

![2022-06-09 19-12-27](https://user-images.githubusercontent.com/4992150/172965787-3254a366-0402-4a8e-ad2e-570be3f83064.jpg)

![image](https://user-images.githubusercontent.com/4992150/172965729-f252a20a-9b76-4845-8273-65bee20d3338.png)

![image](https://user-images.githubusercontent.com/4992150/173163094-a7e5eae0-a3c1-41d7-a58d-5fd7a1722b93.png)

**Comment by erikn69** [comment]
Looks like you didn't install correctly the package

**Comment by wbetalleluzd** [comment]
Now, is perfect....
