### ISSUE TITLE
Insert function not working ??

### ISSUE THREAD

**Issue by Prabhath1996** [owen-it/laravel-auditing#721]
| Q                 | A
| Insert function not working ??| ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.x.y
| Package version   | 12.x.y
| PHP version       | 7.4.y

#### Actual Behaviour

When I try to insert a new user in the controller this way it is not audited.
$result = User::insert(
            [
                'first_name' => $firstName,
                'last_name' =>  $lastName,
                'email' =>  $emailAddress,
                'mobile' =>  $phoneNumber,
                'location' =>  $location,
                'password' => Hash::make(1234),
                'active_status' => $active_status,
                'is_admin' => $is_admin,
                'user_role'=>$user_role,
                'address'=>$address,
                'nic'=>$nic,
                'created_at' => date("Y-m-d"),
            ]
        );

#### Expected Behaviour

Describe the behaviour you're expecting.
'events' => [
        'insert',
        'created',
        'updated',
        'deleted',
        'restored',
        'detach',
        'attach',
        'associate',
        'dissociate',
        'updateOrCreate',
    ],

**Comment by MortenDHansen** [comment]
insert will not fire the events audit is listening for. You need to use new User()->save() or create([<attributes>]). Insert is essentially a queryBuilder and will bypass audit
