### ISSUE TITLE
Attributes with enums as values as automatically excluded from audit

### ISSUE THREAD

**Issue by mogottsch** [owen-it/laravel-auditing#722]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.0
| Package version   | 13.0
| PHP version       | 8.1

#### Actual Behaviour

When using enums in attributes, then those attributes are excluded from the audit.

#### Expected Behaviour

Attributes that have enums as values should be included in the audit with the `->value` of the enum.

#### Steps to Reproduce

1. Assign an enum to the attributed of an auditable model
2. Save
3. See that attribute is missing from audit

#### Possible Solutions

This piece of code adds the attributes to the excluded list because enums are of type object and do not implement `__toString()`.

https://github.com/owen-it/laravel-auditing/blob/2317a5ed72f0c4256b1c274d3e6ef53db5d0598c/src/Auditable.php#L116-L121

It is possible to check whether a given value is an enum. See [here](https://stackoverflow.com/questions/70237057/how-to-check-if-enum-type).

**Comment by MortenDHansen** [comment]
Good one. I will release the pr 👍
