### ISSUE TITLE
Question: sync adds a lot of [] values, intended?

### ISSUE THREAD

**Issue by rezaffm** [owen-it/laravel-auditing#725]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version |  8
| Package version   | 13
| PHP version       | 8

Hi,

I am fighting my way through the package (which is greeeeaaaaat!). 

While sync some relationships (to be exact authors, categories and tags), like:

```php
    public function syncAuthors(array $authors)
    {
        $syncWithPivot = collect($authors)->mapWithKeys(function($author) {
            return [
                $author['id'] => [
                    'type' => $author['type'],
                    'order_column' => $author['order_column']
                ]
            ];
        })
        ->toArray();

        //$this->authors()->sync($syncWithPivot);
        $this->auditSync('authors', $syncWithPivot);
    }

    public function syncCategories(array $categories)
    {
        $categories = Category::whereIn('id', $categories)->select('id')->get();

        //$this->categories()->sync($categories);
        $this->auditSync('categories', $categories);
    }

    public function syncTags(array $tags)
    {
        $tags = Tag::whereIn('id', $tags)->select('id')->get();
        //$sync = $this->tags()->sync($tags);
        $sync = $this->auditSync('tags', $tags);

        foreach (array_get($sync, 'attached') as $attachedId) {
            $tags->where('id', $attachedId)->first()->increment('count');
        }

        foreach (array_get($sync, 'detached') as $detachedId) {
            Tag::where('id', $detachedId)->where('count', '>', 0)->first()->decrement('count');
        }
    }
```
I noticed that in the database a lot of old/new values are generated, even if I haven't changed the relationships at all, like:

![image](https://user-images.githubusercontent.com/40648929/177000784-c623fd28-be00-4cbd-ba3b-5b724d8860df.png)

**Is this wanted behavior?**

I know I could change that by disabling empty values at all or by using a function in the ::creating boot method (happy for further ideas tough...).

**Comment by MortenDHansen** [comment]
No. There should be a fix for it released. I will check up on it

**Comment by martijnimhoff** [comment]
Any status update on this?

**Comment by 7twelve** [comment]
am experiencing the same behavior running latest v13

**Comment by parallels999** [comment]
Did you try this?
https://github.com/owen-it/laravel-auditing/blob/332d136a7d67a2c06ee85aa17efeafb3ba25c972/config/audit.php#L89-L107

**Comment by parallels999** [comment]
Seems closed by https://github.com/owen-it/laravel-auditing/pull/684
