### ISSUE TITLE
Vendor publish not working in Lumen 8

### ISSUE THREAD

**Issue by nicoherms** [owen-it/laravel-auditing#728]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 8.3.4
| Package version   | 13.0.4
| PHP version       | 7.4.29

#### Actual Behaviour

When publishing vendor config on Lumen, the next error occurs on command line:
In AuditingEventServiceProvider.php line 9:
Class 'Illuminate\Foundation\Support\Providers\EventServiceProvider' not found 

#### Expected Behaviour

Publish the config file correctly as expects on installation description.

#### Steps to Reproduce

1. Install package via composer
2. Edit **bootstrap/app.php** file to register provider "$app->register(OwenIt\Auditing\AuditingServiceProvider::class);"
3. Install package laravelista/lumen-vendor-publish and register command in kernel.php
4. Run next command to publish files **php artisan vendor:publish --provider "OwenIt\Auditing\AuditingServiceProvider" --tag="config**

<img width="852" alt="Captura de Pantalla 2022-07-20 a la(s) 12 10 01" src="https://user-images.githubusercontent.com/19217412/180018030-14ca38bc-ef0d-4a80-babc-08a4fe861c1c.png">

#### Possible Solutions

Replace **EventServiceProvider** import for Lumen projects.

<img width="625" alt="Captura de Pantalla 2022-07-20 a la(s) 12 13 34" src="https://user-images.githubusercontent.com/19217412/180018792-56ec6a5e-3e8d-42ca-8de6-334b62565081.png">

**Comment by erikn69** [comment]
Just make your own custom service provider with lumen `EventServiceProvider`

**Comment by parallels999** [comment]
@anteriovieira already fixed by #731, must be closed
