### ISSUE TITLE
Documentaion "Audit Migration" is highly inaccurate

### ISSUE THREAD

**Issue by VijitCoder** [owen-it/laravel-auditing#729]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 9.19
| Package version   | 13.0
| PHP version       | 8.1.7

#### Actual Behaviour

Here is the **official** document - https://www.laravel-auditing.com/docs/13.0/audit-migration

In the part _"UUID over auto-incrementing ids"_ said about `User` and `Auditable` models, but proposed changes relates to the tables in the database, not models. Let it be so. But in the migration absent these models/tables! So, make us guessing. I suppose, `Auditable` is `audits` actually, but where is the `User` in the migration - hell is know.

Also, why it is required to change

```
$table->nullableMorphs('user');
```

into two fields + index, while the Laravel can make it easily under the hood of calling method `$table->morphs()`?

BTW: `$table->nullableMorphs('user')` from the documentation is supposed to be `$table->morphs('auditable')` in the migration. Does is look the same? Guessing again.

I checked the older versions of documentation and source code. It seems this misleading **always been there**. Nice..

#### Possible Solutions

Rewrite the documentation according to the reality. Make it at least once.

**Comment by VijitCoder** [comment]
I found that there is [a separate repo](https://github.com/owen-it/laravel-auditing-doc/blob/13.0/audit-migration.md) with documentation. Well, who could have foreseen? I think this problem should be described there.

**Comment by Shkeats** [comment]
@VijitCoder your attitude stinks.

**Comment by VijitCoder** [comment]
Really? That's strange cause my attitude only reflects the quality of the document that I reported. Nothing personal.

**Comment by MortenDHansen** [comment]
Thank you for reporting! - and You are of course right. We are aware that the documentation needs a refactor just like various parts of the software that has grown out of itself does. The hours we have at our disposal are limited though. I have not myself tried changing ids for uuids, hence i have not looked at the documentation. In general i would need to try out various usecases before updating the documentation to reflect reality. It will eventually be done, but for now, i simply can't spare the time. Sorry.

If you are able to, you are very welcome to open a pull request against https://github.com/owen-it/laravel-auditing-doc/pulls 🙂
