### ISSUE TITLE
Question: Custom resolver always get only field new_values

### ISSUE THREAD

**Issue by julianphp** [owen-it/laravel-auditing#730]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 9.23
| Package version   | 13
| PHP version       | 8.1

#### Actual Behaviour
I adding to the config/audit.php in resolvers a custom for the field "old_data" or another, and in the Auditable $auditable always get the data of the "new_values" field.

#### Expected Behaviour

At created a custom resolver, use the data of the field selected. 

#### Steps to Reproduce
'old_values' => \App\AuditResolvers\DataToCompress::class,
```
<?php

namespace App\AuditResolvers;

use Illuminate\Support\Facades\Log;
use OwenIt\Auditing\Contracts\Auditable;
use OwenIt\Auditing\Contracts\Resolver;

class DataToCompress implements Resolver
{
    public static function resolve(Auditable $auditable)
    {
        Log::debug($auditable);
       return base64_encode(gzdeflate(json_encode($auditable)));
    }
}
```
Always get $auditable fields new_values

**Comment by MortenDHansen** [comment]
The resolvers are run as part of generating the audit (\OwenIt\Auditing\Auditable::toAudit) and i think what you are after is actually the finished audit. The toAudit method collects data that is to be audited. The resolvers are part of that, so having a resolver that needs the finished (resolved) audit does not really work. I guess that is the problem. What is it exactly you want to be stored?

**Comment by julianphp** [comment]
@MortenDHansen 
I simply want to convert to base64 and compress the "old_values" and "new_values" fields,
the other is with
```
public function transformAudit(array $data): array
    {
        $data['old_values'] = base64_encode(gzdeflate(json_encode($data['old_values']));
        $data['new_values'] = base64_encode(gzdeflate(json_encode($data['new_values']));
        return $data;
    }
```
but I don't want to have to put it in every model. With a trait would be a correct way to do it? the truth is that I don't know much about it.

**Comment by MortenDHansen** [comment]
All right. Well. The resolvers are meant to add (meta)data. The property in the resolver does not have the new_values and old_values. They come as the result after the resolvers are executed. 

What you need is probably to change the storage logic instead. Maybe look at the driver? \OwenIt\Auditing\Drivers\Database::audit

 - You can create your own driver (simply copy the database one).
 - Create a new Audit model that extends the Audit model from the package
 - make a method called auditCreate or something like that which forwards to laravels create. 

In the middle of that method you can now work with the finished audit data (thats the argument you get in line 19 of the driver $model->toAudit).

**Comment by julianphp** [comment]
@MortenDHansen 
I'm trying to extend it from a model, but I'm leaving something out.
```
<?php

namespace App\Models;


class AuditCustom extends \OwenIt\Auditing\Models\Audit
{

    public function transformAudit(array $data): array
    {
        $data['old_values'] = base64_encode(gzdeflate(json_encode($data['old_values'])));
        $data['new_values'] = base64_encode(gzdeflate(json_encode($data['new_values'])));
        return $data;
    }
}

```
in config/audit.php ->     'implementation' => \App\Models\AuditCustom::class,
and in the model I want to use I simply import the two traits ?
```
use OwenIt\Auditing\Contracts\Auditable;
use \OwenIt\Auditing\Auditable as AuditableUse;
```

**Comment by MortenDHansen** [comment]
Awesome!

**Comment by MortenDHansen** [comment]
You solution is much better than mine 🤣
