### ISSUE TITLE
Bug when "created_at" and "updated_at" fields are named differently

### ISSUE THREAD

**Issue by juanotiz1997** [owen-it/laravel-auditing#735]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.63.0
| Package version   | 13.0.5
| PHP version       | 8.0.10

#### Actual Behaviour

When I rename the fields "created_at" and "updated_at" it throws an error when using the getModified() method.
It throws the following error:
"IlluminateDatabaseEloquentModel::serializeDate(): 

#### Expected Behaviour

Espero que el trait Audit tome el valor que defino en mi modelo  y no el valor por default

#### Steps to Reproduce

1.-Change the name of "created_at" and "updated_at" to another one.
2.-define these new names in the model with the attributes "CREATED_AT" and "UPDATED_AT" of the Model class.
3.-Implement the auditor
4.-Use the getModified() method.

Make sure to **include code** (affected models, configuration, ...).

Pastebins, screenshots and/or other resources that may help us understand what's going on, will also be appreciated.

In a nutshell, help us, help you.

![const_c u](https://user-images.githubusercontent.com/26563010/184042952-80488c51-6c66-42d9-a995-cdfc0ce8f06d.png)
![error](https://user-images.githubusercontent.com/26563010/184042953-0e485098-b742-4904-94c2-4a127e57a92e.png)
![log](https://user-images.githubusercontent.com/26563010/184042954-20ecea85-8818-43e1-816d-eeea01a57c7d.png)
![model](https://user-images.githubusercontent.com/26563010/184042958-7713b664-bb1c-4629-b459-932a31e0de84.png)
![NEW](https://user-images.githubusercontent.com/26563010/184042959-98b3c01b-66c1-408d-974a-f618695a7a3a.png)
![OLD](https://user-images.githubusercontent.com/26563010/184042961-d86f462a-c4fd-482e-be64-a45d4a3b691a.png)

#### Possible Solutions

In the Audith.php file, in line 78 and 79 change the following:

![old_lines](https://user-images.githubusercontent.com/26563010/184043197-67ba7635-1251-4a6c-8727-3ecc4282158e.png)

to this:

![new_lines](https://user-images.githubusercontent.com/26563010/184043242-79420012-048b-437e-ad45-f26bc19bd8fd.png)

By:
Jose Juan Ortiz Lopez
juan.ortizlopez25@gmail.com

**Comment by PaolaRuby** [comment]
If you know the solution make a PR

**Comment by parallels999** [comment]
merged
