### ISSUE TITLE
https://laravel-auditing.com/ is down

### ISSUE THREAD

**Issue by ptums** [owen-it/laravel-auditing#737]
| Q                 | A
| ----------------- | ---
| Bug?                     |yes

#### Actual Behaviour

[Laravel Auditing](https://laravel-auditing.com/) is down

#### Expected Behaviour

[Laravel Auditing](https://laravel-auditing.com/) is running

#### Steps to Reproduce

Go to [Laravel Auditing](https://laravel-auditing.com/)

#### Possible Solutions

Checkout ``heroku logs --tail``

**Comment by parallels999** [comment]
Duplicate of #708
