### ISSUE TITLE
Is there a way to add some note/description to any change on model? 

### ISSUE THREAD

**Issue by charlesbatista** [owen-it/laravel-auditing#738]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 9.
| Package version   | 13
| PHP version       | 8..1

#### Actual Behaviour

I really need to add some note to any change on model like a description of why that record was changed. Does anybody have a idea for that solution? Thanks in advance.

**Comment by RobTDE** [comment]
Hi! i need to do the same, have you find a solution?

**Comment by RobTDE** [comment]
i turned around the problem making a manual relation with a notes table where to store audit_id right after the audit creation

**Comment by parallels999** [comment]
https://laravel-auditing.com/guide/audit-transformation.html
Also you could add a new field on migration, and use `transformAudit` to set that field from request to audit db table
