### ISSUE TITLE
New resolver not being created via CLI

### ISSUE THREAD

**Issue by kps1ny** [owen-it/laravel-auditing#741]
| Q                 | A
| ----------------- | ---
| Bug?              | maybe
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.83.23
| Package version   | 13.0.5
| PHP version       | 7.3.33

#### Actual Behaviour

In the documentation at https://www.laravel-auditing.com/docs/13.0/audit-resolvers it says that a new resolver can be created with artisan auditing:audit-resolver but when using php artisan auditing:audit-resolver test nothing seems to happen. There is no error message, nor is there any new file added to /vendor/owen-it at any level.

#### Expected Behaviour

I was expecting a file called testResolver.php in the folder /src/Resolvers, or perhaps somewhere else within /vendor/owen-it.

Perhaps it is being created somewhere else?

#### Steps to Reproduce

enter php artisan auditing:audit-resolver test

result:
$ php artisan auditing:audit-resolver test
Add your new resolver to the resolvers array in audit.php config file.
AuditResolver created successfully.
$

#### Possible Solutions

In the documentation at https://www.laravel-auditing.com/docs/13.0/audit-resolvers clarify what should happen when issuing the command to make a new resolver, in addition to noting that it has to be added to the audit.php file.

**Comment by parallels999** [comment]
Maybe your file permissions
I did test  `php artisan auditing:audit-resolver test` and it is working, look
```php
<?php

namespace App\AuditResolvers;

use OwenIt\Auditing\Contracts\Auditable;
use OwenIt\Auditing\Contracts\Resolver;

class test implements Resolver
{
    public static function resolve(Auditable $auditable)
    {
        // TODO: Implement resolve() method.
    }
}
```
