### ISSUE TITLE
SoftDelete problem

### ISSUE THREAD

**Issue by RobTDE** [owen-it/laravel-auditing#755]
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 8
| Package version   | 13
| PHP version       | 8

#### Actual Behaviour

hi, i need some help, i'm trying to make a custom Audit model to add the sofdeleted models, but it doesn't work may i made any mistakes.
first i copied the Audit.php model of the package and then i did the implementation on my app\config.php, but anyway it doesn't work.
i read the doc for the softdelete but for me isn't so clear and i can't make it work :(
the only solution to my problem at this moment is adding ->withTrashed() to functions in trait in the vendor folder, but i'd like to avoid that.

#### Expected Behaviour

i've read that the functions would be added to the model and not to the trait, but in my package (v.13) is still in the trait

#### Possible Solutions

make the documentation for implementing the softdelete easier 

if anyone can help, thanks

**Comment by nekoding** [comment]
i think you should make custom class and extend it to `OwenIt\Auditing\Models\Audit`  and change the implementation in `config\filament.php` . i try like this and it work 

![image](https://user-images.githubusercontent.com/64598048/211974534-9287c23d-def4-429a-a637-1b15460c8a2e.png)
![image](https://user-images.githubusercontent.com/64598048/211974572-3f9fe18d-327e-4fae-9ca9-82527f6e36e7.png)
