### ISSUE TITLE
Problem to save the files

### ISSUE THREAD

**Issue by rrodrigofranco** [owen-it/laravel-auditing#761]
Hi there,
I followed the tutorial putting the configuration in config/audit.php from repository https://github.com/betapeak/laravel-auditing-filesystem/, this way:
![image](https://user-images.githubusercontent.com/16249363/215083801-48bbe242-1b21-44ff-a6e0-8f64decd28fd.png)

and I ran the composer install and composer update in the terminal, however this does it working.
I do not see the folder auditoria in storage:
![image](https://user-images.githubusercontent.com/16249363/215083851-0cb3aad2-fd1e-4cc4-a4f2-baf3a0746921.png)
Someone can help me?

**Comment by parallels999** [comment]
Maybe writing permissions

**Comment by parallels999** [comment]
closed due to inactivity, this is also a question for [betapeak/laravel-auditing-filesystem](https://github.com/betapeak/laravel-auditing-filesystem/), that dricer looks abandoned
