### ISSUE TITLE
Please tag latest release for Laravel 10 support

### ISSUE THREAD

**Issue by LTKort** [owen-it/laravel-auditing#766]
@anteriovieira 

 On installing Laravel 10, composer produces the following error:
```
Problem 1
    - Root composer.json requires laravel/framework 10.x-dev -> satisfiable by laravel/framework[10.x-dev].
    - owen-it/laravel-auditing v13.0.5 requires illuminate/filesystem ^7.0|^8.0|^9.0 -> satisfiable by illuminate/filesystem[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.51.0].
    - Only one of these can be installed: illuminate/filesystem[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.51.0], laravel/framework[10.x-dev]. laravel/framework replaces illuminate/filesystem and thus cannot coexist with it.
    - Root composer.json requires owen-it/laravel-auditing ^v13.0.5 -> satisfiable by owen-it/laravel-auditing[v13.0.5].
```

But when using the master branch it does not fail, could you please tag the latest release?

**Comment by aglipanci** [comment]
I would really appreciate if you guys can tag the latest release.

**Comment by parallels999** [comment]
Everybody wants that, but looks like @anteriovieira has no time, maybe he could add somebody else to the staff for common tasks https://github.com/owen-it/laravel-auditing/pull/756#issuecomment-1412258845

**Comment by wbetalleluzd** [comment]
He put that:

Warning

Hi guys, thank you for your trust in this package. I would like to dedicate more time to the project but at the moment it is not possible. If this project is useful to you and you would like to help, please contact me at [anteriovieira@gmail.com](mailto:anteriovieira@gmail.com). I have no intention of archiving this project.

:(

**Comment by mllull** [comment]
Well, current [last commit in `master` branch](216630ea7f1b091444ca659e60119f35664bd4eb) is supporting Laravel 10 as of 1c727f506d4f274bef99044f5191715d81b66b34 merge.

So what I did to install Laravel 10 in my project was to config `composer.json` to use this commit has a source of `owen-it/laravel-auditing` package.

So, as a temporary fix, you can set `owen-it/laravel-auditing` package version as:

```json
"owen-it/laravel-auditing": "dev-master",
```

This will pull last commit in GitHub and not from *packagist* and then this will allow you to install Laravel 10 in your project.

P.S: Laravel 10 requires you to set  `minimum-stability` as `stable`, but you need to set as `dev` if you want to install  `owen-it/laravel-auditing` from GitHub, once installed you can set `minimum-stability` as `stable`.

:warning: :warning:  **Note:** This is a **temporary fix** and not recommended way of maintaining your packages versions!

**Comment by LTKort** [comment]
I've sent him an email

**Comment by anteriovieira** [comment]
done! sorry for the delay
