### ISSUE TITLE
Failed requirements for Laravel-10

### ISSUE THREAD

**Issue by txdFabio** [owen-it/laravel-auditing#767]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10.0.0
| Package version   | 13.0
| PHP version       | 8.2

#### Actual Behaviour

I'm trying to use it on the new-realeased Laravel-10 but it fails on requirements contraints with the following message:

> Using version ^13.0 for owen-it/laravel-auditing
> ./composer.json has been updated
> Running composer update owen-it/laravel-auditing
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires owen-it/laravel-auditing ^13.0 -> satisfiable by owen-it/laravel-auditing[v13.0.0, ..., v13.0.5].
>     - owen-it/laravel-auditing[v13.0.0, ..., v13.0.5] require illuminate/console ^7.0|^8.0|^9.0 -> found illuminate/console[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.
> 
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require owen-it/laravel-auditing:*" to figure out if any version is installable, or "composer require owen-it/laravel-auditing:^2.1" if you know which you need.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

#### Expected Behaviour

A successful installation

#### Steps to Reproduce

`composer create-project laravel/laravel laravel_10`
`cd laravel_10`
`composer require owen-it/laravel-auditing`

**Comment by txdFabio** [comment]
I've seen it's the same issue of https://github.com/owen-it/laravel-auditing/issues/766, I'm closing this one

**Comment by parallels999** [comment]
Also https://github.com/owen-it/laravel-auditing/pull/756#issuecomment-1412258845
