### ISSUE TITLE
Upgrading from v12 to v13 shows a dead link for upgrade instructions

### ISSUE THREAD

**Issue by jameswilddev** [owen-it/laravel-auditing#769]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.41.0
| Package version   | 13.1.0
| PHP version       | 8.0

#### Actual Behaviour

Link to upgrade instructions is dead.

#### Expected Behaviour

Link to upgrade instructions is valid.

#### Steps to Reproduce

- Install and configure owen-it/auditing v12.
- Use Composer to upgrade to v13.
- Visit any page.

![image](https://user-images.githubusercontent.com/3138458/223513336-b6c6a6ec-9d50-4bdd-819d-03f428179dbe.png)

#### Possible Solutions

Reinstate upgrade documentation

**Comment by parallels999** [comment]
Looks like a typo, here is the link
https://laravel-auditing.com/guide/upgrading.html
