### ISSUE TITLE
Option to queue auditing

### ISSUE THREAD

**Issue by Cannonb4ll** [owen-it/laravel-auditing#77]
I think it would be cool if the auditing package could queue the queries in the background so the user would not notice any longer loading times whenever another query is executed. Not that it is currently slowing down my application, but I can see when you get alot of data it might affect the application.

**Comment by anteriovieira** [comment]
Hi @Cannonb4ll ,
Awesome idea, I will start working on it. I am also open the pull request. Thanks for the tip. :wink:
