### ISSUE TITLE
#743 doesn't respect TrustedProxy settings

### ISSUE THREAD

**Issue by ceejayoz** [owen-it/laravel-auditing#804]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10.3.3
| Package version   | 13.4.0
| PHP version       | 8.2

#### Actual Behaviour

Insertion fails, as it attempts to insert the ([correctly](https://serverfault.com/questions/846489/can-x-forwarded-for-contain-multiple-ips)) multi-IP forwarding header.

`Illuminate\Database\QueryException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type inet: "175.157.86.118, 10.0.16.108" (Connection: pgsql, SQL: insert into "audits" ("old_values", "new_values", "event", "auditable_id", "auditable_type", "user_id", "user_type", "tags", "ip_address", "user_agent", "url", "updated_at", "created_at") values (...  175.157.86.118, 10.0.16.108...)`

#### Expected Behaviour

Laravel Auditing should only use `Request::ip()`. This already respects `X-Forwarded-For` headers internally, **if** the TrustedProxy middleware is correctly configured. That's where this should be handled.

Note that #743 has introduced a security hole, as `X-Forwarded-For` can be modified by a malicious user, resulting in an incorrect IP being logged in the audit trail.

#### Steps to Reproduce

Run Laravel Auditing in a multi-proxy scenario (in our case: nginx --> Docker).

Alternatively, use cURL to spoof the header (`curl -H "X-Forwarded-For: 123.123.123.123" http://example.com`) on an endpoint that will cause an audit log entry. The faked IP should appear in the database. `curl -H "X-Forwarded-For: 123.123.123.123 10.0.0.1" http://example.com` will cause the SQL error.

#### Possible Solutions

Revert change from #743.

**Comment by systemsolutionweb** [comment]
>  if the TrustedProxy middleware is correctly configured. That's where this should be handled.

Hi, examples? Can you share a link where everyone can see that configuration?
It is to prevent it from happening again and keep information for the future.

**Comment by MortenDHansen** [comment]
That makes sense. The package should do as basic as possible, and rely on users to extend when needed.

**Comment by ceejayoz** [comment]
@MortenDHansen Thanks!

Just to be clear, extending isn't necessary for @lincolnpjames's issue (and would introduce the same security hole); they just need to configure their TrustedProxy middleware correctly for their load balancer / proxy setup.
