### ISSUE TITLE
Not logging when where is used

### ISSUE THREAD

**Issue by ukpasupport** [owen-it/laravel-auditing#81]
Is there any reason why it does not work when I use where and it works when I use find?

[Does Not work]
Police::where('id', $request->poilice_id)->update($flds);

[Works]
Police::find($request->poilice_id)->update($flds);

**Comment by anteriovieira** [comment]
Hello @ukpasupport ,

I've been working on a new version that will come with this fix.

Had any progress?

**Comment by ukpasupport** [comment]
Hi Anteriovieira,

We have implemented laravel-auditing in our project. We have amended our code base to make use of the find as much as we can though. 

Thank you for making Laravel -Auditing available for everybody :)

Cheers

**Comment by anteriovieira** [comment]
I will check it for you and give you a response as soon as possible

**Comment by anteriovieira** [comment]
Please try the version v2.4.5
