### ISSUE TITLE
Laravel 5.3 support?

### ISSUE THREAD

**Issue by axyr** [owen-it/laravel-auditing#82]
Composer does allow install this package on 5.3.

Any plans to update this?

**Comment by anteriovieira** [comment]
Hello @axyr , I'll do it tonight.

**Comment by anteriovieira** [comment]
Give me some time because I will change some things and provide support for 5.3. I'm working on it now.

**Comment by anteriovieira** [comment]
Added support from version v2.4.1

**Comment by axyr** [comment]
Great thanks!
