### ISSUE TITLE
Install on laravel 10

### ISSUE THREAD

**Issue by Tahernejad** [owen-it/laravel-auditing#835]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 10.13.0
| Package version   | last
| PHP version       | 8.2

Hello,

Problem 1
    - Root composer.json requires laravel/framework 9.*, found laravel/framework[v9.0.0, ..., v9.52.8] but the package is fixed to v10.13.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by parallels999** [comment]
https://github.com/owen-it/laravel-auditing/blob/7d09546436ff3317edc899362c9bc20af27be39c/composer.json#L41-L45
https://github.com/owen-it/laravel-auditing/blob/master/README.md#version-information
