### ISSUE TITLE
ArrayObject::__construct() TypeError

### ISSUE THREAD

**Issue by kubenkwi** [owen-it/laravel-auditing#858]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 9.52.4
| Package version   | 12.2.1
| PHP version       | 8.1.17

#### Actual Behaviour

When calling `getModified()` on an audit contains a null property that casts to an `ArrayObject`, a `TypeError` is thrown.

#### Expected Behaviour

Successfully retrieving modified.

#### Steps to Reproduce

Create an audit of a model that casts a property to `ArrayObject`, and have the `old_values` of the audit include `{"cast_property":null}`. Then call `getModified()`.

#### Possible Solutions
[patch.txt](https://github.com/owen-it/laravel-auditing/files/12526135/patch.txt)

**Comment by parallels999** [comment]
Make a PR
