### ISSUE TITLE
auditSync - writes an empty array when there is no data change

### ISSUE THREAD

**Issue by webdevpetrov** [owen-it/laravel-auditing#859]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10.10
| Package version   | 13
| PHP version       | 8.1

#### Actual Behaviour

Empty array - [] when using auditSync.

When there is no change in auditSync, an empty array is written to the database and fills the table with unnecessary records.
Database:
event: sync
old_values: []
new_values: []

Relationship: $this->belongsToMany(User::class)->withTimestamps();

$image->auditSync('users', $validated['users']);

#### Expected Behaviour

When there is no relationship change and auditSync is executed, do not write anything to the database - it is currently writing an empty array.

#### Steps to Reproduce

Model Relationship: $this->belongsToMany(User::class)->withTimestamps();
View: $validated['users'] - array of ids - should not be changed, just call update again in the controller 
Controller:$image->auditSync('users', $validated['users']);

#### Possible Solutions

Add a check that the old array of ids and new array of ids data match.

**Comment by parallels999** [comment]
> Add a check that the old array of ids and new array of ids data match.

welcoming PRs for us to review 👍

**Comment by erikn69** [comment]
It is an expected behavior, I don't know the reason for this behavior
https://github.com/owen-it/laravel-auditing/blob/7d929c01cad48be1785ae8c7160761d390e2f46b/tests/Functional/AuditingTest.php#L634-L653
