### ISSUE TITLE
Error when saving characters in Spanish

### ISSUE THREAD

**Issue by jlinares-96** [owen-it/laravel-auditing#860]
laravel-auditing works fine, the problem I notice is when saving records with tilde. Better said words in Spanish.
![evidencia](https://github.com/owen-it/laravel-auditing/assets/47828214/43b30bc4-3053-478e-94b9-a4e347209f10)

and in the table: types, it is saved correctly.

![evi2](https://github.com/owen-it/laravel-auditing/assets/47828214/efccea80-44d8-4275-9ca3-4aee0295482c)
how do I solve it?

**Comment by parallels999** [comment]
Check audits table collation

**Comment by jlinares-96** [comment]
> Check audits table collation

where do I check it?

**Comment by parallels999** [comment]
That depends on the tool you are using, and from the screenshot I am sure that we do not use the same one.

**Comment by jlinares-96** [comment]
> That depends on the tool you are using, and from the screenshot I am sure that we do not use the same one.

I am using the package from https://laravel-auditing.com/

**Comment by parallels999** [comment]
You are really lost

>Check table charset, collation

Use google
