### ISSUE TITLE
Record non modified fields

### ISSUE THREAD

**Issue by nicktan147** [owen-it/laravel-auditing#877]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10
| Package version   | 13
| PHP version       | 8.1

I would like to make it record all the fields regardless whether is it modified or not. However now it is only tracking fields that are modified only.

<img width="265" alt="Screenshot 2023-11-27 154833" src="https://github.com/owen-it/laravel-auditing/assets/7764638/6c9aa3ce-3e32-4f62-acf7-9aa75c2dd472">

There are fields like name, country so forth, however due to its current functionality to keep track only what is changed, is there any option or configuration I can change to make it need not to track only fields that are being modified?

**Comment by parallels999** [comment]
That would fill the DB with unnecessary data. 👎

**Comment by parallels999** [comment]
https://github.com/owen-it/laravel-auditing/blob/1a9cc9a442a048f3e41c2a424dc883b6df05103e/src/Auditable.php#L199-L215
You could override `getUpdatedEventAttributes`, It should go through all the attributes, instead of just the dirty ones
