### ISSUE TITLE
Audit is not created when manually triggering the updated event on model

### ISSUE THREAD

**Issue by omerbaskurt** [owen-it/laravel-auditing#878]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 10.23.1
| Package version   | 13.5.1
| PHP version       | 8.2.12

I update a property of a model and `saveQuietly` to not to trigger events on the save. Then, manually fire the update event later. I expect an `update` audit getting triggered but it doesn't. `created`, `restored`, `deleted` events work as expected.

```
$article->title = $newTitle;
$article->saveQuietly();
...
event('eloquent.updated: App\Models\Article', $article);
```

`updated` is included in the audit config file (**audit.php**)
```
'events' => [
        'created',
        'updated',
        'deleted',
        'restored'
],
```

**Comment by parallels999** [comment]
Maybe it's because `update` uses `dirty`, and after saving, `dirty` is empty
Try this  way
```php
$article->title = $newTitle;
event('eloquent.updated: App\Models\Article', $article);
$article->saveQuietly();
```

**Comment by omerbaskurt** [comment]
Thanks, that does the trick. But it kinda defeats the purpose of not firing events on save. We do fire the events after the business logic block. Something like this:

```
$article->title = $newTitle;
$article->saveQuietly();
$events[] = ['updated', 'App\Models\Article', $article];

$user->restoreQuietly();
$events[] = ['restored', 'App\Models\User', $user];

... a bunch of other operations without events while saving event data

// then fire the events
foreach ($events as $event) {
    event('eloquent.' . $event[0] . ': ' . $event[1], $event[2]);
}
```

**Comment by parallels999** [comment]
Did you try `clone` before save??
```php
$article->title = $newTitle;
$events[] = ['updated', 'App\Models\Article', clone $article];
$article->saveQuietly();
```
I can't give you a specific answer if you don't specify the full scenario

**Comment by omerbaskurt** [comment]
Using `clone` on the event works, thank you.
