### ISSUE TITLE
Selects

### ISSUE THREAD

**Issue by ruverd** [owen-it/laravel-auditing#88]
Is It possible to audit select?

**Comment by anteriovieira** [comment]
Can you provide an example of how you would like to do this?

**Comment by ruverd** [comment]
I have an application in modules and I wanna record searches, updates, inserts and deletes in some of this modules. I saw the Trait,  in this file you use the static methods from Eloquent that listen events but doesn't exist event for searches. Then I don't know if I create an event for listen this event and implement in this Trait will work. Other tip you could implement one way to insert manual logs!

**Comment by anteriovieira** [comment]
Hi @ruverd , if you have a sample code would be good.

You can manually inserts:

```php
use OwenIt\Auditing\Log;

$log = new Log();
$log->old_value   = ['values'];
$log->new_value   = ['values'];
$log->owner_type  = \App\User::class;
$log->owner_id    = 1;
$log->type       ='updated'

$log->save();

```

Tell me if this can help for now. I will implement the improvements suggested by you

Feel free to send us a pull request.

**Comment by anteriovieira** [comment]
Hello @ruverd ,

Had any progress?
