### ISSUE TITLE
The [sync] queue connection has not been configured.

### ISSUE THREAD

**Issue by alvaronds** [owen-it/laravel-auditing#880]
| Q                 | A
| ----------------- | ---
| Bug?              | Don't know
| New Feature?      | Think yes
| Framework         | Laravel
| Framework version | 10.37.3
| Package version   | 13.6.0
| PHP version       | 8.2

#### Actual Behaviour

I don't want to use queues to add the audits to database. Since updated to 13.6.0, if I don't modify config file I get this error:
The [sync] queue connection has not been configured.
If I put a valid queue connection it works but uses queues, wich makes much database use for my app.

#### Expected Behaviour

I need direct execution as before. I think I have all well configurated.

#### Steps to Reproduce

Update to package version 13.6.0 and have this in audit.conf
'queue' => [
        'connection' => 'sync',
        'queue'      => 'default',
        'delay'      => 0,
    ],

Update a model

**Comment by MortenDHansen** [comment]
Do you have the connection in the queue.php config file?
`
    'connections' => [

        'sync' => [
            'driver' => 'sync',
        ],
`

**Comment by MortenDHansen** [comment]
#846

**Comment by erikn69** [comment]
@MortenDHansen It would be a good idea to add some option for those who do not want/can't use queue. #881

**Comment by MortenDHansen** [comment]
We have released the opt-in version of v13.6.0. Hope that solves the issue 👍

**Comment by alvaronds** [comment]
Thanks a lot for the responses and solution. It's resolved.
