### ISSUE TITLE
Enabling queue causes Unable to JSON encode payload. Error (5)

### ISSUE THREAD

**Issue by danharper83** [owen-it/laravel-auditing#885]
After updating to the latest version it seems that the queue is automatically enabled. 

This caused all my auditable models to stop saving and return this error:

`Unable to JSON encode payload. Error (5): Malformed UTF-8 characters, possibly incorrectly encoded {"userId":1,"exception":"[object] (Illuminate\\Queue\\InvalidPayloadException(code: 0): Unable to JSON encode payload. Error (5): Malformed UTF-8 characters, possibly incorrectly encoded at /app/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:109)`

Publishing the config and setting the queue to false solves the issue but it's not clear why this is happening.

laravel/framework v10.38.1
owen-it/laravel-auditing v13.6.3

Thanks Dan

**Comment by parallels999** [comment]
Your json is not utf-8, check db encoding, json encoding

**Comment by danharper83** [comment]
The database is `utf8_unicode_ci`

Everything works as expected when the queue is turned off, the audits are written to the audit table correctly.

**Comment by parallels999** [comment]
Difficult to reproduce without the model to verify what data the malformed UTF-8 has, if you can upload an example in a clean installation showing the problem it would be very helpful

**Comment by djibrilcolynat** [comment]
I just opened an issue for the same reason. Guys, something broke in new updates. I reverted to version 13.5.1 and things went back working fine. I used binary uuid (Dyryndra/laravel-efficient-uuid), but I notice that the "Malformed character" error comes from the fact that binary uuid in models are not longer casted into string using the custom caster I provided in attributedMotifiers property. So trying to encode bytes in JSON will result in a "Malformed character" error

**Comment by parallels999** [comment]
https://github.com/owen-it/laravel-auditing/issues/884#issuecomment-1866373894

**Comment by parallels999** [comment]
Could you try #893

**Comment by djibrilcolynat** [comment]
@parallels999  It didn't work either. Have to temporarily stick to v13.5.1 in production.

**Comment by MortenDHansen** [comment]
I have released 13.6.4 where the queue feature is disabled by default (as it should have been, sorry). I expect avoiding the serialization for queue should mitigate the problem. If not, let me know and stick to v13.5.1 in production.
