### ISSUE TITLE
Audit excludes fields records are creating in table

### ISSUE THREAD

**Issue by iamnoorsk** [owen-it/laravel-auditing#886]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 9.0
| Package version   | 12.0
| PHP version       | 8.2.13

#### Actual Behaviour
I exclude two columns `last_login, remember_token` in User Model and try to login after login i check audit table there i see both (old_values, new_values) columns empty record created
![image](https://github.com/owen-it/laravel-auditing/assets/89458293/63f2e7e4-af9e-4b9a-a397-b50671dc379c)
![image](https://github.com/owen-it/laravel-auditing/assets/89458293/8065164e-34dd-4b28-b880-60780fd2efdb)

#### Expected Behaviour
if (old_values,new_values) columns is empty then record shouldn't be created

#### Steps to Reproduce

List **all the steps** needed to reproduce the issue you're having.

Make sure to **include code** (affected models, configuration, ...).

Pastebins, screenshots and/or other resources that may help us understand what's going on, will also be appreciated.

In a nutshell, help us, help you.

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by parallels999** [comment]
Problems reading settings?
https://github.com/owen-it/laravel-auditing/blob/66498a9cfa23dc1b34601dfb74ef691772eca800/config/audit.php#L91-L104

**Comment by iamnoorsk** [comment]
> Problems reading settings?
> 
> https://github.com/owen-it/laravel-auditing/blob/66498a9cfa23dc1b34601dfb74ef691772eca800/config/audit.php#L91-L104

:sweat_smile:

**Comment by parallels999** [comment]
Problems updating previous versions? 😄😄😄
