### ISSUE TITLE
No audits when updated by another function?

### ISSUE THREAD

**Issue by drickferreira** [owen-it/laravel-auditing#89]
I'm using Auditing trait, is working very well...

I have another function that updates data from this model running on background.

the code:
```
$command = CommandXML::where('id_command', xmlGetVal($xml,'ID_COMMAND'))->first();
$command->response =  '...';
$command->save();
```

In this case, the changes are not auditing.

**Comment by anteriovieira** [comment]
Hello @drickferreira ,

I am studying it, including already have discussions on this subject. The auditing package depends on the eloquent events.

https://github.com/laravel/framework/issues/14427#issuecomment-245044768
