### ISSUE TITLE
The events (DispatchAudit) are missing the SerializesModels trait

### ISSUE THREAD

**Issue by mjawad096** [owen-it/laravel-auditing#890]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 10.38.1
| Package version   | 13.6.3
| PHP version       | 8.2.13

#### Actual Behaviour

The constructor of the model is not being called for a queued audit event. As I'm initializing a protected property in the constructor. So, as the contractor is not called that property is never initialized. 

This is due to, the `OwenIt\Auditing\Events\DispatchAudit` listener missing the `Illuminate\Queue\SerializesModels` trait which results in a large payload for the queue. Also without this, the models are just hydrated/unserialized without calling the construct. Which also makes an issue for me. As I'm initializing a protected property in the constructor. So, as the contractor is not called that property is never initialized.

#### Expected Behaviour
The model should be hydrated from the database instead of just unserializing from the job payload.

#### Steps to Reproduce
Create an auditable model with a constructor to perform some action. .e.g. to initialize a protected model property. 
Then perform some action on model create/update. 
You'll notice that the constructor is not called.

#### Possible Solutions
Please use the `Illuminate\Queue\SerializesModels` trait for both events or at least for `OwenIt\Auditing\Events\DispatchAudit`.

**Comment by parallels999** [comment]
https://github.com/owen-it/laravel-auditing/issues/884#issuecomment-1866373894

**Comment by mjawad096** [comment]
I already check this config. But I want to use the queue. For now, I manage it by modifying the serialization's magic method but it does not seem a proper solution. So, it will be appreciated if the `SerializesModels` trait can be added to the events.

![image](https://github.com/owen-it/laravel-auditing/assets/28442413/313c81ee-196b-4626-8934-1c85ecd869a9)

**Comment by parallels999** [comment]
Question; with that, wouldn't the `dirty`  be lost in case of `updating` event?

**Comment by cangelis** [comment]
This is also causing Sanctum tests to fail with the error below after upgrading to the latest version of the package.

```
ErrorException: serialize(): Mockery_1_Laravel_Sanctum_PersonalAccessToken::__sleep() should return an array only containing the names of instance-variables to serialize
```

Example code:

```php
Sanctum::actingAs($user = User::factory()->create());

// Account is auditable
Account::factory()->for($user)->create();
```

I can confirm that using `SerializesModels` trait within `OwenIt\Auditing\Events\DispatchAudit` solves the issue.

For the ones that have this issue should either downgrade or disable the queueing audits by setting `audit.queue.enable` to `false`

**Comment by parallels999** [comment]
> I can confirm that using SerializesModels trait within OwenIt\Auditing\Events\DispatchAudit solves the issue.

>wouldn't the dirty be lost in case of updating event?

@cangelis hi, can you confirm my question?

**Comment by parallels999** [comment]
> Question; with that, wouldn't the `dirty` be lost in case of `updating` event?

Could you test that?

**Comment by cangelis** [comment]
the dirty values will get lost once a job with `SerializesModels` is pushed to the queue as the model is retrieved from the database in the process of restoring the model so the `DispatchAudit` event should also contain the dirty and the original values seperately instead of using the model as a container.

**Comment by angeljqv** [comment]
Feel free to make a PR fixing it

**Comment by parallels999** [comment]
There are other properties that would be lost besides `auditEvent`, I don't see it as possible, example `auditExclude`
https://github.com/owen-it/laravel-auditing/blob/66498a9cfa23dc1b34601dfb74ef691772eca800/tests/Functional/AuditingTest.php#L534-L539

**Comment by parallels999** [comment]
>the dirty values will get lost once a job with SerializesModels is pushed to the queue as the model is retrieved from the database in the process of restoring the model so the DispatchAudit event should also contain the dirty and the original values seperately instead of using the model as a container.

@cangelis, you seem to understand the problem well, please review #893
