### ISSUE TITLE
Duplicate entries for every action

### ISSUE THREAD

**Issue by K-Neu-Projects** [owen-it/laravel-auditing#896]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.0
| Package version   | 13.6
| PHP version       | 8.0

#### Actual Behaviour

The audits table creates two identical entries for every action. 

#### Expected Behaviour
I'd expect a single entry for every action.

#### Steps to Reproduce
I'm using the default configuration for the most part except the table name. That I changed to 'auto_audits'.
Also since its Laravel 8 I did not explicitly register the ` OwenIt\Auditing\AuditingServiceProvider::class`. 

```
use OwenIt\Auditing\Auditable as AuditingAuditable;
use OwenIt\Auditing\Contracts\Auditable;

class MyModel extends Model implements Auditable
{
    use CamelCaseAttributes;
    use AuditingAuditable;
...
```

 I checked the query output using `DB::enableQueryLog` and `DB::getQueryLog` which shows 1 Update query and 2 inserts into the audits table with the same values.

#### Possible Solutions

Does the autoload somehow cause the event to be fired twice? Thats my only idea based on my findings.

**Comment by K-Neu-Projects** [comment]
But how?
Im not registering it manually at all.
I tried explicitly listing it in the `app/config.php` providers but the result is the same.

**Comment by angeljqv** [comment]
> Im not registering it manually at all.

It is automatic

> I tried explicitly listing it in the `app/config.php` providers

Worst

**Comment by K-Neu-Projects** [comment]
Will do so, thanks for the input

**Comment by K-Neu-Projects** [comment]
So, I tried some stuff,
- Updated to Laravel 9 -> no change
- Reinstalled the lib -> no change
- setup test project -> works fine 

Even after I removed the registration of the `AuditingEventServiceProvider` in the package, I still got 2 entries. Still puzzles me a bit since I expected none after that. 

But yeah, as mentioned, some issue with the project so this can be closed.
thanks again for the input though!

**Comment by K-Neu-Projects** [comment]
Alright after debugging the issue for quite some time I noticed that the Auditing event was fired twice for every send.

The issue was the booted method in the model:

``` php
class MyModel extends Model implements Auditable
{
    use CamelCaseAttributes;
    use AuditingAuditable;

    protected static function booted()
    {
        static::addGlobalScope(new CustomScope());

        parent::booted(); // this line is the issue
    }
...
```
The `Auditable` trait was initialized twice since the laravel Model which is my base class recursivly initializes the traits on the class in its `booted()` method. This causes 2 `auditing` events and therefor 2 db entries.

Fix was to remove the `parent::booted();` line completly since the constructor of the laravel Model::class is enough to set everything up.
