### ISSUE TITLE
Log - messages

### ISSUE THREAD

**Issue by ecmattos** [owen-it/laravel-auditing#9]
@devthiagolino
Os meus logs aparecem assim:

user.name atualizou os dados de SANTA CATARINA1
De: old.uf -> Para: new.uf updated in 2015-10-02 02:33:45
De: SANTA CATARINA -> Para: SANTA CATARINA1 updated in 2015-10-02 02:33:45
user.name atualizou os dados de SANTA CATARINA
De: old.uf -> Para: new.uf updated in 2015-10-02 11:01:41
De: SANTA CATARINA1 -> Para: SANTA CATARINA updated in 2015-10-02 11:01:41

2 duvidas por mais obvias pois estou comecando a utilizar o laravel:
1) Por que ao inves do nome do usuario aparece user.name ? Tenho que fazer um relacionamento das tabelas logs e users ?
2) Como suprimir os logs onde old.campo e new.campo são nulos ?

**Comment by anteriovieira** [comment]
Bom dia @ecmattos 

Você pode personalizar as mensagens de resposta fazendo conforme descreve [aqui](https://github.com/owen-it/laravel-auditing#apresentando-log).

O user.name aparece justamente porque não foi encontrada a propriedade name no objeto user, verifique se seu registro de log comtém um usuário vinculado. Este é o usuário responsável pela alteração do registro auditado, o mesmo é vinculado caso esteja logado, o contrário o campo user fica como null e user.name irá aparecer na sua mensagem personalizada. Vou implementar a possibilidade de adicionarmos valores defaults para esta situação.

Realmente os camos nulos não são omitidos das mensagens de logs, essa é uma melhoria que pretendo adicionar ainda esta semana.

**Comment by ecmattos** [comment]
@anteriovieira 
Oi !
Obrigado pelo retorno !
A minha tabela user já possui o id 1 e o name correspondente ecmattos.
Eu não preciso fazer o relacionamento entre as tabelas users e logs ?

**Comment by ecmattos** [comment]
@anteriovieira, Quanto a omissão das mensagens de logs quando os old.campo e new.campo são nulos , seria apenas uma modificação no arquivo auditing.blade.php ?

**Comment by anteriovieira** [comment]
@ecmattos , não precisa fazer o relacionamento do log com o user, este relacionamento já esta presente no model log com o trecho de código a seguir:

```php
    public function user()
    {
        return $this->belongsTo(\Config::get('auth.model'));
    }
```
> Agora uma coisa que temos que ficar atento é definir corretamente o model do usuário no arquivo de configuração ``` config\auth.php ```, pois precisamos saber qual é o model do usuário que temos que relacionar.

Agora se você quiser buscar todos os logs registrados por um usuário X fazendo ``` $user->logs ```, ai sim você precisaria relacionar, neste caso poderia fazer assim:

```php
use OwenIt\Auditing\Auditing;
use OwenIt\Auditing\Log;
class User extends Auditing 
{
        // ...
	public function logs()
	{
		return $this->hasMany(Log::class, 'user_id');
	}
}
```
Quanto a omissão dos campos nulos, não temos um template auditing.blade para as mensagens, vou ter que alterar a lógica na hora de montar as mensagens. Uma outra ideia futura é adicionar um aquivo de config para caso o desenvolvedor queira alterar funcionalidades padróes do pacote.

**Comment by ecmattos** [comment]
@anteriovieira 
O arquivo pelo qual me referia era o seguinte:

 // resources/views/my-app/auditing.blade.php
    ...
    <ol>
        @forelse($logs as $log)
            <li>
                {{ $log->customMessage }}
                <ul>
                    @forelse($log->customFields as $field => $message)
                        <li>{{ $message }}</li>
                    @endforelse
                </ul>
            </li>
        @empty
            <p>No logs</p>
        @endforelse
    </ol>
    ...

**Comment by ecmattos** [comment]
@anteriovieira 
meu config/auth.php está assim

/*
    |--------------------------------------------------------------------------
    | Authentication Model
    |--------------------------------------------------------------------------
    |
    | When using the "Eloquent" authentication driver, we need to know which
    | Eloquent model should be used to retrieve your users. Of course, it
    | is often just the "User" model but you may use whatever you like.
    |
    */

    'model' => App\User::class,

    /*
    |--------------------------------------------------------------------------
    | Authentication Table
    |--------------------------------------------------------------------------
    |
    | When using the "Database" authentication driver, we need to know which
    | table should be used to retrieve your users. We have chosen a basic
    | default value but you may easily change it to any table you like.
    |
    */

    'table' => 'users',

**Comment by ecmattos** [comment]
@anteriovieira Desconsidere a minha informacao anterior.
Resolvido conforme a tua dica.

Obrigado.

**Comment by anteriovieira** [comment]
Seu model ```User``` esta conforme sua configuração?
``php
'model' => App\User::class,
```

**Comment by ecmattos** [comment]
@anteriovieira 
meu config/auth.php está assim

/*
|--------------------------------------------------------------------------
| Authentication Model
|--------------------------------------------------------------------------
|
| When using the "Eloquent" authentication driver, we need to know which
| Eloquent model should be used to retrieve your users. Of course, it
| is often just the "User" model but you may use whatever you like.
|
*/

'model' => App\User::class,

/*
|--------------------------------------------------------------------------
| Authentication Table
|--------------------------------------------------------------------------
|
| When using the "Database" authentication driver, we need to know which
| table should be used to retrieve your users. We have chosen a basic
| default value but you may easily change it to any table you like.
|
*/

'table' => 'users',

**Comment by ecmattos** [comment]
Pensei que tivesse resolvido mas continua aparecendo {user.name} nos logs.

**Comment by anteriovieira** [comment]
Removas os registros de logs do banco e tente fazer novas modificações para testar. Estou criando uma aplicação aqui para testar também. Quanto as configurações acredito que estejam certas, pois não foi retornado nenhum erro de model not found.

**Comment by ecmattos** [comment]
@anteriovieira Nao sei se pode ser isso que está causando o problema:
Estou com problema na minha autenticacao que ainda vou resolver mas os dados do id 1 da tabela users estao todos preenchidos.
Ao registrar os logs, o user_id vem como NULL como disseste anteriormente.
Eu edito o campo user_id de NULL para 1 e deveria funcionar normalmente ?
Vou limpar os logs.

**Comment by anteriovieira** [comment]
Sim deveria, vou testar aqui e te dou um retorno

**Comment by ecmattos** [comment]
ok

**Comment by ecmattos** [comment]
@anteriovieira 
Limpei e continua {user.name} !

**Comment by ecmattos** [comment]
@anteriovieira 
Para ir pensando numa atualizacao (seria bem legal pois nao encontrei nada ainda):

Nas mensagens de logs, para os campos com relacoes em outras tabelas, deveria mostrar a informacao do relacionada ao campo correspondente.

Exemplo:
Alterei a categoria de um produto (de TV para Celular).
Na tebela logs, efetuará o registro do log da category_id de 1 para 2 mas na mensagem do log deveria mostrar de "TV" para "Celular" (textos) e nao os valores do campo.

Nao sei se de repente associar tambem:
protected $doKeepLogOf    = ['description', 'category_id']; // Informe os campos que deseja registrar no log.
protected $do????????    = ['description ???', 'categories.id']; // Informe os campos que deseja relacionar no log.

Nao sei se me entendeste ?

**Comment by empty** [comment]
Why are you emailing me?

**Comment by ecmattos** [comment]
@empty I dont know !

**Comment by empty** [comment]
:)

**Comment by anteriovieira** [comment]
@empty , you was mentioned in one of the comments, you can leave this issue, we will be more careful in the comments.

**Comment by ecmattos** [comment]
@anteriovieira 
Pensei que tinha sido culpa minha !

**Comment by anteriovieira** [comment]
rsrsrs pior que foi @ecmattos , foi no comentário que você adicionou sobre o auditing.blade, mas já editei pra não referenciar mais nosso amigo empty. Coloquei ``` para encapsular o código.

**Comment by anteriovieira** [comment]
É uma fazermos isso quando postar exemplos de código. Fazemos isso com [Markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by ecmattos** [comment]
Puts !
Obrigado !

**Comment by ecmattos** [comment]
Desculpa !

**Comment by anteriovieira** [comment]
rsrsr tranquilo.

**Comment by ecmattos** [comment]
Tambem o cara coloca o user dele de "@empty" igual a funcao do blade !

Rsrsrsrsr

**Comment by ecmattos** [comment]
@anteriovieira 
Incluí ele de novo ?

**Comment by anteriovieira** [comment]
kkkkkkkk sim

**Comment by anteriovieira** [comment]
Sim, sempre que você colocar @ecmattos , vai estar mencionando alguém.

**Comment by ecmattos** [comment]
@anteriovieira 
Agora para ele sair devo editar colocando ´´´ antes e depois do usuario dele no meu comentario acima ? e depois avisar ele para sair ?

**Comment by anteriovieira** [comment]
Esquenta não, faz o sequinte estou fechando este issue, dai você abre outro com a nossa questão em principal.
