### ISSUE TITLE
Implement support for Laravel 11.x.

### ISSUE THREAD

**Issue by brunobacha** [owen-it/laravel-auditing#907]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 11.x
| Package version   | -
| PHP version       | 8.2 / 8.3

#### Actual Behaviour

Currently, the project does not support Laravel version 11.x.

#### Expected Behaviour

We expect the project to support Laravel version 11.x.

#### Steps to Reproduce

None

#### Possible Solutions

Implement support for Laravel 11.x.

**Comment by parallels999** [comment]
#905, already done, just needs review

**Comment by weirdlooop** [comment]
Any movement on this @erikn69 - can this be merged?
