### ISSUE TITLE
How can i set $dateFormat to log eloquent model?

### ISSUE THREAD

**Issue by thiagoaos** [owen-it/laravel-auditing#91]
Hi,

In all my models i use created_at and update_at with timestamp with timezone.
I change too the Logs migration to use timestamp with time zone.
But how can i set $dateFormat in Log Model to 
protected $dateFormat = 'Y-m-d H:i:sO';

?

**Comment by anteriovieira** [comment]
Hello @thiagoaos ,

Many people have asked me how to customize the log template. I'm working on version 3.0 and will provide this feature.

We will have the concept of auditor in version 3.0. You can use the native auditor of the package or if you prefer to create their own auditors.
