### ISSUE TITLE
Laravel Audit breaks Events Auto Discovery 

### ISSUE THREAD

**Issue by AbdullahALT** [owen-it/laravel-auditing#924]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 11.5.0
| Package version   | 13.6
| PHP version       | 8.2 

#### Actual Behaviour

Laravel's event auto discovery breaks after installing laravel-aduit

#### Expected Behaviour

Events should still be auto discovered, installing Laravel Audit shouldn't affect that

#### Steps to Reproduce
you can reproduce this on a fresh laravel project
- Create a new Laravel Project
``` 
composer create-project laravel/laravel example-app
```
- Create an event 
```
php artisan make:event ProductOrdered
```
- Create a Listener
```
php artisan make:listener PrintMessage --event=ProductOrdered
```
- Check if the event is discovered or not
```
sail artisan event:list | grep App 
```
result: discovred
```
App\Events\ProductOrdered ..................................................App\Listeners\PrintMessage@handle 
```
- now install laravel-audit
```
 composer require owen-it/laravel-auditing
```
- Check if the event is discovered or not again
```
sail artisan event:list | grep App 
```
result: empty result, event is not discovered

**Comment by parallels999** [comment]
- #916
