### ISSUE TITLE
Extra fields to log?

### ISSUE THREAD

**Issue by gsc89** [owen-it/laravel-auditing#93]
Hi There I have an app that has user_id's which work as expected fine but many of these accounts are shared and as a unique identifier the system uses pin-codes which are unique to a user and are used when performing deletes on the system.

Could you advise where I might do an extension to include this as a null-able field in the logs?

**Comment by anteriovieira** [comment]
Hello @gsc89 ,

There is no way to do this for now. But I'm working on a refactoring to version 3.0 and I'll think about it.

**Comment by gsc89** [comment]
OK no worries I will need to use something else so no point doing this on my account.

I will have to find a workable solution using something else. 

Thanks for clarifying though.

**Comment by gsc89** [comment]
Hi @anteriovieira I forked and added that specific feild I wanted myself, I basically used a session to store the feild I needed which was allowed to be null so if it wasn't set for some actions it wouldn't be stored / cause an issue, just wanted to thank you for the code you wrote. 

Thanks!
