### ISSUE TITLE
Custom types or sub types

### ISSUE THREAD

**Issue by sabrio** [owen-it/laravel-auditing#94]
Is there away of adding custom type instead of [created, saved, deleted]? Or better would be adding category/subtype field and categorize your logs?

**Comment by anteriovieira** [comment]
Hello @sabrio ,

you can give me an example of what needs

**Comment by sabrio** [comment]
I have reservation system and in one particular reservation we have a lots of updates and I want to show some of them and ignore the rest, for e.x: my client what to see only who changed the status/price and not the rest. 
You got me?

**Comment by anteriovieira** [comment]
I understood,

You can add in your model that you want to audit:

```php
    // Fields that you do NOT want to register.
    protected $dontKeepLogOf = ['created_at', 'updated_at'];

    // or 

    // Fields that you do want to register.
    protected $keepLogOf = ['status', 'price '];
```

[Documentation](http://laravel-auditing.herokuapp.com/docs/2.4/configuration)

This helps you?

**Comment by sabrio** [comment]
hmmmmm maybe it will help but what exactly I need is this:
`protected $auditableTypes = ['created', 'saved', 'status_changed'];

    public static $logCustomFields = [
        'message' => [
            'created' => '{user.first_name|Anonymous} {type} the reservation {elapsed_time}',
            'status_changed' => '{user.first_name|Anonymous} changed the status from {old.status} to {new.status} on {updated_at}',
        ]
    ];`

**Comment by anteriovieira** [comment]
But auditable type are the events that the eloquent fires, you would like to add another event? (e.g: status_changed).

You can create a Trait and add to your model extending audit resources.

```php

namespace Path\To\Traits

trait StatusChanged {

    public function bootStatusChanged (){
        static::saved(function ($model) {
            if ($model->isTypeAuditable('status_changed')) {
                $model->auditStatusChanged();
            }
        });
    }

    public function auditStatusChanged()
    {
        if ($this->isAuditEnabled()) {
            $log = ['new_value' => null, 'old_value' => null];
            foreach ($this->updatedData as $key => $value) {
                if ($this->isAuditing($key)) {
                    $log['new_value'][$key] = $value;
                }
            }
            $this->audit($log, 'status_changed');
        }
    }

}

    // In your model

    use Illuminate\Database\Eloquent\Model;
    use OwenIt\Auditing\AuditingTrait;
    use Path\To\Traits\StatusChanged;

   class User extend Model {

        use AuditingTrait, StatusChanged ;

        protected $auditableTypes = ['created', 'saved', 'status_changed'];

        public static $logCustomFields = [
            'message' => [
                'created' => '{user.first_name|Anonymous} {type} the reservation {elapsed_time}',
                'status_changed' => '{user.first_name|Anonymous} changed the status from {old.status} to    {new.status} on {updated_at}',
              ]
        ];
   }

```

**Comment by sabrio** [comment]
Seems like I don't need to create another event, at least I don't see any reason doing that but I thing to create another field inside the table logs[category|subtype] and being able to address logs with it like:
` $reservation->logType('someType')->save() ` and also I will need something like this:

````
public static $logCustomFields = [
            'message' => [
                'someType' => '{user.first_name|Anonymous} changed the status from {old.status} to    {new.status} on {updated_at}',
              ]
        ];
````
What do you say?

**Comment by anteriovieira** [comment]
I'm going by another way. Version 3.0 is coming with a big refactoring. I'm working on updating documentation, now will better incorporate the concept of audit allowing the creation of auditors. The auditors are responsible for maintaining the model changes, and you can even create and customize their auditors as desired.

```php
namespace App\Auditors;

class MyAuditor 
{
    public audit($auditable){
        // Audit as you prefer, use another model if you prefer 
        // or any other audit method.
    }
}
```


```php
namespace App;

use App\Auditors\MyAuditor;
use OwenIt\Auditing\Auditable;
use Illuminate\Database\Eloquent\Model;

class Reservation extends Model 
{
    use Auditable;
    
    //  My Auditor
    protected $auditors = [MyAuditor::class];
}

```

If you omit the `$auditors` attribute, by default auditing will use `DatabaseAuditor` and record the data using the native model. You can also specify various auditors now.

`$auditors = ['database', 'notification', MyAuditor::class, FileAuditor::classs, ...]`

During the audit process, a review event is fired before the audit and report event after the audit.

#### Before: `AuditReview`

The event will contain:
* Auditable model
* Auditor

#### After: `AuditRepor`

The event will contain:
* Auditable model
* Auditor
* Audit Report


What do you think about this?

**Comment by sabrio** [comment]
This is cool and yes, somebody should update the docs, that would be awesome to. Thanks anyway @anteriovieira and please close the issue if you dont have something to add :)

**Comment by anteriovieira** [comment]
@sabrio, would you like to help me with the documentation?

I'll probably take longer to upgrade because my English is basic.

**Comment by sabrio** [comment]
My English is under basic :D My skills are below 0 for writing and explaining things, I cant even write correctly in my native language. I am so sorry to say it(fresh example: It took me about 5 mins to write this comment)

**Comment by anteriovieira** [comment]
It's all right 😉
