### ISSUE TITLE
Audited logs deleted on fresh install with threshold set to > 0

### ISSUE THREAD

**Issue by neil-cldagency** [owen-it/laravel-auditing#947]
### PHP Version

8.3

### Laravel Version

11.x

### Package Version

13.6.7

### Description

Hi there, firstly thanks for the great package!

I'm not sure if this is something I'm doing or what, but I've just installed a fresh copy, followed the instructions to the letter, and it was refusing to keep audit log entries when I'd tried saving in the following manners:

- Via "save" buttons in Filament PHP
- Via tinker `->save()` method on a model instance (with `console` set to `true` in the config)

I'd stopped short of making a custom controller just to test this, as I had added the following to my model:

```php
/**
 * The "booted" method of the model.
 */
protected static function booted(): void
{
    static::updated(function (Property $property) {
        dump('updated', $property);
    });
}
```

And that dump was coming through on the above save methods.

I'd also added an event listener for `OwenIt\Auditing\Events\Auditing` which was dumping out each time I tried the above save methods as well.

It wasn't until I'd set the `threshold` option back to `0` (from my preference of `100`) that it started actually logging anything.

I've tested this with the threshold at various values and it seems that the prune method might have a bug in it as when the value is anything other than `0`, the entire log for that model (and only that model instance, it seems) is removed on each audit event.

### Steps To Reproduce

- Install auditing tool
- Configure as normal
- Create at least one auditable model
- Set threshold to anything other than 0
- Trigger an update/create etc event

**Comment by parallels999** [comment]
There are tests for that functionality, 
https://github.com/owen-it/laravel-auditing/blob/22682dd5c800aab90ef261530098625e26a66709/tests/Functional/AuditingTest.php#L292-L310

Could you debug the delete query?
https://github.com/owen-it/laravel-auditing/blob/22682dd5c800aab90ef261530098625e26a66709/src/Drivers/Database.php#L25-L30

**Comment by jamiewatsonuk** [comment]
I have the same issue when using this package in my development setup.

When running 13.6.5 (as mentioned above), the threshold appears to work as expected.  In the latest version, setting the threshold to anything other than 0, removes all audits for the model being audited.

I see that the tests pass when I check out master to my dev environment.  Changing the test driver from `sqlite` to `mysql` causes this issue to present itself in the test as well.

```
There was 1 failure:

1) OwenIt\Auditing\Tests\Functional\AuditingTest::itWillRemoveOlderAuditsAboveTheThreshold
Failed asserting that 0 is identical to 10.
```

**Comment by parallels999** [comment]
[src/Illuminate/Database/Query/Grammars/MySqlGrammar.php#L117-L145](https://github.com/laravel/framework/blob/202422d4e6d91fbc301c8f3501f37c58b4fc5326/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php#L117-L145)
Apparently offset has problems when MySql is less than `8.0.11`, but with `8.1` that should not happen
Needs more research, maybe it's a Laravel bug
If you have any idea how to solve it, open a PR

**Comment by erikn69** [comment]
Hi, try #948

**Comment by neil-cldagency** [comment]
Apologies @parallels999 — I've been away on business for a few days and didn't have much time to answer this. Looks like there's a promising PR in the pipeline however, so thanks to @erikn69  / @jamiewatsonuk for their contribs 👍

**Comment by rebbieboi** [comment]
+1 can confirm this is an issue if you have a threshold set after the latest update

**Comment by parallels999** [comment]
>can confirm this is an issue

That has already been established, waiting for someone to confirm that the fix works

**Comment by christian-zippin** [comment]
+1 Confirmed that it is a problem if you have a threshold set after v13.6.5.
For now, I set my composer.json to v13.6.5 to make it work.

**Comment by erikn69** [comment]
>can confirm this is an issue

That has already been established, waiting for someone to confirm that the fix works
