### ISSUE TITLE
https://laravel-auditing.com/ is not accessible

### ISSUE THREAD

**Issue by davidjr82** [owen-it/laravel-auditing#952]
### PHP Version

NA

### Laravel Version

NA

### Package Version

NA

### Description

Website is not accesible:

![image](https://github.com/owen-it/laravel-auditing/assets/4275886/2996c1ce-a297-49c2-940c-56971bb80b78)

### Steps To Reproduce

Open https://laravel-auditing.com and check the Netlify error - 404 Site Not Found

**Comment by parallels999** [comment]
Until while you can use this [laravel-auditing.com/guide/documentation.md](https://github.com/owen-it/laravel-auditing.com/blob/main/docs/guide/documentation.md)

**Comment by lunavalos** [comment]
the /guide/documentation.md is not accessible either

**Comment by lunavalos** [comment]
> Until while you can use this [laravel-auditing.com/guide/documentation.md](https://github.com/owen-it/laravel-auditing.com/blob/main/docs/guide/documentation.md)

The /guide/documentation.md is not accessible either :c

**Comment by parallels999** [comment]
It seems that you did not check 😄😄

In the bar on the left, there you can see all the titles

![image](https://github.com/owen-it/laravel-auditing/assets/109294935/5776f076-c1f2-4482-a006-75446d4324c0)
