### ISSUE TITLE
Incorrect user associated with audit when changing users dynamically

### ISSUE THREAD

**Issue by dariusvelavicius** [owen-it/laravel-auditing#953]
### PHP Version

8.1

### Laravel Version

8.x

### Package Version

13.6.8

### Description

Hello guys,

When changing user on-the-fly and performing a few changes on the same model, all audits have the same associated user because of this change - https://github.com/owen-it/laravel-auditing/commit/66498a9cfa23dc1b34601dfb74ef691772eca800#diff-682a5b02fc6acf79eda6201541882897f0f0a3fca0d35f02e3398021fd77c63eR368-R372

Is there a reason why the user is always preloaded? Can we discuss an approach where it would be possible to control when the user should be preloaded and when it should be re-resolved?

### Steps To Reproduce

- Set up Auditable for any model
- On the same request:
  - Update the model
  - Dynamically change the user (`Auth::setUser()`)
  - Update the model some more

**Comment by erikn69** [comment]
>because of this change - https://github.com/owen-it/laravel-auditing/commit/66498a9cfa23dc1b34601dfb74ef691772eca800#diff-682a5b02fc6acf79eda6201541882897f0f0a3fca0d35f02e3398021fd77c63eR368-R372

- #883 is a correction of #846 breaking changes

> Is there a reason why the user is always preloaded?

You could ask the author of that change, maybe he or she will give you an answer.
You could also clear that variable to return to the old operation.

**Comment by parallels999** [comment]
>>Dynamically change the user (`Auth::setUser()`)

Why??
Are you doing some type of impersonalization? _like [404labfr/laravel-impersonate](https://github.com/404labfr/laravel-impersonate)_

**Comment by willpower232** [comment]
If you have multiple users within a single request to your code doing auditable activity as well as changing users, it would probably be easier to make use of [transformAudit](https://github.com/owen-it/laravel-auditing/blob/28ecd2d5cc05c3619f99af42611877f54371af20/src/Auditable.php#L358C21-L358C35) rather than rely on observers which won't match your particular use case
