### ISSUE TITLE
Should getMorphClass be used? Issue with auditing Bouncer package

### ISSUE THREAD

**Issue by veodko** [owen-it/laravel-auditing#961]
### PHP Version

8.3

### Laravel Version

11.10.0

### Package Version

13.6.8

### Description

When using Bouncer package for roles and using custom role model like so:
```php
use Silber\Bouncer\Database\Role as BouncerRole;
use OwenIt\Auditing\Contracts\Auditable;

class Role extends BouncerRole implements Auditable
{
}

// In AppServiceProvider
\Bouncer::useRoleModel(\App\Models\Role::class);
```

changes made to the role model (I allow creation & assignment of custom roles) are audited with following `auditable_type`: `roles` like so:
|id|user_type|user_id|event|auditable_type|auditable_id|old_values|new_values|url|ip_address|user_agent|tags|created_at|updated_at|
|--|---------|-------|-----|--------------|------------|----------|----------|---|----------|----------|----|----------|----------|
|6|App\Models\User|1|updated|roles|2|{"name":"test2"}|{"name":"test"}|http://localhost/roles/2|172.20.0.1|...||2024-07-26 13:58:06.000|2024-07-26 13:58:06.000|

This is because using a custom model in Bouncer updates the morh mapping and `toAudit` in `Auditable.php` uses `getMorphClass`:
```php
    'auditable_type'       => $this->getMorphClass(),
```

Is this by design, shouldn't the `auditable_type` always be an absolute namespaced name of the edited model class?

### Steps To Reproduce

Use Bouncer package with custom Role/Ability model and make it auditable, or use `Relation::morphMap` on any other model.

### Possible Solutions

`$this->getMorphClass()` could be replaced with `get_class($this)` which returns the namespaced class name correctly in my case, but maybe there is some specific reason behind using `getMorphClass()` that I do not know about.

**Comment by parallels999** [comment]
You could overwrite `getMorphClass`
```php
public function getMorphClass(){
    return get_class($this);
}
```

**Comment by veodko** [comment]
> You could overwrite `getMorphClass`
> 
> ```
> public function getMorphClass(){
>     return get_class($this);
> }
> ```
> 
> `getMorphClass` is the laravel standar for morph relations

This causes a whole lot of other issues, Bouncer basically stops working and things start throwing "403 unauthorized".
I guess when displaying a list of the audit log, I should just do something like this to display the full class name and still make use of morph mapping.
```php
$morphMap = Relation::morphMap();
$className = $morphMap[$audit->auditable_type] ?? $audit->auditable_type;
```

**Comment by parallels999** [comment]
I don't use bouncer, I can't test this, if you can make a repo with a fresh Laravel installation showing the problem it would be very helpful

**Comment by veodko** [comment]
I think the solution I gave is the most appropriate:
```php
$morphMap = Relation::morphMap();
$className = $morphMap[$audit->auditable_type] ?? $audit->auditable_type;
```

This returns the currently active class no matter if it's stored as full name or just the morph alias. I can see the idea behind using `getMorphClass` now. I can close this issue for now.
